### ISSUE TITLE
[Docs]: Uploading file that does not exist does not produce any error

### ISSUE THREAD

**Issue by Akxe** [puppeteer/puppeteer#10053]
### Bug expectation

I expected an error but did not get one. I did waste half a day on it (I am not mad, it is only really hard to tell if something went wrong...)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent('<input type="file">')
  const inputHandle = await page.$('input[type=file]');
  await inputHandle.uploadFile('non-existing-src.jpg');
})();
```

### Error string

no error

### Puppeteer configuration

```TypeScript
I am using `jest-pupeteer` with `.jest-puppeteerrc.json` file: 


{
  "launch": {
    "headless": true,
    "devtools": true,
    "exitOnPageError": false
  }
}
```

### Puppeteer version

19.10.0

### Node version

16.13.2

### Package manager

npm

### Package manager version

9.1.2

### Operating system

Windows

**Comment by jrandolf** [comment]
Sorry about this. We used to validate, but now we don't because the file comes from your *remote* environment which is not possible to validate. This sadly implies if your remote *is* your local, then we still can't validate because we can't detect that difference.

Under the hood, the `input` element doesn't validate what gets set there, it's assumed that you validated beforehand, so it's best to somehow validate the file before using your own framework (if it's local, then just use `fs.existsSync`) and then continuing on from there.

**Comment by Akxe** [comment]
How about an update to the docs of `uploadFile`? Maybe a hint that the file is not validated could be helpful?
