### ISSUE TITLE
[Bug]: Failed to launch the browser process

### ISSUE THREAD

**Issue by erenkarakal** [puppeteer/puppeteer#10523]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const browser = await puppeteer.launch({ headless: 'new' });
```

### Error string

Error: Failed to launch the browser process!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Trying to open a page, code works fine on local (Windows 11, Node 20) but doesn't work on my VPS (Ubuntu 22, Node 18).

### Expectation

Launch the browser

### Reality
```
/home/container/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259
                reject(new Error([
                       ^
Error: Failed to launch the browser process!
/home/container/.cache/puppeteer/chrome/linux-114.0.5735.133/chrome-linux64/chrome: 1: Syntax error: "(" unexpected
TROUBLESHOOTING: https://pptr.dev/troubleshooting
    at Interface.onClose (/home/container/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Puppeteer version

v20.8.0

### Node version

v18.16.1

### Package manager

npm

### Package manager version

8.5.1

### Operating system

Linux

**Comment by erenkarakal** [comment]
tried using puppeteer-core with the browser that puppeteer installed, reinstallig everything and literally everything I could think of but I still can't figure it out.

**Comment by OrKoN** [comment]
It looks like a mismatch in cpu architectures between the binary and the server. What kind of cpu do you have? E.g., https://github.com/puppeteer/puppeteer/issues/9384 we do not currently have arm64 binaries for Linux (but we hope to have it soon).

**Comment by erenkarakal** [comment]
> It looks like a mismatch in cpu architectures between the binary and the server. What kind of cpu do you have? E.g., https://github.com/puppeteer/puppeteer/issues/9384 we do not currently have arm64 binaries for Linux (but we hope to have it soon).

the server is using an ampere cpu, i forgot to post an update but the issue was that i need a gui. don't really know how i'll get it but i'll figure it out eventually 👍

**Comment by cognettings** [comment]
I was getting the same error message, but was able to solve it by installing Nodejs with Volta instead of using the version that was installed with the snap package manager.

Here's a bit more info... I'm migrating from an x86 AWS EC2 instance to an ARM instance using Ubuntu 22. At first Puppeteer failed to install Chrome so I installed chromium-browser with apt. However, the snap package manager actually ended up installing it for some reason (something to do with it being a "transitional package"). Then set the "executablePath" for Puppeteer to the package-manager-installed version of Chromium, but kept getting the "Failed to launch the browser" error. I tried a LOT of different things that didn't work out.

Eventually I launched a fresh ARM EC2 instance and started from scratch but ended up using Volta to install Nodejs and it worked right away. I didn't realize the first machine had used snap to install Nodejs until I was comparing everything I could between the two servers and compared the output from the command "snap list".

So in the end I

- installed volta: curl https://get.volta.sh | bash
- used volta to install nodejs and yarn: volta install node && volta install yarn
- installed puppeteer with yarn: PUPPETEER_SKIP_DOWNLOAD=1 yarn add puppeteer
- installed chromium with apt/snap: apt install chromium-browser
- set the puppeteer launch option "executablePath" to the package-manager-installed chromium
