### ISSUE TITLE
page.Type slow in 0.12.0

### ISSUE THREAD

**Issue by bitbangtech** [puppeteer/puppeteer#1058]
Using page.type has become painfully slow during the last update.

It looks like between characters there's the same amount of delay specified in the slowMo parameter, is this intentional?

**Comment by aslushnikov** [comment]
@bitbangtech do you use slowMo option when launching pptr? Do you have a repro scenario?

**Comment by danieljuhl** [comment]
@aslushnikov I encountered the same, and I assume `slowMo` is applied to each keystroke instead of the whole command. So even when `delay` is set to `0` on the `page.type()`, each keystroke will be delayed with the `slowMo` value.

I would assume `slowMo` was applied to the command just once, and the `delay` options was applied to each keystroke.

I can confirm that removing `slowMo` makes it fast again.

**Comment by NicolasWebDev** [comment]
I confirm the problem. Was it by design?

**Comment by aslushnikov** [comment]
> I confirm the problem. Was it by design?

Yes, `slowMo` argument adds delay between characters in `page.type`. This is by design. 

The `slowMo` is not supposed to be used on a production system; it's purely for debugging purposes.

**Comment by NicolasWebDev** [comment]
I guess that we were abusing it a bit (at least in my case) as a sleep to make the actions work. I will have to use better the waitFor* instead.

**Comment by danieljuhl** [comment]
I partly disagree with the current behaviour. I understand that slowMo is a debug thing, but if the tests is using any page.type adding slowMo to debug is practically impossible, as the "slowness" in the typing is way to much compared to the rest of the actions. I would assume that slowMo was only applied once between each action. I don't see cases where I would be debugging each key stroke, and if I had that case I could simply apply the delay on page.type

**Comment by theblang** [comment]
@aslushnikov @danieljuhl I would also like to respectfully voice my disagreement with how the `type` delay works currently, especially since there is a [delay option](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-pagetypeselector-text-options) that can be passed directly to `type`. Currently the [slowMo option](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-puppeteerconnectoptions) will supersede the `delay` option, so there is no way to speed up typing when using `slowMo`. This makes debugging so painful if you have to wait on anything that needs to type input, like authentication.

My current workaround is to use `evaluate` to give me access to my frontend framework so that I can set the form data and refresh the ui within the browser context, which then allows me to `click` the login button and subvert having to wait for the slow typing.

**Comment by booleanbetrayal** [comment]
Seems like `slowMo` should key off of events if defined, otherwise defaulting to a global value if an integer value is provided. ie - maybe something like:

`slowMo: { default: 200, click: 100, keyup: 10 }`  or `slowMo: 200`
