### ISSUE TITLE
Don't use browser Request api, make our own simple one

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#106]
@aslushnikov can you fill in why? I just have it in my notes that we should do it.

**Comment by Garbee** [comment]
What exactly would this kind of API look like? I think not using the built in browser systems where available is harmful. As then developers need to learn yet-another-syntax to get the same results. Even though we already have (and are probably using) exactly what they know underneath.

**Comment by aslushnikov** [comment]
> What exactly would this kind of API look like?

We'll get rid of `Headers` object and use something like a map instead. It would be consistent with `page.setHTTPHeaders` methods.

> I think not using the built in browser systems where available is harmful. Even though we already have (and are probably using) exactly what they know underneath.

The API in question is consumed by node.js, not by browser. We don't have [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) in node. We have [protocol's network domain](https://chromedevtools.github.io/devtools-protocol/tot/Network/) which we expose via the [puppeteer's request](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-request) and [puppeteer's response](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-response) classes. 

Browser also has [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) and [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) classes, so we tried to align puppeteer's request and response with the browser counterparts. It turned out that:
- our capabilities are very limited, for example, [puppeteer's request](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-request) implements only 3 our of 11 fields of the [browser's request](https://developer.mozilla.org/en-US/docs/Web/API/Request).
- our usage scenario differs from the browser's one, so we'd like to have a slightly different api, for example [Request.response()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#requestresponse) method

Since we failed to implement browser api to a reasonable extend, we don't want to commit to it any more.

**Comment by Garbee** [comment]
Ah, thanks for the clarification @aslushnikov. Knowing that it SGTM to make this change.
