### ISSUE TITLE
[Feature]: Support lazy install of browser based on configuration at runtime

### ISSUE THREAD

**Issue by dsherret** [puppeteer/puppeteer#10637]
### Feature description

Whenever making changes to the configuration of puppeteer, an explicit removal then reinstall of the npm packages is necessary.

> After adding the configuration file, you will need to remove and reinstall puppeteer for it to take effect.

This seems inconveient. Additionally, it relies on a post-install step for npm, but a handful of users ignore scripts (ex. `npm install --ignore-scripts`) or run in Deno because Deno does not run install scripts.

Perhaps instead the code could instead lazily install the browser on first run based on the current configuration.

Alternatively, perhaps there could be an `ensureInstall` function to ensure the browser is installed based on the current configuration without having to uninstall and then reinstall the npm package:

```ts
import puppeteer from "puppeteer";

await puppeteer.ensureInstall();
```

Related: https://github.com/puppeteer/puppeteer/issues/5239

**Comment by OrKoN** [comment]
In my opinion, it'd be better to provide a command-line interface for downloading the binary for the current puppeteer project, which is our plan. Installing the binary from within your program/server is not a good idea because that can easily fail and it changes the startup time in unexpected way. 

There is also a workaround for now: `node node_modules/puppeteer/install.js`

**Comment by Lightning00Blade** [comment]
We now provide the command-line interface mentioned above, you can no run `npx puppeteer browsers install` to download all browser depending on our configuration.
