### ISSUE TITLE
[function naming]: Locator API isn't the best name IMO...

### ISSUE THREAD

**Issue by lucasrmendonca** [puppeteer/puppeteer#10656]
### Feature description

Hi @jrandolf and Puppeteer team... it feels strange to me that `waitForSelector` which was very easy to read and understand is getting kind of an experimental upgrade called `locator`which doesn't indicate clearly that it's not only locating the selector, but also waiting until it's ready to be interacted with... also it makes me a bit uneasy that it's being named after a noun instead of starting with a verb.

```js
// reads pretty well, easy to understand for beginners, even explains what the needed parameter is
await page.waitForSelector('my-selector'); 

// hard to understand what "locator" does without reading the docs.
// Does it just locate? does it locate and then wait for it?
// It evens sounds less powerful than waitForSelector() when in fact it's supposed to be more powerful...
await page.locator('my-selector').click(); 

// my suggestion (just an idea)
await page.waitUntilReady('my-selector').click();
```
The special part about locators is combining waiting for selector and then acting in a single line, which is more reliable and also cleaner than doing it separately, in other words, when we're done waiting, the element is ready to act upon! without having to save it in a constant. I feel like it's name doesn't give justice to the awesomeness this API conveys, it should express its intent better, which is to make the element ready to act and in a better, reliable, less flaky way... it sounds like it's just locating the selector and that's it...

**Comment by OrKoN** [comment]
`locator` here indicates the you get a Locator object for the provided selector. Note that you can totally use it separately from the action:

```
async function myHelper(locator: Locator) {
  await locator.click();
  await locator.hover();
}
await myHelper(page.locator('.cls'));
```

We decided against calling it `.locate` or `page.waitUntilReady` because the waiting does not start/happen on this call. E.g., `await page.waitUntilReady('my-selector')` would do nothing on its own (unlike `waitForSelector`). Some frameworks already adopt the name `locator` for creating such objects so we also didn't want to create minor differences in how it is named to simplify the learning.

**Comment by lucasrmendonca** [comment]
That makes sense, I think I got used to the page.waitForSelector returning an elementHandle instead of it being ` await page.elementHandle()`  and the locator syntax just felt strange.

 Thanks for your quick response
