### ISSUE TITLE
[Bug]: npm_package_config_puppeteer_skip_download not working

### ISSUE THREAD

**Issue by renandecarlo** [puppeteer/puppeteer#10757]
### Minimal, reproducible example

```TypeScript
// Add this to project's package.json
"config": {
  "puppeteer_skip_download": true
}
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

The "puppeteer_skip_download" variable is not working when using it in the project's package.json config.
Using the variable in .npmrc works though.

### Expectation

I expect it to avoid downloading a chrome installation. 

### Reality

It does download it even when using the variable in project's package.json config

### Puppeteer version

21.1.0

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Windows

**Comment by xfournet** [comment]
The correct configuration in package.json is

```json
  "puppeteer": {
    "skipDownload": true
  }
```

**Comment by OrKoN** [comment]
It looks like in this is caused by change in npm? https://github.com/npm/rfcs/blob/main/implemented/0021-reduce-lifecycle-script-environment.md I confirmed that npm does not set expected environment variables in this case any longer. We recommend using Puppeteer configuration files https://pptr.dev/guides/configuration
