### ISSUE TITLE
In page.emulate(option), option. hasTouch not worker

### ISSUE THREAD

**Issue by sheweichun** [puppeteer/puppeteer#1079]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:0.12.0
* Platform / OS version:mac 10.11.6
* URLs (if applicable): any mobile page

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. prepare the demo like beblow:
```
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');
const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.emulate(devices['iPad landscape']);
  await page.goto(REDIRECT_URL);
```
2. interact with the page in the chrome

**What is the expected result?**
touch operations  work

**What happens instead?**
touch operations don't work

**Comment by JoelEinbinder** [comment]
Emulating a touch device with Puppeteer sets up the page so that something like modernizr will detect touch support. It doesn't convert mouse clicks into touch events. You can use [`page.touchscreen`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-touchscreen) to send automated taps into the page.

**Comment by actionnick** [comment]
This should work. 

```javascript
const devtoolsProtocolClient = await page.target().createCDPSession();
await devtoolsProtocolClient.send("Emulation.setEmitTouchEventsForMouse", { enabled: true });
```

**Comment by TNT-Likely** [comment]
@actionnick it work fine for me,thanks
