### ISSUE TITLE
Element handles

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#111]
There has been a lot of talk about element handles/references. Some points to consider:

- Should they reference actual nodeIds, or reference a selector/finder function
- Do we need them?
- What happens if the element leaves DOM? If it gets garbage collected?
- Do we still have `page.click(selector)`?

How they might look:
```js
let button = page.$('button');
await button.click();
```

```js
let button = await page.waitForSelector('button');
await button.click();
```

```js
page.$('button')
    .focus()
    .click()
    .run(b => b.textContent = 'hello');
```

```js
let button = page.$('button')
await page.waitFor('button')
await button.click();
```

```js
let button = page.$('button')
await page.waitFor('button')
await button.click();
```

**Comment by aslushnikov** [comment]
### Suggestion
Let's design element handles similarly to the element handles in devtools console. This would be a
very natural and familiar behavior.

<img width="400" alt="screen shot 2017-07-29 at 11 26 52 pm" src="https://user-images.githubusercontent.com/746130/28751179-ca5585b0-74b5-11e7-9864-c5116d85da8b.png">


Answering questions from this standpoint: 

> - Should they reference actual nodeIds, or reference a selector/finder function

They should reference actual nodes through RemoteObjects.

> Do we need them?

Yes. There are good reasons to have element handles:
- Everybody wants element handles so that they don't have to re-type selectors multiple times
- Handles would allow us to interact with nodes which are only accessible through page's javascript
- Handles will give us a good isolated namespace. Such methods as `Element.screenshot()` would be easily added.

> What happens if the element leaves DOM? If it gets garbage collected?

if element gets detached from DOM, nothing happens. The element is never garbage collected since it is retained through remote object.

> Do we still have page.click(selector)?

Yes, they come handy for small scripts and it would make us closer to other API's.

### API Draft

Let's introduce the `Element` class which is a representation of Page's element.

`Element` instance could be created by one of these methods:
1. Querying the page for the selector

```js
let elem = await page.$('div');
```

2. Returning element from `page.evaluate`:
```js
let elem = await page.evaluate(() => document.body);
```

3. Awaiting element to appear in page:
```js
let elem = await page.waitFor('div');
```

`Element` instance could be destroyed via the `release` method (though I imagine noone would care):
```js
elem.release();
```

`Element` instances would be also destroyed on frame navigation.

API Demo:
```js
let elem = await page.waitFor('input[type=search]');
await elem.focus();
await page.type('Hello, world');
await page.press('Enter');
```

**PROS**:
- Addresses all the needs while piggy-backing on a well-known concept
- Works nice with `page.evaluate`
- If we ever expose RemoteObject, Element will play nicely with it: `Element extends RemoteObject`.
- `page.click` and others are naturally implemented as a sugar atop of Element
```js
/**
 * @param {string} selector
 * @return {!Promise}
 */
async click(selector) {
  const e = await page.$(selector);
  await e.click();
  await e.release();
}
```

**CONS**
- Not sugary enough, hard to write one-liners to evaluate on selector
- Manual memory management: elements should be released manually

The first **CONS** could be addressed by introducing a `page.$eval` function which does query and eval simultaneously
```js
page.$eval('form', form => form.submit());
```

The second **CONS** might result in memory leaks. Node itself has this problem with event listeners and throws a [process warning](https://nodejs.org/api/process.html#process_process_emitwarning_warning_options) when there are too many of them. We can do the same when there are more then 100 elements created per frame.

**Comment by aslushnikov** [comment]
cc @dgozman who has a draft implementation

**Comment by JoelEinbinder** [comment]
## Suggestion

#### page.$(descriptor)
  - `descriptor` is a selector or a function that returns an element.

returns: [Element](#element)

Because you don't need to await the element, we can replace `page.click(selector)` with `page.$(selector).click()`

#### page.waitFor(selectorOrPageFunction)
if `selectorOrPageFunction` is a selector or a pageFunction that returns an element, `page.waitFor` resolves to an [Element](#element)

### Element
#### element.click([options])
#### element.hover([options])
#### element.type(text, [options])
#### element.press(key, [options])
#### element.uploadFile(...files)
#### element.eval(pageFunction, ...args)

`page.click`, etc.

## Questions

> Do we need them?

Yes.

Adding finder functions into `page.click` is awkward.

Our api is becoming disorganized because all methods are mirrored everywhere.

> Should they reference actual nodeIds, or reference a selector/finder function

Finder function or selector


> What happens if the element leaves DOM? If it gets garbage collected?

Methods called on the element will throw if the element cannot be found.

> Do we still have `page.click(selector)`?

No

## Examples

```js
await page.$('button').click();
```

```js
let div = page.$('div');
await div.waitFor({visible: true});
await div.click();
```

```js
await page.$(() => UI.inspectorView.element).click();
```


## Pros

Removes the tension we have between `keyboard.type` and `page.type`. It is now clear that `keyboard.type` just types, but `element.type` will type into the element.

Removes the need to duplicate our entire api on frame.

Allows for easy re-use of elements.

No extra roundtrips.

Very succint syntax.

## Cons

Elements get leaked unless they are released or the page is navigated.
