### ISSUE TITLE
[Bug]: 'headless: "new"' creates 2 page responses (favicon.ico), 'headless: "true"' only one

### ISSUE THREAD

**Issue by SKuhlemann** [puppeteer/puppeteer#11162]
### Steps to reproduce

Testes on a Windows machine with Node.js v18.18.1, (chromium: win32-117.0.5938.149):

```
let browser = await puppeteer.launch({
       headless: "new"
    })

page.on('response', async (response) => {
console.log(response.url())
});

await page.goto(urlToFetch, {
    waitUntil: 'networkidle2'
});
```

### Expected results

With `headless: true` there is only one response, which is what I expect.
The response.url() is: 
"https://api.openweathermap.org/data/2.5/weather?APPID=........."

### Actual results

With `headless: "new"` there are 2 responses, which leads to code that gets executed twice within the async response-block.
The responses are: 
"https://api.openweathermap.org/data/2.5/weather?APPID=........."
"**https://api.openweathermap.org/favicon.ico**"

Favicon should not be present in headless mode in my opinion.

**Comment by Lightning00Blade** [comment]
Hello, `--headless=new` has the same behavior as normal Chrome (you can read more [here](https://developer.chrome.com/articles/new-headless/)) so this is expected behavior, 
as we want users to test with as closes as possible to the real browser. 

You can use a similar helper to filter the 
```ts
export const isFavicon = (request: {url: () => string | string[]}): boolean => {
  return request.url().includes('favicon.ico');
};
```
And remember to use `request.continue()` if you are using Network interception.
