### ISSUE TITLE
Why does page.bringToFront act differently between headless: 'new' and headless: true and is this intended?

### ISSUE THREAD

**Issue by santanaG** [puppeteer/puppeteer#11266]
I had an issue when I first started using Puppeteer and attempting concurrent tasks with headless: new. I did not recognize the issue as unusual until I gained more experience using Puppeteer and realized the actual cause in my code. I do not know if this is a bug yet, but I can file this as a bug if you find that this is not intended. I am asking this question instead.

When I first looked up the issue, I encountered the following error "TargetCloseError: Protocol error (Input.dispatchKeyEvent)" and found a [related issue](https://github.com/puppeteer/puppeteer/issues/10144) here on the Puppeteer Issues page. I could not make much sense of it back then because increasing the limit only made the script last longer before failing. I assumed I was making a mistake in my code. Eventually, I was able to work around this.

More recently, I connected the dots and noticed [this](https://stackoverflow.com/questions/55775332/puppeteer-headless-false-timesout-true-works) issue and [this](https://stackoverflow.com/questions/76566595/puppeteer-headless-new-false-not-working-properly) unanswered Stackoverflow question and realized it happens when using Page.bringToFront on a page and then attempting other tasks on other pages. It appears it might also be a Mac issue. Since I was able to resolve this by using headless: true I have since stopped pursuing solutions. So that leaves the question now.

**Comment by OrKoN** [comment]
Yes, page.bringToFront behaves differently in the old headless because in the old headless mode the behavior is changed in a non-compliant way to pretend each page is always visible. The new headless behaviour matches the headful browser behaviour where the page visibility and throttling are applied realistically. It is recommended to focus on the tab before doing tasks in it just like a regular user would do. If you don't need realistic behaviour for your tasks, you can keep using the non-standard behaviour of the old headless.

**Comment by santanaG** [comment]
One last, and related question. Apologies for reopening this. What is the suggested course of action if you want to concurrently run tasks without using a third-party solution and with the compliant route? Would it be to run more instances of puppeteer? Thanks for the quick response.

**Comment by OrKoN** [comment]
In the general sense, it might not be easy because browsers have optimisations for hidden windows etc and having a window in a background might affect the execution of the sites. In an ideal case, you would need to have one browser per machine and distribute tasks between machines. Using the old headless is fine though if you don't need the complete match with the regular browser.
