### ISSUE TITLE
[Bug]: TimeoutError: Waiting failed

### ISSUE THREAD

**Issue by flexeo** [puppeteer/puppeteer#11325]
### Minimal, reproducible example

```TypeScript
try {	
  const pages = await currentBrowserInstance.browser.pages();
  const page = pages[0];
  await page.setViewport({ width: 100, height: 100 });
  const watchDog = page.waitForFunction('!!window.DRAW_FINISH', {timeout: timeout});
  await page.goto(backendURL, {timeout: timeout});
  await watchDog;
}
catch(e) {
  console.error(e);
}
```

### Error string

TimeoutError: Waiting failed: 15000ms exceeded

### Bug behavior

- [x] Flaky
- [ ] PDF

### Expectation

Approximately one time out of 2, the error is impossible to catch with the try catch block, and the script ends by crashing.

> /home/.../node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:59
>                 void this.terminate(new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`));
>                                     ^
> 
> TimeoutError: Waiting failed: 15000ms exceeded
>     at Timeout.<anonymous> (/home/.../node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:59:37)
>     at listOnTimeout (node:internal/timers:564:17)
>     at process.processTimers (node:internal/timers:507:7)

### Reality

The script ends by crashing.

### Puppeteer version

21.5.0

### Node version

v18.13.0

### Package manager

npm

### Package manager version

9.2.0

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Hello @flexeo, sadly I am unable to reproduce locally as well, but I have a suspicion what may be the issue here.
The thing is even though you have a `try/catch` block the catch handler is attached to the `watchDog` only when you do `await`. So `watchDog` can throw while you are waiting for  `await page.goto(backendURL, {timeout: timeout});`
then you will have a unhandled Error.
to fix this you need to wrap both Promises in `Promise.all` like so:
```ts
Promise.all(
  page.waitForFunction('!!window.DRAW_FINISH', {timeout: timeout}),
  page.goto(backendURL, {timeout: timeout});
)
```
