### ISSUE TITLE
[Feature]: Update pptr.dev to Docusaurus v3

### ISSUE THREAD

**Issue by Lightning00Blade** [puppeteer/puppeteer#11337]
### Feature description

Release notes: https://docusaurus.io/blog/releases/3.0

- [ ] See if anything needs to be update the file prior to the v3 update - https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3 
- [ ] Than run the steps described on the Migration guide - https://docusaurus.io/docs/migration/v3

**Comment by AbdulrahmanAlosaimi** [comment]
I'd like to work on it, please assign

**Comment by TheJoin95** [comment]
I created this PR https://github.com/puppeteer/puppeteer/pull/11434 to handle this: there were needed some changes on the .md files in order to onboard the V3 but everything was straight forward.

Please let me know if there is anything more that I can do, I'm still waiting for an approval to run the workflow in the PR.
Thank you!
