### ISSUE TITLE
[Bug]: command failed: command sh -c node install.mjs

### ISSUE THREAD

**Issue by MatthijsBurgh** [puppeteer/puppeteer#11553]
### Minimal, reproducible example

```TypeScript
{
  "name": "test",
  "description": "None",
  "version": "0.0.1",
  "devDependencies": {  # or "dependencies"
    "puppeteer": "^21.0.1"
  },
  "engines": {
    "node": ">=0.10"
  }
}
```

### Error string

command failed: command sh -c node install.mjs

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

`npm install` and `npm ci` don't work

### Expectation

Puppeteer should install fine.

### Reality
```
npm info run puppeteer@21.6.1 postinstall node_modules/puppeteer node install.mjs
npm info run puppeteer@21.6.1 postinstall { code: 1, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:517:28)
npm verb stack     at maybeClose (node:internal/child_process:1098:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
npm verb pkgid puppeteer@21.6.1
npm verb cwd /home/matthijs/src/roslibjs
npm verb Linux 6.2.0-37-generic
npm verb node v18.18.0
npm verb npm  v10.2.4
npm ERR! code 1
npm ERR! path /home/matthijs/src/roslibjs/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.mjs
npm verb exit 1
```

### Puppeteer version

21.6.1

### Node version

18.18.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by MatthijsBurgh** [comment]
I have tested in a clean docker, with the installation according to the node.js website. This works.

Previously I was using the node installation via snap. That might be the issue, as when I use the node.js installation on my machine it also works.

So leaving this message for future references.

**Comment by bltr** [comment]
The error can be reproduced if node is installed via snap.

**Comment by jaller94** [comment]
+1 for this being an issue when Node is installed via Snap on Ubuntu.

**Comment by salim-b** [comment]
I can reproduce this issue on Ubuntu 22.04 with Node.js installed [via Snap](https://snapcraft.io/node) (with both `v20.11.1` and `v21.6.2`).

While searching for a solution, I stumbled upon a [similar issue in `esbuild`](https://github.com/evanw/esbuild/issues/1711) that was [found to be related to `stderr` not being writable](https://github.com/evanw/esbuild/issues/1711#issuecomment-1027554035) in the Snap version of Node.js. It was [fixed by simply prepending `stdio: 'pipe'` to a `execFileSync` call](https://github.com/evanw/esbuild/commit/54ebf0cc7f7580e9b290a5a225ae8c784745d45f). Hope it helps to narrow down the root cause.
