### ISSUE TITLE
[Feature]: Mobile Flutter Support

### ISSUE THREAD

**Issue by RokeJulianLockhart** [puppeteer/puppeteer#11611]
### Feature description

I'm aware of https://pub.dev/packages/puppeteer#limitations-with-flutter:

> Due to limitations on mobile platforms (iOS and Android), it is not possible to launch an external Chrome process on iOS and Android. So, step 1) does not work on mobile.

...per https://github.com/ImranR98/Obtainium/discussions/1047#discussioncomment-7988267. However, there are an awful lot of mobile applications which require the ability to scrape the web, but can't, because there's no alternative to Puppeteer. Is there at least a route for remediating the problems outlined in the aforementioned section of the ReadMe? For instance, is there a relevant issue open on the AOSP bug tracker which could at least track the blocker for this?

**Comment by OrKoN** [comment]
Hi, I am not sure what the best way to track but it's likely not here. Puppeteer generally works with anything that supports CDP so it works on Android. The limiting factor is in the operating system itself: Puppeteer cannot launch anything there because it's not running on the host so you need to use puppeteer.connect after you launched Chrome on the device. With iOS, the situation is more complicated because the iOS Chrome version uses webkit (as all other browsers on iOS) so it does not talk the same protocol. I suggest you file the issue in the puppeteer-dart package. Note that it's a third party package, not maintained by the Puppeteer team.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/puppeteer/puppeteer/issues/11611#issuecomment-1873668553

@OrKoN, where is `puppeteer-dart`'s issue page?
