### ISSUE TITLE
[Bug]: Files downloaded with duplicate name are replacing existing files instead of renaming with numbering like filename(1).txt

### ISSUE THREAD

**Issue by shubham-damkondwar** [puppeteer/puppeteer#11664]
### Minimal, reproducible example

```TypeScript
const client = await page.target().createCDPSession()
    await client.send('Page.setDownloadBehavior', {
        behavior: 'allow',
        downloadPath: path.resolve(__dirname, downloadPath),
    });
```

### Error string

none

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Download duplicate files with a number

### Reality

downloading file with same name replaces existing file

### Puppeteer version

21.7.0

### Node version

v16.16.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Linux

**Comment by OrKoN** [comment]
This feature is not part of Puppeteer's API as you reach out to the CDP directly. Would you mind filing a feature request for crbug.com and note that https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior is deprecated. Try using Browser.setDownloadBehaviour instead.

**Comment by matt22207** [comment]
For reference to anyone looking into this problem, looks like this bug was submitted to the CDP team here, but has no progress & was marked (incorrectly due to confusion over the Page vs Browser change) as deprecated / won't fix: https://issues.chromium.org/issues/41492073

**Comment by OrKoN** [comment]
I believe you can use allowAndName behavior and re-name if needed yourself upon receiving the downloadWillBegin/downloadProgress event.

**Comment by matt22207** [comment]
Thanks @OrKoN . Here's what I have working in case it helps others. That said, I'd prefer not to add/maintain all this extraneous workaround code. Hoping the CDP team comes up with a real fix.

```
async function saferClickAndDownload(page, downloadPath, elToClick) {

  // track the downloads
  const downloads = new Map();
  let downloadResolvers = new Set();

  const waitForDownloadCompletion = () => {
    return new Promise(resolve => downloadResolvers.add(resolve));
  }
  
  // https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior
  let client = await page.createCDPSession()
  await client.send('Browser.setDownloadBehavior', {
    behavior: 'allowAndName',
    downloadPath: downloadPath,
    eventsEnabled: true,
  })

  client.on('Browser.downloadWillBegin', event => {
    if (downloadResolvers.size > 0) {
      downloads.set(event.guid, {
        resolvers: downloadResolvers,
        filename: event.suggestedFilename,
      });
      downloadResolvers = new Set();
    }
  });

  client.on('Browser.downloadProgress', event => {
    const { guid } = event;
    if (event.state === 'completed' && downloads.has(guid)) {
      const { resolvers, filename } = downloads.get(guid);
      downloads.delete(guid);
      resolvers.forEach(resolve => resolve({ guid, filename }));
    }
  });

  const [{ guid, filename }] = await Promise.all([
    waitForDownloadCompletion(),
    elToClick.click()
  ]);

  let finalFilename = filename;
  // rename the "guid" file to "filename", but first check if a file already exists with the same "filename" and if so append a number to the end of the filename
  const existingFiles = fs.readdirSync(downloadPath);
  if (existingFiles.includes(finalFilename)) {
    // File already exists with the same name, appending a number to the end of the filename
    let i = 1;

    // split the filename into its base and extension, accounting for the case where the filename has no extension and also accounting for the case where there are multiple periods in the filename
    const filenameParts = finalFilename.split('.');
    
    // join everything except the last element into a string
    const baseFilename = filenameParts.slice(0, -1).join('.');
    const extension = (filenameParts.length > 1 ? "." : "") + filenameParts[filenameParts.length - 1];
    console.log("baseFilename: " + baseFilename + " extension: " + extension);
    while (existingFiles.includes(`${baseFilename} (${i})${extension}`)) {
      i++;
    }
    finalFilename = `${baseFilename} (${i})${extension}`;
  }
  // Actually renaming downloaded file to finalFilename
  fs.renameSync(`${downloadPath}/${guid}`, `${downloadPath}/${finalFilename}`);

  // Detaching CDP session
  await client.detach();

  return Promise.resolve(true);
}
```

**Comment by OrKoN** [comment]
@matt22207 if you are interested in working on a PR we could include it into Puppeteer with the following API:

```
const browser = await puppeter.launch({ downloadsDir: `...` })
page.on('download', (download) => {
   await download.saveAs(`/path/${download.suggestedFilename()}`);
});
```

Puppeteer should call setDownloadBehavior with allowAndName and name if the launch / connection options have a downloadsPath. And then create instance of a Download class that keeps the guid and tracks the progress of downloads. The saveAs method can handle renaming similar to your code.

**Comment by matt22207** [comment]
I'd be happy to give it a shot, @OrKoN , although may take a while :) .. 

Any suggestions / examples on how to create tests (especially for a download) that don't rely on external resources (as per the contribution policy) ?

**Comment by OrKoN** [comment]
You can use the test server package (https://github.com/puppeteer/puppeteer/tree/main/packages/testserver) which is already available in the test state and set up a download route to set headers and send a file as a download. Here is an example for setting cookie headers https://github.com/puppeteer/puppeteer/blob/2a20ce919589fb2629bf142a1498432944162eb9/test/src/cookies.spec.ts#L50

**Comment by matt22207** [comment]
Made a tiny bit of progress towards adding the saferClickAndDownload style workaround. I was able to get a test spec running, including the built-in test server to download a file. 

I was having trouble calling setDownloadBehavior from anywhere logical though (and possibly without some deeper refactoring that I don't feel comfortable with).. It seemed like the `launch` method in `packages/puppeteer-core/src/node/BrowserLauncher.ts` should be the best spot, but after the `browser` instance is created, I couldn't find any existing methods on it to call setDownloadBehavior (and without a new CDPSession).   There is an existing method on `packages/puppeteer-core/src/cdp/BrowserContext.ts`, but that context is not accessible on the returned `browser` (to my knowledge). I don't feel it makes sense at the framework level during `launch()` to do something heavy like I was doing during my personal implementation of creating a whole new `Page` and `page.createCDPSession()` just to call `client.send('Browser.setDownloadBehavior'...`. Maybe I'm missing a simpler way though.

That said, after fumbling through all that, I found that the `launch` method already accepts a `downloadBehavior` in the options (although its not obvious in the [launchOptions docs](https://pptr.dev/api/puppeteer.launchoptions) until you notice it extends [connectOptions](https://pptr.dev/api/puppeteer.connectoptions)) , so I'm leaning towards just using that as-is. This seemed the most natural to me anyway.. So instead of calling the heavier `client = createCDPSession()` then `client.send('Browser.setDownloadBehavior', {downloadPath: downloadPath})`  , users would switch to just`puppeteer.launch({downloadBehavior : { policy: 'allowAndName', downloadPath: downloadPath } } );` which is already in place, and then I just need to work on the event hooks for tracking/renaming the duplicate files. 

(I was also easily able to modify `launch` to accept `options.downloadPath`, but without a way to call setDownloadBehavior directly, this would mean we'd need to merge/reconcile into any existing `options.downloadBehavior` that may come in from other ways to call `launch` to be safe, so this felt messy/fragile.)

Plan from here:

1) in `BrowserLaunchers.ts`, before launching the browser, if we get options.downloadBehavior with a downloadPath AND a policy of "allow", force it to use "allowAndName" so we always save downloads (temporarily) to a UUID unique name.. AND regardless, add eventsEnabled:true so we can get events to monitor the download to rename after.

2) work on the event hooks as suggested: ... create instance of a Download class that keeps the guid and tracks the progress of downloads and saveAs method..

3) check how `connect` works and apply anything needed here too.

Let me know if this makes sense, @OrKoN ..

**Comment by OrKoN** [comment]
Sounds good, the only concern if we force allowAndName when allow is passed, is it going to be a breaking change for clients? I would suggest we first implement the download API if the policy is already to allowAndName and we handle deprecation/change of behavior for allow separately?

**Comment by matt22207** [comment]
Yes, was thinking that too as I slept on this.. will keep experimenting and see where this lands, trying to avoid breaking changes.
