### ISSUE TITLE
Consider cache .local-chromium dir for next installation faster

### ISSUE THREAD

**Issue by axetroy** [puppeteer/puppeteer#1167]
Like it said.

Every time I install this module, It will reinstall chromium.

Some time I got a  bad nework, I have to wait for a long long time.

So, can you cache .local-chromium in ``$HOME``, not in module' dir.

Every installation will run the script the check the chromium'version is match the npm version or not.

If not match, Download the matchest chromium and replace the .local-chromium.
if match, do nothing.

do you think so?

**Comment by aslushnikov** [comment]
- In some weird environments and platforms, we might not have access to `$HOME`.
- Introducing env variable to control installation location doesn't work since it might not be available at the time of running script itself.

You can cache downloaded chromium for yourself and point puppeteer to use executable from it with the `executablePath` option of `puppeteer.launch`.
