### ISSUE TITLE
[Bug]: PUPPETEER_SKIP_DOWNLOAD environment variable is ignored during installation

### ISSUE THREAD

**Issue by ybalcanci** [puppeteer/puppeteer#11750]
### Minimal, reproducible example

```TypeScript
PUPPETEER_SKIP_DOWNLOAD=true npm install puppeteer
```

### Error string

npm ERR! command failed npm ERR! command sh -c -- node install.mjs npm ERR! node:fs:1583 npm ERR!   handleErrorFromBinding(ctx);

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've been trying to install puppeteer in a machine with no write access to the home directory of the user. 

### Expectation

 It would raise an EACCES unless run with PUPPETEER_SKIP_DOWNLOAD env variable set to true and run without any issues when it's set.

### Reality

But it's been raising that error nonetheless since yesterday.

### Puppeteer version

21.9.0

### Node version

16.20.2

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Linux

**Comment by OrKoN** [comment]
I was not able to reproduce with the same node/npm version on a Linux machine when using a Puppeteer cache directory that is not accessible. It looks like it might be a problem with Node/NPM installation (or perhaps the config lookup fails because home folder is not accessible). Note that Node 16 reached EOL in September and is not maintained anymore. 

> I've been trying to install puppeteer in a machine with no write access to the home directory of the user.

Also, you can change the cache to a writable location https://pptr.dev/guides/configuration#changing-the-default-cache-directory or use `npm install puppeteer --ignore-scripts` to skip all installation scripts altogether.
