### ISSUE TITLE
window inner size not equal to viewport size

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1183]
**Tell us about your environment:**

* Puppeteer version: 0.13.0-alpha
* Platform / OS version: macos high sierra 10.13
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```javascript
// start.js

const puppeteer = require('puppeteer')

const run = async () => {
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 250,
    args: [
      '--disable-infobars',
    ],
  });

  const page = await browser.newPage();

  await page.goto('https://www.google.com/');

  await page.waitFor(60000)
  await browser.close();
}

run()
```

1. `node start.js`

**What is the expected result?**

1. window inner size and viewport should be equal, all the default 800px x 600px

**What happens instead?**

1. window inner size is larger than the viewport size

![google-puppeteer.png](https://i.loli.net/2017/10/27/59f2f0f3b461e.png)

**Comment by entrptaher** [comment]
To add more salt into it, opening devtools will make the viewport lose the predefined size. For example,
![image](https://user-images.githubusercontent.com/8284972/32138788-178bc6cc-bc5b-11e7-8050-34543d4a2705.png)

**Comment by zicongxie** [comment]
It has a param can be reset the window viewports in launch method.

**Comment by ghost** [comment]
@zicongxie `await page.setViewport({ width: 600, height: 400 })` only change the viewport size, but the window size will not changed to 600px x 400px too.

**Comment by ghost** [comment]
@entrptaher I noticed that too.

**Comment by aslushnikov** [comment]
@chanjsq what's your usecase? Why would you need to change the window size?

**Comment by entrptaher** [comment]
For me, say I will want to test responsiveness.

**Comment by ghost** [comment]
@aslushnikov When setting the viewport size larger than the default window size, we also need to set the window size with the same value to see the whole page width, it's convenient if the window size can change with viewport size accordingly.

**Comment by mike-aungsan** [comment]
Have the same issue on Windows 8.

**Comment by aslushnikov** [comment]
@entrptaher isn't viewport enough for responsiveness?
@chanjsq so this is mostly for debugging purposes?

**Comment by ghost** [comment]
@aslushnikov yes, smart can be better

**Comment by z-vr** [comment]
can i make the viewport equal to the size of the window by default, and adjustable while resizing? i don't want the viewport which is not equal to the window size :( +1 on this one

**Comment by radekmie** [comment]
I'm using this code:

```js
await page.setViewport({height, width});

// Window frame - probably OS and WM dependent.
height += 85;

// Any tab.
const {targetInfos: [{targetId}]} = await browser._connection.send(
  'Target.getTargets'
);

// Tab window. 
const {windowId} = await browser._connection.send(
  'Browser.getWindowForTarget',
  {targetId}
);

// Resize.
await browser._connection.send('Browser.setWindowBounds', {
  bounds: {height, width},
  windowId
});
```

I think that `Tab window` + `Resize` parts could be part `browser` API such as:

```js
browser.resize({height, width})
```

**Comment by tnoetzel** [comment]
Definitely also need this, fwiw.

**Comment by ganfubin** [comment]
this function is very necessar

**Comment by leachimsumiri** [comment]
+1

**Comment by akylkb** [comment]
[https://peter.sh/experiments/chromium-command-line-switches/#window-size](https://peter.sh/experiments/chromium-command-line-switches/#window-size)

```
const puppeteer = require('puppeteer')

const run = async () => {

    // Viewport && Window size
    const width = 400
    const height = 600

    const browser = await puppeteer.launch({
        headless: false,
        args: [
            `--window-size=${ width },${ height }`
        ],
        defaultViewport: {
            width,
            height
        }
    });

    const page = await browser.newPage();
    await page.goto('https://www.google.com/')

    // await browser.close()
}

run()
```

**Comment by Mehuge** [comment]
I am using the following to achieve the desired effect.

    const chrome = { x: 0, y: 74 };   // comes from config in reality
    args.push(`--window-size=${width+chrome.x},${height+chrome.y}`);
    puppeteer.launch({ headless, sloMo, args });
    // ...
    page.setViewport({ width, height });

**Comment by tomholub** [comment]
Based on https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/docs/api.md#pagefocusselector and @Mehuge asnwer
```js
const chrome = { x: 0, y: 74 };   // comes from config in reality
args.push(`--window-size=${width+chrome.x},${height+chrome.y}`);
puppeteer.launch({ headless, sloMo, args });
// ...
page.setViewport({ width, height });
```
(correcting typo in `setViewport` above)

**Comment by I-keep-trying** [comment]
Thanks, guys!!! I combined @akylkb with @Mehuge and got the perfect solution! 

And fwiw, for people who didn't understand why viewport size is important. It was stopping me dead in my tracks, because a common practice in many websites is to change the layout from pc / laptop to mobile based on viewport size, and the default size was causing it to go to the mobile layout, which did not have the login button available without an extra menu, involving two extra clicks. The entire DOM and navigation path can be completely different depending on how many different responsive designs the website designers have in place; they could have several, from smart watches to mobile, to ipads and tablets, touch screens and kiosks as well. The world includes much, much more than just laptops and pcs, and each and every layout will have a completely different DOM structure. 

So, again, THANK YOU,  @akylkb and @Mehuge, your solutions deserve a lot more attention imo!!

**Comment by grantstephens** [comment]
Think this is actually a bug when connecting over a websocket as I can't find a way to set the window size when on web socket. This means that some sites render incorrectly as they seem to look at the window size and not that set viewport, i.e:
Launch the browser
Connect to it via websocket
Set the viewport to be bigger than the window size of the websocket browser
Screenshot is based on window size.

I'm not 100% sure of this, but would seem to be the case and would appreciate anybody who could confirm.

**Comment by PayteR** [comment]
Hi, thx guys for solutions, but **screen.width** and **screen.height** are in `headless: true` always 800x600 and for `headless: false` is always resolution of actual screen. Any suggestions to solve this other than manually do it so in `evaluate()` method? Code:

```
await Page.evaluateOnNewDocument((screenWidth, screenHeight) => {
    screen.__defineGetter__('width', function () {
        return screenWidth;
    });
    screen.__defineGetter__('height', function () {
        return screenHeight;
    });
}, width, height);
```

**Comment by winterli** [comment]
This might be related issue, 

When saving as PDF (have to use headless mode), the window size triggers the incorrect media query. For example, if `page.setViewport(1200,960)`, then load below HTML page and save to PDF. Will expect the DIV has a gray background. But it actually shows a yellow background.

```
<body>
	<script>
		document.write("Window width: "+window.innerWidth);
	</script>
	<style>
		div{
			background: gray;
		}
		@media (max-width: 767px) {
			div{
				background: yellow;
			}
		}
	</style>
	<div>gray indicates window > 767px, yellow indicates window <=767px</div>
</body>
```  
![1523341516653 pdf 2018-04-09 23-25-38](https://user-images.githubusercontent.com/7054916/38539511-5aadf520-3c4d-11e8-81f9-a9cc5115e6a3.png)

**Comment by Mehuge** [comment]
I am now using @radekmie's solution, as well as the --window-size argument.  

In my test environment, the browser size may be specified before the browser window is open, and may be altered afterwards.  So in the case where it is specified before the browser window is open, I remember the size and use --window-size when launching the browser.  If the test scripts later specify a new size, I then use the resize code provided by @radekmie.

**Comment by Maluen** [comment]
As workaround, the default 800x600 viewport can be disabled by calling [Emulation.clearDeviceMetricsOverride](https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-clearDeviceMetricsOverride) after page is created

```javascript
args.push(`--window-size=${width},${height}`);
puppeteer.launch({ headless: false, args });
...
await page._client.send('Emulation.clearDeviceMetricsOverride')
```

This way there is no need to explicitly call `page.setViewport` or to rely on OS dependent values for the chrome size, since the viewport will automatically be equal to the window inner size.

**Comment by TheCloudlessSky** [comment]
@Maluen this solution worked for my problem getting `window.devicePixelRatio` in #2372.

**Comment by DanielRuf** [comment]
Definitely the same issue that I have.

Would make sense to disable the viewport emulation in headful mode.

Or provide an option like in the linked PR.

**Comment by winterli** [comment]
@Maluen the Emulation.clearDeviceMetricsOverride solution seems not working in headless mode which is the only mode support Save to PDF feature :(

**Comment by DanielRuf** [comment]
@winterli which version of Puppeteer do you use?

Should normally work with this.
https://github.com/DanielRuf/website-checks/blob/master/index.js#L131

**Comment by winterli** [comment]
@DanielRuf I'm using v1.4.0 from NPM. Below is the code I'm using, 

 
```javascript

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
      headless: true,
      args: [
          `--window-size=1280,960`
      ],
  });
  const page = await browser.newPage();
  await page._client.send('Emulation.clearDeviceMetricsOverride');
  const url="http://winterli.atwebpages.com/test.html";  
  await page.goto(url, {waitUntil: 'networkidle2'});    
  await page.pdf({path: 'viewport_test.pdf', format:"A4", printBackground:true});
  await browser.close();
  console.log("done!");  
})();

```

Did I miss anything here?

**Comment by DanielRuf** [comment]
> args: [
>           `--window-size=1280,960`
>       ],

Why this?

**Comment by DanielRuf** [comment]
![image](https://user-images.githubusercontent.com/827205/40448373-a18f9098-5ed5-11e8-8c46-b747a94c2d67.png)

**Comment by DanielRuf** [comment]
In general I do not see any `viewport` metatag. Please add one.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/QrRyvV

**Comment by winterli** [comment]
@DanielRuf thanks for your response. In the test page, I put some CSS media query to test the viewport. If the viewport is wider than 767, the second line should have a gray background. If the viewport is narrower than 767, the second line should have a yellow background. In my example, the window width is 1280, I should see a gray background for the second line. But as the screenshot you shared shows, it's not the case. 
PS: I have added the viewport tag in the test page also.

**Comment by entrptaher** [comment]
I've tested it out, the max viewport height I could do was around 20000px from my computer. I tried to take a ultra fullpage screenshot :D ...

**Comment by mbwhite** [comment]
@Maluen solution has worked for me just now;  also I did discover that if you go into debug model (ctrl-shift-I) that has the required effect.  Useful for manual testing etc.

**Comment by silkcom** [comment]
I'm having this same problem and it effects the way that css with vw and vh work, since they go based on the window size not the viewport size.  It's a problem in both headless and not.

**Comment by ghost** [comment]
Awesome!

**Comment by danielmello** [comment]
I'm having this same problem with puppeteer@1.7.0. When you launch the browser with defaultViewport null and headless true, nothing change, but with headless false, the viewport is affected.

**Comment by hegelstad** [comment]
Surely some strange things still going on.

**Comment by junguchina** [comment]
Same problem, is there any solution to change the options in [puppeteerlaunchoptions](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions)?
When I set the value like below:
```
        defaultViewport: {
          width: 1920,
          height: 1080
        }
```
The viewport is still 800*600, this is not convenient to debug by viewport.

**Comment by DanielRuf** [comment]
See https://github.com/GoogleChrome/puppeteer/commit/25632133e2683c613c97d9088968c48e3c07a086 @junguchina

**Comment by DanielRuf** [comment]
Please also try the latest release.

**Comment by junguchina** [comment]
@DanielRuf Thanks, my version of puppeteer is the latest version(1.8.0).
It still has this problem.I use codeceptjs with puppeteer.
The viewport size of chromium is `800x600`,but inner homepage size is `1920x1080`.
![jietu20180917-175801-hd](https://user-images.githubusercontent.com/14007943/45617072-ca397980-baa3-11e8-8015-8b056e04fd51.gif)

**Comment by fergardi** [comment]
I'm facing the same issue as above.

**Comment by DanielRuf** [comment]
Mh weird, it seems this was not resolved as I am still getting the narrow / small viewport even if I resize. Is there some regression?

**Comment by fergardi** [comment]
I want to share my personal experience. This will be a long trip.

**I'm using puppeteer@1.8.0 and Google Chrome V69.0.3497.100 in a Windows10 environment.**

Let's say I am new to Headless Chrome, and I want to print a dashboard in PDF. I searched for a typical responsive template dashboard and found this one I will be using as an example, credits to the original author: https://demos.creative-tim.com/bs3/paper-dashboard/dashboard.html

Then I create a new fresh script to work with:

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({headless: false}) // debug
  const page = await browser.newPage()
  await page.setViewport({width: 768, height: 1024, deviceScaleFactor: 2})
  await page.goto('https://demos.creative-tim.com/bs3/paper-dashboard/dashboard.html', {waitUntil: 'networkidle0'})
  await page.waitFor(1000)
  await page.click('button.close') // remove notification
  await page.click('a.navbar-brand') // click on page to close advertisement
  await page.emulateMedia('screen') // force screen CSS
  await page.waitFor(1000) // wait for every modal to dissapear
  await page.pdf({path: `${Date.now()}.pdf`, format: 'A4', printBackground: true})
  await browser.close()
})()
```

After that, I prove that in _headful_ mode, and it gives me this result:

![image](https://user-images.githubusercontent.com/3602272/45949509-690e2a80-bffc-11e8-8e51-479b1951613e.png)

Firstly, why that blank space? Is that the difference between the default 800px width viewport minus my 768px viewport? I don't think so. However, this does not show in the final PDF, only in _headful_ mode, but it stills bugs me a lot. In _headless_ mode, it shows at follows:

![image](https://user-images.githubusercontent.com/3602272/45949906-d66e8b00-bffd-11e8-8f07-aeae581d6740.png)

Secondly, why the media CSS flex is not triggering as showed in the intial picture? There should be two columned layout, not the single one. As I inspect them, they show as classic '@media' queries. Maybe the 'screen' forced mode instead of 'print' is causing this? I do not know.

Thirdly, why my pixel resolution is not being respected? If, in _headful_ mode, I show the DevTools and extract them from the page (which seems, by the way, to re-render the page to the expected behaviour), I can see the pixel resolution is not at all the one I setted of in the initial step.

![image](https://user-images.githubusercontent.com/3602272/45949691-02d5d780-bffd-11e8-9ac9-e18b48276836.png)

In fact, I could even increase the pixel resolution to have no results on the output:

![image](https://user-images.githubusercontent.com/3602272/45950006-36653180-bffe-11e8-8588-7d2f81228ba1.png)

Ah, that seems the old 800x600 viewport issue we were talking about. So I started to test every solution in this post, with these results:

1. **Force puppeteer to launch to a nulled defaultViewport?** No changes either in headless or headful.
2. **Force puppeteer to launch to a defaultViewport with exactly the same resolution as I wanted?** No changes either in headless or headful.
3. **Force puppeteer to launch to a defined --window-size arg commands?** That seems indeed to change the headful result and fix the strange blank space, leaving me with my desired initial resolution (to test responsiveness, for example). That leads me to the next issue. If I'm visiting this website with 768px width, which effectively triggers the corresponding \@media query, why in _headful_ I see one result and in _headless_ I see another different result?

![image](https://user-images.githubusercontent.com/3602272/45950730-4d595300-c001-11e8-96a2-27ea3031f933.png)

Maybe the float is affecting the behaviour? But again, why am I not achieveing the exact same result being in _headful_ or in _headless_, as this is the whole point? I do not know. That will be an entirely different issue.

**Comment by jarrodpayne** [comment]
Is there any way we can get this opened? It's still an issue, and @fergardi's [comment](https://github.com/GoogleChrome/puppeteer/issues/1183#issuecomment-423950729) describes the issue nicely.

cc @aslushnikov

**Comment by samburgers** [comment]
I was knocking my head over this for some time, until i realised (at least for my particular use case) is that this is all i needed to do to break out of the default 800 x 600 size:

```javascript

const puppeteer = require("puppeteer");

(async () => {

  const browser = await puppeteer.launch();

  const page = await browser.newPage();

  await page.emulateMedia("screen"); // <- optional but super useful

  await page.goto("http://localhost:3000", {
    waitUntil: "networkidle2"
  });

  await page.pdf({
    path: "filename.pdf",
    pageRanges: "1",
    width: 1600, // <- set width
    height: 1240, // <- set height
    printBackground: true
  });
})();
```

**Comment by redochka** [comment]
why is this issue closed, while the problem is still there?

**Comment by shawnnaquin** [comment]
tested, still an issue.

**Comment by aslushnikov** [comment]
**Everybody**: the reason this issue is closed is because you can actually disable viewport emulation with `defaultViewport: null` option.

Here's an example:

```js
const browser = puppeteer.launch({
  defaultViewport: null, // <= set this to have viewport emulation off
});
const page = await browser.newPage();
// ... 
```

**Comment by meeple142** [comment]
thanks for the tip @aslushnikov

**Comment by KotieSmit** [comment]
FWIW

My workaround was to add:

>    _beforeSuite() {
    this.helpers.Puppeteer.resizeWindow(1200, 960)
  }


This way the view port is always set the size I want.  You can go a step further and read out the values from the config file.


https://codecept.io/helpers/Puppeteer#resizewindow

**Comment by deqline** [comment]
As of today @aslushnikov method still works for anyone having this problem.
```js
const browser = puppeteer.launch({
  defaultViewport: null, // <= set this to have viewport emulation off
});
```

**Comment by destroyer22719** [comment]
> **Everybody**: the reason this issue is closed is because you can actually disable viewport emulation with `defaultViewport: null` option.
> 
> Here's an example:
> 
> ```js
> const browser = puppeteer.launch({
>   defaultViewport: null, // <= set this to have viewport emulation off
> });
> const page = await browser.newPage();
> // ... 
> ```

THANK YOU SO MUCH YOU ARE AN ANGEL

**Comment by jonwilliams-bluescape** [comment]
having fought with this for a few days, none of the googled solutions worked for me.
Although some of what's been posted will result in the window size being set, the values won't be readable from window.outerWidth after a page navigation.

However...

```
function setWindowDimensions ({width, height}) {
  window.outerWidth = width;
  window.outerHeight = height;
}

(async () => {
  const dimensions = await page.evaluateOnNewDocument(setWindowDimensions, {width, height});
})();
```

Executing this before navigating to the target URL will allow a script on that page to properly read the window size.
Tested in both headless and non-headless mode (Chromium)

**Comment by siva349** [comment]
Started working with puppeteer since few days, struggled with this problem. But this solution worked like a magic. Thanks @aslushnikov 

```
const browser = puppeteer.launch({
  defaultViewport: null, // <= set this to have viewport emulation off
});
```

**Comment by f-g-s** [comment]
I´m using Puppeteer and Jest and this jest-puppeteer.config.js works for me. :)

```
module.exports = {
    launch: {
        args: ['--start-maximized'], // get full screen browser window 
        defaultViewport: null, // get default (full size) viewport 
    },
}
```

**Comment by danangponorogo** [comment]
a little addition 
```
(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        ignoreHTTPSErrors: true,
        defaultViewport: null,
        args: [`--start-maximized`]
    });
    const page = await browser.newPage();
    await page.goto('https://domain.com');
    await browser.close();
})();
```

**Comment by mystic-poet** [comment]
#> this.helpers.Puppeteer.resizeWindow(1200, 960)



> ```js
> const browser = puppeteer.launch(
> ```



> Started working with puppeteer since few days, struggled with this problem. But this solution worked like a magic. Thanks @aslushnikov
> 
> ```
> const browser = puppeteer.launch({
>   defaultViewport: null, // <= set this to have viewport emulation off
> });
> ```

Where did you add these lines?

**Comment by ganfubin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vigneshwaran-chandrasekaran** [comment]
```
 const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: null,
        args: ['--start-maximized'], // we can use '--start-fullscreen' || --start-maximized
    });
```

**Comment by ganfubin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by augustoaraujoo** [comment]
```
const browser = await puppeteer.launch({
    /* headless: false */,
    defaultViewport: null,
    args: ['--start-maximized']
  });

```

**Comment by ganfubin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nickfthedev** [comment]
> As of today @aslushnikov method still works for anyone having this problem.
> 
> ```js
> const browser = puppeteer.launch({
>   defaultViewport: null, // <= set this to have viewport emulation off
> });
> ```

4 years later, you made my day sir! Thanks!

**Comment by TheGP** [comment]
That Chinese guy is on vacation for 2 years already

**Comment by Mecanik** [comment]
The issue is still there. If you call .emulate for any phone device, the viewport does not match the window size and it's really hard to work with it...

Setting window size save as the viewport returned by the device settings does not help. Neither any suggested solution from all this long discussion.

**Comment by ganfubin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
