### ISSUE TITLE
(CORS) Loading external script on a page

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#1204]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v0.12
* Platform / OS version: Ubuntu 16.04 64bit
* URLs (if applicable): https://github.com/

**What steps will reproduce the problem?**

- Disable web security, same origin policy etc.
- Load a website, 
- Add jQuery/Artoo from external url etc.
- It fails to load

_Please include code that reproduces the issue._

```js
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    args: ["--no-sandbox", "--disable-web-security", `--user-data-dir=data`]
  });

  const page = await browser.newPage();
  await page.goto("https://github.com/");

  await Promise.all([
    // add an external script, FAIL
    page.addScriptTag({
      url: "medialab.github.io/artoo/public/dist/artoo-latest.min.js"
    }),
    // add a raw script content, FAIL
    page.addScriptTag({
      content: `console.log("test")`
    }),
    // add a function, PASS
    page.evaluate(function(){
      console.log("test")
    })
  ])
})();

```

**What is the expected result?**
It should load/Execute the script.

**What happens instead?**
It fails to load due to cors issue.

You can always read the artooJS/jquery using nodejs, pipe it to evaluate, but that is another long way to do things.

Sometimes you will want to scrape a page with jQuery, or, sometimes you might want to use some other libraries from a cdn for testing purpose. or maybe a bootstrap theme from bootswatch on a bootstrap based site which has CORS.

**Comment by sajithsajan** [comment]
I am also facing this issue :-( . Please anybody help us...

**Comment by xprudhomme** [comment]
Have you faced this kind of error: " [...] is not an allowed source of script in the following Content Security Policy directive" ?

**Comment by michael2h4ng** [comment]
@Xavatar Yes, the error message reads:

_Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' http://*.example.com"._

**Comment by xprudhomme** [comment]
Since Puppeteer's page.addScriptTag method has taken over the deprecated page.injectFile method, on some specific websites I'm no longer able to inject JS files using this new addScriptTag method.

But I have a workaround, I have simply re-implemented the old page.injectFile method as follows

```javascript
  async injectFile(page, filePath) {

    let contents = await new Promise((resolve, reject) => {
      fs.readFile(filePath, 'utf8', (err, data) => {
        if (err) return reject(err);
        resolve(data);
      });
    });
    contents += `//# sourceURL=` + filePath.replace(/\n/g,'');
    return page.mainFrame().evaluate(contents);
  }
```

Using this old method works better in my case. Maybe it can help some of you guys.

**Comment by entrptaher** [comment]
@aslushnikov, why deprecate `injectFile` if we don't have a proper alternative? Like `addScriptTag` broke CORS on many sites where `injectFile` could deal with them properly. Can we improve `addScriptTag` where we put `path` argument?

**Comment by aslushnikov** [comment]
@entrptaher the `injectFile` is polifillable with a oneliner:

```js
await page.evaluate(fs.readFileSync(filePath, 'utf8'));
```

In the issue description, the following fails:
```js
    // add an external script, FAIL
    page.addScriptTag({
      url: "medialab.github.io/artoo/public/dist/artoo-latest.min.js"
    })
```
This is due to the CORS that prevent resources from loading. This could be work-around by loading the resource server-side and then injecting it into the page.

Also, the `content` fails as well:
```js
    // add a raw script content, FAIL
    page.addScriptTag({
      content: `console.log("test")`
    })
```
This fails due to the CSP policy. In fact, CSP stays in puppeteer's way in many cases, please upvote https://github.com/GoogleChrome/puppeteer/issues/1229.

Overall, closing this issue in favor of #1229.
