### ISSUE TITLE
Please public build 0.13.0 to npm 

### ISSUE THREAD

**Issue by maicss** [puppeteer/puppeteer#1209]
Your API DOC is `v0.13.0`, but `npm i` and `npm search` get `0.12.0`.
It takes me a lot time to debug my code, and read local source code, and check your github document and your github source code...

Finally, it turns out you guys not publish it to npm...how ridiculous.

**Comment by GuilloOme** [comment]
`v0.13.0` is still in `alpha` state (see the API header: **Puppeteer API v0.13.0-alpha**).
If you want to access the `v0.12.0`, check here the related tag here: https://github.com/GoogleChrome/puppeteer/tree/v0.12.0

**Comment by maicss** [comment]
But API doc now is 13……

**Comment by ebidel** [comment]
Agreed that it's confusing we rev the docs in master and point to those instead of the current stable release. We've tried to address that with clear labelling at the top of the API docs saying what version you're on, but people tend to miss that. When you install the stable release from npm, our everything points you to the `-alpha` docs.

A proper doc story will help: https://github.com/GoogleChrome/puppeteer/issues/1068

For now, please make sure you're looking at the correct version of the docs for the release of puppeteer that you've installed.
