### ISSUE TITLE
Read this if you experience PDF printing hanging on Windows

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12471]
With M125 Chrome uses sandboxes for printing (https://crbug.com/338553158) which may require additional permissions on the Chrome installation folder:

See https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows for how to set permissions.

**Comment by TiAlRo** [comment]
Thanks for this explanation!

Instead of icacls `$HOME/.cache/puppeteer/chrome /grant "ALL APPLICATION PACKAGES:(OI)(CI)(RX)"`, the command should be `icacls %USERPROFILE%/.cache/puppeteer/chrome /grant *S-1-15-2-1:(OI)(CI)(RX)`.

`%USERPROFILE%` is the windows equivalent of `$HOME` and `S-1-15-2-1` is the SID – the user friendly name does not work in non-english Windows.

**Comment by Mansion-dotcom** [comment]
I need

**Comment by mariusrak** [comment]
Will this be fixed? Could it at least print a warning on installation with link to workaround? Thanks.

**Comment by OrKoN** [comment]
The fix will be available once Puppeteer ships Chrome 127.

**Comment by ako-v** [comment]
My puppeteer version is `win64-127.0.6533.72`, I used `icacls $HOME/.cache/puppeteer/chrome /grant "ALL APPLICATION PACKAGES:(OI)(CI)(RX)"`, nothing changed, and still have this problem!
The only way I can start it working is to start my app in debug terminal!!!!
I am using Windows 11.
