### ISSUE TITLE
"page.waitForXPath is not a function"   in 22.10.0

### ISSUE THREAD

**Issue by 3SCadmin** [puppeteer/puppeteer#12485]
Did miss something?

I use puppeteer on and off so I am not an expert.
I have one installation that is version 20.8.3, and `page.waitForXPath`  works!

I just setup a new project (22.10.0), and `page.waitForXPath`  gives the error `TypeError: page.waitForXPath is not a function`

If (in the new project) I downgrade the puppeteer installation to 20.8.3 my code suddenly works.

So did I miss something?  Has that syntax changed between versions.

**Comment by OrKoN** [comment]
Yes, it was removed in v22 (see the changelog for puppeteer-core) and the feature was merged with waitForSelector, so you can use XPath there too the same way as other types of selectors:

```
await page.waitForSelector(`xpath/${xpathExpression}`);
```

See https://pptr.dev/guides/page-interactions#built-in-selectors

**Comment by jtsato** [comment]
```
    page.waitForXPath = async (selector, options) => {
        return await page.waitForSelector(`xpath/${selector}`, options);
    }
```

**Comment by softwareengineerprogrammer** [comment]
> ```
>     page.waitForXPath = async (selector, options) => {
>         return await page.waitForSelector(`xpath/${selector}`, options);
>     }
> ```

Thanks for this.

---

A suggestion for puppeteer maintainers, perhaps future versions should also helpfully remove `waitForSelector` so that everyone can go and add the following to their scripts as well:

```
page.waitForSelector = async (selector, options) => {
    return await page.evaluate(await page.evaluate(`document.querySelector(${selector})`);
}
```

(/s)

**Comment by pauldraper** [comment]
I do not find this string-concatentation any easier to use than the previous well typed function.

**Comment by tjwebb** [comment]
these breaking function removals are such a waste of everybody's time.

now the string we have to send this function isn't a valid anything. it's not valid xpath, nor a css selector, nor anything else. you're inventing your own magic string prefixes that users have to include instead of adding a separate argument, or just keeping the original `waitForXPath` which already made perfectly good sense.

I understand there are cases where developers want to transfer some of their irritation onto users for maintainability reasons, but there is way too  much wholesale creation of new irritation out of thin air for no good reason.

it's starting to look like people here making changes just to farm github karma

**Comment by niceboyat** [comment]
> these breaking function removals are such a waste of everybody's time.
> 
> now the string we have to send this function isn't a valid anything. it's not valid xpath, nor a css selector, nor anything else. you're inventing your own magic string prefixes that users have to include instead of adding a separate argument, or just keeping the original `waitForXPath` which already made perfectly good sense.
> 
> I understand there are cases where developers want to transfer some of their irritation onto users for maintainability reasons, but there is way too much wholesale creation of new irritation out of thin air for no good reason.
> 
> it's starting to look like people here making changes just to farm github karma

I completely agree.
