### ISSUE TITLE
[Feature]: Use semver ranges instead of exact versions for dependencies

### ISSUE THREAD

**Issue by w3nl** [puppeteer/puppeteer#12608]
### Feature description

Now dependencies have hard versions, so we have to wait on a puppeteer release after dependencies have fixes, like vulnerability fixes.
The current version of puppeteer-core has e.g. a dependency of `ws` version `8.17.0`, that has a vulnerability.
There is a new version of `ws` with the fix, version `8.17.1`.
But because puppeteer has strict dependency versions, we have to wait till puppeteer has a new release.
So that will bring an extra wait time for security fixes.

Of you e.g. use `"ws": "^8.17.0"` (with the `^`), then we get already the fix with no changes in puppeteer.

Do you have a policy why you have chosen to point to strict dependency versions, and doesn't allow patch versions?

**Comment by OrKoN** [comment]
I believe you can use the package manager features to override the version if needed using overrides. We choose to specify exact versions to have better reproducibility in case direct dependencies are causing issues. Also, Puppeteer does not seem to be affected by the ws since it does not use the server from the ws package.

**Comment by w3nl** [comment]
Override is indeed an option:
```json
 "overrides": {
    "ws": "^8.17.1"
  }
  ```

But my question was, why would you pin to a version, so we have to override for a fix.
If puppeteer just use e.g. ^, no new release op puppeteer was needed.

So it is just a why on puppeteer, not how I can fix it with an overrule.

**Comment by OrKoN** [comment]
@w3nl if two users install puppeteer at different times, their lock files will have a different version and, thus, when reporting a bug we do not know which dependency version was used.

**Comment by w3nl** [comment]
I understand, but also doesn't always will give you the right answer.
But that is how you try to eliminate some questions about dependencies of puppeteer, because you don't trust the dependencies of puppeteer follow semver, or doesn't test very well.

And if I override, you also don't know the version, or you know that I had a override of a dependency in my package.json.
So the version of dependencies in the lock file of the user is the answer for you.
Then you know the version of dependencies of dependencies was used.

The question in my head is, how can you help the user of puppeteer the best.

- To fix to a version, so if they ask you, the change of an answer is more quick. And you don't have to ask always for the versions in the lock file.
- Or allow fixes that should now break, and user receives more quick bug and vulnerability fixes, and trust that the dependency follows the semver principle.

**Comment by OrKoN** [comment]
We will consider changing the way we declare dependencies.

**Comment by rene-bos** [comment]
For us it is important to be able to update Puppeteer's dependencies without updating Puppeteer because we use an older version of Puppeteer on purpose.

We use Puppeteer inside Alpine Docker images ([docs](https://pptr.dev/troubleshooting#running-on-alpine)) and thus provide our own Chromium executable to Puppeteer. We use Alpine 3.18 so we are [stuck with Chromium 119](https://pkgs.alpinelinux.org/packages?name=chromium&branch=v3.18&repo=&arch=&maintainer=). This versions [corresponds](https://pptr.dev/supported-browsers) with Puppeteer version 21.7.0. Even with the latest Alpine version (3.20), we will be [stuck with Chromium 124](https://pkgs.alpinelinux.org/packages?name=chromium&branch=v3.20&repo=&arch=&maintainer=) and Puppeteer 22.8.2.

All people which supply their own Chromium executable would want to pin to an older Puppeteer version. The pinned Puppeteer dependencies then makes it impossible to upgrade to secure dependencies. This may even give problems when Puppeteer is unaffected by a security issue in a dependency, as our application may use the dependency on its own.

A solution for the problem for now knowing the exact dependency versions may be to ask for the output of `npm list --all` or just the contents of the package-lock.json in situations that a problem could not be reproduced.

**Comment by OrKoN** [comment]
@rene-bos in the meantime, you can use https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides to override any dependency for your application without a need to update Puppeteer.
