### ISSUE TITLE
document.getElementsByTagName returns object tree with empty values?

### ISSUE THREAD

**Issue by webchaz** [puppeteer/puppeteer#1263]
I have the following code:

```
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://www.amazon.com');

  const a = await page.evaluate(() => {
    return document.getElementsByTagName('a')
  });
  console.log(a)
})();
```

This results in a long list of:

```
{
  '0': {},
  '1': {},
  '2': {},
  '3': { jQuery16409950154717072515: 199 },
  '4': { jQuery16409950154717072515: 191 },
  '5': {}
}
```

How do I get the actual DOM from this?

**Comment by ebidel** [comment]
You can't return the actual page DOM back into a puppeteer script. Those objects live in separate worlds. What you get from `page.evaluate()` is a [JSONHandle](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args) that you can actual on. By default, this gets serialized (if it can be). So that's what you're seeing.

`jsonValue()` and `getProperties()` are useful for acting on the return object. For example, if you wanted to get all of the hrefs:

```js
const list = await page.evaluateHandle(() => {
  return Array.from(document.getElementsByTagName('a')).map(a => a.href);
});
console.log(await list.jsonValue());
```

What are you trying to do?

**Comment by ernstbolt** [comment]
Thank you! Just what I was looking for!
