### ISSUE TITLE
[Bug]: BFCache behavior breaks exposeFunction

### ISSUE THREAD

**Issue by DerGernTod** [puppeteer/puppeteer#12662]
### Minimal, reproducible example

```TypeScript
// taken from puppeteer test test/src/cdp/bfcache.spec.ts and augmented with exposeFunction

    const {httpsServer, page, close} = await launch({
      ignoreHTTPSErrors: true,
    });
    let message = '';
    try {
      page.setDefaultTimeout(3000);
      await page.exposeFunction('ping', (msg: string) => {
        message = msg;
      });
      await page.goto(httpsServer.PREFIX + '/cached/bfcache/index.html');

      await Promise.all([page.waitForNavigation(), page.locator('a').click()]);

      expect(page.url()).toContain('target.html');

      await Promise.all([page.waitForNavigation(), page.goBack()]);
      await page.evaluate(() => {
        (window as any).ping('hello');
      });
      expect(message).toBe('hello');
      expect(
        await page.evaluate(() => {
          return document.body.innerText;
        })
      ).toBe('BFCachednext');

    } finally {
      await close();
    }
```

### Error string

Invalid arguments: should be exactly one string.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

i'm actually coming from playwright since we're using it to test our bfcache behavior. to allow finishing our tests in playwright, we expose a playwright "finishTest(assertionFailures: string[])" function that allows us to fail the test on playwright context from the test page. this breaks on puppeteer because it seems that the exposed function isn't properly exposed after a bf cache restore

### Expectation

the exposed function is called and executed properly, without errors

### Reality

an exception is thrown upon calling the exposed function from the browser context, and it's not executed on node context

### Puppeteer version

22.12.0

### Node version

18.20.3

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Linux

**Comment by DerGernTod** [comment]
i don't think it makes sense to post here the full reproducible example, it's easier for you to simply adapt the already existing bfcache.spec.ts i think. i didn't change much, but i would expect "message" to be populated of course:
![image](https://github.com/puppeteer/puppeteer/assets/19726130/2a9c41e0-1ea3-4eb0-b396-01f0122a1939)

**Comment by OrKoN** [comment]
@DerGernTod so you mean that this scenario works in Playwright but does not work in Puppeteer? I am curious if that means that you are testing with both libraries?

**Comment by OrKoN** [comment]
I am able to reproduce the issue (although not the error, but the exposed function is not called after restore). It looks like after the restore the wrapper set up by Puppeteer is gone. Added the test here https://github.com/puppeteer/puppeteer/pull/12663

**Comment by DerGernTod** [comment]
@OrKoN no the error actually happened on playwright when i tested this scenario, and i came across puppeteer when i searched for the exception. maybe playwright wraps certain mechanisms of `exposeFunction` that lead to this error (e.g. incorrectly forwarding it to the wrong function reference upon bfcache restore or something like this, i don't really have any insights into playwright).

i have to admit, i didn't spend more time on the puppeteer reproducer to also build a log or exception forwarding mechanism for that test, because the exception actually happens on the browser context, not on the node context, upon calling the exposed function. it might also only happen on playwright and not on puppeteer, but the error is definitely coming from puppeteer (playwright has no code that would log this exact string, but i found two puppeteer issues that also mention it: https://github.com/puppeteer/puppeteer/issues/4126 and https://github.com/puppeteer/puppeteer/issues/5998#issuecomment-1824020074)

**Comment by OrKoN** [comment]
@DerGernTod sorry, I am a bit confused: I do not think Playwright uses any of the Puppeteer code. I guess you mean that the error is coming from the browser which is why it is the same for both libraries.  I think to reproduce the error, the test needs to change to not give an argument to the ping call but the underlying issue seems to be in Chrome: bfcache restored pages do not restore bindings properly.

**Comment by DerGernTod** [comment]
aah that makes most sense then. that's probably also the reason why i couldn't find the exception anywhere in either codebases (i can't find it in chromium either though 😅 )

**Comment by OrKoN** [comment]
I believe it is in v8 https://source.chromium.org/chromium/chromium/src/+/main:v8/src/inspector/v8-runtime-agent-impl.cc;l=925;drc=6251d9d96d573dcd67ca8ee6aad7bd1225a66dfa

**Comment by DerGernTod** [comment]
that also explains why i couldn't find it on github 😅

**Comment by OrKoN** [comment]
So the error itself is as expected, but how it works under the hood:

1) Puppeteer registers bindings on the window of the page
2) Puppeteer installs scripts to run on new document that wrap the binding on the window object with a javascript function to provide an API that allows passing more than strings

This usually allows to keep bindings for new documents (e.g., when navigating).

In case of the bfcache restore (which is a newer feature in Chrome), it looks like both the bindings and the script to run on the new document are executed on restore but potentially they run in a different order and Puppeteer finds the unwrapped binding instead of the wrapper and unwrapped binding only allows sending a single string argument.
