### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 1103538665** [puppeteer/puppeteer#12813]
### Minimal, reproducible example

```TypeScript
Unable to provide more codes
```

### Background

![微信图片_20240723162331](https://github.com/user-attachments/assets/f429b82c-9b95-4d45-8c2f-489b5d646d11)

### Expectation

Solving optimization memory issues

### Reality

I used pueteer to create a browser instance and opened 50 tabs, receiving instructions through express to automate the page. The entire program can run very well, but the memory of the browser continues to increase. After the program runs stably for a week, the memory consumed by the browser reaches an astonishing 9G. I want to know what is the problem? how to solve this problem。

### Puppeteer version

22.2.0

### Node version

20.15.1

### Package manager

npm

### Package manager version

10.7.0

### Operating system

Linux

**Comment by 1103538665** [comment]
Thanks for the answer, since this is a huge program I have difficulty raising a small example. Can the debugging information you mentioned be set up to be cleaned regularly? Because business requirements cannot close the page, this will affect the stability of the business.

**Comment by OrKoN** [comment]
First, we would need to know what is exactly causing the issue and if it is the expected behavior. It would be really difficult to do without a minimal example representing the actual app. Note that Chrome DevTools Protocol is primarily for debugging and test automation so it might not optimize for long-running processes.
