### ISSUE TITLE
[Bug]: yarn postinstall hangs after browser download

### ISSUE THREAD

**Issue by Seacant** [puppeteer/puppeteer#12833]
### Minimal, reproducible example

```TypeScript
# brand new repo
yarn init

# this will hang
yarn add puppeteer@^20.9.0

# after a few minutes
^Ctrl-C

# running this after the above failure will work
yarn install

# this will cause the issue to reappear
rm -rf ~/.cache/puppeteer/
yarn rebuild
```

### Background

We are hitting build timeouts in our CI environment since about last night. We were able to narrow it down to `yarn install` not finishing at `Building Fresh Packages...` (https://github.com/yarnpkg/yarn/issues/9085) 

From there, we were able to reproduce it locally in our own repo by deleting `~/.cache/puppeteer` and doing a clean install. We then reproduced it in a brand new repo as well. The download appears to finish but hang and never resolve. This is across multiple versions of yarn and multiple OSs (mac and linux).

### Expectation

The postinstall should correctly finish and exit after downloading what it needs

### Reality

The postinstall hangs forever.

### Puppeteer version

20.9.0

### Node version

18.20.4

### Package manager

yarn

### Package manager version

4.1.1

### Operating system

Linux

**Comment by GrayedFox** [comment]
We're unable to simply update puppeteer to the latest version given this means a node upgrade for us too, this bug is blocking our test pipelines entirely.

**Comment by OrKoN** [comment]
I believe it is a bug in the older versions that only happens when the server sends HTTP redirects which is the case after https://github.com/GoogleChromeLabs/chrome-for-testing/pull/108 You can either update Puppeteer to the latest version or use the env variable to use the URL without the redirects: `PUPPETEER_DOWNLOAD_BASE_URL=https://storage.googleapis.com/chrome-for-testing-public/ npm i puppeteer@20.9.0`

Note that those older versions are deprecated and cannot be updated anymore.

**Comment by MooDySmiles** [comment]
We had the same problem with version `21.3.8`, updating to version `21.11.0` seems to have fixed the issue 🤷🏼

**Comment by bjsawyer** [comment]
For those who can't upgrade puppeteer (i.e. we use applitools, which uses puppeteer@21 and upgrading to v22 breaks it), @OrKoN's solution worked for us:

`PUPPETEER_DOWNLOAD_BASE_URL=https://storage.googleapis.com/chrome-for-testing-public npm ci`

**Comment by rocktheshan** [comment]
> For those who can't upgrade puppeteer (i.e. we use applitools, which uses puppeteer@21 and upgrading to v22 breaks it), @OrKoN's solution worked for us:
> 
> PUPPETEER_DOWNLOAD_BASE_URL=https://storage.googleapis.com/chrome-for-testing-public npm ci

For those who are using version older than v20.1.1 and can't upgrade to latest version, you might want to set PUPPETEER_DOWNLOAD_HOST environment variable instead of PUPPETEER_DOWNLOAD_BASE_URL to get rid of this issue.
`PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com/chrome-for-testing-public`
