### ISSUE TITLE
[Bug]:  Failed to launch the browser process

### ISSUE THREAD

**Issue by gsteavenbh** [puppeteer/puppeteer#12839]
### Steps to reproduce

I am using puppeteer - 22.13.1
Deployed it on Azure with Node slim version

Facing this issue after upgrading puppeteer from 19.11.1 to higher versions.
Tried installing google chrome stable & chromium both but facing same issue for both

### Expected results

Pdf should be generated

### Actual results

Error: Failed to launch the browser process!\nchrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information.\n[19:19:0728/170841.821751:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n

**Comment by OrKoN** [comment]
Is it reproducible with the [docker image](https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer) we provide? I am not able to reproduce.  In general, the slim node image is not recommended since it might be missing packages that the browser relies on (since Puppeteer is a not a node-only app, it launches a full browser in the background). Also see the list of system libraries that are needed by the browser: https://pptr.dev/guides/system-requirements

**Comment by gsteavenbh** [comment]
> Is it reproducible with the [docker image](https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer) we provide? I am not able to reproduce. In general, the slim node image is not recommended since it might be missing packages that the browser relies on (since Puppeteer is a not a node-only app, it launches a full browser in the background). Also see the list of system libraries that are needed by the browser: https://pptr.dev/guides/system-requirements


Yeah. I tried with the mentioned docker image as well but the same error that, not sure if it any issue with env. Can you share any sample docker file which is working with puppeteer latest version

**Comment by OrKoN** [comment]
https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer (source: https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile) should work as confirmed by our automated tests
