### ISSUE TITLE
Docker image failed to run with: /etc/machine-id contains 0; Missing X server or $DISPLAY; Failed to connect to the bus;

### ISSUE THREAD

**Issue by da1z** [puppeteer/puppeteer#13009]
### Minimal, reproducible example

```TypeScript
I am running your docker image on railway.app ghcr.io/puppeteer/puppeteer:23.2.0
I did not add any additional configuration, i just added docker image there.
```

### Background

I am trying to start docker image on railway.app

### Expectation

docker image works

### Reality

I am getting few error:

Starting Container

[1:1:0827/162013.158079:ERROR:browser_dm_token_storage_linux.cc(105)] Error: /etc/machine-id contains 0 characters (32 were expected).
[1:1:0827/162013.183979:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
[1:1:0827/162013.184090:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
[1:29:0827/162013.214692:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

container event container died

### Puppeteer version

23.2.0

### Node version

na

### Package manager

npm

### Package manager version

na

### Operating system

Linux

**Comment by OrKoN** [comment]
You need to provide a custom command when running the docker image to start your Puppeteer script as described here https://pptr.dev/guides/docker Also see the automated test run for v23.2.0 https://github.com/puppeteer/puppeteer/actions/runs/10566122223/job/29272539706 as an example. The dbus errors in the browser output are expected since dbus needs to be started at runtime but the dbus dependency is optional. Also, make sure you run the browser in the headless mode as the headful mode would not work without configuring the X server as the error message suggests.

**Comment by da1z** [comment]
@OrKoN thank you! could you please elaborate on how custom command should look like? something like `docker run -i --init --cap-add=SYS_ADMIN --rm puppeteer-test-image node -e "`cat test/smoke-test.js`"` ?

**Comment by OrKoN** [comment]
So in this example, the file content is passed to node using the `-e` argument. That would work if you want to run some puppeteer-only scripts using the image. If you have a more complex app, either mounting it as a volume or building a custom docker image with ghcr.io/puppeteer/puppeteer:23.2.0 as the base image is the way to go. Usually, if you extend the image, you can copy all your app files and you can re-define the CMD in the docker file to be something like `node your-app.js`.

**Comment by da1z** [comment]
@OrKoN yeah, that what i want to do. I have bun hono js server that uses puppeteer and i want to run it in docker. do you have examples of Dockerfile where it extends base image and runs some service?
