### ISSUE TITLE
[Bug]: Failed to launch the browser process! but i dont have any error stderr for debug

### ISSUE THREAD

**Issue by hoangduy02071997** [puppeteer/puppeteer#13051]
### Steps to reproduce

I have bug when launch pdf save file
Error: Failed to launch the browser process! 
but i dont have any thing information about that

I deploy production in Almalinux 8.9
NodeJs version: v20.17.0
Puppeteer version: ^23.3.0

i was set up chromium and fully step

when i run via cli PATH=$PATH:..... run ok but when i call puppeteer that was problem ! 
i check pdf file was saved but why that failed

<img width="976" alt="Screenshot 2024-09-05 at 01 17 44" src="https://github.com/user-attachments/assets/415d319b-7acb-48fd-b5ee-afc046ddf7c9">

the command generate is 

PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node '/xxx/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/tmp\/619073741-0111098001725473430\/index.html","action":"pdf","options":{"path":"\/xxx\/storage\/app\/contracts\/2024-09-05-72c79b75-993e-4c98-aac5-fbbdc7be4057.pdf","args":["--no-sandbox"],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"executablePath":"\/xxx\/storage\/puppeteer\/chrome-headless-shell\/linux-128.0.6613.119\/chrome-headless-shell-linux64\/chrome-headless-shell","format":"A4","printBackground":true}}'

and result i get on linux cli is array buffer
but i run in code was failed with log but no stderr out ! please help me

### Expected results

Let me how to debug stderr 

### Actual results

!!

**Comment by Lightning00Blade** [comment]
Chrome does not explicitly support that Linux distribution [System requirements](https://pptr.dev/guides/system-requirements). 
What you can do to debug this issue is use `dumpio: true` when running `puppeteer.launch`. That will give you the logs from the browser and you can see if there are any errors there.
Also to see Puppeteer debug logs you can run your command with prefix env `DEBUG=puppeteer:*`.
