### ISSUE TITLE
[Bug]: Latest version of Amazon linux 2023 doesn't support epel

### ISSUE THREAD

**Issue by oleg-nikitin-findigo** [puppeteer/puppeteer#13094]
### Minimal, reproducible example

```TypeScript
https://pptr.dev/troubleshooting#running-puppeteer-on-aws-ec2-instance-running-amazon-linux
is an example for outdated OS: https://docs.aws.amazon.com/linux/al2/ug/what-is-amazon-linux.html as it described here: https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#epel
```

### Expectation

Need to have an updated documentation

### Reality

Misconfiguration error happens

### Puppeteer version

23.2.1

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by neehhaa06** [comment]
Hello @oleg-nikitin-findigo 

fix: #13094
``
The issue occurs because Amazon Linux 2023 doesn’t support EPEL, but outdated documentation still references it. You can either find equivalent packages in Amazon Linux 2023's repositories or manually install dependencies. If EPEL is necessary, switch to Amazon Linux 2 and report the outdated documentation to AWS and Puppeteer.
``
