### ISSUE TITLE
Support Drag-and-Drop

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#1376]
We support `ElementHandle.uploadFile` for `<input type=file>` but we don't support emulating dragging in files onto an arbitrary element.

**Comment by sourcec0de** [comment]
Just ran into this issue in selenium. I would be awesome to see support for this in puppeteer.
I'm currently rewriting a lot of our automated tests in puppeteer.

**Comment by fran0254** [comment]
I agree, it would be very interesting. Many websites do not have "input [type = file]"

**Comment by fran0254** [comment]
Hello, I would like to know if in the future it will be supported.
I have finished my development but I can not continue because I need to upload files "drag" and "drop". If this were not possible, would there be any other alternative using puppeteer? .

**Comment by aslushnikov** [comment]
@fran0254 we prioritize work based on the `demand / effort` ratio. Since we don't see much interest in this issue, and the effort is unclear but surely requires upstream contribution to chromium, this issue is a low-pri for us.

**Comment by aslushnikov** [comment]
For the record: there's a [DevTools API proposal](https://docs.google.com/document/d/14k80eesa60RL9Q5RjDNG6M4EoLayv9SO0Y0EagKhAbw/edit?usp=sharing) on drag-and-drop.

**Comment by Couragyn** [comment]
I would love this feature

**Comment by LukeHero** [comment]
Would really appreciate this feature also.

**Comment by agentzh** [comment]
Same here.

**Comment by Dginozator** [comment]
In my case it has been resolved with direct search input[type="file"] tag, not button

**Comment by frankinedinburgh** [comment]
me too

**Comment by frankinedinburgh** [comment]
> Would really appreciate this feature also.

me too

**Comment by allenhwkim** [comment]
I have just tested mouse down/move/up with pupeeteer at https://try-puppeteer.appspot.com/
However it did not work with no errors
This is the code that I have tested.
```
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('http://html5demos.com/drag/');
await page.waitFor(2000);

await page.mouse.move(438,  194);
await page.mouse.down();
await page.waitFor(100);
await page.mouse.move(436,  192, { steps: 2});
await page.waitFor(100);

await  page.mouse.move(208,  301, { steps: 200 });
await  page.mouse.up();

console.log('xxxxxxxxxxxxxxxx');
await page.screenshot({path: 'screenshot.png'});
console.log('yyyyyyyyyyyyy');
```

![image](https://user-images.githubusercontent.com/1437734/48658086-ead17180-ea09-11e8-9b21-84fe89175b03.png)

However the above code works with kleki.com, which is a canvas drawing.
It seems that html5 element drag and drop is not working with mouse down/move.up

![image](https://user-images.githubusercontent.com/1437734/48669406-0011d300-ead2-11e8-95d2-b1413ee1bc6b.png)

**Comment by ffMathy** [comment]
I need this as well. Building an automation framework.

**Comment by Bhav1907** [comment]
Any solution we have on this ?

**Comment by rfeie** [comment]
Any word on this being addressed? It is understandable if it is not a priority but I just want to know for planning purposes.

**Comment by sharma-amit-1120** [comment]
My team needs this as well, any updates about the timeline are highly appreciated.

**Comment by BenWeigt** [comment]
Registering my interest in this issue. Drag drop remains the only (and gaping) hole my error reproduction emulator.

**Comment by anton-yarchuk** [comment]
Can't test drag-n-drop feature without drag-n-drop in puppeteer:(

**Comment by elaine95** [comment]
I would also like this drag and drop feature since it is a very common functionality and testing drag and drop using puppeteer is quite in demand now. 
Using page.mouse.down, mouse.move and mouse.up didn't work for me either. I also tried it in https://try-puppeteer.appspot.com/ and below is my code: 

const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('http://html5demos.com/drag/');
await page.waitFor(2000);

// Move mouse to the item that will be drag and mouse down
const dragItem = await page.$('a[id="one"]');
const  dragItemBox = await dragItem.boundingBox();
const x = dragItemBox.x + (dragItemBox.width/2);
const y = dragItemBox.y + (dragItemBox.height/2);

console.log(x);
console.log(y);

await page.mouse.move(x,  y);
await page.mouse.down();
await page.waitFor(100);


// Move teh drag item to container and release mouse 
const container = await page.$('div#bin');
const containerBox = await container.boundingBox();
const x1 = containerBox.x +  (containerBox.width/2);
const y1 = containerBox.y + (containerBox.height/2);

console.log(x1);
console.log(y1);

await page.mouse.move(x1,  y1);
await page.waitFor(100);
await  page.mouse.up();


// Supposely the 'Best VPN' item should be drag into container and it should be disappeared on the right side. However it still remain at the same place since the mouse down, mouse move and mouse up didn't quite work and the real drag and drop 

console.log('Finished');
await page.screenshot({path: 'screenshot.png', fullPage: true});
console.log('Screenshot taken');

It didn't drag the item into the bin as expected.

**Comment by jpoints** [comment]
I think I ran into the issue as well. 

Part of my test page has custom drag and drop functionality with jquery.
The mouse down, move, mouse up steps worked correctly with this scenario.

However, another part relies on the browser's native drag and drop behavior. 
(For example, the user can drag images by default, view a ghost image, and drop it in a dropzone)
With the native drag in puppeteer, it appears that mouse down it not triggering the drag event, and nothing happens on mouse up (drop). Since the mouse cursor is not provided, I did not expect the ghost image, but that would be a nice to have.

**Comment by chelproc** [comment]
We can now upload our files to dropzone by converting `HTMLInputElement.files` to `DragEvent.dataTransfer.files` like this:

```JavaScript
const fileInputIdentifier = "some-unique-identifier";
const dropZoneSelector = ".dropzone";
const filePath = "/path/to/file";

await page.evaluate((fileInputIdentifier, dropZoneSelector) => {
    document.body.appendChild(Object.assign(
        document.createElement("input"),
        {
            id: fileInputIdentifier,
            type: "file",
            onchange: e => {
                // Do not use DragEvent instead of Event.
                // DragEvent has native dataTransfer property, which cannot be created by scripts.
                document.querySelector(dropZoneSelector).dispatchEvent(Object.assign(
                    new Event("drop"),
                    { dataTransfer: { files: e.target.files } }
                ));
            }
        }
    ));
}, fileInputIdentifier, dropZoneSelector);

const fileInput = await page.$(`#${fileInputIdentifier}`);
await fileInput.uploadFile(filePath);
```

...unless dropzone checks `Event.isTrusted`.

See [this article](https://ja.stackoverflow.com/questions/48184/dropzone%E3%81%A7%E5%AE%9F%E8%A3%85%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%E3%82%92puppeteer%E3%81%8B%E3%82%89%E7%99%BB%E9%8C%B2%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95).

**Comment by DJ-Glock** [comment]
Hi
Also interested in built-in solution for this.

**Comment by wardnath** [comment]
Hey if anyone is stuck trying to get this to work and needs an immediate solution check out my post over here: https://github.com/puppeteer/puppeteer/issues/1366#issuecomment-589828387

I hope puppeteer provides a built in solution, in the meantime this above approach worked for me.

**Comment by alexgalkin** [comment]
Waiting for this feature also.

**Comment by hmoreras** [comment]
This would be helpful ! Drag elements over time is more common. Waiting for this to be able to implement my unit test. :)

**Comment by sundaycrafts** [comment]
Maybe this #74 pull request works for this issue?

**Comment by CookieMonster42** [comment]
Having the same wish for that request.

**Comment by s2005lg** [comment]
What's the conclusion ? I'm having the same issue right now

**Comment by alandawi** [comment]
Also me. Would be great to have this feature.
