### ISSUE TITLE
Should get an error when select option is not found

### ISSUE THREAD

**Issue by TildeWilliams** [puppeteer/puppeteer#1384]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: OSX 10.12.6
* URLs (if applicable): not available

**What steps will reproduce the problem?**
HTML:
```html
<select id="my-select">
  <option value="first-option">First Option</option>
</select>
```

```js
await page.select('select#my-select', 'First Option');
```

**What is the expected result?**
I would expect an error that Puppeteer was unable to select the option specified since it seems to be looking at the `value` attribute and not the innerHTML. 

**What happens instead?**
The code executes without warning or error

**Comment by dios-david** [comment]
Hi @TildeWill,

I implemented the change (#1617) as I also agree with you, I think Puppeteer should throw an error in these cases.
Otherwise the current [documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselectselector-values) says:

> returns: <Promise<Array<string>>> Returns an array of option values that have been successfully selected.

Which is also an acceptable solution, because you can compare the result with your original values, so you can filter out the invalid ones.

What do you think @TildeWill, @aslushnikov ?

**Comment by TildeWilliams** [comment]
This looks prefect. Thanks for the change! I like the error because it helps in the case where I'm not already checking the returned promise - making the problem much more discoverable and speeds up test-writing.

**Comment by aslushnikov** [comment]
There's been an extensive discussion about throwing an error in #1099. Returning currently selected options seems to be a good compromise to me that satisfies all the interested parties.

The throwing behavior could be simulated with little effort:
```js
const selected = await page.select('select#my-select', 'First Option');
console.assert(selected.includes('First Option'), 'Failed to select an option!');
```

Closing this for now; we can revisit this later if there are many clients who are unhappy with the API.
