### ISSUE TITLE
Method to uniquely identify Pages/Targets?

### ISSUE THREAD

**Issue by ks07** [puppeteer/puppeteer#1428]
When using `browser.pages()` or `browser.targets()` is there a way to uniquely identify each Page object? I.e. is there some property of the Page object that I can compare with those returned by `browser.pages()` to identify if they're both referencing the same browser tab?

**Comment by Khady** [comment]
I think this is what the targetId is for. But it is not officially available. I get it with `page._client.targetId` for now. Maybe this value should be made officially part of the page API.

**Comment by ks07** [comment]
@Khady Thanks - I think you're right. +1 to exposing it officially!

**Comment by vsemozhetbyt** [comment]
Do `somePage === pages[index]` or `Object.is(somePage, pages[index])` work here?

**Comment by aslushnikov** [comment]
@ks07 you're guaranteed to have only one `page` instance for the target, so you can use triple-equals to compare pages.

**Comment by Khady** [comment]
I still think it would be interesting to have the targetId exposed. I use it while debugging (checking the number of pages opened, which ones are opened, etc) from outside of puppeteer. And to pass it to other tools like lighthouse.

**Comment by aslushnikov** [comment]
> I still think it would be interesting to have the targetId exposed. I use it while debugging (checking the number of pages opened, which ones are opened, etc) from outside of puppeteer.

@Khady would it help if we give you a nicer `toString()` for target/page objects?

> And to pass it to other tools like lighthouse.

Can you please share if there are other tools besides lighthouse that you use? I'd love to take a look.

The lighthouse has been mentioned a few times already; we'd probably need to do a better interop. cc @paulirish

**Comment by Khady** [comment]
> Can you please share if there are other tools besides lighthouse that you use? I'd love to take a look.

For now, I'm using puppeteer, lighthouse, chrome-launcher and handmade requests using CDP or the `/json`,`/json/version`,`/new`,`/close` commands. Trying to unify all this. I'm happy using `page._client.targetId` for now.

I created an [issue](https://github.com/GoogleChrome/lighthouse/issues/3837) and a [PR](https://github.com/GoogleChrome/lighthouse/pull/3857) on lighthouse repository while trying to find a nice way to mix puppeteer and lighthouse. But the story doesn't seem to be as easy as expected. I would be very happy to see a conversation/guideline about the interop between those two tools.

This specific PR is relying on the targetId. But I'm not a CDP/Chrome expert. So there is maybe a better way to achieve this rather than to pass an id everywhere.
