### ISSUE TITLE
feature request : version number of puppeteer

### ISSUE THREAD

**Issue by MehdiRaash** [puppeteer/puppeteer#1468]
If I'm not mistaken, in the code or at least in the API I didn't find a method to just yield the current version number of pptr instance.

It's not needed? @aslushnikov

**Comment by Garbee** [comment]
What is your use-case for knowing this information pragmatically?

**Comment by MehdiRaash** [comment]
I just thought when we have got **browser version()** method available in pptr, it would be nice one for pptr itself, the _use cases_ vary, like you have got pptr version _A_ running, and _B_ running, so let's say they share some common utility... 
You think these things are useless?

**Comment by Garbee** [comment]
The browser version is far more useful in itself for writing test output and logging data. Especially since you can have one version of puppeteer connect to multiple Chrom{e,ium} instances while doing a single execution.

As far as "sharing utilities" I'm not sure I understand a real-world scenario where that would cause an issue. Could you please provide one? It's best to have feasible cases for new functionality instead of pure theoretical needs. As far as this goes, either your "shared utility" is a micro-service in which case it runs independently of the multiple instances and is not tied to any version in particular; or you have a library that is shared among multiple microservices that each have a puppeteer dependency. Now, in the latter scenario you'd update the utility and publish a new version if a breaking change occurs in puppeteer. At that point, you update your microservices individually as you upgrade puppeteer in each. And each would still self-stand in an isolated manner. In both cases, having a puppeteer version accessed programatically isn't necessary nor even a good long-term method of handling changes.
