### ISSUE TITLE
Asynchronous parallel screenshotting

### ISSUE THREAD

**Issue by Oleg-Arkhipov** [puppeteer/puppeteer#1479]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Debian Jessie (Linux 5d08acbab1a9 4.13.12-200.fc26.x86_64) (from `node:8-slim` Docker image)

**What steps will reproduce the problem?**

I have set up very basic Express.js application which takes URL in request and returns screenshot in response. Here is the important code:
```js
router.post('/screenshot', async function (req, res) {
  const page = await browser.newPage();
  await page.goto(req.body.url);
  const buffer = await page.screenshot();
  await page.close();
  res.set('Content-Type', 'image/png');
  res.write(buffer, 'binary');
  res.end(null, 'binary');
});
```
(`browser` is created only once).

**What is the expected result? / What happens instead?**

When I send multiple requests at the same time they all are completed synchronously, one after another.
Node's ``--trace-sync-io`` flag outputs a lot of info about sync I/O output too.

*Question*: Am I right in suggestion that it is not possible to use Puppeteer for asynchronous screenshotting with one Node process and I have to spawn multiple instances of Node?

Sorry if that should be obvious, I just want to confirm (Google did not help). Thanks in advance.

**Comment by vonGameTheory** [comment]
Probably chrome and not node that can't do simultaneous screenshots.  I suspect it has to bring the tab you want to screenshot into focus, and therefore can only do one at a time (just like in the browser -- you can see only one tab at a time).

But instead of multiple node processes, you could launch multiple browser instances from a single node process since you are going to get them either way (e.g. you could have 10 nodes launching 1 chrome each, or 1 node launching 10 chromes).  Just don't launch so many at once as to overburden your system.   Overall speed probably equal if you re-use instances (although on my system anyway startup time is negligible) -- just make sure to close them if you don't re-use them.

**Comment by TheGuywithTheHat** [comment]
I encountered issue, and "solved" it the way @vonGameTheory suggested (opening multiple browser instances). 3, 4, or 5 instances improved the performance, but after that the total time to make many screenshots started going back up.

Keeping a pool of tabs open (one per browser) reduced screenshot times by ~1 second per screenshot. However, chromium remains open if node crashes (#1367), and if you're running headless you have to manually kill the process with task manager or `kill`.

**Comment by Oleg-Arkhipov** [comment]
@vonGameTheory, @TheGuywithTheHat thanks for the replies! Opening new Chrome each time is what I considered to do initially. But with that code (I know it is dumb, that is just for a quick test):
```js
const browserPool = [];
(async () => {
  for (let i = 0; i < 4; i++) {
    browserPool[i] = await puppeteer.launch({args: ['--no-sandbox']});
    await browserPool[i].newPage();
  }
})();

let index = 0;
router.post('/screenshot', async function (req, res) {
  const browser = browserPool[index];
  if (index < 3) {
    index += 1;
  } else {
    index = 0;
  }
  const page = (await browser.pages())[0];
  await page.goto(req.body.url);
  const buffer = await page.screenshot();
  res.set('Content-Type', 'image/png');
  res.write(buffer, 'binary');
  res.end(null, 'binary');
});
```
all requests are still completed synchronously. I see a lot of processes are spawned at the same time, yes, requests are dispatched round-robin to different browsers, but completed strictly one after another (e.g. if 2 secs are required to make a screenshot and I launch 4 requests simultaneously, the second one will take ~4 secs and the last one will always take ~8 secs).

Do I miss something?

**Comment by vonGameTheory** [comment]
Works ok when I try it (with slightly different code) -- are you "await"ing each request in sequence causing them to block before the next one can start?  (Or something like that.)

**Comment by Oleg-Arkhipov** [comment]
@vonGameTheory thanks for your information about the fact that you made it to work, so I understood that it is something on "my" side, not Puppeteer's. Indeed, the code is right, the problem is that I was testing by refreshing few tabs with requests in my own Chrome, and [Chrome sends only one request to the same origin at the same time](https://stackoverflow.com/a/35826053/2725901), haha. I then tested with `ab` tool and everything is right. Thanks!

**Comment by drmrbrewer** [comment]
@Oleg-Arkhipov I'm interested in your thoughts on this, because I'm wondering the same thing.  Please can you tell me: are you satisfied now that *with your original scheme* (single browser, multiple pages) the pages are processed and screenshotted in parallel?  Or is it necessary to use your modified scheme (multiple browsers, each with a single page)?  The former seems so much simpler to me... open a single browser (just once), then open/close multiple pages (as and when required)... so I hope that you have determined that the pages are indeed processed in parallel in that situation :)  Thanks.

**Comment by fringd** [comment]
I would expect that a single browser with multiple pages would still allow screenshots, but if it doesn't, then there should be an exception thrown instead of just behaving indeterminately.

Ideally I'd like a page screenshot to await a lock on switching tabs before taking the screenshot.

Any chance this can be re-opened?

**Comment by aslushnikov** [comment]
> Question: Am I right in suggestion that it is not possible to use Puppeteer for asynchronous screenshotting with one Node process and I have to spawn multiple instances of Node?

@Oleg-Arkhipov trying to do screenshots in parallel inside a single browser will result in screenshots done sequentially; we serialize them per-browser. Internally, we have a `screenshotTaskQueue` for that:

https://github.com/GoogleChrome/puppeteer/blob/f6b7c1331628dfb45a916ec5cd1f04e5ed61bf01/lib/Browser.js#L28-L37

> I would expect that a single browser with multiple pages would still allow screenshots, but if it doesn't, then there should be an exception thrown instead of just behaving indeterminately.
>
> Ideally I'd like a page screenshot to await a lock on switching tabs before taking the screenshot.

@fringd That's exactly what we do.

**Comment by fringd** [comment]
Okay it was something else wrong with my server causing timeouts I think.
My bad

**Comment by tomgallagher** [comment]
I've been playing around with the idea of a Puppeteer pool, using the [generic-pool](https://github.com/coopernurse/node-pool) from NPM to handle multiple instances of Puppeteer. 

I know this is something that is outside the realms of Puppeteer issues but it seems like it's going to be common usage so worth discussing.

What I have found is that, running the node app inside a Cloud9 workspace, any attempt to run a pool greater than 3 or 4 causes a massive spike in page crashes and timeouts.

I'm guessing that the network connection of the workspace is being overloaded. I'd love to hear if anyone has been successful in running a pool larger than that on a garden variety machine. I'm going to try it on an Amazon EC2 instance at varying sizes and see if that makes a difference. I'll report back.

**Comment by syzer** [comment]
@tomgallagher have you considered reduce image resolution before sending images back and forth ?

**Comment by tomgallagher** [comment]
@syzer 
I'm not actually doing any screenshots - if that's what you're referring to - I'm just doing page loads. What I have considered and implemented is running a stripped down version of the browser by aborting requests for advertising scripts, images and media, etc. And that did make a difference in terms of the time taken for the pool to complete 100 sites. However, the browsers in the pool still become unresponsive from time to time. In a perfect world, Puppeteer would have have a `browser.on(error) `handler, although I imagine that's going to be pretty complex to put together.

**Comment by syzer** [comment]
@tomgallagher we did price (near) realtime tracker using https://www.npmjs.com/package/working-x-ray 
Maybe you don't need puppeteer after all?

**Comment by intellix** [comment]
Also having massive issues with parallel screenshot handling and can't seem to find a sweet spot or how to properly optimise this to perform well and not crash. I've currently got 12 arrays of pages to visit and screenshots to take (4 sites with desktop, mobile and tablet with different device ratios).

12 Browser with 1 page each causes server to have load of 13+ and eventually things start timing out and browsers start crashing outright
4 Browsers with 3 pages each causes load of around 6+ and again, things start to timeout.
1 Browser with 12 pages is super slow, seems to be ok, but if I only have 2 requests in, then a screenshot just stops..... the whole thing just stops and there's no error, like it just gave up and there was nothing thrown.

These are my params:
```ts
const browser = await puppeteer.launch({
  headless: true,
  args: ['--no-sandbox', '--disable-setuid-sandbox'],
});
this.page = await this.browser.newPage();
await this.page.setViewport({
  ...device.viewport,
  height: scrollHeight,
});
await this.page.screenshot({ fullPage: true });
```

Originally ran on an AWS t2.medium and then tried a c5.large. Nothing seems stable. I wouldn't mind so much if it was just slower but it's either a timeout fest or things just give up. Are there any recommendations for the flags when starting up perhaps or some extra params to setup the server with? I've set shared-mem to 1gb

**Comment by drmrbrewer** [comment]
@intellix I'm no expert but rather than setting shared mem to 1gb have you tried disabling it entirely with `--disable-dev-shm-usage` as a launch option?  See [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#tips).  Also, what args are you passing to `page.goto()`, for determining when navigation is considered to have succeeded?

I'm interested in any conclusions you come to regarding the "sweet spot"... I've been experimenting in the same way... including trying to re-use pages as well as re-using browsers.  I'm finding things to be very stable, but the problem I'm finding is that using puppeteer/chrome requires *so* much more CPU than using phantomjs to do the same job, and I haven't ruled out that I'm just not using puppeteer correctly yet!

**Comment by intellix** [comment]
@drmrbrewer using `page.goto(somewhere, { waitFor: 'networkidle0' })` and recently added some stuff to find links and click those instead if they exist for better SPA perf, but it seems like the server just stops working randomly at the screenshot stage according to console logs.

I'm not seeing much memory usage but when I increased it to 1gb initially things stopped crashing, maybe it needs increasing or disabling entirely... sounds like a good idea and hope it works, thanks :)

**Comment by drmrbrewer** [comment]
@intellix yep I recall that I was getting lots of strange and unexplained errors (typically not immediately but within after a short time of being up and running), and these errors completely went away as soon as I started using `--disable-dev-shm-usage` as a launch option.  As it says in the link, with that option enabled, `/tmp` is used instead of `/dev/shm`.  However, I would imagine that 1gb shared mem would have a similar effect, unless you are making particularly heavy use of shared mem ;)

**Comment by fringd** [comment]
I had serious issues with webpack devel server choking. Production
compiling my site sped things up.

**Comment by banxian** [comment]
@Oleg-Arkhipov  sometimes (await browser.pages())[0] return an undefined object (about 10 in 40 parallel browser instance). I think it's better check pages() length and then wait for blank page created or just fallback to newPage() call.

**Comment by tajo** [comment]
@aslushnikov 

> > Question: Am I right in suggestion that it is not possible to use Puppeteer for asynchronous screenshotting with one Node process and I have to spawn multiple instances of Node?
> 
> @Oleg-Arkhipov trying to do screenshots in parallel inside a single browser will result in screenshots done sequentially; we serialize them per-browser. Internally, we have a `screenshotTaskQueue` for that:
> 
> https://github.com/GoogleChrome/puppeteer/blob/f6b7c1331628dfb45a916ec5cd1f04e5ed61bf01/lib/Browser.js#L28-L37
> 
> > I would expect that a single browser with multiple pages would still allow screenshots, but if it doesn't, then there should be an exception thrown instead of just behaving indeterminately.
> > Ideally I'd like a page screenshot to await a lock on switching tabs before taking the screenshot.
> 
> @fringd That's exactly what we do.

Does the same thing apply for `elementHandle.screenshot([options])` API? It seems it should but this method also does some additional scrolling to bring the element to viewport, right? If I run it in parallel for multiple elements, the crops are not properly aligned and I end up with different results every run (race condition?).

[This](https://github.com/GoogleChrome/puppeteer/blob/5ee21d97e796263857b9f3fbeaf63366179d346f/lib/JSHandle.js#L367) should be queued and called synchronously?

**Comment by aslushnikov** [comment]
> If I run it in parallel for multiple elements, the crops are not properly aligned and I end up with different results every run (race condition?).

@tajo Yes, this is a race condition. Please, queue these calls on your end.

> This should be queued and called synchronously?

Queueing these call's on Puppeteer side doesn't make much sense to me: `elementHandle.screenshot` is no different from `page.click` - both scroll the page, stating this behavior in their documentation, and thus don't make much sense to run in parallel.
