### ISSUE TITLE
About chromium version

### ISSUE THREAD

**Issue by Kevindyb** [puppeteer/puppeteer#1498]
*About chromium version*

**Excuse me, how to use the 55 version of chromium library?**

Commit: ea46662d4008c9fcfb8a3ee1933dd2f5e90a9c3b
Branch Base Commit: 614d31daee2f61b0180df403a8ad43f20b9f6dd7
Branch Base Position: 423768
V8 Version: 5.5.372.29
V8 Position: 59
Skia Commit: d1740f81c843c65acd58d1b571ce94b90fee99d0

**Thank you**

**Comment by ebidel** [comment]
If you want to use another version than the one Puppeteer bundles, use `executablePath`: https://github.com/GoogleChrome/puppeteer#default-runtime-settings

However, 59 is the absolute minimum version that's required since that's the version that headless chrome was released in. See https://www.chromestatus.com/features/5678767817097216.

**Comment by Kevindyb** [comment]
Thank you very much！！
