### ISSUE TITLE
Clarify whether this uses Chrome or Chromium

### ISSUE THREAD

**Issue by karloskalcium** [puppeteer/puppeteer#1516]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13
* Platform / OS version: Mac OSX 10.12.6
* URLs (if applicable):

The documentation is rather confusing - it is hard to tell if you are using Chromium or Chrome (or both?)

For example:
"Puppeteer is a Node library which provides a high-level API to control headless Chrome over the DevTools Protocol. It can also be configured to use full (non-headless) Chrome."

then
" When you install Puppeteer, it downloads a recent version of Chromium (~71Mb Mac, ~90Mb Linux, ~110Mb Win) that is guaranteed to work with the API"

then
"Puppeteer launches Chromium in headless mode. To launch a full version of Chromium, set the 'headless' option when launching a browser:"

then
"By default, Puppeteer downloads and uses a specific version of Chromium so its API is guaranteed to work out of the box. To use Puppeteer with a different version of Chrome, pass in the executable's path when creating a Browser instance:"

Within the course of two sentences, it changes from Chromium to Chrome.

Another example:
"Puppeteer works only with Chrome. However, many teams only run unit tests with a single browser (e.g. PhantomJS). In non-testing use cases, Puppeteer provides a powerful but simple API because it's only targeting one browser that enables you to rapidly develop automation scripts.

Puppeteer uses the latest versions of Chromium."

Does Puppeteer use Chrome, or Chromium?

Please clarify. I think the docs should also be updated to be consistent in the use of 'chrome' vs 'chromium'

FWIW, when I install it on a mac, it installs Chromium into .local_chromium.

**Comment by ebidel** [comment]
I think we can clean some of this up, but both are mentioned for good reasons. The first is that it's better for SEO. Devs are more likely searching for "headless Chrome library" rather than "headless Chromium". Second, lots of folks still don't know what Chromium even is. Thirdly, Puppeteer _is_ a indeed a library for working with headless Chrome. It installs the open source version Chromium, but can be used with any Chrome* binary.

**Comment by karloskalcium** [comment]
That's fair, but
1) for SEO, I reckon that mentioning once or twice, in the FAQ, that this works with headless chromium and headless Chrome would be sufficient.
2) If you are using puppeteer, you are likely a developer, and should thus be expected to know the difference btw chrome/chromium, and it probably wouldn't hurt to link to a page explaining that difference here. The difference *is* important to developers, because if your users are using Chrome but you're testing in Chromium, there may be relevant differences.
3) on point 3, please find a way to explain that better in the FAQ. I read it and the documentation several times, and was confused as to when/how/if one could use chrome vs. chromium - mostly due to the fact that the current documentation seems to use the terms interchangeably.

Really appreciate the response, and hoping you can improve the documentation. I'd be happy to help but I don't really know what the docs are supposed to say!

**Comment by elviswolcott** [comment]
> "By default, Puppeteer downloads and uses a specific version of Chromium so its API is guaranteed to work out of the box. To use Puppeteer with a different version of Chrome, pass in the executable's path when creating a Browser instance:"

>Within the course of two sentences, it changes from Chromium to Chrome.

You're right, that's because in the first case it means Chromium and in the second it means Chrome. Puppeteer comes with a Chromium browser pre included, but you might not always want to use this. Say a user on the very old Chrome 17.0.963 was having problems and you wanted to run your tests on it. It's not very useful to run on the relatively new Chromium included with Puppeteer, so you could download Chrome 17.0.963 and have give Puppeteer the excitable path and run your tests against that client version.

So it is correct to say
> Puppeteer uses the latest versions of Chromium.

But it is correct to say 
>"Puppeteer is a Node library which provides a high-level API to control headless Chrome over the DevTools Protocol. It can also be configured to use full (non-headless) Chrome."

because Chromium is a headless Chrome browser and it can be configured to run "full" Chrome.

Hope that clears it up a bit.

**Comment by karloskalcium** [comment]
I just think the language could be a lot more clear. It doesn't make sense to say "It works with the latest version of X. To use another version of Y, do the following."  (especially if users are already possibly confused between chrome/chromium)

Rather, it would be more clear to say something like:
By default, Puppeteer provides a high-level API to control headless Chromium or Chrome over the DevTools protocol. It uses the latest Chromium by default, but can be configured to use a particular version of Chromium or Chrome as needed."

**Comment by aslushnikov** [comment]
> Rather, it would be more clear to say something like:
By default, Puppeteer provides a high-level API to control headless Chromium or Chrome over the DevTools protocol. It uses the latest Chromium by default, but can be configured to use a particular version of Chromium or Chrome as needed."

@karlwbrown would you like to send a PR for this and other cases of Chrome/Chromium confusion?

**Comment by karloskalcium** [comment]
Sure, I will take a shot...
