### ISSUE TITLE
Tor SOCKS5 proxy : ERR_NO_SUPPORTED_PROXIES

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#1527]
Lunching puppeteer with: 

`browser = await puppeteer.launch({timeout :90000, headless: false, args: ['--no-sandbox', '--proxy-server="socks5://127.0.0.1:9050"']});`

Gives the error: 
`ERR_NO_SUPPORTED_PROXIES`

Ubuntu server used.

**Comment by vonGameTheory** [comment]
Get rid of the double-quotes around the proxy address.  (And are you sure that shouldn't be port 9150?)

**Comment by aslushnikov** [comment]
Looks like @vonGameTheory nailed it; speculatively closing

**Comment by jatinseth2007** [comment]
@aslushnikov @vonGameTheory Why we should use port 9150?, it's not working for me, I have tried 9050(socket port) and 9051(control port) both ports, all three ports are not working for me.

my code is given below:
` let browser = await puppeteer.launch({
                    headless: false,
                    args: ['--proxy-server=socks5://127.0.0.1:9051'],
                    timeout: 0
                });`

9150 port error - net::ERR_PROXY_CONNECTION_FAILED
9051 port error - net::ERR_TIMED_OUT
9050 port error - no error is coming but it seems it's not using any proxy settings.

I am using Tor with password, how to authenticate while connecting.

**Comment by vonGameTheory** [comment]
The comment about the port was just a secondary possible problem as I think that's the standard port the TOR listens on unless you change it, so I was just saying to that poster essentially "make sure you use the correct port for your proxy setup", whatever that is.  The problem you seem to be having now looks like a tor problem more than a puppeteer problem -- make sure tor is working properly (on the same local network obviously since you're using a local address, and on the chosen port, etc etc).  Authentication could also be the problem, which is tricky in puppeteer.  Turn off password authentication and see if it works.  (Is that necessary since it is local?)

**Comment by jatinseth2007** [comment]
@vonGameTheory Thanks, I fixed the problem with Tor, removed password authentication  and it's working fine, I will be putting this project on production, for that we need to switch password authentication ON, do you have any idea how to do that or if you know any article which can guide me to achieve so ?

**Comment by vonGameTheory** [comment]
There is an Authenticate function in puppeteer, I don't know if it works with a tor socks proxy.  (I think it fails with https proxy if I'm not mistaken -- I use it ok with proxies, but haven't tried tor.)  Or if you need the authenticate function for the target page itself it can be a problem I think.  (You can also try manually setting the auth header with the extraHeaders option.)

If that doesn't work,  some hack involving a second proxy in the middle or a ssh tunnel to tor that puppeteer can connect to without auth (or with an auth that works).
