### ISSUE TITLE
PDF Generation hanging for documents with many large images

### ISSUE THREAD

**Issue by matthewdingley** [puppeteer/puppeteer#1534]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: OSX 10.13.1
* Node versions: tested with v8.6.0, v8.9.0 & v9.2.0
* URLs (if applicable): N/A

**What steps will reproduce the problem?**

The code below isolates a problem discovered while using Puppeteer to generate PDF reports. While Puppeteer has been fantastic so far, I have come across a problem with pages containing a large number of images.

index.html: 
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Test App</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

pdfImages.js: 
```
const puppeteer = require('puppeteer');

const IMAGE_URIS = [
  // A list of 1949 image URIs as strings
  // The images used range in size between 1KB to 1.7MB with an average size of 200KB.
];

const PDF_OPTIONS = {path: `${__dirname}/output.pdf`, format: 'A4', printBackground: true, landscape: false, margin: {top: '10mm', left: '10mm', right: '10mm', bottom: '15mm'}};
const IMAGE_LOADING_TIMEOUT = 60 * 1000 * 5;

function addImagesToPage(imageUriList) {
  const root = document.getElementById('root');
  imageUriList.forEach((imageUri) => {
    const div = document.createElement('div');
    const img = new Image();
    img.src = imageUri;
    img.style = 'max-width: 20vw; max-height: 20vh;';
    div.appendChild(img);
    root.appendChild(div);
  });
}

function waitForAllImagesToCompleteLoading() {
  const allImagesInDocument = Array.from(document.getElementsByTagName('img'));
  return allImagesInDocument
      .map((img) => img.complete)
      .every((completeStatus) => completeStatus);
}

let browser;
puppeteer.launch({headless: true})
  .then((newBrowser) => {
    browser = newBrowser;
    return browser.newPage();
  })
  .then((page) => {
    return page.goto(`file://${__dirname}/index.html`)
    .then(() => page.evaluate(addImagesToPage, IMAGE_URIS))
    .then(() => page.waitForFunction(waitForAllImagesToCompleteLoading, {timeout: IMAGE_LOADING_TIMEOUT}))
    .then(() => page.pdf(PDF_OPTIONS))
    .then(() => page.close());
  })
  .then(() => browser.close());
```

I run this using:
`env DEBUG="puppeteer:*" node --max-old-space-size=16384 pdfImages.js`

**What is the expected result?**
Running this code should generate a PDF.

Please note that running this with 1100 images and with --max-old-space-size=8174, the code runs without a problem.

**What happens instead?**
Running the code with the command above causes the code to hang on the PDF generation stage. Please see [HungPdfPrint.log](https://github.com/GoogleChrome/puppeteer/files/1527613/HungPdfPrint.log) for the logs produced when this happens.

The code consistently hangs in the following combinations:
- When --max-old-space-size=8174 (8GB) or 16348 (16GB) and,
- When the number of images is 1200, 1500 or 1949.

The code crashes when the --max-old-space-size flag is removed with an out of heap memory error. See this log: [OutOfMemoryCrash.log](https://github.com/GoogleChrome/puppeteer/files/1527858/OutOfMemoryCrash.log)

Again, when the number of images is 1100 and --max-old-space-size=8174 the code runs without a problem

**Comment by matthewdingley** [comment]
A couple of extra data points that may be useful:

1. This still happens using Chrome Canary (65.0.3287.0)
2. Running this in non-headless mode, there is no problem with creating a PDF via the File > Print menu.

**Comment by HugoDF** [comment]
I'm having the same issues taking PDF snapshots of HTML containing images, where the combined image size is more than 200MB, if we have 193MB of images it works but over 200 it hangs.

**Comment by matthewdingley** [comment]
I've taken another look at this, comparing the logs in successful and hanging cases: 
[HungPdfPrintNew.log](https://github.com/GoogleChrome/puppeteer/files/1626798/HungPdfPrintNew.log) & 
[SucceedingPdfPrint.log](https://github.com/GoogleChrome/puppeteer/files/1626799/SucceedingPdfPrint.log) (truncating the PDF data in the successful case). Interestingly, from the point at which the printToPdf command is made through to the end of the session, the logs are exactly the same, other than missing the PDF data response.

The correct series of events are:
- SEND Page.printToPDF
- RECV {"id":16,"result":{}}
- RECV Page.frameResized (the resize for the print page size)
- **RECV a message containing the PDF data (missing in the hanging case)**
- RECV Page.frameResized (the resize back to the screen size)
- RECV Page.lifecycleEvent (firstMeaningfulPaint)
- RECV Page.lifecycleEvent (networkAlmostIdle)
- RECV Page.lifecycleEvent (networkIdle)
- close

In the hanging case, the only log missing is the one for receiving the PDF data. Presumably, the pdf Promise is never resolved because the response is never received.

This looks like it is almost certainly an upstream issue with Chromium. Would you mind sanity checking the upstream assumption please and I'd be more than happy to file the upstream bug myself as it's become a significant issue that's preventing us from using Puppeteer successfully in our reporting pipeline

**Comment by sergiofm** [comment]
I'm having this issue too, and my HTML have around 100 images. With smaller HTMLs It work Fine. How can I contribute to solve this issue?

**Comment by sergiofm** [comment]
Hi, I've figured out what's happening im my case. I'm running my project in a docker container, and by default it runs with a small /dev/shm shared memory space (64Mb). This is what is causing my chrome crashs. Raising this value for 2Gb solved my problem. This problem is described [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#tips). I hope this can help somebody with the same problem.

**Comment by matthewdingley** [comment]
I'm afraid that in my case, it is not because of the /dev/shm Docker problem (although we are running Docker with the --shm-size flag).

The code in the original post was run outside of Docker and still experienced the same issue.

**Comment by galvez** [comment]
Ran into the same issue -- fixed by embedding all large images as base64 in the document.

**Comment by galvez** [comment]
It seems puppeteer has a really hard time managing a lot of large, concurrent downloads.

**Comment by Mgonand** [comment]
Any updates on this? I am currently experiencing the same behavior. With any amount of images which their total size is greater than 200Mb the PDF is never generated.

Puppeteer version: 1.6.0

I tried to launch with pipe option active and I get this error:
```
RangeError: Invalid string length
    at Pipe._dispatch (/Users/marcosgonzalez/Proyectos/ProMIR/printService/node_modules/puppeteer/lib/Pipe.js:47:38)
    at Socket.Pipe._eventListeners.helper.addEventListener.buffer (/Users/marcosgonzalez/Proyectos/ProMIR/printService/node_modules/puppeteer/lib/Pipe.js:29:64)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onread (net.js:587:20)
```

I tried to launch with `args: ['--disable-dev-shm-usage']` and nothing changed.

Any ideas?

**Comment by galvez** [comment]
@Mgonand the only way you're getting this to work reliably is by creating a batch of PDF files and then joining them in a final file (I used [pdftk](https://www.pdflabs.com/docs/pdftk-cli-examples/)). I use puppeteer  to generate series of 10-image PDFs and then join one final file.

**Comment by Mgonand** [comment]
@galvez Thank you for the tip!

**Comment by bruceCzK** [comment]
@Mgonand I think you are getting this error is because puppeteer transfer the pdf buffer to string, I found source code around
https://github.com/GoogleChrome/puppeteer/blob/cf8c62e835b565feb9d19639a3832a59d9b07aca/lib/PipeTransport.js#L48
Yet nodejs has a limitation for string length of 1GB, so it means if your result pdf is large than this number, puppeteer will crush. 

Here is a answer from stackoverflow explaining this，https://stackoverflow.com/a/44540335

Hope the team will make some change to fix this.

**Comment by Mgonand** [comment]
Yes, that is probably the issue when I tried to use Puppeteer in pipe mode.
I tried the approach suggested by @galvez and it worked fine.

**Comment by gordonkristan** [comment]
I also found that galvez's solution worked. We had a 27 page PDF that would not export no matter how much time we gave it, but if we cut it into 10-page chunks we got it exported in around 22 seconds. Thanks for the tip!

Also, instead of using pdftk try using Ghostscript. It takes a little bit longer but compresses the PDFs without a loss in quality. Some of our PDFs were approaching 100MB, so that was a nice side-effect.

```bash
gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=output.pdf 0.pdf 1.pdf 2.pdf
```

**Comment by eric10k93** [comment]
I am using Puppeteer Sharp and encountering a similar issue when my HTML is overly large, the PDF does not generate.  How are you using Puppeteer to split the HTML into smaller files?  What options enable that?

**Comment by Mgonand** [comment]
@eric10k93 

We use the option `pageRanges`:
```
<string> Paper ranges to print, e.g., '1-5, 8, 11-13'. Defaults to the empty string, which means print all pages.
```
You can check all the options here:
https://pptr.dev/#?product=Puppeteer&version=v8.0.0&show=api-pagepdfoptions

I hope it helps.

**Comment by milczarekIT** [comment]
I have the same issue. @Mgonand, `pageRanges` did not resolve the problem. Looks like generating pdf with 500+ pages with `pageRanges` ('1-4') and with default config take the same amount of time.

**Comment by sefasenturk95** [comment]
@Mgonand @gordonkristan how did you manage to get the total amount of pages? I have a large PDF as well and I want to chunk it, but I can't calculate the number of chunks I will have because I cannot get the total amount of pages that can be printed via Puppeteer..

Issue reference: https://github.com/puppeteer/puppeteer/issues/8070

**Comment by gordonkristan** [comment]
@Sef1995, it's been a long time since I've looked at this code but you can just get the total height of the document and then divide by the height of the page size. Our CSS shows roughly 98dpi and we're using the `letter` format, which is 8.5x11in, so our page size is 833px/1078px.

We make it easy by creating a `<div class='pdf-page'></div>` element for each page, then just counting those. The style for the page has `overflow: hidden` and is set to the exact dimensions of the page size plus 1/2" of padding.

**Comment by sefasenturk95** [comment]
Hey @gordonkristan , thank you for taking the time to reply. Our HTML template consists a long table which we cannot divide into  a `<div class='pdf-page'></div>` element for each page because we don't know where to cut it off. We have a `break-inside: avoid;` in the `td` so while printing the elements don't get cut off on the end of the page but instead start on a new page.. I don't think this is taken into account when doing a calculation based on the height of the page size..

**Comment by gordonkristan** [comment]
We actually created the `pdf-page` item for the exact reason you mention – we didn't know how long the PDF would be otherwise. Our application requires that we know how long the PDF is, so we write application logic to break long tables into multiple small tables across pages. If that's not doable for you then maybe the new `createPDFStream()` function could help solve the issue of large PDFs for you.

**Comment by Shuichi-code** [comment]
Sorry for the noob question @gordonkristan, but would you happen to have sample code on splitting the pages? On how to count the `<div class='pdf-page'></div>`?

**Comment by gordonkristan** [comment]
Unfortunately that code is quite complicated (several hundred lines of code). There's no browser or standard library logic to help out (as far as I know), you have to write it all yourself. The gist:

1. Render all of the React components to one long "page"
2. Measure the height of each fully-rendered component
3. Calculate which components can fit on a page, and which components are taller than one page and need to be split across pages
4. Re-render all of the components, giving them instructions for how to split themselves apart (if necessary)
5. Count the number of page elements and capture the PDF

To implement this kind of logic, every component has to be "PDF aware" and be able to render itself based on the common PDF props we may pass into it. (For instance, a table might need to render only 20 rows at a time but have multiple copies on the same page to get every row.) It's complicated but these PDFs are user-defined, so we have to handle any case.

Short of this level of application logic, I'm not quite sure how you could get the level of control you need to be able to split and count pages. 🤷

**Comment by Shuichi-code** [comment]
Thanks. I'm actually just receiving the HTML file that already has `<div class="page"></div>`. But I'm not sure how to count those in a puppeteer browser using Node.js?

**Comment by Shuichi-code** [comment]
Found the answer in the documentation and used page.$$eval()!

https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageevalselector-pagefunction-args
