### ISSUE TITLE
Feature request: Give access to created processes

### ISSUE THREAD

**Issue by GregRos** [puppeteer/puppeteer#1539]
It would be great if the library gave access to the browser process it creates. I need access to it and I'm thinking of either forking the repository or creating the browser process myself.

**Comment by vonGameTheory** [comment]
Yeah.  And give us a property that tells us the process id of the main chromium process after launch.

**Comment by aslushnikov** [comment]
@GregRos @vonGameTheory can you guys share the usecase?

As a workaround, you can use [chrome-launcher](https://www.npmjs.com/package/chrome-launcher) to launch chrome, parse the browser target from chrome's output and connect to it later with `puppeteer.connect`.

The hardest part here is probably extracting browser target from stdout; here's how we do it:

https://github.com/GoogleChrome/puppeteer/blob/a164524c72443920e0f008d62c5362c08a7794a0/lib/Launcher.js#L194-L248

**Comment by GregRos** [comment]
@aslushnikov Thanks for the workaround!

There are many use-cases.

1. Run custom cleanup code on process crash (I know `puppeteer` runs some cleanup, but I want to run more).
2. Track process resource use
3. Force the process to crash directly in some cases.

To do those things we need the `pid` of the Chrome process `puppeteer` creates.

**Comment by aslushnikov** [comment]
@GregRos thanks for the usecases!

> Run custom cleanup code on process crash (I know puppeteer runs some cleanup, but I want to run more).

You can also do this with the [`browser.disconnected`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-disconnected) event

> Track process resource use

Reasonable.

> Force the process to crash directly in some cases.

I'm curious about this usecase! Can you share more details about it? We currently simulate this in tests via connecting multiple browsers to the same process and closing one of them: 
https://github.com/GoogleChrome/puppeteer/blob/a164524c72443920e0f008d62c5362c08a7794a0/test/test.js#L266-L290

**Comment by GregRos** [comment]
> You can also do this with the browser.disconnected event

Ah, I didn't know about this one. Can the event tell me whether the process actually crashed or the `puppeteer` simply disconnected? Can it tell me if a kill signal was sent or the process's exit code? Does it sit in the process itself or does it go through the protocol?

> Force the process to crash directly in some cases.

I run browsers in a limited-memory Linux environment. I've learned that in critical memory conditions that happen due to Linux over-committing and the unpredictable memory usage of web browsers, I have to force them to close immediately (`SIGKILL` style) or else the system will simply hang. I know the Linux OOM killer is supposed to help in these cases, but in my experience it hasn't.

This is, of course, just one use-case for this ability. I'm sure there are other reasons to `SIGKILL` browser processes. And when it comes to `SIGKILL`, I prefer to do it as directly as possible, without going through `puppeteer`.

----

Having the `pid` would also allow me to monitor the processes from another `node` instance, tell how many `chrome` processes have been created in the process tree, and open up other opportunities. It's really a must-have feature for my project.

**Comment by vonGameTheory** [comment]
There have been a number of times my node process crashed and left chrome processes still running.  I have a separate "master control" process for garbage collection (i.e. id zombie processes and kill them in cases like that) and overall monitoring.  What I am doing is writing an API to your API where I run a node server that accepts requests and spins off chromes to fulfill them.  (It is essentially a javascript-enabled CURL library -- in-fact it is an extension to the API I have been using to libcurl for the last 10 years or something.  I do website browsing automation and scraping.)  I might have up to 100 chromes running at once all controlled by a single (or a few) node/puppeteer process(es).  I need to make extra that sure when they get killed (or when something crashes and they aren't explicitly killed), they die, or if one them is hogging memory or freezing or something on a strange website then I can figure out which one it is, etc etc.   Also if I have other Chromes running outside of puppeteer, I can make sure I don't kill them accidentally because I know which is which.    It is just a huge help to have the PID -- even if you don't provide anything other than that I can figure it out.  (I know it's in there, I just haven't looked at it closely but I figure it will be something lots of people will want so it really should just be an available property.)  Everything I am describing I have already been doing with PhantomJS for the last couple years, but as that has been abandoned and headless chrome seems to be better overall I'm switching everything over to chrome.  PID-tracking is about the last thing I'll need for this so I haven't gotten to it yet, but I'll definitely need it.

**Comment by ebidel** [comment]
@aslushnikov This would be useful when running pptr and headless in the cloud. That's challenging to do atm. For example, it would allow me to keep track chrome processes for try-puppeteer and know which ones to kill off if they get in a bad state.
