### ISSUE TITLE
HTTP basic authentication without challenge from server

### ISSUE THREAD

**Issue by konstantinblaesi** [puppeteer/puppeteer#1593]
I have noticed that using [page.authenticate(credentials)](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageauthenticatecredentials) only works if the server sends an authentication challenge to the client. I am dealing with a webserver that does not do this, but gives a different response depending on whether an Authentication header for HTTP basic authentication was provided or not. I basically have to rely on [page.setExtraHTTPHeaders(headers)](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetextrahttpheadersheaders) for the authentication.
Would it make sense to add a second optional parameter [page.authenticate(credentials)](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageauthenticatecredentials) allowing to force HTTP basic authentication for this case?

**Comment by vonGameTheory** [comment]
I believe page.authenticate relies on the request interception system (which so far has had a number of other drawbacks with certain headers not being sent, hangups in odd scenarios, etc).  Just making the header yourself and using setExtraHTTPHeaders seems to me like the better way to go at this point even if the page does send the challenge.  I would suggest page.authenticate be reconsidered to simply be a helper to set that header instead of using interception. (Are there other advantages to doing it that way?)

**Comment by konstantinblaesi** [comment]
@aslushnikov What do you think?

**Comment by aslushnikov** [comment]
> I believe page.authenticate relies on the request interception system (which so far has had a number of other drawbacks with certain headers not being sent, hangups in odd scenarios, etc).

@vonGameTheory We're fixing these; it takes time.

> I would suggest page.authenticate be reconsidered to simply be a helper to set that header instead of using interception. (Are there other advantages to doing it that way?)

@vonGameTheory the header would work nicely only for basic auth; meanwhile, there are many other schemes of http auth: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

> Would it make sense to add a second optional parameter page.authenticate(credentials) allowing to force HTTP basic authentication for this case?

@konstantinblaesi I agree with @vonGameTheory here, I'd just use HTTP header here manually.
