### ISSUE TITLE
Yarn install doesnt add chromium, got error: "Chromium revision is not downloaded."

### ISSUE THREAD

**Issue by freereikicourse** [puppeteer/puppeteer#1602]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: WIN 10 64 bit
* URLs (if applicable):

**What steps will reproduce the problem?**

Install with `yarn install puppeteer`.
Run my app
Get warning: "Chromium revision is not downloaded. "

_Please include code that reproduces the issue._
Is the demo code...
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();

```

**Comment by wind36830** [comment]
I think you don't install Chromium when install puppeteer .I use `npm i puppeteer` instead.
In the readme file it says:
> When you install Puppeteer, it downloads a recent version of Chromium (~71Mb Mac, ~90Mb Linux, ~110Mb Win) that is guaranteed to work with the API.

you may check your network  and try again.

**Comment by cilerler** [comment]
I believe this issue still exists.

```
npm install // <= initial install for all packages in package.json
npm install puppeteer // <= to make sure puppeteer gets installed.  I know it is weird but you have to install this separately
```

now if we try the same thing with YARN

```
yarn install
yarn install puppeteer // <= not working
```
second command does not install it.

**Comment by joshribakoff** [comment]
@cilerler  `yarn install` is not valid, its `yarn add`.

 This error message happens if you `yarn install` on your mac, but you try to run puppeteer inside something like Docker / Vagrant which is linux. I wish it would tell me "has it downloaded but for the wrong platform" instead of saying "its not downloaded" which is wrong.

**Comment by squarism** [comment]
I'm also having this same error where it says it's not downloaded and also npm and yarn are acting differently.

Very weirdly, it is downloaded!  I have 185mb in my `node_modules` folder from a `yarn add` and it's definitely Chrome for my platform (mac).  I'm trying npm install now and it seems to download again.  I did not do an `npm install` before doing a `yarn add`.  Sorry I cannot isolate and reduce the problem to a decent example right now.

Also, the `yarn install` suggestion came from the error message:
https://github.com/GoogleChrome/puppeteer/blob/e8a085ccfb478d51cd45172dbc7f4d1311c75ec8/lib/Launcher.js#L97
If that's not right then it shouldn't suggest it.

_Update: jest seems to cause this but following this example works_
Described here:
https://facebook.github.io/jest/docs/en/puppeteer.html#content
Which leads to this example repo:
https://github.com/xfumihiro/jest-puppeteer-example
I didn't have as much setup to do using mocha.  I guess there's an async thing going on.

**Comment by joshribakoff** [comment]
Why are you mixing npm & yarn? Did you try deleting node_modules & then starting over w/ just one or the other?

**Comment by squarism** [comment]
Right, mixing npm and yarn is weird, I agree.  That's not my normal workflow, I was just trying to debug after I got in a weird state.  How I reset to test like you suggested is:

* Delete `package-lock.json` after doing npm install.
* Keep `yarn.lock`
* Delete `node_modules`
* Run `yarn install`

As far as mixing, moving from npm to yarn is legal.  Maybe it's edge case.  Npm install and then run yarn.  I think that's where the error message happens.  But it's maybe edge case.  You'd want to `yarn add` from the start to avoid the confusing error message?

The happy path:
```
$ mkdir puppeteer_install
$ cd puppeteer_install
$ yarn init
$ yarn add --dev puppeteer
$ mkdir tests  # test code written with jest, skipped here

# add jest, jest config which just adds env stuff and other things around puppeteer
```
That works flawlessly.

The edge case (unhappy) path.  Since yarn can be run on an npm project, add puppeteer through npm and then run `yarn`.

```
$ mkdir puppeteer_npm_install
$ cd puppeteer_npm_install
$ npm init
$ npm add --save-dev puppeteer jest

# package.json is now (same as yarn)
  "devDependencies": {
    "jest": "^22.4.0",
    "puppeteer": "^1.1.0"
  }

# add some tests (same as previous) and jest config ...

$ npm run jest
```
Works!  But now what if we want to use yarn?  Yarn can be run on an existing project.

```
$ yarn  # it re-downloads chromium here, weird
$ rm package-lock.json
```
Works fine!  I don't know what my issue was.  I said I wanted to isolate it with a couple of spikes like this and I have even though I can't reproduce.  I'm sorry for droning on for basically a non-issue but I wanted to explain more and give people something to hit off Google if they get this error.

I think the answer is: _Use npm OR yarn_ like the README says but don't mix or try to install puppeteer globally.  Also, reseting by deleting `node_modules` and leaving `yarn.lock` does work too like you suggested.  It will just download chromium again.  🎈

**Comment by dimroc** [comment]
I have a pure yarn setup and am still running into this issue.

**Comment by brandonkal** [comment]
I just ran into an issue where Chromium was not installed. To fix the issue just run the install manually:
```js
node node_modules/puppeteer/install.js
```

**Comment by MichalMoravik** [comment]
@brandonkal You saved my day, after long hours of searching for the problem I just run this one and it works! thanks!
