### ISSUE TITLE
Toggle cookies storage

### ISSUE THREAD

**Issue by namma-geniee** [puppeteer/puppeteer#1632]
May you add the ability to enable/disable cookies storage on the browser as the configuration in the screenshot below?

![image](https://user-images.githubusercontent.com/30993148/34197772-7b28f2fa-e59a-11e7-8525-79f2f92e4353.png)

While scraping, i have to destroy and create a new instance for each website to have them forget everything saved in the cookies storage, eg. the authentication.

Thank you!

**Comment by Everettss** [comment]
I know it's not precisely what you ask for. But you don't have to destroy browser instance in order to remove all cookies. You can use dirty way (since we are waiting for #31 ) of sending [clearBrowserCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-clearBrowserCookies) to raw devtools protocol:
```javascript
await page._client.send('Network.clearBrowserCookies');
```

**Comment by namma-geniee** [comment]
@Everettss Nice! Thank you very much!

**Comment by namma-geniee** [comment]
The issue was solved, but it would be better for a shortcut function call. 😄
