### ISSUE TITLE
Conditional catch for errors

### ISSUE THREAD

**Issue by brigand** [puppeteer/puppeteer#1694]
<sup>Issue template didn't really apply.</sup>

I can't find anything in the api docs page about error handling. The main type of error that's encountered is a timeout. The issue is that there's no documented way to distinguish the type of error received in the `catch` after awaiting a promise that rejects.

The issue is that good code (most of the time) needs to do conditional catches to avoid silencing unexpected errors. There doesn't seem to be a good, stable way to do this currently.

I tried inspecting some of the errors. For these tests, the output is logging `error` and then logging `{...error}`.

```js
await page.click('doesntexist');

// Result
{ AssertionError [ERR_ASSERTION]: No node found for selector: doesntexist
    at Console.assert (console.js:188:23)
    at Page.click (/private/tmp/temp-puppet-7695/node_modules/puppeteer/lib/Page.js:770:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
{ generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

Gives a generic `AssertionError` with no information about the cause, except if you want to parse the error message, which seems very unstable as it can change without much notice.

The next issue is `waitFor`:

```js
await page.waitFor('doesntexist');

// Result
Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/private/tmp/temp-puppet-7695/node_modules/puppeteer/lib/FrameManager.js:593:58)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
{}
```

Again, the only way I see to extract information is the error message.

---

There are a few potential solutions here:

1. document the error messages and give an example regex to check them. This requires no code changes, but makes it clear that the error messages changing would be a breaking change. 
2. don't change the errors, but give official utility functions like `puppeteer.isTimeoutError(error)`. Very little code changes, but the api will be stable across versions. Better than 1.
3. make each error either an Error subclass, or give it properties e.g. `type: 'PuppeteerTimeout', selector: 'doesntexist'`. This is about tied with 2, since it gives a readable way to check the error type.

Thoughts? Sorry if this has come up before, but I couldn't find anything relevant.

**Comment by JoelEinbinder** [comment]
Can you give some more context as to why you are catching errors in the first place? This seems reasonable, but I'd be scared to rely on Puppeteer failing in a consistent way. Maybe there is some other change we could make to make your life easier.

**Comment by aslushnikov** [comment]
This sounds reasonable. How about using [`error.code`](https://nodejs.org/api/errors.html#errors_error_code) for the purpose?

```js
if (err.code === 'PPTR_TIMEOUT') {
  // .. handle timeout error
}
```

**Comment by pwnall** [comment]
I was about to open an issue and found this. I hope my comments are relevant.

I am catching puppeteer's timeouts. In my case, timeouts can come from page.goto, page.waitForNavigation, and page.waitForSelector. I don't think that puppeteer is anything wrong in this case, as it is simply following my commands. (in response to @JoelEinbinder's comment) At the same time, timeouts do happen (think tens of timeouts per 100,0000 navigations), so I do need to catch the timeouts and retry the tasks.

I would be grateful if puppeteer's errors would inherit from a custom error class exposed in the API. My handlers are quite removed from the callsite, because I have a resource manager that assigns pages to tasks and implements retries. My error handling must distinguish between business logic errors and puppeteer errors, and it'd be nice if I could just distinguish puppeteer-originated errors and retry on them.

I understand that some errors will bubble up from libraries used by puppeteer. I'm not concerned with those for now. I currently regexp-match errors' `message` property, and I'd sleep better at night if I had a trustworthy filter for puppeteer-originated errors. A custom class is the best way I can think of, in the sense that it's least likely that some other library would emit an error that looks like a puppeteer error.

If the custom error class happens, it'd be nice to add properties like the reason (e.g., 'timeout') as well as metadata to help debugging, such as the page that originated the error, the current timeout value. The reason can be encoded in `error.code` if you prefer that approach.

**Comment by aslushnikov** [comment]
> I currently regexp-match errors' message property, and I'd sleep better at night if I had a trustworthy filter for puppeteer-originated errors. 

@pwnall why puppeteer-specific `error.code` values aren't good enough for your usecase? I prefer them to custom error classes for a few reasons:
- `error.code` values are lightweight
- `error.code` values fit nicer with the rest of the API: ATM we have no classes exposed, only instances.

**Comment by pwnall** [comment]
@aslushnikov `error.code` uses a global namespace, so there's always a tiny chance that some other library settles on the same prefix.

If you'd rather not expose a custom class, how about a custom property?

**Comment by brigand** [comment]
Sorry, missed the notifications on this issue. Yeah, error codes would be good with me.

I can take this issue when a decision is made.

**Comment by tomgallagher** [comment]
Something I don't understand about timeout errors.

If I have a page crash on me, then I have this handler:

```
page.on('error', error => {
    debug(`Chrome Handler: GENERAL ERROR on: ${targetURL} : ${error}`);
    debug(`GLOBAL CHROMEPOOL count after releasing instance on ERROR: ${global.chromepool.borrowed} for: ${targetURL}`);
    global.chromepool.release(browser);
});
```

This is useful for tidying up after errors.

However, if a page simply times out, then I get no error other than the rejection of the promise.

I have tried using this in the general error event handler, no luck. 

```
if (error.code === 'PPTR_TIMEOUT') {
    debug(`Chrome Handler: TIMEOUT`);
}
```

Wrapping the whole block of code in a try catch statement seems ugly. A listener for the timeout error event would be perfect.

**Comment by brigand** [comment]
@tomgallagher the `error.code` thing is being proposed in this issue, not something that currently exists.

**Comment by tomgallagher** [comment]
Ah, sorry. From my limited experience, the two errors that occur most often are timeout errors and page crashes. Having to deal with each of those in a different manner is a bit confusing at the moment.

**Comment by marijanlekic** [comment]
Is there any sense to throw timeout exception if page crashes?

    page.on("error", async () => {
        await page.close();
        console.log("page crash");
    });

    try {
        await page.goto("chrome://crash/");
    } catch (e) {
        console.log("timeout exception");
    }   

    console.log("after");


Output is:

> page crash
> timeout exception
> after

What is a good way to handle page crash (and other errors), in case when i have some code which provokes these kind of errors and i want to repeat the same thing?

For example: 

    const someFn = async () => {
        const page = await browser.newPage();
        // Code that can provoke page crash
        await page.goto("url");
        await page.evaluate(() => {
            //something
        });
    };

**Comment by tomgallagher** [comment]
@marijanlekic 
Have a look at [this](https://github.com/GoogleChrome/puppeteer/issues/1862) - I raised it yesterday - tries to impose some structure on error handling.
