### ISSUE TITLE
[BUG] Different color shades of screenshots taken from different displays

### ISSUE THREAD

**Issue by skyiea** [puppeteer/puppeteer#1699]
I'm trying to use `puppeteer` for visual regression testing.
When I do `page.screenshot` output images differ (in shades of colors) on different displays (MBP built-in display vs Dell monitor display).
Am I missing some option?

**Comment by aslushnikov** [comment]
@skyiea No, shades of color shouldn't differ. I'm not sure what could be causing this, we don't do anything special with this regard. The only screenshot discrepancy I'm aware of is related to different font rendering on different platforms.

It looks like somethings is changing in the OS when you switch displays. I'll speculatively close this for now.

**Comment by skyiea** [comment]
@aslushnikov Yeah, I would expect that _puppeteer_  shouldn't care about display's specific color range, saturation, etc. But that's what I've got. Thought maybe you've faced this issue before.
What's also weird is that there is no color differences when I'm testing with _Gemini_.

ATM I'm working this around with additional color-threshold in the tool I'm using to compare images, but I would rather not to.

**Comment by cmcculloh-kr** [comment]
I'm having the same issue. It looks like Chrome has changed the way they render colors. 

[Chrome is now following the "color rendering profile" of the device](https://productforums.google.com/forum/#!topic/chrome/2-pFZipsBpM). This makes Puppeteer much less useful for visual regression testing if you are running the tests on two different machines (which I believe most people are). For instance, generating the initial screenshots on my local machine and then having my CI server (Heroku or TravisCI) run my tests on every PR is much less effective because the CI server has either no display, or a much poorer quality display than my Retina Macbook display, so I get a lot of false positives and my tests fail.

The way I've addressed this is by having different thresholds for my CI server than I have for local development, eg:

```
const threshold = isLocal ? 0 : 0.1;
const failureThreshold = isLocal ? 0 : 0.01;

export const commonSnapshotConfig = {
	customDiffConfig: { threshold },
	failureThreshold
};
```

This is sub-optimal to say the least. It would be great if there was a way to tell Puppeteer to pass a flag or something when it opens Chrome to force a color profile (either a default that lives in Puppeteer, or one that you provide).

**Comment by giocodes** [comment]
@cormacmccarthy thanks for sharing the information.
The solution didn't quite work for us because the test is breaking for a different shade of color on the background of the component which causes an error of over 30%. 

+1 to the idea of a color profile option, what do you think @aslushnikov?

**Comment by 8eecf0d2** [comment]
Have you tried the [Chromium flag](https://peter.sh/experiments/chromium-command-line-switches/#force-color-profile) `--force-color-profile=srgb|generic-rgb|color-spin-gamma24`?

**Comment by jasbeard** [comment]
have the same issue, works fine locally but when deployed to heroku, the screenshot becomes fuzzy.

Local Machine -
OS: MacOS Cataline v10.15.3
Node: 12.17.0
puppeteer: 3.1.0
![ss](https://user-images.githubusercontent.com/24859633/83212298-d25f1d00-a191-11ea-93b3-f5c9b51e1f09.png)

followed buildpack from https://github.com/jontewks/puppeteer-heroku-buildpack
result with heroku:
![image](https://user-images.githubusercontent.com/24859633/83212500-5d401780-a192-11ea-8a2c-868721275292.png)
