### ISSUE TITLE
Frame object returned via events has issues with promise based methods

### ISSUE THREAD

**Issue by pyper** [puppeteer/puppeteer#1725]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Docker, Linux, Cent OS 7
* URLs (if applicable):
* Node.js version: 7.10.1

**What steps will reproduce the problem?**

Use this code:
```
const puppeteer = require('puppeteer');

puppeteer.launch({args: ['--no-sandbox']}).then(async browser => {
  const page = await browser.newPage();  
  page.on('frameattached', async frame => {
    console.log('Frame found: ' + frame);
    console.log('What kind of object is this? ... ' + frame.constructor.name);
    const result = await frame.title();
    console.log('Result: ' + result);
  });
  await page.goto('https://www.google.com/chrome/browser/canary.html');
  await browser.close();
});
```
**What is the expected result?**

That it should no throw an exception. 

**What happens instead?**

I get the following error for every frame:
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): TypeError: Cannot read property 'evaluate' of null
```

I get the same problem with other methods that use promises on the Frame object.  Non promise-based methods seem to work.

**Comment by yujiosaka** [comment]
Same occurred to me in the following conditions

- Puppeteer version: 0.13.0
- Platform / OS version: Mac OS
- URLs (if applicable):
- Node.js version: 8.9.1

Meanwhile, I confirm that it does not occur on the master branch.
It doesn't show the result, though (I didn't look into it yet)

```
Frame found: [object Object]
What kind of object is this? ... Frame
Frame found: [object Object]
What kind of object is this? ... Frame
Result:
Result:
Frame found: [object Object]
What kind of object is this? ... Frame
Frame found: [object Object]
What kind of object is this? ... Frame
Result:
Result:
```

What happens if you try installing `puppeteer@next` instead?

**Comment by yujiosaka** [comment]
Same occurred to me in the following conditions

- Puppeteer version: 0.13.0
- Platform / OS version: Mac OS
- URLs (if applicable):
- Node.js version: 8.9.1

Meanwhile, I confirm that it does not occur on the master branch.
It doesn't show the result, though (I didn't look into it yet)

```
Frame found: [object Object]
What kind of object is this? ... Frame
Frame found: [object Object]
What kind of object is this? ... Frame
Result:
Result:
Frame found: [object Object]
What kind of object is this? ... Frame
Frame found: [object Object]
What kind of object is this? ... Frame
Result:
Result:
```

@pyper

What happens if you try installing `puppeteer@next` instead?

**Comment by pyper** [comment]
@yujiosaka I think that master branch run you did is working correctly, the frames just didn’t have titles yet.  That is, when frame attached fired the HTML in the page wasn’t loaded yet, so title was blank.  I will test with @next as suggested and report back.  Thanks buddy!

**Comment by pyper** [comment]
@yujiosaka Just tested with the master branch.  The issue is corrected there for me too.  It appears to be a bug that affects 0.13.0

Thanks for the help!
