### ISSUE TITLE
PDF Creation Client Side

### ISSUE THREAD

**Issue by srhise** [puppeteer/puppeteer#1747]
So impressed with PDF creation functionality in Puppeteer.

Is it possibly to apply the PDF generation functions client side? It seems like this would be a great solution to create PDFs from pages on your *actual* chrome browser vs. headless. Given the fact it works headless, how would one go about implementing this client side in an actual browser?

**Comment by ebidel** [comment]
The closest you can get is calling `window.print()` and the have the user manually chose "Save as PDF" > "Save". As for a true client-side solution, there lots of libraries on npm for generating pdfs. https://www.npmjs.com/package/pdfjs-dist (https://mozilla.github.io/pdf.js/) and https://www.npmjs.com/package/pdfkit are two.

You could also create/host a web service that generates PDFs when sent a URL or HTML. Perfect use case for headless Chrome and puppeteer! There are some [example projects](https://github.com/GoogleChrome/puppeteer/tree/master/examples#rendering-and-web-scraping) that show how to get started.

**Comment by jwillingham789** [comment]
I'm using Puppeteer to generate a pdf with a supplied url and it works great for printing static pages. However, I'm working on a React application that has complex component state changes and I'm wanting to capture those state changes in a pdf. The problem I'm having is that printing via puppeteer only prints the initial page layout and doesn't reflect any of the state changes.

I can't use window.print() because the print to pdf gives me a blank page. So my question is, how does puppeteer print the visible screen and scale it to the provided pdf layout?

I've tried using libraries like jsPDF, however, they don't work well with SVGs and my project is loaded with svg charts. 

Anyways, really like the puppeteer project and will continue utilizing it!

**Comment by ebidel** [comment]
Puppeteer uses headless Chrome's feature for creating PDFs. https://developers.google.com/web/updates/2017/04/headless-chrome#create_a_pdf_dom

If you run those state changes and try printing the page manually (cmd+p), are they captured in the PDF preview?

**Comment by calrays** [comment]
@jwillingham789  I understand this is old, but to achieve something similar to what it sounds like you need(ed), I wrote a node script to:
1. render my React server side to static HTML
2. pass that to wkhtmltopdf (there are wrappers for popular languages)
3. send resulting PDF to client

The key was step #1. If you can't do that, due to the state changes you need first, I had some success with client browser generated HTML (from React), and server generated PDF with wkhtmltopdf, using --window-status, a global flag to not export until the client browser sets window.status to what you want. (--window-status worked more consistently for me than '--javascript-delay' or '--wait-for-javascript' or whatever the other flags are called.)

(+) SVG charts worked surprisingly well. 
(+) Browser consistency
(+) wkhtmltopdf is powerful
(+/-) good enough performance
(-) I did have to fiddle with CSS between web and print, and adjust how we had laid out the SVG chart containers.
(-) wkhtmltopdf is particular, and aging. any mistake, such as not formatting templates with doctype tags, usually spits out unhelpful garbage like blank pages

You may be able to get similar going with puppeteer using `page.setContent(html)`, or just chrome headless print to PDF, depending on your needs. I needed dynamic custom headers, which I couldn't figure out with chrome headless at the time.
