### ISSUE TITLE
1.0 page.waitFor  Error: Evaluation failed: EvalError

### ISSUE THREAD

**Issue by san4io** [puppeteer/puppeteer#1814]
**Tell us about your environment:**

* Puppeteer version: 1.0
* Platform / OS version: Xubuntu 16.04
* URLs (if applicable): https://linkedin.com
* Node.js version: 9.3

**What steps will reproduce the problem?**
```
    await page.goto('https://linkedin.com');

    await page.type('#login-email', credentials.email);
    await page.type('#login-password', credentials.pass);
    await page.click('#login-submit');

    await page.waitFor('#profile-nav-item');
```

**What is the expected result?**

It should wait for element to appear. In 0.13 everything works perfectly.

**What happens instead?**

UnhandledPromiseRejectionWarning: Error: Evaluation failed: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'report-sample' 'sha256-6gLjSWp3GRKZCUFvRX5aGHtECD1wVRgJOJp7r0ZQjV0=' 'unsafe-inline' static.licdn.com s.c.lnkd.licdn.com static-fstl.licdn.com static-src.linkedin.com https://www.linkedin.com/voyager/service-worker-push.js https://platform.linkedin.com/js/analytics.js static-exp1.licdn.com static-exp2.licdn.com s.c.exp1.licdn.com s.c.exp2.licdn.com static-lcdn.licdn.com s.c.lcdn.licdn.com https://www.linkedin.com/sc/ https://www.linkedin.com/scds/ https://qprod.www.linkedin.com/sc/ https://www.linkedin.com/sw.js https://www.linkedin.com/voyager/abp-detection.js".

**Comment by aslushnikov** [comment]
@san4io this happens since we now create a new function as a part of `waitFor` task in puppeteer. This is necessary to support JSHandle as arguments to the `waitFor` functions. 

As a result, `page.waitFor` falls victim to page's [CSP policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

CSP deals us quite a lot of trouble; closing this in favor of #1229. Please upvote to help us with prioritization.
