### ISSUE TITLE
I am trying to save a page as mhtml file. Is there any way to do this through puppeteer?

### ISSUE THREAD

**Issue by markusmobius** [puppeteer/puppeteer#1820]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by aslushnikov** [comment]
@markusmobius no, there's currently no way. Chrome has this functionality only as experiment.

The best option would be to use some third-party mhtml generators.

**Comment by sean-hill** [comment]
@markusmobius did you find a solution for this elsewhere? @aslushnikov do you recommend any third-party mhtml generators that could work with Puppeteer?

**Comment by aslushnikov** [comment]
>  @aslushnikov do you recommend any third-party mhtml generators that could work with Puppeteer?

@sean-hill I'll refrain from recommending here: I don't have much experience with any

**Comment by vsemozhetbyt** [comment]
Reference: see https://github.com/GoogleChrome/puppeteer/issues/2433#issuecomment-466215925

**Comment by markusmobius** [comment]
I wrote a Puppeteer script that creates HTML single-pages from websites
based on the  SavePageWE Chrome/Firefox extension by DW-dev.

https://github.com/markusmobius/nodeSavePageWE

I found that that extension produced excellent self-contained HTML files
which are as good or better as the inbuilt MHTML creator - plus HTML files
work on all browsers and not just those that support MHTML.I have been
using the node script for a production script for a month now.

**Comment by drundanibel** [comment]
Great job, @markusmobius! 👍 

Especially since I noticed that there are some problems with mhtml when rendering through different browsers. For example, if such files are stored on a web resource instead of a local storage, they can not be rendered but only downloaded. But with these real HTML files there are of course no such problems!

However, it's a bit unfortunate that you don't provide any possibility to interfere with the rendering process by puppeteer. For my purposes it is e.g. necessary to interact with the web page in order to put it into a defined state via integrated scripts and Ajax requests. Or sometimes a form has to be filled out and sent by post before I get the actual desired web page.

In other words: In my case it is not enough to pass a URL to the scrape function, because I have to perform further automation steps before the resulting web page appears and can be passed to the actual saving routine. So I would have to adapt your code to be able to implement such interaction code. But unfortunately I don't have a clue how to do it yet ...;-)

I think for this it would be best if I could create my own browser and page object in order to be able to decide on things like headless and sandbox mode as well as user agent and viewport resolution myself. So I wish there was a more lowlevel function to which I could pass my finished rendered page object.

Could you imagine to extend your module for such requirements?

**Comment by drundanibel** [comment]
Okay, I think I've roughly understood how your approach works. Do I see it correctly that all resources of the website to be saved have to be retrieved twice?

A first time using the page.goto() method to inject the pageloader-compressed.js script. By subsequent page.evaluate() call it stores all further documents to be integrated base64-encoded.

Afterwards, all document URLs are retrieved a second time using the request() method, although it is not quite clear to me whether and why this is really necessary. Isn't it possible to integrate the already base64 encoded and cached document contents into the main document after the first call?

If it is really necessary to use the simple request method for this, subsequent interactions with the webpage itself are of course not possible. :(

**Comment by markusmobius** [comment]
Hi. I think it should be possible to streamline this. To be honest, I don't understand the reason for the the twice retrieving either because I simply based it on the Chrome extensions SavePage WE. I didn't touch most of the client-side code and simply transferred the code that was defining the actual extension to NodeJS. Once I had that working I stopped because it was good enough for my purposes (I didn't want MHTML because I wanted to run headless plus the format is rendered inconsistently across browsers as you noted). Unfortunately, I don't have the time to refine this but I agree with you that much more should be possible - and there should be a simple way to serialize a rendered page at a certain point in time.

**Comment by drundanibel** [comment]
Hi, I compared the behavior yesterday a little bit with the original Chrome extension. With this I couldn't find that the resources had been fetched a second time from the web when the save function was called. On the contrary, web pages are actually stored in the adapted state to which I put them through my preceding interactions (including form entries etc.). I would conclude from this that the Chrome extension somehow processes the already loaded resources in their current state and does not actually retrieve them a second time.

However, I have also noticed that in the current version of this extension there must have been significant code changes compared to your starting point, which are also reflected in the renaming of probably crucial script files (pageloader[-compressed].js -> shadowloader[-compressed].js).

It is a pity that I still do not see through enough to make the necessary adjustments. I find the original code too extensive and confusing, probably because of the many options the extension offers. Although the author commented astonishingly much ...

**Comment by markusmobius** [comment]
@sean-hill 

see:  https://github.com/markusmobius/nodeSavePageWE

**Comment by markusmobius** [comment]
I updated the code - it's now based on the March 2023 version of the SavePageWE extension. 

Still here:
https://github.com/markusmobius/nodeSavePageWE

The old one still works but the new version works much better on modern websites.
