### ISSUE TITLE
Good puppeteer tutorial is needed.

### ISSUE THREAD

**Issue by voleynik** [puppeteer/puppeteer#1823]
Hello friends.
Could someone point me to a good puppeteer tutorial which goes beyond printing PDF of the screen and actually working on Windows 10? Everything I found does not work as advertised.
Thanks,
Vladimir.
sw-eng-kyivATmail.com

**Comment by schelkun** [comment]
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

**Comment by tnolet** [comment]
@voleynik maybe these examples help a bit: https://github.com/checkly/puppeteer-examples although I admit I did not test them on Windows.

**Comment by ebidel** [comment]
@voleynik what types of things would you like to see? I have plans to create a bunch of articles, but your feedback would be helpful. 

AFA window is concerned, what's not working?

**Comment by voleynik** [comment]
Eric, thanks a lot for your reply. 

As an example, please look at https://github.com/GoogleChrome/puppeteer/issues/1839

I general, my task on my project involves replacement of PhantomJS with Headless Chrome.

PhantomJS is started from java web application and controlled with the help of classes written by Selenium people like: 

org.openqa.selenium.phantomjs.PhantomJSDriverService				
org.openqa.selenium.phantomjs.PhantomJSDriver

I see that there are classes like these, which were written for 
chrome driver applicable for Selenium framework.

org.openqa.selenium.chrome.ChromeDriverService;
org.openqa.selenium.chrome.ChromeDriver;

Hopefully I can switch to "chrome" version on these classes in my task.

We actually see three different animals here:

1) Driver mentioned on Selenium site http://www.seleniumhq.org/download/
https://sites.google.com/a/chromium.org/chromedriver/

2) Chrome .exe by default installed on Windows 10 installed installed
C:\Program Files (x86)\Google\Chrome\Application\chome.exe

3) A chromium driver (the blue one) which I downloaded separately.

So,the question is: which one is the best candidate to replace PhantomJS in my project.

And if you don't mind could you tell me in which capacity are you involved with this project? (I mean Headless Chrome and Puppeteer)

Regards,
vladimir.oleynikATmailDOTcom

**Comment by ebidel** [comment]
Ah, so #1839 and the projects you listed are more related using headless Chrome/ChromeDriver but otherwise unrelated this project. I think there are already solid resources out there for Selenium and ChromeDriver, so we wouldn't want to replicate anything.  https://developers.google.com/web/updates/2017/04/headless-chrome#drivers talks about how to use headless Chrome with Selenium and ChromeDriver...though Windows coverages might be lacking. The ideas should be the same though.

If you want to replace PhantomJS with Puppeteer's and its APIs, you'll **need to run NodeJS**. The big differences between ChromeDriver and Puppeteer is the latter is Node and has higher level APIs. No one has created Java bindings for Puppeteer AFAIK. However, there is a [python wrapper](https://pypi.python.org/pypi/pyppeteer).

I recommend also checking out the various libraries available for working directly with the DevTools Protocol: https://github.com/ChromeDevTools/awesome-chrome-devtools#protocol-driver-libraries-in-various-languages lists

**Comment by theoutlander** [comment]
@ebidel I have puppeteer on my articles todo list. I would like to collaborate.

**Comment by Mideen** [comment]
Have you replaced phantomjs by chrome driver successfully? If you have done, please list out what are difficulties you are faced. We are in beginning at the same process. It would help us lot. @voleynik 

Still, are you using selenium or migrated to puppeteer? @voleynik

**Comment by AymenLoukil** [comment]
I wrote a modest Puppeteer tutorial here : https://www.aymen-loukil.com/en/blog-en/google-puppeteer-tutorial-with-examples/

**Comment by Cannonjc** [comment]
I'm currently building an app with puppeteer and am more on the novice side of nodejs programming. My biggest problem that i'm running into is error handling with puppeteer and how to do that. Every tutorial and examples that I find all just assume that puppeteer is going to work with everything its given, however in my case I have no control of the selectors given to my app. And therefore I get errors quite a bit because of bad selector paths. Is there some better way to error handle these instead of having to check every single time page.[method] is successful?
