### ISSUE TITLE
Navigation Timeout Exceeded when page returns a 204 code or contains iframe returning 204

### ISSUE THREAD

**Issue by Khady** [puppeteer/puppeteer#1879]
### Steps to reproduce

* Puppeteer version: puppeteer@1.0.0 and puppeteer@1.0.0-next.1516669982697
* Platform / OS version: debian
* URLs (if applicable): https://httpstat.us/204
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

test204.js:

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const url = process.argv[2];
  console.log("url:", url);
  const args = [
    "--disable-gpu",
    "--disable-setuid-sandbox",
    "--force-device-scale-factor",
    "--ignore-certificate-errors",
    "--no-sandbox",
  ];
  const browser = await puppeteer.launch({args});
  const page = await browser.newPage();
  const res = await page.goto(url);
  console.log(res);
  await browser.close();
})();
```

1. nodejs test204.js https://httpstat.us/204
2. wait
3. cry

**What is the expected result?**

```
$ nodejs test204.js https://httpstat.us/204
url: https://httpstat.us/204
LONG LOG WITH RESPONSE FROM GOTO
```

**What happens instead?**

```
$ nodejs test204.js https://httpstat.us/204
url: https://httpstat.us/204
(node:22606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded
(node:22606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C⏎         
```

**Comment by zachbadgett** [comment]
This is a tough one...because (correct me if I'm wrong), chrome doesn't change document views when receiving a 204. If you don't care about what's in the response you can use this work around:
```js
await page.goto('about:blank');
await page.addScriptTag({
    url: 'https://httpstat.us/204'
});
```
Adding the script tag will cause a synchronous load of the resource specified and will not return until it receives a response.

**Comment by norstbox** [comment]
This is very annoying bug, because it's extended to pages contain "affected" `iframe`, i.e.:
```html
<html>
<title>This page is also affected! - Timeout Exceeded</title>
...
<iframe src="//some-ad-network-return-status204"></iframe>
...
</html>
```
@Khady, perhaps it would not be a bad idea to reflect this consequence in title or/and description of the issue.

**Comment by Khady** [comment]
@norstbox updated, let me know if you want to say it in a better way

**Comment by aslushnikov** [comment]
> This is very annoying bug, because it's extended to pages contain "affected" iframe

@norstbox subframe case was fixed by https://github.com/GoogleChrome/puppeteer/pull/2339, I'm adding a test to make sure this is not regressed in future.

@Khady navigation to https://httpstat.us/204 is indeed tricky - chrome doesn't commit navigation if it receives 204. We'll need to handle this better on the protocol level.
