### ISSUE TITLE
chromedriver.exe VS chrome.exe - is there any difference?

### ISSUE THREAD

**Issue by voleynik** [puppeteer/puppeteer#1892]
Hello friends.
Is there any chance to start in headless mode a web driver which is used with Selenium framework?
The executable is "chromedriver.exe". You get it from Selenium site.
And a parallel  question: Is there anything in common between that Selenium tailored "chromedriver.exe" and regular "chrome.exe" that you get when you install Google Chrome on your Windows PC?
Thanks,
Vladimir
vladimir.oleynikATmailDOTcom

**Comment by voleynik** [comment]
Found this
https://teamtreehouse.com/community/selenium-web-driver-vs-chrome-driver
"WebDriver is the Selenium library of code containing the FindBys and Clicks and SendKeys code. ChromeDriver is a library of code that controls the Chrome Browser."
I think he is right. 
Any comments?

**Comment by zjhken** [comment]
@voleynik these names are really easy to make people confused.
I think the page you found is talking the other things, which is selenium's api "WebDriver".
and what I found is, seems the chromedriver.exe is make by Google. [homePage](https://sites.google.com/a/chromium.org/chromedriver/home)
seems it can be used instead of the chrome.exe

**Comment by antonpiks** [comment]
chromedriver.exe is a standalone server that takes commands from Selenium Server and communicates with browser's API via JSON commands. There is nothing to do with Chrome browser itself.
To run Chrome headless you better first read this topic: https://developers.google.com/web/updates/2017/04/headless-chrome
