### ISSUE TITLE
2 space indentation across project

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#19]
@aslushnikov 

Mind if we switch to 2-space identation? That's more common in JS projects these days and we tend to stick with Google's style guide in the GoogleChrome org. 

We can extend the google style guide in eslintrc.js to enforce it :)

**Comment by aslushnikov** [comment]
> Mind if we switch to 2-space identation?

The 2-space indentation sounds fine for me - would you mind sending a pr?

> ...we tend to stick with Google's style guide in the GoogleChrome org.

The current eslintrc.js is a copy of [chrome devtools eslintrc](https://github.com/ChromeDevTools/devtools-frontend/blob/master/.eslintrc.js) (with the only difference of 4 spaces, for historic reasons).

I'm not really familiar with the Google's style guide. I think it's fine to adopt it if there's a tool which enforces it to full extend - so that we don't end up with a code written in a mixture of devtool's and google styles.

**Comment by ebidel** [comment]
Sure. I can send a PR with the update.
