### ISSUE TITLE
Response Time in page event

### ISSUE THREAD

**Issue by rafaelugolini** [puppeteer/puppeteer#1929]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: OS X
* URLs (if applicable):
* Node.js version: v8.9.1

Looking at the API, there is no way to retrieve information about how long it took for a network request. The only way I saw to retrieve this information is by using [tracing](https://github.com/GoogleChrome/puppeteer/issues/1368)

What do you think about adding some extra attributes/methods on the [Request](https://github.com/GoogleChrome/puppeteer/blob/HEAD/docs/api.md#class-request) and [Response](https://github.com/GoogleChrome/puppeteer/blob/HEAD/docs/api.md#class-response) to retrieve this information?

**Comment by rafaelugolini** [comment]
Just saw this PR https://github.com/GoogleChrome/puppeteer/pull/1795

**Comment by ebidel** [comment]
Closing in favor of #1795

**Comment by mems** [comment]
The #1795 has been closed long time ago but without been merged.

Also I think it's better to use [response field `timing`](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Response) which provide [detailed informations](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-ResourceTiming) instead of the event's timestamp

**Comment by edwinljacobs** [comment]
Are there any plans for this feature? As far as I can see it this is not available in 2.0.0.
Having access to the ResourceTiming information (https://chromedevtools.github.io/devtools-protocol/tot/Network#type-ResourceTiming) would be very helpful indeed.

I am new to puppeteer so if there is a simple way to do this in version 2.0.0 and I missed it sorry about that.
