### ISSUE TITLE
page.type should block the event loop until complete

### ISSUE THREAD

**Issue by boogerlad** [puppeteer/puppeteer#1958]
### Steps to reproduce

* Puppeteer version: v1.0.0
* Platform / OS version: 4.14.8-1-ARCH & Windows 8, 10
* Node.js version: v9.3.0 & v 9.5.0

**What steps will reproduce the problem?**
test.js
```
(async () => {
	const browser = await (require('puppeteer')).launch({headless: false});
	let page = await browser.newPage();
	await page.goto('https://facebook.com');
	await Promise.all([
		page.type('#pass', 'hello'),
		page.type('#email', 'world')
	]);
})();
```
`node test.js`
**What is the expected result?**
`world` is typed in the email field, `hello` typed in the password field
![2018-02-02t23 20 43-05 00](https://user-images.githubusercontent.com/1903750/35762963-a7e90b02-086f-11e8-8b0b-14444217f928.png)

**What happens instead?**
`hweolrllod` is typed in the email field.
![2018-02-02t23 03 39-05 00](https://user-images.githubusercontent.com/1903750/35762875-9518ec1a-086d-11e8-92ef-768717d6ead2.png)

**Comment by tomgallagher** [comment]
Or maybe better, page.type should have an internal task queue

**Comment by yanivefraim** [comment]
The problem in `ElementHandle`:

```
 async type(text, options) {
    await this.focus();
    await this._page.keyboard.type(text, options);
  }
```

There element focus and keyboard `type` are async, which makes typing in parallel (on different inputs) impossible.

**Comment by yanivefraim** [comment]
The issue is in `ElementHandle`:

```
 async type(text, options) {
    await this.focus();
    await this._page.keyboard.type(text, options);
  }
```

Element focus and keyboard 'type' are one after the other, async, which makes typing in parallel, on different inputs, impossible. 

- I don't like the 'event loop block' idea. 
- Maybe there's a way to do both in same evaluate?
- I'm asking if this is a reasonable behaviour (pressing multiple fields in parallel?)

WDYT?

**Comment by entrptaher** [comment]
- Blocking the event loop for **Promise.all** is not the job for page.type, it's the job for **async await/promises**. 
- You cannot tell chrome to focus on two element at same time. To type on somewhere, you will need to focus. This is not a browser issue, nor it's a puppeteer issue, it's the expected behavior from the browser and the async nature of JS.
- At most you can use evaluate to manually fill up the fields using js, which doesn't require focus.

Otherwise if you want to process huge form fields you can structure the code like this,
![image](https://user-images.githubusercontent.com/8284972/35826969-a129091c-0ae4-11e8-8e55-fa86d20039c9.png)

```js
// structure like this for multiple form fields
const formData = [
    ["#firstName", "hello"],
    ["#lastName", "world"],
    ["#username", "someusername"]
];
for (const field of formData) {
    await page.insert(field[0], field[1]);
}

// structure like this if you want to keep things simple
await page.type('#pass', 'hello')
await page.type('#email', 'world')
```

**Comment by JoelEinbinder** [comment]
This looks like it’s working as intended. As entrptaher said, chrome can’t focus two elements at the same time by design.
