### ISSUE TITLE
Missing HTML content

### ISSUE THREAD

**Issue by MadGhigno** [puppeteer/puppeteer#2007]
Hi,
I'm experiencing a problem on this website with puppeteer.

Website url: http://www.aspo.com/en/news

The page seems to load properly. After the page is loaded it waits for a while before displaying the press-release list. The data for the press-releases is loaded after the main page and it takes a few seconds the be renedered in html.

The html content for the press release list is not present in the code returned by puppeteer.

Below the code to reproduce the issue: 

```
const puppeteer = require('puppeteer');
var fs = require ("fs");
let docRedirected = false;

(async () => {
    const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox'],        
        headless: false,
        timeout: 10000
    });

    const page = await browser.newPage();
    await page.waitFor(1000);
    await page.setRequestInterception(true);
    
    const onResponseHandler = (response) => {
        docRedirected = response._url;
    };

    page.on('response', onResponseHandler);
    
    page.on('request', interceptedRequest => {
        interceptedRequest.continue();
    });
 
    await page.setViewport({
        width: 1280,
        height: 800
    });

    try {
        const htmlCode = await page.goto('http://www.aspo.com/en/news');
        await page.waitFor(500);
        console.log(await htmlCode.text());
        await browser.close();

    } catch (e) {
        console.log(e);
        browser.close();
    }
})();
```

If you search inside the html code returned by puppeteer by one of the title present in the press-release list nothing is present.

Am I doing something wrong ?

**Comment by vsemozhetbyt** [comment]
@MadGhigno 

`htmlCode.text()` (i.e. [`response.text()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#responsetext)) contains HTML returned by the server without any dynamic content added by the page scripts.

You need the [`page.content()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagecontent) instead, but it is huge for this page due to a big amount of data hidden in the Releases table. If you just need a visible list of titles, this can suffice:
```js
console.log(await page.evaluate(() => document.body.querySelector('#archive').innerText));
```
