### ISSUE TITLE
Can I set timeout for screenshot?

### ISSUE THREAD

**Issue by KimSeongIl** [puppeteer/puppeteer#2117]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: mac and docker container(ubuntu 16:04)
* URLs (if applicable):
* Node.js version: 8.9.3

**What is the expected result?**

page.screenshot({ timeout: 1000 });

I want it to run like the code above.

**What happens instead?**

I use many chrome browsers to create many screenshots in real time.

When multiple requests are accumulated in one browser, the puppeteer implements screenshotTaskQueue, which slows down the response.

The page rendering can set a timeout, but the screenshot does not know how to handle the timeout.

I want to control the screenshot.
Is there a way to add a timeout setting to the screenshot?

**Comment by mohanrohith** [comment]
May be below code works for you.

```javascript
function delay(ms) {
    return new Promise(r => setTimeout(r, ms));
}

page.on('load', async() => {
                const p = `${__dirname}/SS_${page_key}.png`;
                await delay(2000).then(() => {
                    return page.screenshot({ path: p, fullPage: true }).catch(e => console.error(e))
                });
            })
```

**Comment by KimSeongIl** [comment]
It seems that the intention of my words is not clearly conveyed.
After a certain period of time, I want to interrupt the operation of the screen shot.

**Comment by JoelEinbinder** [comment]
Would this work?
```js
await Promise.race([page.screenshot(), new Promise((resolve, reject) => setTimeout(reject, 1000))]);
```

**Comment by KimSeongIl** [comment]
@JoelEinbinder 
Great!
It is exactly what I wanted.
thank you!

**Comment by KimSeongIl** [comment]
@JoelEinbinder 
It seems that i can get error results when time passes, but the task of browser.screenshotTaskQueue does not stop.

**Comment by aslushnikov** [comment]
@KimSeongIl the only way to "interrupt" the screenshot is to close the page during the screenshot.

Hope this helps.

**Comment by mattzeunert** [comment]
There are some cases where Chrome doesn't respond to Page.captureScreenshot, so having a timeout for those cases would be nice. Taking a screenshot fails about 1% of the time for me.

I added retry logic to my code a while ago, but only realized yesterday that Puppeteer will still wait for the previous screenshot to finish (which it never does) before retrying.

Today I added an internal Puppeteer patch that adds a timeout to the `screenshot` call. If I retry after 5s it always works and now I can always take a screenshot.

So I think being able to have the call time out would be great. I'd be happy to submit a pull request if you're interested.

(I've not been able to notice a pattern of when taking the screenshot doesn't work. E.g. it's not because the page crashed or something like that.)

**Comment by rmzg** [comment]
I too am running into the situation where after some random number of page open and closes, the screenshot function hangs forever. I don't have a good way to instrument exactly why it stops responding but it is running inside a docker container for what its worth.

**Comment by ForbiddenEra** [comment]
> There are some cases where Chrome doesn't respond to Page.captureScreenshot, so having a timeout for those cases would be nice. Taking a screenshot fails about 1% of the time for me.
> 
> I added retry logic to my code a while ago, but only realized yesterday that Puppeteer will still wait for the previous screenshot to finish (which it never does) before retrying.
> 
> Today I added an internal Puppeteer patch that adds a timeout to the `screenshot` call. If I retry after 5s it always works and now I can always take a screenshot.
> 
> So I think being able to have the call time out would be great. I'd be happy to submit a pull request if you're interested.
> 
> (I've not been able to notice a pattern of when taking the screenshot doesn't work. E.g. it's not because the page crashed or something like that.)

I seem to be running into this as well. Can you post your patch?

No one else ever ran into this?

I do plan on moving to a better method (right now actually using screenshots to basically stream the viewport, plan on making a sink though) but would still use screenshots for other stuff and don't want it hanging up.

I haven't run into this issue until today, with my app sending upto 10-20fps of screenshots for weeks on end but now my code navigates to a placeholder page between sessions and that seemed to trigger it somehow (and actually currently the screenshot timeout is set much higher, anywhere from 333ms-7500ms because screenshots seem to cause remote devtools to flicker) - I'm thinking maybe the page refreshes or loses context during the screenshot somehow, or a race condition between the start of taking the screenshot and finishing.. 

Either way it hangs up; most other functions have a timeout, this would be good IMHO.

**Comment by mattzeunert** [comment]
It's a simple code change in Page.js, something like this:

```
  let timedOut = false
        let timeout = setTimeout(() => {
            timedOut = true
            console.log("captureScreenshot timed out")
            reject("10s timed out")
        }, 10000)

        const result = await this._client.send('Page.captureScreenshot', {
```

**Comment by ForbiddenEra** [comment]
> It's a simple code change in Page.js, something like this:
> 
> ```
>   let timedOut = false
>         let timeout = setTimeout(() => {
>             timedOut = true
>             console.log("captureScreenshot timed out")
>             reject("10s timed out")
>         }, 10000)
> 
>         const result = await this._client.send('Page.captureScreenshot', {
> ```

Thanks; I'll look into this; attempting to timeout the promise from my userland code wasn't helpful, assuming this is within ppt code itself, will have to give that a shot.

Though in general, I'm finding a lot of race conditions / things failing due to lack of timeouts in ppt unfortunately.

**Comment by Tomsterdrew** [comment]
I don't know if this would help you but to fix my issue I discovered that I could change the protocolTimeout when I do puppeteer.launch({protocolTimeout: time, headless: true}) which stopped the code from getting stuck waiting for the screenshot to timeout. This timeout impacts any task or operation that Puppeteer performs through the CDP connection so be aware of that if you decide to use it.
