### ISSUE TITLE
File upload doesn't work when using Browser and browserWSEndpoint

### ISSUE THREAD

**Issue by sdgluck** [puppeteer/puppeteer#2120]
**Tell us about your environment:**

* Puppeteer version: 1.1.1
* Platform / OS version: Windows 10 Pro
* Node.js version: 8.9.3

**What steps will reproduce the problem?**

Please see this SO issue I have asked (and answered):

https://stackoverflow.com/questions/49032568/upload-a-file-with-puppeteer-in-jest

File uploading (`ElementHandle#uploadFile`) doesn't work when using the set-up in [`jest-puppeteer-example`](https://github.com/xfumihiro/jest-puppeteer-example) (i.e. with `Browser({browserWSEndpoint})`). But it does work if I just use a browser and new page directly (as in the SO link above).

**Comment by pklingem** [comment]
reproduced in 1.2.0.  Is this simply not possible with current chromium/puppeteer?  It would seem that puppeteer would need to serialize a file to send over the websocket for this to work.

**Comment by aslushnikov** [comment]
> reproduced in 1.2.0. Is this simply not possible with current chromium/puppeteer? It would seem that puppeteer would need to serialize a file to send over the websocket for this to work.

@pklingem the `elementHandle.uploadFile` doesn't upload file by itself - instead, it sets file path to be used by browser when form submission happens.

`elementHandle.uploadFile` works for me on pptr 1.2.0; can you share the script that doesn't work for you?

> File uploading (ElementHandle#uploadFile) doesn't work when using the set-up in jest-puppeteer-example (i.e. with Browser({browserWSEndpoint})). But it does work if I just use a browser and new page directly (as in the SO link above).

@sdgluck this is surprising to me. WebSocket should have nothing to do with the `elementHandle.uploadFile` functionality. I'd appreciate if you share an example for me to play with.

**Comment by pklingem** [comment]
@aslushnikov thank you for your response.  I was finally able to get this to work.  The issue was:  I had chrome in a docker container and puppeteer in another docker container.  As you said, puppeteer only sends the path to the file to chrome and the chrome container did not have access to the file at that path.  I ended up sharing a volume between the chrome and puppeteer containers so the file would be available at the proper path.

**Comment by joelgriffith** [comment]
Hate to further drag on a closed issue, but I'm curious if there's any development around sending in FileBlobs or Buffers vs a file-path to upload. Reason I ask is that a somewhat-common use-case is to run puppeteer/chrome-headless in isolated environments (lambda or otherwise), and file-uploads are another common web interaction.

Thanks!

**Comment by aslushnikov** [comment]
> I'm curious if there's any development around sending in FileBlobs or Buffers vs a file-path to upload.

I'm not aware of any. Does web platform support this?

**Comment by joelgriffith** [comment]
Probably not 🙃, my use case is of course wickedly different than most since most folks are running puppeteer alongside chrome. Anyways, I'll give this more thought, thanks Andrey!
