### ISSUE TITLE
Speech synthesis?

### ISSUE THREAD

**Issue by mhingston** [puppeteer/puppeteer#2141]
Is speech synthesis available with puppeteer?

Trying to do the following:

```javascript
#!/usr/bin/env node

const puppeteer = require('puppeteer');

const say = async (text) =>
{
    const browser = await puppeteer.launch(
    {
        args:
        [
            '--no-sandbox',
            '--enable-speech-dispatcher'
        ]
    });
    const page = await browser.newPage();
    await page.evaluate(`
        const msg = new SpeechSynthesisUtterance('${text}');
        window.speechSynthesis.speak(msg);
    `);
    await browser.close();
}

say(process.argv.slice(2).join(' '));
```

**Comment by ebidel** [comment]
Headless doesn't support the speech apis: https://bugs.chromium.org/p/chromium/issues/detail?id=815388

Although, you can launch with `headless: false` and  they should work. If you want to use the Google-specific voices (e.g. "Google UK English Male"), you'll need to launch an official Chrome binary using `executablePath`. Chromium doesn't support those.
 
BTW, I didn't need the `--enable-speech-dispatcher`, at least on Mac.

**Comment by ebidel** [comment]
Closing in favor of that upstream chromium bug and the headful workaround.

**Comment by ebidel** [comment]
Speech demo folks might find useful: https://github.com/GoogleChromeLabs/puppeteer-examples/blob/master/speech.js

**Comment by mikegwhit** [comment]
Any updates with this?  I'm interested in building desktop apps that utilize SpeechSynthesis in a Node environment.  Solving this for now with https://github.com/Marak/say.js/ which seems to branch for native voice API's per OS.  More universality is desirable for designing voice experiences etc.

Interest is for a way to build desktop apps utilizing both SpeechSynthesis and listening for voice commands via SpeechRecognition as well (via an API like https://www.talater.com/annyang/).

**Comment by josephrocca** [comment]
The example posted by ebidel doesn't seem to work anymore. The simple example below tries to log the output of `speechSynthesis.getVoices()`, but it always logs an empty array (even after working around [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1114511) by pausing and then calling `getVoices()` a second time, as is done in the code below). 

```js
(async function() {

  const puppeteer = require("puppeteer");

  const browser = await puppeteer.launch({
    headless:false,
    executablePath: "/usr/bin/google-chrome",
    ignoreDefaultArgs: ['--mute-audio'],
    args: ['--enable-speech-dispatcher'] // (this has no effect)
  });
  
  const page = (await browser.pages())[0]; // loads about:blank by default
  
  await page.evaluate(async () => {
    console.log(speechSynthesis.getVoices());
    await new Promise(r => setTimeout(r, 2000));
    console.log(speechSynthesis.getVoices());
  });

  await new Promise(r => setTimeout(r, 10000000));
})();
```

I'm only guessing, but it seems like Chrome is detecting that it is being controlled by an automated tool, and thus disables its non-local voices. For linux, this means that there are no voices at all due to another Chromium bug where native/local voices are not loaded: https://bugs.chromium.org/p/chromium/issues/detail?id=1057775
