### ISSUE TITLE
Can't found module ChromiumRevision building by webpack

### ISSUE THREAD

**Issue by kutsokon** [puppeteer/puppeteer#2245]
* Puppeteer version: 1.2.0
* Platform / OS version: Windows 10
* Node.js version: 8.9.1

I use puppeteer in a production build, and I build my server by webpack, and there is a line of code:

node_modules\puppeteer\lib\Launcher.js
```js
const ChromiumRevision = require(path.join(helper.projectRoot(),'package.json')).puppeteer.chromium_revision;
```

Inside projectRoot there is:

node_modules\puppeteer\lib\helper.js
```js
static projectRoot() {
  if (!projectRoot) {
    // Project root will be different for node6-transpiled code.
    projectRoot = fs.existsSync(path.join(__dirname, '..', 'package.json')) ? path.join(__dirname, '..') : 
    path.join(__dirname, '..', '..');
  }
  return projectRoot;
}
```

Webpack has to resolve this path during building and put `package.json` it in a separate module. But looks like it can't do it, seems something wrong with `__dirname`, option in webpack config `node: __dirname: false/true` doesn't help.

Is it ok to use puppeteer in build, like in one file: server.js?
Is it ok to bundle puppeteer by webpack?
Any workarounds?

**Comment by kutsokon** [comment]
Isn't it better to replace

```js
const ChromiumRevision = require(path.join(helper.projectRoot(),'package.json')).puppeteer.chromium_revision;
```

with this code?

```js
const ChromiumRevision = require('../package.json').puppeteer.chromium_revision;
```

**Comment by kutsokon** [comment]
here is my webpack config:
```js
var path = require('path');

module.exports = {
    entry: path.resolve(__dirname, '../server/src/index.ts'),
    output: {
        path: __dirname + './../dist/',
        filename: 'server.bundle.js',
    },
    target: 'node',
    node: {
        __filename: true,
        __dirname: true,
    },
    module:{
        rules:[
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                exclude: /node_modules/
            }
        ]
   },
    resolve:{
        extensions: [
            '.web.ts',
            '.ts',
            '.web.tsx',
            '.tsx',
            '.web.js',
            '.js',
            '.json',
            '.web.jsx',
            '.jsx',
        ],
    }
};
```

**Comment by MaksJS** [comment]
same problem here

**Comment by vc1** [comment]
Yesterday I tried to use rollup and I can't pack it.

```javascript
const ChromiumRevision$1 = commonjsRequire(path.join(helper$34.projectRoot(), 'package.json')).puppeteer.chromium_revision;
...
function commonjsRequire () {
	throw new Error('Dynamic requires are not currently supported by rollup-plugin-commonjs');
}
```

 And there is a problem with circular references(https://github.com/rollup/rollup-plugin-commonjs/issues/248)

**Comment by Oupsla** [comment]
Hi all ! Do you get a workaround for this one ? 
Can't build a lambda with webpack including puppeteer...

**Comment by MaksJS** [comment]
It only works with versions <= 0.13.0

**Comment by thewillhuang** [comment]
`webpack.config.js`
```js
export default {
  ...
  externals: ['aws-sdk', 'puppeteer'],
}
```

**Comment by aslushnikov** [comment]
Looks like the issue is with webpack; I'd try asking this on the webpack bugtracker.

**Comment by EugeneDraitsev** [comment]
@aslushnikov I checked several issues about webpack bundling ([1644](https://github.com/GoogleChrome/puppeteer/issues/1644), [1224](https://github.com/GoogleChrome/puppeteer/issues/1224)) and I don't understand why  you're closing it. Please, reopen at least 1 issue with this problem to track progress on it or to find some workarounds how to fix it.

**Comment by aslushnikov** [comment]
> I checked several issues about webpack bundling (1644, 1224) and I don't understand why you're closing it. 

@EugeneDraitsev these issues fall outside of our core competency. We can't have issues regarding any "downstream" or integration project here; they should be addressed in their own repositories. I suggest filing over to WebPack because that's their field.

If there's something we can do to help Puppeteer work with WebPack we'd be happy to, but we have no resources to look into this.

**Comment by EugeneDraitsev** [comment]
@aslushnikov You still can help at least to highlighting this issue like **unresolved** and stay active discussion about that. Maybe someone find workaround or solution for this **unresolved** issue in this or another therd, or if webpack team fix it you can add solution to this opened thread to help other developers solve their problem. Also will be nice if you can link webpack issue with this thread. Does it make sense to you?

**Comment by aslushnikov** [comment]
> @aslushnikov You still can help at least to highlighting this issue like unresolved and stay active discussion about that. Maybe someone find workaround or solution for this unresolved issue in this or another therd, or if webpack team fix it you can add solution to this opened thread to help other developers solve their problem

- We close issues when they are no longer "actionable": Puppeteer core team has no plans regarding it.
- Feel free to continue discussion in the closed issue, that's pretty common.

Please file the issue downstream to WebPack repository and post a link here. This way all newcomers will know where to post concerns and further details.

**Comment by aengl** [comment]
I really don't think that this is an issue that would be appreciated in the webpack issue tracker, though, since some of puppeteer's code would be near-impossible to support for any bundler (e.g. dynamic requires).

But it's also not strictly an issue with puppeteer.

I do believe that bundling is an important part of the Javascript ecosystem that any project should strive to support, however.

That being said, if you're not afraid to override some of puppeteer's code, here are the necessary changes to make it work with webpack:

In `node_modules/puppeteer/lib/Launcher.js`

Change
```
const ChromiumRevision = require(path.join(helper.projectRoot(), 'package.json')).puppeteer.chromium_revision;
```
into
```
const ChromiumRevision = require('../package.json').puppeteer.chromium_revision;
```
(as pointed out by @kutsokon already)

In `node_modules/puppeteer/lib/BrowserFetcher.js` (in case you need this module)

Change
```
const request = require(driver).request(options, res => {
```
into
```
const request = require('https').request(options, res => {
```

Lastly, the required bits in the webpack configuration:
```
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  target: 'node',
  optimization: {
    // Disables the built-in UglifyJsPlugin
    minimize: false,
  },
  plugins: [
    new UglifyJsPlugin({
      uglifyOptions: {
        // Necessary for puppeteer, otherwise there will be odd bugs
        keep_fnames: true,
      },
    }),
  ],
};
```

Evidently puppeteer accesses some functions dynamically as well and therefore doesn't play nicely with `UglifyJS`. Keeping function names fixes some odd runtime issues, but I haven't done the research where in puppeteer's code one would have to make changes to address that.

All of these changes were tested with `webpack@4`. Hope it helps! 😃

**Comment by 131** [comment]
How could this be closed ?
We can't bundle puppeteer (with browserify) for the same reasons - this is a major drawback.

A try/catch & fallback to a process.env.PUPPETEER_CHROMIUM_VERSION ( per puppeteer/[install.js](https://github.com/GoogleChrome/puppeteer/blob/master/install.js#L23)  design ) would be perfect

**Comment by daveykane** [comment]
@aengl suggested changes work, I think puppeteer could and should spend some time investigating this issue and look to put a fix / workaround in place.

**Comment by aslushnikov** [comment]
> I do believe that bundling is an important part of the Javascript ecosystem that any project should strive to support, however.

> I think puppeteer could and should spend some time investigating this issue and look to put a fix / workaround in place.

@aengl @daveykane sure, let's make pptr bundle'able. Moving this discussion over to #2119. 

> A try/catch & fallback to a process.env.PUPPETEER_CHROMIUM_VERSION ( per puppeteer/install.js design ) would be perfect

@131 I'm not sure I follow this.

**Comment by Emidomenge** [comment]
Ok guys, I'm on Mac OS and here the solution which I did and work in order to use pupperteer in one single file:

STEP 1:
in `webpack.config.js` add this:
```
//...
  externals: {
   //...
    puppeteer: 'require("puppeteer")'
  }
```

STEP 2:
Install those dependencies and update again your `webpack.config.js` according this [stackoverflow comment](https://stackoverflow.com/a/33527883/6261968)

STEP 3:
`sudo npm install -g puppeteer --unsafe-perm=true`

It should works after :)
