### ISSUE TITLE
Can't control tab focus or interact with tabs when not focused

### ISSUE THREAD

**Issue by natew** [puppeteer/puppeteer#2254]
### Steps to reproduce

Desired actions are:

1. Open a tab while Chromium is not focused
2. Have tab not be selected by default
3. Have that tab do some stuff (load content, then click some things)

**What is the expected result?**

Not doable currently.

Really there's a lot I think that could avoid issues I'm running into. These two primary ones would fix it:

1. `page.bringToFront()` steals focus from other apps. This is annoying for scripting.
2. Page actions like `page.click` require Chromium tab being focused. This prevents parallelization of actions across tabs.

**Comment by natew** [comment]
An alternative helpful API would be to have Browser event `tabchanged`. For my specific use case I could at least wait for the user to change to the tab, then trigger my page actions. That way it wouldn't steal focus by doing bringToFront() preemptively. Sort of a lazy-load action.

**Comment by aslushnikov** [comment]
@natew clicks work just fine for me in non-focused tabs.

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
      headless: false,
    });
    await browser.newPage();
    await browser.newPage();
    const pages = await browser.pages();
    await Promise.all([
      gotoAndClick(pages[0], 'https://aslushnikov.com', 'a.twitter'),
      gotoAndClick(pages[1], 'https://aslushnikov.com', 'a.github'),
      gotoAndClick(pages[2], 'https://aslushnikov.com', 'a.facebook'),
    ]);
})();

async function gotoAndClick(page, url, selector) {
  await page.goto(url);
  await page.waitForSelector(selector);
  await page.click(selector);
}
```

Focus stealing by headful chrome from other apps is expected. The best I can suggest here
is to wait for the sreencast feature #478 and run headless.

**Comment by melissachang** [comment]
I have the same problem. I'm trying to open many tabs and do things in them simultaneously. This works in headless.

With headless=false, browser code from only one tab -- the focussed tab -- is executed at a time.

The problem is, I need headless=false because I need to do a manual Google login (with captcha).

Any other workarounds I can try?

I also tried using mulitple contexts instead of tabs [as suggested here](https://github.com/GoogleChrome/puppeteer/issues/4219#issuecomment-479224433). The problem is, I have to manually login to all contexts.
