### ISSUE TITLE
how to abort requests in Puppeteer with a timeout

### ISSUE THREAD

**Issue by leem32** [puppeteer/puppeteer#2316]
Puppeteer: 1.2.0
Node: 9.6.1

When taking screenshots with Puppeteer I notice that some aren't taken because a script on the website takes to long to load which triggers the `goTo` timeout (after 60 secs). I don't want to increase the timeout any more and even if I did some scripts still don't load because they hang indefinitely.

How can I abort scripts which take to long to load??

I notice `request.abort` accepts `timedout` as an error reason in the API docs but I don't know how I could test/trigger the error.

I would like to abort scripts after around 20 seconds.

```javascript
await page.setRequestInterception(true);

page.on('request', request => {

    if (request.resourceType() == "script") {
        // abort script if it takes longer than 20 seconds to load
    }

});
```

If I cannot abort scripts with ` page.setRequestInterception` how else could I do this?

**Comment by aslushnikov** [comment]
> How can I abort scripts which take to long to load??

@leem32 there are a few strategies you can employ to get similar results:

1. Instead of aborting requests that take more then 20 seconds to load, you can just proceed with the page after the 20 seconds. For example, you can use `Promise.race` to race between `page.goto` command and your custom timer.

```js
await Promise.race([
  page.goto(url).catch(e => void e),
  new Promise(x => setTimeout(x, 20 * 1000))
]);
// Go on with the page: it's either loaded, or we exceeded our 20 seconds timeout
```

2. You can manually fetch scripts server-side and fulfill the `request` with the fetched script body. In this case, you're in full control of aborting requests to scripts however you want.

```js
page.on('request', async request => {
  if (request.resourceType() === 'script') {
    const scriptBody = await fetchScriptInLessThen20Seconds(request.url());
    if (scriptBody)
      request.respond({body: scriptBody});
    else
      request.abort();
  } else {
    request.continue();
  }
});
```

Hope this helps.

**Comment by zengxiaobai** [comment]
I have the same problem and can you tell how is function "fetchScriptInLessThen20Seconds" like?

**Comment by bluepeter** [comment]
Hi @aslushnikov I think this is a serious issue that should be re-opened. There are problems w/ both of the proposed solutions.

We notice that when running Puppeteer/Chrome on Lambda, that some CDNs "sit and spin" when we request blocking JS files. (Presumably this is some WAF response to AWS IPs.) In any event, because of this, `domcontentloaded` and all of the other `waitUntil` resolutions for `goto` never fire. (Note: this occurs only when we use `setRequestInterception(true)`.)

> Instead of aborting requests that take more then 20 seconds to load, you can just proceed with the page after the 20 seconds. For example, you can use Promise.race to race between page.goto command and your custom timer.

The problem with this solution is that in the situation I described, the page response is still null even after the timer wins `race`.

> You can manually fetch scripts server-side and fulfill the request with the fetched script body.

This seems really non-ideal, as we will have to take on cookie management/etc for all of the resources on a page.

What would be ideal is if we can `abort()` a resource even if it has already been `continue()`d?

**Comment by aslushnikov** [comment]
> What would be ideal is if we can abort() a resource even if it has already been continue()d?

@bluepeter there's no such fine-grained control in the devtools protocol, and adding one will require some Chromium work.

> This seems really non-ideal, as we will have to take on cookie management/etc for all of the resources on a page.

To workaround this, you can fetch scripts from-inside the page, or even open new pages to fetch the script; these should do the cookie management for you.

**Comment by hewenguang** [comment]
same issue!! any solution??
