### ISSUE TITLE
Support connecting to a running chromium instance

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#238]
In certain cases, it would come handy to:
- launch a long-running chromium instance which is [detached from parent node process](https://nodejs.org/api/child_process.html#child_process_options_detached)
- connect to the instance later (from another script)

Launching long-running chromium instance might look like this:
```js
const {Browser} = require('puppeteer');
const browserTargetId = Browser.launchDetached({
  // standard Browser options
});
```

Connecting to the detached instance might be:
```js
const {Browser} = require('puppeteer');
const browser = await Browser.connect(browserTargetId);
...
```

To think about:
- stderr/stdout streams would not work for `Browser.connect` (unless those are forwarded to a fd?)
- users should do their own profile folder management

**Comment by rohmanhm** [comment]
Is it already published?
I got this error 😄

```bash
const browserTargetId = Browser.launchDetached({
                               ^
TypeError: Cannot read property 'launchDetached' of undefined
```

**Comment by aslushnikov** [comment]
@rohmanhm it got landed as [`puppeteer.connect`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions)

**Comment by rohmanhm** [comment]
@aslushnikov I can't find any examples. Would you make some examples?

**Comment by ORESoftware** [comment]
buenisismo

**Comment by jbione** [comment]
Hi @aslushnikov  , I tried to connect to an existing chromium instance using "puppeteer.connect" with no success. So I was wondering if "browserWSEndpoint" only exists on chromium instances that are launched with Puppeteer?

Actually, maybe the real question should be, can I connect to an existing instance of chromium that wasn't launched with Puppeteer?

Thanks!

**Comment by lepinekong** [comment]
can I connect to an existing instance of chromium that wasn't launched with Puppeteer?: I really second on this one.

**Comment by rohmanhm** [comment]
@lepinekong I think yes you can, but you need the browserWSEndpoint.

**Comment by jbione** [comment]
Hi guys, after searching for quite a while I found this piece of code that I think will help


$> /Applications/Path To/Google Chrome --remote-debugging-port=9222 # OSX

$> curl localhost:9222/json
[ {
   "devtoolsFrontendUrl": "/devtools/devtools.html?host=localhost:9222&page=1",
   "faviconUrl": "",
   "thumbnailUrl": "/thumb/chrome://newtab/",
   "title": "New Tab",
   "url": "chrome://newtab/",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/1"
} ]


URL: https://www.igvita.com/2012/04/09/driving-google-chrome-via-websocket-api/

Sadly, this doesn't solve my problem because I'm using NightwatchJS with Chromedriver and... other stuff :P and its a little more complicated for me.

I hope that this helps you at least. It seems that it is posible to get the wsEndpoint (webSocketDebuggerUrl) with those commands and with that connect the instance of Chrome to Puppeteer. But you need to launch Chrome with the "--remote-debugging-port=9222" flag and use the port to get the data.

**Comment by dougpagani** [comment]
The methods here didn't really work for me, so I have this as an alternative:

I got it to work without having to require any manual steps. It would be easy to put this into some kind of pre-script instrumentation (especially for tests). This script should be runnable so long as you have an npm project w/ puppeteer (+chromium) installed into node_modules. I only tested this on macos so disparities in process-signalling behavior might break it across OS's, but it's worth a shot even if you're on linux. I wanted to be able to ^C out of the initializing node process and leave a headful browser running, and that's what this gist does.

https://gist.github.com/dougpagani/4681838a12a7821c096640d491649a43
