### ISSUE TITLE
can click fanction returns response instead of None?

### ISSUE THREAD

**Issue by dkkacceler** [puppeteer/puppeteer#2406]
hi there

[https://miyakogi.github.io/pyppeteer/_modules/pyppeteer/page.html#Page.setDefaultNavigationTimeout](url)
`async def click(self, selector: str, options: dict = None, **kwargs: Any) -> None:`

can this function returns response instead of None?
i use this function to click a button and send a http request, i hope to get the http response data ,i want to now how to do that

i use pypuppeteer

**Comment by yrshaikh** [comment]
The above link 404s unless you copy and paste, this is the link he is trying to share - https://miyakogi.github.io/pyppeteer/reference.html#pyppeteer.page.Page.setDefaultNavigationTimeout

**Comment by Kalliser** [comment]
You can't do it directly because puppetter is unaware of a click consequences, you must implement a [request interception](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue) then listen for event [requestfinished](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-requestfinished) where you filter the targeted request in order to retrieve needed data.

**Comment by aslushnikov** [comment]
There's also [`page.waitForNavigation`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions)  that returns Response.
