### ISSUE TITLE
Need to trigger CTRL+S to Save Page and related content

### ISSUE THREAD

**Issue by c094728** [puppeteer/puppeteer#2433]
I can't find any way to do this so maybe this is a feature request.
CTRL+S brings up save page as dialog to save the webpage, complete with all js,css,etc..
I need to trigger and control this from puppeteer.

**Comment by aslushnikov** [comment]
@c094728 pptr doesn't emulate chrome-level input, only webpage. Ctrl-S is implemented on the browser level, so there's no way to get the behavior through pptr.

**Comment by c094728** [comment]
If you can save an image of the page why not implement a function to save page itself with all artifacts (like CTRL+S) does which I believe also fixes up the href and src references to make them all relative so the page can be pulled up in a different directory.

**Comment by aslushnikov** [comment]
@c094728 this functionality falls outside of the scope of the project. But it should be totally possible to implement this atop of puppeteer as a third-party library.

**Comment by vsemozhetbyt** [comment]
It is currently possible via experimental CDP call [`'Page.captureSnapshot'`](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-captureSnapshot) using [MHTML](https://en.wikipedia.org/wiki/MHTML) format:

```js
'use strict';

const puppeteer = require('puppeteer');
const fs = require('fs');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://en.wikipedia.org/wiki/MHTML');

    const cdp = await page.target().createCDPSession();
    const { data } = await cdp.send('Page.captureSnapshot', { format: 'mhtml' });
    fs.writeFileSync('page.mhtml', data);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by sinnlosername** [comment]
Wow, living in 2019 and it's still impossible to trigger a damn hotkey in a browser

**Comment by ghost** [comment]
:(

**Comment by aeksco** [comment]
Just in case anyone else stumbles upon this problem I was able to solve it (somewhat) by manually triggering the hotkey combination at the OS level:

```js
const robot = require("robotjs")

async function savePageAs() {
    // Press the CMD+S hotkey
    robot.keyTap('s', 'command');
    // 1000ms delay
    await new Promise(resolve => setTimeout(resolve, 1000));
}
```

You can then just invoke this function inside your Puppeteer script to perform the `File -> Save Page As` action.

Some caveats:
- This doesn't work when `{ headless: true }`
- The operating system (MacOS, in my case) *must* be have Puppeteer's Chromium browser as the active (mouse + keyboard focus) application, otherwise the global `CMD+S` hotkey will be handled by whichever application is active.

So while this solution "works", it's not suitable if you want to multitask while the Puppeteer script is running (since you'll constantly be moving your focus away from the open Chromium browser window).
