### ISSUE TITLE
Error: Protocol error (Target.closeTarget): Target closed.

### ISSUE THREAD

**Issue by mahnunchik** [puppeteer/puppeteer#2515]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: `node:8` Docker image. It seems to be Debian Jessie
* URLs (if applicable): Any
* Node.js version: 8

**What steps will reproduce the problem?**

1. Open pages with concurrency about 3-5 pages in the same time
2. Wait for the page `load` event.
3. Close page with `await page.close();`

Randomly after some hours of work the error `Error: Protocol error (Target.closeTarget): Target closed.` happened.

**What is the expected result?**

No this error.

**What happens instead?**

`Error: Protocol error (Target.closeTarget): Target closed.` followed by `Error: not opened` for any new pages.

**Comment by aslushnikov** [comment]
@mahnunchik this is a very generic error. This can happen if you try to access the closed page somewhere in your code; or it could be there's some bug on our side. It could also be that that's due to page or browser crashes.

This is not actionable unless there's a repro for me to play with. Please re-file once you have one.
