### ISSUE TITLE
puppeteer 1.4.0 sometimes fails to decode downloaded fonts

### ISSUE THREAD

**Issue by SarveshRedkar** [puppeteer/puppeteer#2544]
Hi there,

**My environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Ubuntu 16.04
* Node.js version: 8.9.3

**The Issue!**

_I have a few HTML documents, which i open using puppeteer. The HTML has custom fonts which i have downloaded in the local directory. Previously I used the 1.3.0 version of puppeteer for opening the files and didn't have any issue. After upgrading to version 1.4.0 sometimes puppeteer fails to decode the fonts and I get the following error._

**The Error!**

> PAGE LOG: Failed to decode downloaded font: file:///home/User/Documents/fonts/optim.ttf
> PAGE LOG: OTS parsing error: cmap: Failed to parse table.

**PS:** 
1. The font mentioned above does work in few cases.
2. This happens with other downloaded fonts as well.
3. After downgrading to version 1.3.0, did not face this issue.

Any help would be greatly appreciated.
Thank you in advance!

**Comment by aslushnikov** [comment]
@SarveshRedkar puppeteer 1.4 is doing a much better job in reporting page messages then pptr 1.3 (see https://github.com/GoogleChrome/puppeteer/pull/2400). To verify this, try running pptr 1.4 against chromium from puppeteer 1.3:

```js
const browserFetcher = puppeteer.createBrowserFetcher();
const revisionInfo = await browserFetcher.download('536395');
const browser = await puppeteer.launch({executablePath: revisionInfo.executablePath})
```

If the logs remain, then that's the case and nothing has changed in practice.

Otherwise, something has changed in Chromium itself; in this case I'd recommend filing a bug upstream to `https://crbug.com/new`.

Hope this helps.
