### ISSUE TITLE
what's the differents between "await page.$(selector)" and "page.$(selector)" ?

### ISSUE THREAD

**Issue by heaven1025** [puppeteer/puppeteer#2575]
Is there anyone met this quesiton?
when I used "await page.$(selector)", and it returned null. but I removed the "await", it returned the right object.
why?

![image](https://user-images.githubusercontent.com/20590402/40275459-0ac68302-5c22-11e8-806f-3e76a231afed.png)

**Comment by vc1** [comment]
null是因为执行结果是没有找到元素；不加await返回的是Promise任务信息，不是实际获取到的元素。
http://es6.ruanyifeng.com/#docs/promise
这种js基础问题就别提issues了

**Comment by ChristosChristofidis** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

**Comment by jiangwenyang** [comment]
your selector didn't anything,so return null. page.$() return a Promise, if you want to get ElementHandle,you should wait for this Promise resolve.

**Comment by SashaDesigN** [comment]
that output which you saw (Promise after await) just displaying that you will return a Promise, but you need to use await because that Promise will resolve the selected element
I mean there will be something like:

return new Promise(resolve => {
  resolve(element);
});

Sure, Promise itself is just a logical wrapper, not selected element at all.
