### ISSUE TITLE
Incorrect values for await page.$$('.')).length

### ISSUE THREAD

**Issue by hexad** [puppeteer/puppeteer#2688]
I wanted to keep scrolling down, until all the elements with a particular classname are loaded in a dynamic HTML environment.

This is the code i used:

`while (  (await page.$$('.xj7')).length < counter) { 
        await page.evaluate( () => 
            window.scrollBy(0, window.innerHeight));
    }`

The problem is that after it loads all the elements, it doesn't stop scrolling. I don't know why is that, as it should exit the while loop.

I decided to test the value of the page.$$('.xj7')).length

I wrote this test code:

`while (  (await page.$$('.xj7')).length < counter) { 
        const read = (await page.$$('.xj7')).length;
        console.log(read);
        await page.evaluate( () => 
            window.scrollBy(0, window.innerHeight));
    }`

The values increased from 12, to 24, then they got stuck at 30! Then when the page has loaded all the elements, the value dropped to 28! I should note the page has hundreds of these elements loaded!

That's why it stucks to this loop. I don't understand while the page has hundreds of these elements, it ranged to these values.

**Comment by hexad** [comment]
Anyone else has had a similar experience?

**Comment by aslushnikov** [comment]
@hexad this looks suspicious. The `page.$$` should work just fine in this scenario; there might be some trickery that happens either in your automation code or in the page itself.

However, there's no way for us to help since there's no way we can repro the behavior.

Closing this for now since it's not actionable; feel free to re-file if you have a good repro for us to play with.
