### ISSUE TITLE
Chrome&Chromium will not display webfonts, @import fonts on Ubuntu 16

### ISSUE THREAD

**Issue by DavidFricker** [puppeteer/puppeteer#2692]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: **1.4.0**
* Platform / OS version: **Ubuntu Server 16.04 LTS**  
* URLs (if applicable): **http://graphemica.com/%E2%A7%81**
* Node.js version: **v8.11.2**

**What steps will reproduce the problem?**
1. Open new browser & page
2. Navigate to URL
3. Take screenshot to file on disk

_Please include code that reproduces the issue._
```
'use strict';

const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({
	headless: false, 
	executablePath: '/usr/bin/google-chrome-stable',
	args: ['--no-sandbox','--disable-web-security','--disable-gpu', '--hide-scrollbars', '--disable-setuid-sandbox']
  });
  const page = await browser.newPage();
  await page.goto('http://graphemica.com/%E2%A7%81');
  await page.screenshot({path: 'example.png'});
  await browser.close();
})();
```

**What have I tried?**
- Bundled version of Chromium and latest stable Chrome
- Headless and non-headless

**What is the expected result?**
As rendered on my Windows 7 desktop:
![image](https://user-images.githubusercontent.com/6656039/41066062-87eb05ec-69d8-11e8-8078-bf3a00571841.png)

**What happens instead?**
The icon is not rendered, instead the placeholder box is shown
![image](https://user-images.githubusercontent.com/6656039/41065993-4c0de670-69d8-11e8-84d3-d0b40018ece2.png)

Any help would be appreciated, already spent most of the day on this issue.

**Comment by puncleV** [comment]
Hello @DavidFricker.
Try to use 9.4.0 version of node. I launched your code and saw a page as fine as suppose to.

**Comment by aslushnikov** [comment]
I agree with @punkkk - the following works just fine for me on pptr v1.5.0:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--no-sandbox','--disable-web-security','--disable-gpu', '--hide-scrollbars', '--disable-setuid-sandbox']
  });
  const page = await browser.newPage();
  await page.goto('http://graphemica.com/%E2%A7%81');
  await page.screenshot({path: 'example.png'});
  await browser.close();
})();
```

**Comment by jroper** [comment]
I've been trying to deal with similar issues, and it appears to be the same cause as #422. Unlike #422, my problem is not solved by taking a screenshot before doing a pdf export (since I'm not doing a pdf export at all). Watching running it in non headless mode, I can see it takes a fraction of a second for the font to load. I suspect all taking a screenshot in #422 did was introduce a long enough latency for the font to complete loading.

What I think triggers this to happen is when there is a very low latency to loading the page, specifically, a low latency before `domcontentloaded` is fired (for me the page is a local file so that's practically instant), but a high latency to loading the font (I'm in Australia, loading the font means a round trip across the pacific).

So the work around is to wait until `networkidle0` on `goto` (though this assumes everyone has a network connection fast enough to load all fonts in 500ms, which is a bad assumption, especially for Australia).

**Comment by noinkling** [comment]
I found this works for me without having to use the `networkidle` options:

```js
await page.goto(...);
await page.evaluateHandle('document.fonts.ready');
```

Documentation is kinda sparse on this browser API, but there's some more info here: https://stackoverflow.com/questions/5680013/how-to-be-notified-once-a-web-font-has-loaded/32292880#32292880

**Comment by Worie** [comment]
I'd suggest to just turn off headless mode for a while and enable devtools, then reassure that there are no CORS related issues - in my case, this was the real issue.
