### ISSUE TITLE
Background Pages Don't Get requestAnimationFrame

### ISSUE THREAD

**Issue by tolmasky** [puppeteer/puppeteer#2694]
So, I'm pretty sure this is related to this: https://bugs.chromium.org/p/chromium/issues/detail?id=834822&can=1&q=requestAnimationFrame%20tolmasky&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

Basically, I am using Puppeteer to run tests. I run many tests at once, in different pages. Since only one page is ever focused at once, the tests are actually all blocked on eachother, waiting on requestAnimationFrame to fire, for the test to finish, and for the page to close, allowing the next one to focus. Is there any way to allow all the pages to "feel" focused. I'd rather not pay the price of starting multiple browsers.

**Comment by aslushnikov** [comment]
@tolmasky since puppeteer 1.5 you can now use [browser contexts](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-class-browsercontext) for parallelization - they should work just fine.

Let me know how it goes.

**Comment by dgp1130** [comment]
Encountered this problem today and took me a while to narrow down the issue to RAF not getting triggered because it was backgrounded due to running multiple pages at the same time.

The link above on browser context appears to be broken, is there any more detail on how Puppeteer should be used for parallelism? There is the [API docs on `BrowserContext`](https://pptr.dev/api/puppeteer.browsercontext/), but exactly how that relates to foregrounded / backgrounded pages is unclear. Is the intended solution for parallelized tests to use a different context for each test with only one page active at a time in each context?

Currently it seems that Web Test Runner currently handles this incorrectly and reuses a single browser context for its concurrency implementation. I suspect the right answer is for it to create a new browser context for each concurrent page, but I figured it was worth checking here to make sure my understanding of the workaround is correct.

https://github.com/modernweb-dev/web/issues/2588
