### ISSUE TITLE
Difference in screenshot compared to our corresponding webpage.

### ISSUE THREAD

**Issue by grv190** [puppeteer/puppeteer#2726]
When i take the screenshot of the webpage, local screenshot has some design alignment issues like having more padding.I couldn't figure out why it is happening?

I am using puppeteer with jest and lib includes emotion package.

**Comment by aslushnikov** [comment]
@grv190 there might be endless reasons for this, and it's quite hard to tell for sure given how little information you've shared here.

If the screenshots were generated on different platforms, using different browser versions, or just in wrong timing - they'll be different simply because environments vary.

If browser and OS are the same, then the problem might be somewhere in the serving stack. It's easy to see simply navigating to the pages. If pages are the same, but their screenshots are different - well, that's a bug, please file it over to us! However, please make sure there's a good repro so that we can reproduce it locally.
