### ISSUE TITLE
 Cannot find module './types/standard' from 'index.js'

### ISSUE THREAD

**Issue by budarin** [puppeteer/puppeteer#2754]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Windows 7
* URLs (if applicable): [repo](https://github.com/budarin/react-bootstrap-project)
* Node.js version: 10.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. upgrade puppeteer from 1.1.1 to 1.5.0 version
2. run test: ````npm test App1```

**What is the expected result?**
to run puppeteer

**What happens instead?**
error: 
```
    Cannot find module './types/standard' from 'index.js'

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:210:17)
      at Object.<anonymous> (../node_modules/puppeteer/node_modules/mime/index.js:4:27)
```

if I return to 1.1.1 version - puppeteer runs and pass the test

**Comment by Prior99** [comment]
I am experiencing the exact same error with version `1.5.0` and it works just fine when downgrading to `1.1.1`.

**Comment by jonjiang1** [comment]
Also had the same error and downgrading worked. Is there no other fix though?

**Comment by aslushnikov** [comment]
I see you've managed to upgrade to 1.5.0 here: https://github.com/budarin/react-bootstrap-project/commit/98923901309ca251cf170c315492403cdff9787d

The error itself doesn't relate to puppeteer: instead it has something to do with jest module resolution.

**Comment by AdirAmsalem** [comment]
**Cause:**
The error happens because puppeteer v1.5 started to use `mime@2.x`: https://github.com/GoogleChrome/puppeteer/commit/37cc9f567d9c2d8da1eeb630d13202e95a48cbed#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32).

in `mime@2.x` they added a `require` to a JSON file: https://github.com/broofa/node-mime/blob/master/index.js#L4

Most "copy-paste" Jest configurations doesn't support loading JSONs as-is, so that's probably the cause.

**To solve the problem:**
Simply add "json" to the `moduleFileExtensions` entry in the `jest` property in your `package.json` file.

```
// package.json

"jest": {
  "moduleFileExtensions": [
    "json"
  ]
}
```

\- You probably already have other extensions there, so make sure not to remove them but to add "json" in addition.

**Comment by alexesca** [comment]
This error is pretty clear. Jests outputs `You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js', 'jsx', 'html'].` I added the file extension(in this case `json`) to my `moduleFileExtension` field in the `jest.config.js` of my lib. If you are using a monorepo, every app/lib creates its own `jest.config.js`.
