### ISSUE TITLE
Cache Chromium

### ISSUE THREAD

**Issue by XhmikosR** [puppeteer/puppeteer#2759]
It would be nice if Chromium used by puppeteer was cached in the npm-cache folder. It's a quite a big download and changing branches/cleaning the local node_modules folder leads to re-downloading from scratch.

**Comment by JoelEinbinder** [comment]
Seems reasonable. I'm not an expert in how npm's cache works (or how it works with yarn). PRs welcome.

**Comment by XhmikosR** [comment]
@JoelEinbinder I'm not an expert either :/ There must be some way we can do this. From a quick look I couldn't find any info, though.

BTW, this change might seem trivial to many people, but if you have a slow internet speed, it'll make a huge difference. ~123 MB isn't a small download.

**Comment by XhmikosR** [comment]
Maybe just caching the download in the `tmp` folder would be a good first step? Although cache won't stick if one clears their temporary folder. I still cannot find any docs about this.

**Comment by aslushnikov** [comment]
> It would be nice if Chromium used by puppeteer was cached in npm-cache folder.

@XhmikosR I have a few concerns regarding this:
- Using designated `npm-cache`, if there's any, will raise some questions regarding yarn-compatibility.
- if you store all chromium revisions in the same designated folder, you'll have to have back-references to the installed puppeteer packages so that you can cleanup unused chromium versions. I'm not sure this is quite manageable.

This all makes it too complicated for us to get into; I'd wait for a better solution to appear somewhere.

> It's a quite big download and changing branches/cleaning local node_modules leads to redownloading from scratch.

I can easily understand the pain; there are a few workarounds I can think of:
- If you're using puppeteer directly, you can use [`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-environment-variables) env variable and [`BrowserFetcher`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-class-browserfetcher) to manage chromium instances on your end.
- you can also install puppeteer globally and hack `NODE_PATH` to teach `require` to get the module from the global install.
- you can have a local proxy that will cache chromium revisions on its end. You can point puppeteer to use your proxy with a [`PUPPETEER_DOWNLOAD_HOST`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-environment-variables) env variable.

Closing this since I don't think this is actionable on our end.

**Comment by XhmikosR** [comment]
Thanks, but IMO your reply isn't the proper one. Anyway, I guess every package which depends on puppeteer will have to struggle with this.

**Comment by vesper8** [comment]
Would also love to see this feature added

Cypress was just recently dealing with the exact same problem of a big binary being redownloaded everytime and not cached. They recently solved the problem and I think it might help to have a look at how they did it, you might be able to do the same

https://github.com/cypress-io/cypress/issues/1300

https://github.com/cypress-io/cypress/commit/a4fa1b32f7f12483382466864d7e995936622dc3

**Comment by suhaotian** [comment]
Hi, you should try [tiny-puppeteer](https://www.npmjs.com/package/tiny-puppeteer)

**Comment by sdwvit** [comment]
Upping this issue.

Totally agree with @vesper8 
It's a shame you can't override executable download path via env var. Look how cypress did it.

**Comment by aslushnikov** [comment]
> It's a shame you can't override executable download path via env var. Look how cypress did it.

@sdwvit it's totally possible. There's the [`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`](https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-environment-variables) env variable, but even more handy is [`puppeteer-core`](http://npmjs.com/package/puppeteer-core) package: [puppeteer vs puppeteer-core](https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-puppeteer-vs-puppeteer-core)

**Comment by jsdevel** [comment]
we really do need a way to change the download location.  right now puppeteer uses it's own directory, which means it gets downloaded to `node_modules`.  i frequently find myself using `npm ci` to prevent modifications to package-lock.json.  as others have mentioned, any dependency that requires puppeteer in a way that prevents hoisting will result in chromium being downloaded multiple times.  puppeteer-core also isn't feasible when you're dealing with dependencies of dependencies.  i find the quick dismissal of this issue to be unfortunate.

**Comment by richardkazuomiller** [comment]
This shouldn't be closed. Any project with Puppeteer installed loses the ability to install its dependencies from the cache. Someone who cares about CI breaking when the site hosting Chromium goes down might want to fix this, for example.

**Comment by isuda** [comment]
Not caching chromium in npm-cache defeats the speed gains made by using `npm ci`. In fact, using `npm ci` Downloading the same build of chromium every time CI is run is super wasteful.

**Comment by mubaidr** [comment]
Electron had similar issue and it uses cache for downloaded binaries: https://www.electronjs.org/docs/tutorial/installation#cache

**Comment by boennemann** [comment]
Maybe I'm missing something, but simply moving the downloadFolder to the home directory, or OS-cache directory, or at least making it configurable with an environment variable would make the default experience so much simpler.
https://github.com/puppeteer/puppeteer/blob/master/src/BrowserFetcher.ts#L146

Locally: 
- Why do I need to download the exact same revision of Chromium for every single project that uses puppeteer?
- Want to nuke node_modules real quick? Congratulations now you're downloading ~200MB of chrome and offline/cached npm installs are broken (this has happened to me on multiple train rides/flights).

CI: 
- Why do I need to write a custom script and do environment variable fumbling to cache the chromium download?

Yes, it is possible to achieve this caching behavior with the skip download environment variables and all that, but it is incredibly cumbersome.

This issue is not about something not working at all, this issue is about a broken default.

I'd rather clean up my chromium download cache folder manually if I run out of diskspace (i.e. never) than stumbling over this literally every single time I'm using puppeteer.
The install script could log a warning if there are too many chromium versions installed. Good enough imo.


Thanks for considering something like this 🙏

**Comment by mik13ST** [comment]
For other struggling with this:
If you put the dependency under `devDependencies` in `package.json` and run `npm install` or `npm ci` with the `--production` flag, installation of `puppeteer` will be skipped along with Chromium download.

Making the dependency dev only might have some other implications. See https://docs.npmjs.com/cli/v6/configuring-npm/package-json#devdependencies.
