### ISSUE TITLE
Doesn't wait until Chromium will end the typing

### ISSUE THREAD

**Issue by borysl** [puppeteer/puppeteer#2784]
Looks like when type is used puppeteer doesn't wait type to be finished with use of promises or await/async

**Environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: windows 10 (17134.112), Ukrainian localization
* URL: https://github.com/borysl/puppeteer-playground/tree/usePromises
* Node.js version: 9.2.0

**Steps to reproduce**

1. Automate simple scenario: puppeteer opens google.com fullscreen, types 'Lego Mindstorm Spik3r' and get the results to the screenshot (see https://github.com/borysl/puppeteer-playground/tree/usePromises)
2. Run the scenario several times (10 times)

**Expected**
Should get screenshots with the Lego Mindstorm Spik3r results.

**Actual**
In 4 cases out of 10 it really gets Lego Mindstorm Spik3r search result.
But in other case it search for rapper Lil Peep, because form is submitted far earlier than the typing is stopped.

**Comment by aslushnikov** [comment]
The reason your code doesn't work for you is because Puppeteer uses a real mouse to click things.
When you do:

```js
await page.click('input[type=submit]');
```

Puppeteer moves the mouse to point over the center of the element and presses mouse button.

It happens so that Google shows autocomplete in response to typing into the search bar; autocomplete appears over the "submit" button and receives mouse click. Thus you search for Lil Peep instead.

The simplest solution would be to issue a fake-click over the button instead:
```js
await page.evaluate(() => {
  document.querySelector('input[type=submit]').click();
});
```

I hope this helps.

**Comment by borysl** [comment]
Thanks! It works stable with this fix

**Comment by djErock** [comment]
Where is 'document' defined in this fix?
