### ISSUE TITLE
API consistency: property getters vs methods

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#280]
Conversation from https://github.com/GoogleChrome/puppeteer/pull/272#discussion_r133332351. Some properties of the public API are exposed as methods:

- `browser.version()`
- `page.protocolWSEndpoint()`, `page.url()`, `page.viewport()`
- `frame.title()`, `frame.url()`, `frame.name()`
- ...

Others are properties:

- `page.mouse`, `page.tracing`
- `dialog.type`
- `request.url`, `request.url`
- `response.url`
- ...

Q: Is there a reason all of these aren't ES5 getters? At the very least, we should be consistent across the API surface.

**Comment by JoelEinbinder** [comment]
`browser.version()` and `frame.title()` return promises and make trips through the protocol.

I'm fine with the others being getters. `dialog.type` is currently a property, but should probably be a getter.

`page.viewport` is a little bit weird because it has an asynchronous setter but a synchronous getter.

**Comment by aslushnikov** [comment]
> Q: Is there a reason all of these aren't ES5 getters? 

We can't have everything as getters/setters since some of them are async.

> we should be consistent across the API surface.

Agreed. Some time ago we decided on a simple rule to tell if something is a getter or a method:

> Everything's a method, unless it's a "singleton" like `page.mouse` or `page.keyboard`.

- it's easy to remember, both as library author and library client
- as a library client, regardless of async nature of a method you can always await it if you're lazy to check docs
- (from the experience with devtools codebase) methods are a pleasure to grep for, whereas grepping getters oftentimes yields a lot of noise. (e.g. `.url` might be a prefix to multiple things)

The rule is currently broken in a few places for different historic reasons, and we weren't proactive enough to fix it. E.g. `Request`/`Response` classes were modeled after the fetch api and inherited their getters (that's no longer a case).

If there are no objection to this codestyle, i'm happy to fix all the outliers.

**Comment by ebidel** [comment]
Thanks for the explanation. Agreed that async calls should remain methods that return promises. 

> regardless of async nature of a method you can always await it if you're lazy to check docs

A nice side effect I hadn't thought of! I guess another reason to keep methods everywhere is for later when if/when we add chaining. Chaining methods is more natural.

> we decided on a simple rule to tell if something is a getter or a method

@aslushnikov, can you drop that in at the top of the API docs if we're sticking with those rules?They'll be new to everyone else coming into the project :)

**Comment by ebidel** [comment]
@aslushnikov can we bring this back, address API consistency for 1.0. Good first bug is fine.

> The rule is currently broken in a few places for different historic reasons, and we weren't proactive enough to fix it. E.g. Request/Response classes were modeled after the fetch api and inherited their getters (that's no longer a case).

Yes please! Just ran into this again with `Response.url`. Everywhere else we use `.url()`.

**Comment by aslushnikov** [comment]
@ebidel sg!
