### ISSUE TITLE
'Error: Node is either not visible or not an HTMLElement' is occurred when I execute Puppeteer 1.5.0-next on Chrome browser

### ISSUE THREAD

**Issue by polikeiji** [puppeteer/puppeteer#2833]
### Steps to reproduce
ElementHandle.click method is throwing an error when I use Chrome. Here is the code snippet for reproducing and the result of executing it.

```javascript
import puppeteer from "puppeteer";
import util from "util";

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        sloMo: 500,
        executablePath:
            "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    });
    const page = await browser.newPage();
    await page.goto("https://example.com", { waitUntil: "load" });
    await page.waitFor("body > div > p:nth-child(3) > a");
    const link = await page.$("body > div > p:nth-child(3) > a");
    console.log(`Link element: ${util.inspect(link)}`);
    await link.click();
})();
```

```
(node:13359) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (.../node_modules/puppeteer/lib/ElementHandle.js:86:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:13359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Tell us about your environment:**

* Puppeteer version: 1.5.0-next.1530333501924
* Platform / OS version: Mac OSX 10.12.6
* Chrome version: Version 67.0.3396.99 (Official Build) (64-bit)
* URLs (if applicable):
* Node.js version: v9.7.1

I'm using the latest next tagged version of Puppeteer to avoid a bug discussed in #1325.

**Comment by JoelEinbinder** [comment]
Puppeteer does not support stable Chrome. Please try chrome canary.

**Comment by polikeiji** [comment]
I could run my code using Chrome Canary (Version 69.0.3480.0 (Official Build) canary (64-bit)).

Thanks for your help!

**Comment by TechQuery** [comment]
@JoelEinbinder 
Since Chrome & Chromium are both support **Remote debugging protocol** (usually have same major version, such as 1.x.x), Puppeteer should have same behavior on same feature.

Especially coders in countries where many global IPs are blocked (such as China mainland), downloading a Chromium binary bundle through NPM is such a hard thing... Installing a stable Chrome from a third party App store or Software repository is much easier for us.

**Comment by TechQuery** [comment]
@polikeiji @JoelEinbinder 
RDP command [DOM.getContentQuads](https://github.com/GoogleChrome/puppeteer/blob/254bc80811774007125c48ad012cc8cd90a5efec/lib/ElementHandle.js#L78) responses nothing on stable Chrome, because it's [a new feature of Chromium Inspector core](https://chromium-review.googlesource.com/c/chromium/src/+/1117920), a ["experimental command"](https://github.com/ChromeDevTools/devtools-protocol/compare/ca7022c...a63ed5b#diff-41658d61346287b01926bf8307b2ac8c)...

This feature seems to have a relationship with [a proposal for CSSOM](http://w3-org.9356.n7.nabble.com/CSSOM-Revisiting-transforms-and-getBoundingClientRect-td18404.html), which is used to return Quadrilateral coordinates of `content-box`, `padding-box` & `margin-box`, just like "Box model" view in Element tab of Chrome DevTools:

![Box model](https://user-images.githubusercontent.com/19969570/42687812-93aa96c0-86cc-11e8-8a2f-fe781d3d6761.png)

**Comment by aslushnikov** [comment]
> This feature seems to have a relationship with a proposal for CSSOM, which is used to return Quadrilateral coordinates of content-box, padding-box & margin-box, just like "Box model" view in Element tab of Chrome DevTools:

@TechQuery `DOM.getContentQuads` returns multiple quads for inline flow elements instead of a single quad in the proposal you referred to. That's critical in our case.

> Since Chrome & Chromium are both support Remote debugging protocol (usually have same major version, such as 1.x.x), Puppeteer should have same behavior on same feature.

Please see our FAQ entry regarding this: https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy

**Comment by oliviertassinari** [comment]
I was facing the same problem. Using the "right" version of Chrome fixed the issue.

**Comment by ratkorle** [comment]
I was having the same problem when running my function on AWS-Lambda bu this happens to be best way to do it:
`const link = await page.$("body > div > p:nth-child(3) > a"); 
  try {
       await page.evaluate((el) => {
       return el.click()
        }, link);
        await page.waitFor(1500);
      } catch (e) {
        console.log(e);
     }`

**Comment by kardrean** [comment]
let tabelinha = await page.waitFor('#tabs > li:nth-child(2) > a', {visible: true})
    console.log(tabelinha);
    if('#tabs > li:nth-child(2) > a', {visible: true}){
        await page.click('#tabs > li:nth-child(2) > a')
    }else{
        console.log('não clicou pra aparecer a tabela')
    }

my problem is that when the element is not visible it does not execute the message on the console and has error
