### ISSUE TITLE
What purpose does puppeteer serve over chrome-remote-interface?

### ISSUE THREAD

**Issue by auchenberg** [puppeteer/puppeteer#289]
I've been working with the author of https://github.com/cyrus-and/chrome-remote-interface for several years now, and I'm wondering what purpose puppeteer serves that couldn't have been contributed to chrome-remote-interface?

chrome-remote-interface is already used by [several projects](https://www.npmjs.com/browse/depended/chrome-remote-interface) and other browsers vendors such as Mozilla in https://www.npmjs.com/package/devtools-client-adapters.

The projects and even the abstractions looks much similar, with the obvious exception of Pupperteer (currently) not supporting other browsers out of the box.

I'm glad to see the Chrome DevTools team pushing for CDP usage outside of DevTools. Just curious on the rationale to fork instead of working with the community.

**Comment by pavelfeldman** [comment]
Puppeteer is the next logical abstraction layer on top of the protocol after cri. It encapsulates some of the web domain specifics:
- interprets network events to implement navigation strategies
- explains how device emulation works
- explains how to capture full page screenshots
- how runtime can be used to evaluate complex / async expressions
- and many more to come...

Basically, it serves as a reference to the protocol implementation, where context and order of the events are as important as the protocol method signatures themselves.

It turns out that with this mission is accomplished, we are getting a sound product that can be used for the PhantomJS scenarios running against the modern Chromium platform. So we decided to go all the way there and commit to the use-case-driven lightweight API for web testing and automation with Puppeteer.

This is by no means a replacement for the devtools protocol as an interfacing API for tool vendors to use, quite the opposite, this is a real-time reference for the key protocol methods usage.

**Comment by paulirish** [comment]
I'll add in that we want to see CDP succeed too. At the same time, it's kind of horrifying that it takes [~75 LOC to take a fullpage screenshot with the protocol](https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a).  I felt uncomfortable asking **all** developers to engage with the browser at that layer.

Instead of those 75 lines, that should be more like

```js
const browser = await puppeteer.launch();
let page = await browser.newPage();
await page.goto('https://www.google.com/');
await page.screenshot({path: 'output.png', fullPage: true});
browser.close();
```

This is more reasonable for all developers who want to write an automation script. 

However, yes... there are usecases that puppeteer doesn't satisfy. For example, it's unclear if Lighthouse will ever move to sit on top of puppeteer, as we have very unique usecases. For those situations and for other tool developers, writing against the protocol layer makes total sense.

As an aside, we're going through the exercise of making sure all the protocol methods and features that Puppeteer is using are non-experimental in the protocol. That sort of backpressure on protocol stability feels good, ya?

**Comment by gersonfs** [comment]
I see the relationship of both with the following analogy:
chrome-remote-interface would be the HTTP protocol and puppeteer a REST API .
Great job, this is my choice to replace phantomjs!

**Comment by auchenberg** [comment]
Thanks for sharing the perspective and reasoning @pavelfeldman @paulirish. My initial understanding of puppeteer was "yet another" pure CDP client, but I now understand that the goals for the clients and abstractions are different.

And yeah @paulirish, protocol stability feels good ;)

**Comment by kensoh** [comment]
The release of Puppeteer is a really exciting development. I've been waiting for some time for something like this to happen. We've seen what happened to PhantomJS (almost 2k open issues and main maintainer stepping down without a successor), NightmareJS (lot of unreplied issues for months, probably the project is not a strategic part of Segment) and so on. In theory it is great for an individual or an established startup to drive a web browser automation project. But in reality, the scope of web browser automation simply gets out of hand very quickly. There are just too much edge cases to support for a fast-changing domain. Being driven by a large commercial entity actually has a chance of making it work out.

I'm speaking from the context of test automation and general browser automation. Puppeteer functions more like the high-level browser automation projects above. Whereas Chrome Remote Interface project really is a low-level way to access all that DevTools Protocol can offer. By being low-level it gives developers the tools to do whatever should be possible with the protocol. Puppeteer on the other hand, by being specifically designed to addressed browser automation, makes it so much easier to do common tasks and pain points encountered for browser testing / automation.

The issue for this domain is the DevTools Protocol (Chrome Debugging Protocol was the old name I think) is designed originally for debugging the browser. It looks like there's intention to support more automation use cases. However there is still a lot of hacking needed to do something simple and what is often required, for the example of capturing a full page screenshot. Chrome Team themselves have to write a lot of code to do that. That's really ok, because of the original purpose of DevTools. Puppeteer, however, bridges that gap by abstracting the many low-level steps into simple browser automation methods.

So it's really 2 different projects for different purposes, and should be allowed to developed separately. So that both projects can iterate at its own maximum speed to reach its own potential faster. I'm a CasperJS user for couple of years, and my initial impression of Puppeteer looks like it could be the foundation to transit CasperJS to support visible / headless Chrome.
