### ISSUE TITLE
Request interception and caching compatibility

### ISSUE THREAD

**Issue by ObviouslyGreen** [puppeteer/puppeteer#2905]
According to this issue, https://github.com/GoogleChrome/puppeteer/pull/1154, caching was disabled during request interception to fix unexpected behavior. It didn't mention in the ticket what didn't work properly, specifics, etc.

Are there any plans on getting caching to work with request interception, or updates on the refactor to fix the chrome limitation that's mentioned in the issue?

**Comment by aslushnikov** [comment]
> According to this issue, #1154, caching was disabled during request interception to fix unexpected behavior. It didn't mention in the ticket what didn't work properly, specifics, etc.

@ObviouslyGreen Let me expand on this. There are a few layers of caching: renderer-based in-memory cache and browser-level cache. Neither of them hits network. Now, request interception is in fact doing *network* interception in Chromium, so it's not getting involved with caching is enabled.

> Are there any plans on getting caching to work with request interception, or updates on the refactor to fix the chrome limitation that's mentioned in the issue?

First of all, the network service refactoring is on it's way in Chromium, but I don't have any ETAs on it. (I personally can't wait for it to happen).

Next, once Network Service is in place, it will be easier for us to teach request interception to work with caching enabled. However, we don't have any plans to do this since there is not enough interest that would justify the effort.

Hope this helps.

**Comment by JohnBruce** [comment]
Consider this me expressing my interest in caching being enabled when request interception is enabled.  Consider the following use case:

While using a proxy, you want caching enabled to save bandwidth cost.  However, you might also want to abort some requests that caching might not save you bandwidth on.  For example, all kinds of images, or one problem I've personally run into a few times, some third party script added via a tag manager or something like it that has outages on its end and prevents load events on the page from ever firing (or delays them beyond navigation timeouts).  

Fwiw, at least as recently as version 1.9.0 allows for caching with requestInterception enabled, so I can use that for a while.  It would be nice not to have to choose between newer versions and features though. 🤷‍♂️ 

Cheers

**Comment by jadell** [comment]
I would also like to see caching enabled with request interception, for the same reasons @JohnBruce mentions. Downgrading is not an option for us at the moment. Please consider this as me expressing my interest in justifying the effort, @aslushnikov

**Comment by jadell** [comment]
@aslushnikov Did the big request interception fix in 1.14 make it any easier to implement having caching enabled with request interception? I'm having to jump through many hoops to try and keep bandwidth usage under control, and it doesn't always work. I'd much rather rely on the browser's native caching abilities.

**Comment by mnmkng** [comment]
I'd also like to express our interest in having request interception and cache working at the same time. We need request interception in various use cases and with the cache disabled, the performance of our applications went down the drain.

I suppose that's because without cached Javascript, the [compile cache in V8](https://blog.chromium.org/2015/03/new-javascript-techniques-for-rapid.html) also does not work. We're running multiple tabs concurrently and this extra overhead is killing our CPU.

**Comment by manusis** [comment]
We were not aware that interception will disable the caching. We had the interception to block certain requests to speed up page load but with caching disabled, it beats the purpose.

Can somebody suggest a workaround to make them both work?

**Comment by mnmkng** [comment]
@manusis We're using a different DevTools protocol command than request interception: `Network.setBlockedURLs` instead.

https://github.com/apifytech/apify-js/blob/dfb346a66fee375fd7ec175a80ff637384270418/src/puppeteer_utils.js#L240

**Comment by manusis** [comment]
Thanks, @mnmkng. We will try that. If it works, it will save us huge bandwidth cost and boost our response time.

**Comment by keithbrianptomo** [comment]
?

**Comment by Kendysond** [comment]
Thanks @mnmkng !!! Your solution really helped!

**Comment by jonasgroendahl** [comment]
Any solution to this? I have the same problem, i want to block stuff like images but still make use of the cache to save network traffic needed when behind a proxy

**Comment by Androbin** [comment]
My use case is about using a proxy with authentication. Setting proxy headers manually is blocked by Chromium and using the new authenticate function does request interception.

**Comment by mnmkng** [comment]
@Androbin for your use-case you might want to see the [proxy-chain](https://github.com/apify/proxy-chain#anonymizeproxyproxyurl-callback) library (see the `anonymizeProxy` function). It adds a local proxy between Puppeteer and outside world and allows you to do any request processing you might. We use it in production all the time.

**Comment by emiliavanderwerf** [comment]
+1 for enabling request interception and caching simultaneously. What is the status of this feature please?

**Comment by Androbin** [comment]
My use case has been solved by #6962 @mnmkng your workaround is not needed anymore

**Comment by Androbin** [comment]
@jonasgroendahl Does #6996 work for your use case?

**Comment by leadscloud** [comment]
> 适用于您的用例？

new pptr version. 

`page._client.send is not a function`
