### ISSUE TITLE
Can't access Page on Page close event

### ISSUE THREAD

**Issue by ganuonglachanh** [puppeteer/puppeteer#2910]
Page close event should fire before unload Page.
### Steps to reproduce

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
  page.once('close', () => {
    console.log('Page closed!');
    let cookies = await page.cookies();
    console.log(cookies );
  });
```

**What is the expected result?**
print out cookies.

**What happens instead?**
error

**Comment by aslushnikov** [comment]
We don't have an event that page is about to close; if we were to have one, it wouldn't work since there'll be a race condition between page closing and your script querying for cookies.

However, since cookies are stored inside browser context, it will be enough to just query context for cookies. There's a FR for this: #645 

Closing this in favor of #645.
