### ISSUE TITLE
Error: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by petarthewizard** [puppeteer/puppeteer#2917]
I am getting the above error with a very simple setup here is the code:

```
const puppeteer = require('puppeteer');

(async function() {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.goto('https://digg.com', {"waitUntil" : "networkidle0"});

    await page.setViewport({width: 1280, height: 768});

    await page.waitForNavigation({'waitUntil' : 'networkidle0'}).catch(function (err) {
        console.log('Error while waiting for navigation.', err);
    });

    await page.screenshot({path: 'digg-issue.png', fullPage: true});

    browser.close();
})();
```

I am using digg.com as the example website but same happens for www.bbc.com. The waitForNavigation in this is a bit weirdly placed as it doesn't serve any purpose but this is just an example I want to use this in a script where I scroll down the page little by little and then use it to wait for networks requests to finish/load so that I know that lazy loaded images are loaded.

Any solutions?

**Comment by aslushnikov** [comment]
@petarvasilev91 you're trying to (ab)use `waitForNavigation` to get the idleness state of the page. This doesn't work since navigation is required to change page's URL (see this [FAQ entry](https://github.com/GoogleChrome/puppeteer/#q-whats-considered-a-navigation)).

Instead, you should craft your own little idleness detector that aims towards images only. You can use the
[`request`](https://pptr.dev/#?product=Puppeteer&version=v1.6.0&show=api-event-request), [`requestfinished`](https://pptr.dev/#?product=Puppeteer&version=v1.6.0&show=api-event-requestfinished) and [`requestfailed`](https://pptr.dev/#?product=Puppeteer&version=v1.6.0&show=api-event-requestfailed) events for this.

A draft:

```js
let inflightImageRequests = 0;
page.on('request', request => {
  if (request.resourceType() !== 'image')
    return;
  ++inflightImageRequests;
});
page.on('requestfinished', requestFinished);
page.on('requestfailed', requestFinihsed);

function requestFinished(request) {
  if (request.resourceType() !== 'image')
    return;
  inflightImageRequests = Math.max(inflightImageRequests - 1, 0);
  if (inflightImageRequests)
    return;
  console.log('All image requests are complete!');
}
```

Hope this helps.
