### ISSUE TITLE
Handling `always open these types of links in the associated app`  Dialogs

### ISSUE THREAD

**Issue by 1c3z** [puppeteer/puppeteer#2948]
example 
![image](https://user-images.githubusercontent.com/9052484/43140209-03f52adc-8f86-11e8-8bdc-6e92e90ff79e.png)

**Comment by ThomasSimeroth** [comment]
Check out [the dialog class.](https://github.com/GoogleChrome/puppeteer/blob/v1.6.0/docs/api.md#class-dialog)

I suppose it doesn't have a way to respond to check-boxes though. Still, since every browser instance loses cookies when its closed, I don't think remembering to open links in a certain way would be helpful. I could be wrong though.

**Comment by 1c3z** [comment]
@ThomasSimeroth the dialog class only handle alert prompt

**Comment by aslushnikov** [comment]
@1c3z unfortunately, these are not supported and we don't have any support for these in DevTools protocol. I wonder if there's any chrome preference or flag you can use to workaround these.

I'll close this for now. If there's a substantial demand, we can revisit this later on.

**Comment by YodaLightsabr** [comment]
Is there a way to close it using keyboard presses? Or somehow interact with the page while it's showing?

**Comment by vpanichkin** [comment]
Any solutions?

**Comment by YodaLightsabr** [comment]
^ Is this still being worked on?

**Comment by AlexMarchini** [comment]
+1 for handling these. I can't find a solution.
