### ISSUE TITLE
"ResizeObserver loop limit exceeded"

### ISSUE THREAD

**Issue by raja1313** [puppeteer/puppeteer#3026]
I am Facing this issue only on running E2E Test cases via chrome V68.0.3440.84
"ResizeObserver loop limit exceeded" 

Actual Result:
1) My test cases failed due to "ResizeObserver loop limit exceeded".
2) But All my test cases running successfully when run with Firefox browser

Expected Result:
It should run also on chrome puppeteer in the Upgrade version's too.

**Comment by aslushnikov** [comment]
Puppeteer doesn't use any ResizeObserver  per se, so this might be a Chromium issue that relates to your website.

If this is the case, than it's nice since your tests seem to uncover a real issue in Chromium :) I'd file this upstream to https://crbug.com/new with a good repro steps. This will help chromium authors to fix the bug.
