### ISSUE TITLE
iterating over page.$(selector)?

### ISSUE THREAD

**Issue by rcarmo** [puppeteer/puppeteer#303]
Hello there,

I'd love to be able to iterate over multiple `elementHandle`s, but cannot fathom how to do so. Are there any plans to extend selector evaluation functionality so that we can iterate over results?

I'm trying to do:

```javascript
const divs = await page.evaluate(() => {
    return Array.from(document.querySelectorAll('div'));
});
```

As a workaround, but I cannot find a way to convert the items in `divs`into `elementHandles`, and can't do `elementHandle.hover()`

**Comment by aslushnikov** [comment]
This is similar to #302. I'd also would love to have `page.$$` for the `document.querySelectorAll`.

**Comment by ivanvanderbyl** [comment]
@rcarmo The approach you're taking isn't possible because of the separation between your script and the context in which `evaluate` is running. `evaluate` is similar to calling a script in the Chrome console, as such when the result from this function returns, it has to be serialized and sent back to your script as primitive values, or basically anything which `JSON` can serialize (numbers, strings, booleans, nulls etc) but not Elements and or the DOM.

So for your example, you can do all the work you need on the element inside the evaluate context and return the result to your script:

```js
let content = await page.evaluate(() => {
  let divs = [...document.querySelectorAll('div')];
  return divs.map((div) => div.textContent.trim());
});
```

**Comment by rcarmo** [comment]
@ivanvanderbyl but the result doesn't seem to be an array of `elementHandles`... well, I'll keep fiddling.

**Comment by simone-sanfratello** [comment]
I'm using this solution

it's not elegant, it's not fast, it left a dirty custom attribute on DOM, but allow to use `ElementHandle` as `page.$` does

```js
  async function $$ (page, selector) {
    const ids = await page.evaluate((selector) => {
      const list = document.querySelectorAll(selector)
      const ids = []
      for (const element of list) {
        const id = selector + ids.length
        ids.push(id)
        element.setAttribute('puppeteer', id)
      }
      return ids
    }, selector)
    const getElements = []
    for (const id of ids) {
      getElements.push(page.$(`${selector}[puppeteer=${id}]`))
    }
    return Promise.all(getElements)
  }

// ...

const anchors = await $$(page, 'a')
for (const anchor of anchors) {
  anchor.click()
}

````

**Comment by pavelfeldman** [comment]
Closing in favor of #382.
