### ISSUE TITLE
npm crash when installing on windows 10

### ISSUE THREAD

**Issue by Pomax** [puppeteer/puppeteer#308]
Trying to run `npm install puppeteer` on windows 10 yields the following crash notifation:
```
c:\Users\Mike\Documents\git\temp\pluginboutique>npm install --save-dev puppeteer

> puppeteer@0.9.0 install c:\Users\Mike\Documents\git\temp\pluginboutique\node_modules\puppeteer
> node install.js

Downloading Chromium r494755 - 113.3 Mb [====================] 100% 0.0s
npm ERR! path c:\Users\Mike\Documents\git\temp\pluginboutique\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'c:\Users\Mike\Documents\git\temp\pluginboutique\node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'c:\Users\Mike\Documents\git\temp\pluginboutique\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'c:\\Users\\Mike\\Documents\\git\\temp\\pluginboutique\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'c:\\Users\\Mike\\Documents\\git\\temp\\pluginboutique\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

(For obvious reasons, there is no way in hell I am running any npm install commands with adminstrator rights =D)

**Comment by aslushnikov** [comment]
puppeteer doesn't require fsevents anywhere, is it part of your project?

**Comment by Pomax** [comment]
could be, this is a `create-react-app` generated project so I don't know what their default install set is. That said, another project's node modules shouldn't really manifest during an `npm install` for this dependency (at least... I wouldn't think it would)?

**Comment by aslushnikov** [comment]
can you install any other package?

**Comment by Pomax** [comment]
yeah, I'm doing some "browser-supported" work and have been trying all the various browser-like libraries: phantomjs, jsdom, slimer, etc. all install just fine

**Comment by aslushnikov** [comment]
@JoelEinbinder Joel, could you please take a look on windows?

**Comment by JoelEinbinder** [comment]
I can't reproduce with node 7.10.0 on windows 10 by doing `create-react-app` and then `npm install puppeteer`

**Comment by joemanfoo** [comment]
I get an error as well. I cannot install latest node (I'm on `6.11.2` for keeping environment at the same as Google Cloud Functions). Install process output below. I can install other modules that require `node-gyp`, etc, `phantomjs` installed find, etc.,

I'm pretty sure the issue is with the `async` - if you're going to use advanced features, shouldn't the code be transpiled for less headaches with versions of node that are in LTS pipeline?
```
PS C:\Users\Joe\Downloads\node-test> npm i --save puppeteer

> puppeteer@0.9.0 install C:\Users\Joe\Downloads\node-test\node_modules\puppeteer
> node install.js

C:\Users\Joe\Downloads\node-test\node_modules\puppeteer\utils\ChromiumDownloader.js:89
  downloadRevision: async function(platform, revision, progressCallback) {
                          ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Joe\Downloads\node-test\node_modules\puppeteer\install.js:17:20)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "puppeteer"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@0.9.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.9.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Joe\Downloads\node-test\npm-debug.log
```

**Comment by Garbee** [comment]
Node under 7.x is not supported. Ref #316

**Comment by joemanfoo** [comment]
Thanks @Garbee - Was just reading through previous issues and literally spotted the conversations on node version support when I saw your comment notice.

I use GCF and have massive need to be able to get access to a canvas to run fabricjs server side...

**Comment by Pomax** [comment]
The oddity here being that I'm on Node 8.2.1, so the code itself shouldn't be an issue here. It looks more like it's trying to tap into module that it thinks should be installed, but isn't.

**Comment by Pomax** [comment]
I wiped the node_modules directory and reran `npm install` followed by `npm install --save-dev puppeteer` and nothing throws up any errors, so I am very curious as to why this caused filesystem errors before, but apparently it's not reproducible; which means I'll close this and if I run into it again I'll refile with STR (provided I can find any)

**Comment by Garbee** [comment]
`fs-events` is only for Mac OS (Darwin) based systems. So yea, something funky happened during your initial install attempt.

**Comment by utkarshsaraogi** [comment]
Hi.! Not sure this the right place to ask this question, but since this is related to windows 10, I'll post here anyway.
I am trying to run the project for development following readme in Windows 10, 
When trying to build the project using: "npm i && npm run dev" just prints variables and stops without any errors.


LOG:
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 34283 packages in 13.887s
found 1468 vulnerabilities (70 low, 4 moderate, 1390 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> puppeteer-recorder@0.5.3 dev D:\The Solar Labs\puppeteer-recorder
> set NODE_ENV=development DEBUG=puppeteer-recorder:* webpack --watch

any sort of help is much appreciated. Thanks.

**Comment by utkarshsaraogi** [comment]
Hi.! Not sure this the right place to ask this question, but since this is related to windows 10, I'll post here anyway.
I am trying to run the project for development following readme in Windows 10, 
When trying to build the project using: "npm i && npm run dev" just prints variables and stops without any errors.


LOG:
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 34283 packages in 13.887s
found 1468 vulnerabilities (70 low, 4 moderate, 1390 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> puppeteer-recorder@0.5.3 dev D:\puppeteer-recorder
> set NODE_ENV=development DEBUG=puppeteer-recorder:* webpack --watch

any sort of help is much appreciated. Thanks.

**Comment by Pomax** [comment]
@utkarshsaraogi this issue is closed. File a new issue and then refer to this one if you have to, but don't comment on a closed issue with a new problem =)
