### ISSUE TITLE
Replace the 'entire' path for the chrome version

### ISSUE THREAD

**Issue by rchancey** [puppeteer/puppeteer#3086]
### Steps to reproduce

**Tell us about your environment:**
I am using jsreport 2.1.1, and using the chrome-pdf generator.
Running this under node 8.10
Running this on AWS Lambda. 

Also running local on a Mac and using bitbucket for builds and serverless for deployment

The version of Chrome that is download by default does not work on AWS.. this is a well known issue and many folks have created chrome versions / builds that work. 

The issue is .. puppeteer has expose environment variables to prevent the default Chrome from being downloaded.. which is GREAT.. it also has an environment variable to change the Chrome download 'host' .. which is ALMOST great. 

The is an env variable to change the 'version' of the chrome download as well. 

The bad news is ... parts of the URL are still hard coded.. so we can't actually point to a different chrome instance that would be compatible with AWS Lambda. The code still adds the following to it:
/chromium-browser-snapshots/Linux_x64/564778/chrome-linux.zip

What we need, and a LOT of people would really make use of this, is a way to replace the ENTIRE url with a new one .. including the file name.

The URL could even be an S3 bucket that is exposed. This way we can even maintain a copy and even generate our own builds. 

Please enable the entire URL to be changed / replaced with an environment variable. 98% of the code is already in place.. just have to enable that. 

btw.. this will work for serverless and bitbucket, but would be nice if this also worked for local installs too. Basically enable the same environment variable to be set inside package.json for local overwrite. 

please help! JS report is moving off phantom and with this issue we are stuck on a deprecated pdf generator

**Comment by aslushnikov** [comment]
Hey @rchancey,

So the way we *want* this to work is to have community publish a `puppeteer-aws` package that depends on [`puppeteer-core`](https://github.com/GoogleChrome/puppeteer#puppeteer-core) and has it's own `install.js` to download AWS-compatible version of Chromium. 

Since there's no `puppeteer-aws` ATM, you can do the same trick and depend on `puppeteer-core` instead of `puppeteer`. This gives you a lot of flexibility with managing your own Chromium version. And since `puppeteer-core` doesn't download anything, you won't need to mess with ENV variables.

Would this work?
