### ISSUE TITLE
request.abort() doesn't work for stylesheet in v.1.7.0

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#3089]
Puppeteer version: 1.7.0
Platform / OS version: Win10
Node.js version: 9.4.0
Chromium Version: r579032

request.abort() works on image but doesn't work for stylesheet.

For example:

```js
var puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        userDataDir: "profile",
        ignoreHTTPSErrors: true,
        dumpio: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu']
    });
    const page = await browser.newPage();
    await page.setCacheEnabled(false);
    await page.setRequestInterception(true);
    await page.on('request', request => {
        if ((request.resourceType() === 'image') || (request.resourceType() === 'stylesheet')) {
            request.abort();
        } else {
            request.continue();
        }
    });
    await page.goto('http://www.milas.bel.tr/index.php?modul=2_16&ID=1246', {
            waitUntil: ['networkidle0', 'load', 'domcontentloaded'],
            timeout: 10000
        })
        .then(async () => {
            //something
        })
        .catch(async (error) => {
            console.log(error);
            await browser.close();
        });
    await browser.close();
})();
```

Above code returns 

> "Error: Navigation Timeout Exceeded: 10000ms exceeded"

**Comment by aslushnikov** [comment]
The core issue here is that for certain requests (POST requests that got redirected with 302) DevTools protocol reports unmatching `requestWillBeSent` and `requestIntercepted` events; that's a bug in devtools protocol.

Interestingly this is broken in different way for both NetworkService and non-NetworkService instrumentation. The NetworkService part was regressed back in february: https://chromium-review.googlesource.com/c/chromium/src/+/861952

We'll need to fix this upstream; we'll likely fix this for NetworkService instrumentation only since that's the upcoming future.

**Comment by aslushnikov** [comment]
Closing this in favor of #3471
