### ISSUE TITLE
JS stops running when put chromium in background (hide or minimize)

### ISSUE THREAD

**Issue by thkdog** [puppeteer/puppeteer#3148]
* Puppeteer version: 1.7.0
* Platform / OS version: Mac OS 10.13.6 (17G65)
* URLs (if applicable):
* Node.js version: v8.9.4

**What steps will reproduce the problem?**
1. start a puppeteer program whatever control the elements
2. hide the chromium (CMD+H), or minimize the chromium, or move to another desktop

**What is the expected result?**
The program continues running

**What happens instead?**
The program just paused. It will continue when you reactivate the chromium (put it in foreground)

**Comment by aslushnikov** [comment]
Seems to be a dupe of #3156.

**Comment by david-littlefield** [comment]
### [Solution]:

Add the following values to the array you assign to the args property in the options object. Now, you should be able to run Puppeteer while your window is in the foreground, background, or minimized. 

```
const chromeArgs = [
  '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-renderer-backgrounding'
];
```
Solution and explanation available in an article written by **Rohit Kumar**, @rkr090 at Big Binary:

[Debugging failing tests in puppeteer because of background tab](https://blog.bigbinary.com/2018/08/15/debugging-failing-tests-in-background-tab-in-puppeteer.html)
