### ISSUE TITLE
Clarify how to use puppeteer-core in docs

### ISSUE THREAD

**Issue by callumlocke** [puppeteer/puppeteer#3157]
puppeteer-core sounds appealing, but readme doesn't make it very clear how to use it or what the trade-offs are.

- Is it a drop-in replacement for puppeteer, e.g. `const puppeteer = require('puppeteer-core')`?
- Does it just use whatever Chrome I've got installed on my machine, as the current user? What if I've got multiple Chrome versions (stable, canary, Chromium)?
- Why might I prefer to just keep using the regular (slow to install) version?

**Comment by aslushnikov** [comment]
@callumlocke Good points, thanks for bringing these up.  We'll need to publish a separate README for the puppeteer-core.

Meanwhile, answering your questions:

> Is it a drop-in replacement for puppeteer, e.g. const puppeteer = require('puppeteer-core')?

Yes. The only difference between `puppeteer-core` and `puppeteer` atm is that `puppeteer-core` doesn't install chromium.

In general, we think of `puppeteer-core` as a library to work with devtools protocol, whereas `puppeteer` is a "product". In future, `puppeteer` will learn to respect ENV variables to drive its operation (e.g. `PUPPETEER_EXECUTABLE_PATH` will be used to set default executable path), whereas `puppeteer-core` will respect only programmatic api.

> Does it just use whatever Chrome I've got installed on my machine, as the current user? What if I've got multiple Chrome versions (stable, canary, Chromium)?

You'll have to explicitly specify `executablePath` option in the [`puppeteer.launch`](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-puppeteerlaunchoptions); alternatively, you can connect to a running instance with [`puppeteer.connect`](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-puppeteerconnectoptions)

> Why might I prefer to just keep using the regular (slow to install) version?

`puppeteer-core` comes handy if you don't need the chromium instance that comes with `puppeteer`. There are surprisingly many usecases like this:
- building products that rely on devtools protocol. For example, some `my-pdf-generator` might want to use headless shell instead of Chromium. In this case, `my-pdf-generator` might depend on `puppeteer-core` and have its own custom `install.js` that pulls in the binary.
- if you want to bundle pptr to run inside browser / electron / extension, i'd recommend using `puppeteer-core` since it doesn't take time to install on the dev machine.

**Comment by aslushnikov** [comment]
This is now addressed by [puppeteer vs puppeteer-core](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core) section in our docs.

**Comment by LarenDorr** [comment]
@aslushnikov Hi, I want to use `puppeteer-core` in my Electron application for decrease package size. And I found only can use `executablePath` to point `puppeteer-core` chromium path . My question is set `electron.exe` whether can used for `electron-core`, if not, how to reuse the Electron's chromium : )

**Comment by Maxwell2022** [comment]
I had to come here to know that I need to use `puppeteer.connect()` I was looking at the options of `.launch()`. Maybe this could be added to the `puppeteer vs puppeteer-core section`

**Comment by peperoca116** [comment]
Hello, sorry if my question is a very basic one. I'm deploying an app in a PaaS system and a lot of the puppeteer tools works flawlessly. I tried to deploy it using puppeteer and it worked. Then to save some space and deploy timing i tried to use puppeteer-core, in a local environment it still work with executablePath pointing to the executable file of chromium or chrome, i also used '--no-sandbox', '--disable-setuid-sandbox'. But when i deploy the application to the cloud platform it says 

Error: Failed to launch chrome!  ENOENT, i understand that the app is looking for the executable file, but my question is:
Is it possible to run the app with puppeteer-core in a PaaS service?

**Comment by vj01** [comment]
Hi @aslushnikov !
As you mentioned using puppeteer-core instead of puppeteer as it saves time which is used to install chromium on machine. Is this also take less time to launch browser instance i.e puppeteer.launch . Or the time chromium takes to load DOM and generate pdf, will be lesser with puppeteer-core?
