### ISSUE TITLE
Support callbacks _and_ Promises

### ISSUE THREAD

**Issue by pakastin** [puppeteer/puppeteer#326]
Hi! First of all thanks for the tool, it's wonderful to have an official API!

What's the reason to only use promises? You could as well also support callbacks, which still are the official way of doing async programming in node.js. They're also not going anywhere as the node team has planned to support them both simultaneously.

Thanks!

**Comment by ithinkihaveacat** [comment]
It does seem a little OTT to use Promises absolutely everywhere. For example, if I'm reading the API correctly, if you want to set headers, user agent, *and* viewport, you need to either await on everything and execute sequentially:

```js
await page.setExtraHTTPHeaders(…);
await page.setUserAgent(…);
await page.setViewport(…);
// page is ready
```

or do something funky with Promise.all():

```js
Promise.all([
  page.setExtraHTTPHeaders(…),
  page.setUserAgent(…),
  page.setViewport(…)
]).then(() => {
  // page is ready
});
```

(Are there any other patterns?) Neither of these seems particularly ergonomic or idiomatic…

**Comment by pakastin** [comment]
Well, first of all why those separate `.setXxxxx` and not something like:
```javascript
page.set({
  extraHTTPHeaders: { ... },
  userAgent: { ... },
  viewport: { ... }
}, next);
```

**Comment by pakastin** [comment]
Node.js LTS doesn't support async/await at all, that's another argument..

**Comment by pakastin** [comment]
Why thumbs down? I suggested that **both** promises and callbacks were supported..

**Comment by Garbee** [comment]
Node 8 will go LTS in October. Which is the estimated time for this to be stable. So, it will align with LTS supporting async and all. This is a bleeding edge library and is not currently marked as stable. So supporting older Node isn't a high priority. Ref #316

**Comment by ebidel** [comment]
Promises are used in most places because of the async nature of interacting with Node > DevTools protocol > browser > and back. We used to have an [explanation](https://github.com/GoogleChrome/puppeteer/commit/1e5d9fd8c00705cf00f4472b379edffa6e121edc#diff-04c6e90faac2675aa89e2176d2eec7d8L143) in the readme:

> Since Puppeteer's code is run by Node, it exists out-of-process to the controlled Chromium instance. This requires most of the API calls to be asynchronous to allow the necessary roundtrips to the browser.

IMO, Promises offer a lot of benefits over callbacks: more composable, easier to deal with error handling, reduce [callbackhell](http://callbackhell.com/)....so it's nice to support these patterns out of the box. You can also parallelize multiple operations using `Promise.all` and `async/await` make all of that even better.
