### ISSUE TITLE
The event await page.click('#selector'); does not respond after completion

### ISSUE THREAD

**Issue by StasToken** [puppeteer/puppeteer#3282]
**Tell us about your environment:**
* Puppeteer version:1.5.0
* Platform / OS version:Ubuntu
* Node.js version: 8.9.4

I have encountered unexplained behaver of the event
await page.click('#selector');
I use code:
```
    if (await page.$('#selector') !== null){
    	await page.click('#selector');
    }
    console.log('hello'); // Will not be displayed!!!
```
That the code comes to the line await page.click('#selector'); there is a click on the page, but then no absolutely no code is executed
```
    if (await page.$('#selector') !== null){
    	page.click('#selector');
    }
    console.log('hello'); // Will be shown!!!!
```
WTF!? - Why does it click on an element and go to another page, but the code with **await** does not work anymore, it just gets up and everything!

I'm honestly over the whole practice is the first time you see it is very similar to what page.click is working but will not resolve not reject

**Comment by aslushnikov** [comment]
@StasToken the reason the `console.log` will not be displayed in the second class is because you don't await the click; since the click promise doesn't resolve for you, it hangs in the first snippet.

Can you provide me with a repro script? The fact that `page.click` doesn't resolve is a bug.
Also: try using a newer version of puppeteer - v1.8.0. We did a lot of work to make clicking reliable there.

**Comment by thamerla** [comment]
@aslushnikov I would like to reopen this, encountered the same issue.

**Comment by aslushnikov** [comment]
@nonyy please file a new issue; this one doesn't have sufficient information.

**Comment by nhhockeyplayer** [comment]
whats new issue

same problem persists

latest release
