### ISSUE TITLE
page.click in background tabs are not working.

### ISSUE THREAD

**Issue by imkimchi** [puppeteer/puppeteer#3318]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: macOS Mojave / 10.14
* URLs (if applicable):
* Node.js version:  v10.5.0

**What is the expected result?**

**What happens instead?**

when I create multiple pages and click on the same element in each page, clicking only works in the current tab. my code looks like below, any ways to acheive this?

```
let promises = []

for (page of pageLength) {
  promises.push(browser.newPage().then(crawlPage => {
    await crawlPage.goto('example.com')
    await crawlPage.click('#something')
    await crawlPage.waitForNavigation({ waitUntil: 'networkidle0'})
  })
}

await Promise.all(promises)
```

**Comment by imkimchi** [comment]
headless: true solves this problem

**Comment by aslushnikov** [comment]
Right, you should use [`page.bringToFront()`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-pagebringtofront) in non-headless mode for now;

**Comment by antonioiliev** [comment]
I have stumbled upon this thread as I encountered the same problem. From what I gather, this behaviour has not changed. Is there a plan to change it in the future?

**Comment by ecolss** [comment]
> I have stumbled upon this thread as I encountered the same problem. From what I gather, this behaviour has not changed. Is there a plan to change it in the future?
@antonioiliev

Mar 2020, same issue encountered in `headless: false` mode, anyone has solutions other than use `headless: true` mode?

**Comment by lkrazy** [comment]
@ecolss 
you have to use page.bringToFront() before calling click()

in the case there are many pages running in the same time, you have to setup a token so that each page must wait until token is release, it will take the token and then bringToFront, after click(), that page should release token

hope this help

**Comment by FranckFreiburger** [comment]
Does anyone have any idea of ​​the reason for this behavior ?

**Comment by YassineEddyb** [comment]
> @ecolss
> you have to use page.bringToFront() before calling click()
> 
> in the case there are many pages running in the same time, you have to setup a token so that each page must wait until token is release, it will take the token and then bringToFront, after click(), that page should release token
> 
> hope this help

can you explain more please ?

**Comment by lkrazy** [comment]
@YassineEddyb 
This issue relates to concurrency.
I solved this kind of problem by introduce a mutex-like solution, which i called token. when I have many pages, before perform click on a page, it will check if token is free or not. if:
- token is free, that page will lock the token and then call page.bringToFront() and click(). after that, release the token
- token is locked by other page, wait until token is free

**Comment by christopherreay** [comment]
i just wanna say, for anyone that finds this behaviour difficult to understand, you simply arent thinking about how browsers work. This is obvioiusly the expected behaviour.
 
 If you are a user, the active tab renders all the HTML DOM changes, and the NOT ACTIVE tabs do not render DOM changes, so "click" doesnt mean anything in the not active tabs.

**Comment by surlyhacker** [comment]
This should either be reopened or the documentation should be updated to clearly state it as a limitation.  
@imkimchi, I don't see why you closed the bug after stating that "headless: true solves this problem".
Yes it may solve it, but since "headless: false" is fully supported and does not come with any documented difference in click() behavior, this is a bug.

It is similar in nature to #3339, but not a duplicate of that one since that one seems scoped to only be related to pausing of (script) execution, rather than interactions with elements (e.g. clicks) being ignored entirely. 

I have noticed other types of interactions beyond click being ignored, such as calls to page.type(), etc

@christopherreay, I've read and understand your comment's intentions, but to me that does not negate my points above.  Specifically, you are comparing Puppeteer to "how browsers work".  Puppeteer is not intended to be identical in functionality to a Browser, even though it has overlapping functionality with one and even depends on a Browser to function.

**Comment by Flamenco** [comment]
I found one can simply create 2 browsers, each having a page.  Then each page can be active at the same time.

The bringToFront() procedure is not needed in this case.
