### ISSUE TITLE
Unable to page.setRequestInterception(true) if connecting to chrome

### ISSUE THREAD

**Issue by xiaohangsu** [puppeteer/puppeteer#3364]
For the browser instance puppeteer.launch it can do somethings like
```
await page.setRequestInterception(true);
page.on('request', request => {
    if (request.resourceType() === 'image') {
        request.abort();
    }
    else {
        request.continue();
    }
});
```
But it can not setRequestInterception(true) for a chrome instance ( I do puppeteer connect with chromelaucher or create a chrome with remote debug port manually)

**Comment by jazoom** [comment]
I'm glad it's not just me. I kept checking my code wondering why it was different to the docs. In my case I use the following launch option since I'm running in WSL:

`executablePath: 'chrome.exe'`

Everything seems to work, except the requests are not intercepted.

**Comment by aslushnikov** [comment]
@xiaohangsu @jazoom are you guys sure you use Puppeteer version that matches your chrome version? The compat table is in the very beginning of our [api documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md). Also, check out [our FAQ](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy) for the explanation on why it is important.

**Comment by jazoom** [comment]
@aslushnikov ah thanks. I was wondering where the compatibility table was. I have been using those API docs for the last 4 hours getting everything set up but I never noticed that table because it looks like it's part of the table of contents. I just skipped over the table of contents and did a lot of ctrl+F. Perhaps it would be better placed down with the actual content? Or alternatively, give it some styling so it doesn't blend in with the table of contents?

I'm using Puppeteer 1.9.0 (automatically downloaded by Yarn), which isn't even in that compatibility table. I will downgrade to 1.7.0 to match the version of Chrome and see if it works...

Nope... interception still doesn't work with Chrome 70 and Puppeteer 1.7.0.

**Comment by aslushnikov** [comment]
@jazoom can you please post your script?

**Comment by morganz77** [comment]
@jazoom just curious, does the interception work for you in headless mode (I can get it to work in headless mode, but not with the browser actually being shown)?

**Comment by jazoom** [comment]
```
  let browser;
  try {
    browser = await puppeteer.launch({
      headless: false,
      executablePath: 'chrome.exe',
      args: [`--proxy-server=${options.proxy.ip}:${options.proxy.port}`]
    });

    const page = await browser.newPage();
    await page.setViewport({ width: 800, height: 600 });

    await page.setRequestInterception(true);
    page.on('request', interceptedRequest => {
      console.log('YOU WILL NEVER SEE THIS LOGGED');
      if (['image', 'media', 'font', 'stylesheet'].includes(interceptedRequest.resourceType())) {
        return interceptedRequest.abort();
      }
      interceptedRequest.continue();
    });

    const response = await page.goto(options.url);

    const source = await response.text();

    const content = await page.content();

  } catch (error) {
  }

  browser && await browser.close();
```

@aslushnikov  Since you're already interpreting that code, can you see why `response` would be null? I got it from your comment here (https://github.com/GoogleChrome/puppeteer/issues/749#issuecomment-328600349). Unfortunately, `response` is always `null` so trying to get `text()` from it causes a `TypeError`.

Edit: I think `response` being null is related to the interception failure. The following is never logged:

```
    page.on('response', resp => {
      console.log('GOT A RESPONSE, YO');
    });
```

**Comment by jazoom** [comment]
@mor9anz I cannot run it in headless mode due to this issue: https://github.com/GoogleChrome/puppeteer/issues/1837#issuecomment-413697840

**Comment by xiaohangsu** [comment]
Thanks @aslushnikov I gonna close this one.

**Comment by jazoom** [comment]
So why exactly was this closed? The issue remains.

**Comment by aslushnikov** [comment]
@jazoom it's closed because Puppeteer works only with a matching Chromium version. Please see [this explanation](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy)

If you are sure you're using correct Puppeteer-core version against your stable Chrome version, please file a separate issue with enough details for us to reproduce locally.

**Comment by jazoom** [comment]
Why not use this issue? I've already posted my code here months ago and confirmed I was using matching stable versions. For some reason it was closed after I confirmed that. The new issue would be the same as this one.

**Comment by aslushnikov** [comment]
> Why not use this issue?

@jazoom Keeping unrelated discussions separate is a good hygiene. 
- it helps for future users to search across issues and liberates them from reading through long unrelated discussions.
- it doesn't send e-mails to those who are on this thread and are not interested in our discussion.

> I've already posted my code here months ago and confirmed I was using matching stable versions. 

You code is not runnable locally for me - there's no URL, and there's no PROXY. Can you simplify your script and provide with the exact URL so that I can run it locally? 

I'd appreciate if you file a separate issue for this, and make sure we can run your code and reproduce the issue.

**Comment by jazoom** [comment]
Why is this discussion unrelated? I can't see any mention here from OP or from me that the issue was related to a version mismatch. Where did you get that assumption? What am I missing here?
