### ISSUE TITLE
page.screenshot not working properly, it gets stuck and never takes the screenshot of the webpage

### ISSUE THREAD

**Issue by rohankap** [puppeteer/puppeteer#3377]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: win 10 64 bit
* URLs (if applicable): http://www.fondu.com
* Node.js version: 8.10.0

**What steps will reproduce the problem?**
Please execute the below code to reproduce this issue, I am trying to take the screenshot of this website but page.screenshot got stuck and it never takes the web page screenshot.

_Please include code that reproduces the issue._
```


var puppeteer = require('puppeteer');
var browser, page;


async function capture(url) {
    //console.log(url +': Started');
    console.time(url);
    try {
        await page.goto('http://'+url, {
            waitUntil: ['load', 'domcontentloaded', 'networkidle2'],
            timeout: 30000
        });
    } catch (e) {
        console.log(e.toString());
    }
    await page.screenshot({path: url+'_headless.jpg',fullPage: false});
    console.timeEnd(url);

}

async function test() {
  browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox'],headless:false});
  page = await browser.newPage();
  page.setViewport({ width: 1366, height: 768 }); //my laptops screen
  await capture('www.fondu.com');
  browser.close()
}

test();
```

**What is the expected result?**
It should take the screenshot of the webpage and save it locally

**What happens instead?**
page.screenshot got stuck and it never completes due to which whole script goes to idle state and it never gets completed.

**Comment by przemyslawpluta** [comment]
I see the same issue. Previously `timeout` would be triggered but that does not happen either and entire action grinds to a hold with `r599821`.

**Comment by robertdumitrescu** [comment]
Any update on this?

**Comment by aslushnikov** [comment]
@rohankap the website is emitting ~10 requests/second constantly infinitely. It never emits `'load'`, `'networkidle0'` or `'networkidle2'` events. In other words, the page is never loaded in any of the sensible metrics we use. This website is broken both for users (it just hung my browser tab) and scripts.

If there's a specific thing you want to screenshot on this website - you cat try using `page.waitFor` to wait for it instead of awaiting `page.goto` to finish.

@robertdumitrescu @przemyslawpluta: folks, please file separate bugs if your screenshots still hang. Make sure to add a reproducible examples so that we can debug it locally.
