### ISSUE TITLE
Puppeteer headless false and true different result.

### ISSUE THREAD

**Issue by Jazen1995** [puppeteer/puppeteer#3412]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: macos
* URLs (if applicable):
* Node.js version: 10.7.0

Hello, I met some strange questions about headless mode.

I use several puppeteer page to run my parallel test, but I found that headless = true will work correctly, and headless = false won't. 

For example, page1 has a test of right button click, when mocha parallel test  run in non headless mode, It can not work correctly, the click will show on Page2 edge(or I should say border). But when it turns to headless mode, It works.

**Comment by kobenguyent** [comment]
anyone got the same issue here with the different behaviors in headless mode?

**Comment by Jazen1995** [comment]
> anyone got the same issue here with the different behaviors in headless mode?

this situation happens  in multi puppeteer page. I use mocha-parallel-tests to run my test files. Each file will use a new browser page.

**Comment by dge808** [comment]
> anyone got the same issue here with the different behaviors in headless mode?

I've got the same issue
Environment details:

- Puppeteer version: 1.9.0 
- Platform / OS version: mac OS
- NodeJS version: 8.11.1

I use jest as a test runner

**Comment by aslushnikov** [comment]
This is likely to be related to #3474.
@JoelEinbinder: I remember you were telling something about making all tabs believe they're in foreground. Is this relevant?

**Comment by click666** [comment]
Puppeteer version: 1.10
Platform / OS version: macos
URLs (if applicable):
Node.js version: 8.11.4

i meet a problem where headless is different.

when i set headless false, page.click can do what i expected. however, when headless is true, page.click can not work. and there is no error or message.

**Comment by michael-pont** [comment]
A similar thing happened to me when I have multiple pages running under one browser. I run a function that essentially clicks on a button and downloads a file. Under headless mode false, only one page is actively proceeding in the code, the other pages remain dormant essentially. That behavior changes when I actually click the tab for the other pages. So once I make the other page a target/active it proceeds in the code. This might be due to some properties I set on each page before running the download function??? That would be my guess. In headless mode true, each page is able to run the functions concurrently with the other pages. Anybody have any ideas about this behavior?

**Comment by sampwil** [comment]
I have noticed this behavior with my developers on Macs and not on my developers with Windows. We are using Jest as a test runner. Jest wants to run the tests suites in parallel but appears to blocked from doing so on my Windows machine. The developers on Macs appear to not be blocked from running the tests in parallel. I believe the tests are failing because the test suites are connected to devtools over the same port. I am going attempt to make each suite run on its own port. The --runInBand may also be an option to block Jest from running parallel but you sacrifice only running one suite at a time.

**Comment by TranBaVinhSon** [comment]
Same here. I'm running chrome inside a container which obviously headless is true, and realized that html content of chrome page from `headless: true` and `headless: false` is totally different. (I'm using `headless: false` to launch UI to check component's id, class... etc)

Is there any solution?

**Comment by prb407** [comment]
the problem is because the headless option sets a user-agent to the page and it based on the true and false value.
I came to know by printing the page value returned by **await page.goto(url, { waitUntil: 'networkidle2', timeout: 40000 });**

1. Headless true will set it as: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) **HeadlessChrome/87.0.4272.0** Safari/537.36
2. Headless false will: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/87.0.4272.0** Safari/537.36

so what you can do, you can set your prefered user-agent to the page object by:
await page.setUserAgent(**prefered user-agent**);

**Comment by arismelachroinos** [comment]
> the problem is because the headless option sets a user-agent to the page and it based on the true and false value.
> I came to know by printing the page value returned by **await page.goto(url, { waitUntil: 'networkidle2', timeout: 40000 });**
> 
> 1. Headless true will set it as: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) **HeadlessChrome/87.0.4272.0** Safari/537.36
> 2. Headless false will: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/87.0.4272.0** Safari/537.36
> 
> so what you can do, you can set your prefered user-agent to the page object by:
> await page.setUserAgent(**prefered user-agent**);

Didn't work for me.

**Comment by feavilan04** [comment]
> 2\. Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/87.0.4272.0** Safari/537.36

Worked for me, Thnks.

**Comment by ThibaultJanBeyer** [comment]
So, yes, I can confirm. It is completely different based on whether it is headless or now BUT also on top of that it is differend based on environment. I.e. running the same code that passes on my MacOS M2 on a github action will fail outputting different results. (in my tests, I am using the mouse to click around etc. an advanced functional test)

**Comment by OrKoN** [comment]
yeah, the difference between the old headless and the headful mode is working as expected. The should be almost no differences between the new headless and the headful modes. See https://developer.chrome.com/articles/new-headless/

**Comment by WodenWang820118** [comment]
I have a test using the Puppeteer version: `^21.4.0` still bumps into this problem using the `headless: 'new'`. The Chrome version is v118.0.5993.70.
