### ISSUE TITLE
Chrome-generated PDFs large file size in case of background-image height exceeds the print layout height

### ISSUE THREAD

**Issue by aliaksei-volkau** [puppeteer/puppeteer#3615]
### Steps to reproduce

**Environment:**
* Puppeteer version: 1.8.0
* Platform / OS version: Alpine Linux 3.6.2
* Node.js version: 6.4.1

**What steps will reproduce the problem?**
1. Use HTML page which only contains \<div\> with background-image style: \<div style=" background-image: url('https://...')"\>
2. Save this HTML page as PDF

_Preconditions:_
HTML page contains \<div\> with background-image style: \<div style=" background-image: url('https://...')"\>
And image height is larger that output "paper size" height, and the image bottom should be cut off to fit in the output dimensions. 

_For example:_
350kb jpg as background-image is resulting to: 
- 0.5Mb PDF when 1380x1953pixels initial jpg is saved to A4 layout
- 4.5Mb PDF when 1380x1995pixels initial jpg is saved to A4 layout (too big height to fit in to A4 layout dimensions)
- 4.3Mb PDF when 1311x1953pixels initial jpg is saved to US Letter layout (too big height to fit in to US Letter layout dimensions)

**What is the expected result?**
Output PDF size corresponds to initial JPG file size for all image dimensions.

**What happens instead?**
Output PDF size is 10 times larger than initial JPG file size for images with excessive high.

**Comment by aslushnikov** [comment]
This is somewhat similar to https://github.com/GoogleChrome/puppeteer/issues/1177

Puppeteer PDF generation functionality fully relies on Chromium's "Save as PDF" code - so I'd recommend filing upstream to Chromium at https://crbug.com/new (and posting a link to the bug here for the cross-referencing).

I'll close this for now since it falls outside of the Puppeteer project - but feel free to update the issue with any relevant information.

Hope this helps.
