### ISSUE TITLE
Pdf form inputs not editable

### ISSUE THREAD

**Issue by upstroke** [puppeteer/puppeteer#3646]
I am generating a PDF to HTML with several inputs on the page.
Prefilled inputs get rendered as text, empty inputs are only visible with the pdf.option "printBackground: true". 
What I am missing is the possibility to keep all input fields editable after converting from HTML to PDF. 
I had a full day on researching how to get this working. I had the assumption that I had to add attributes on input fields, or add a non documented pdf.option to get this to work, but I had no luck.

Is it possible to have the input fields editable in the converted PDF at all?
THX

**Comment by jwrubel** [comment]
I'm also curious about this. From everything I've read this isn't something puppeteer supports, but I haven't done a lot of research on it.

**Comment by aslushnikov** [comment]
@upstroke @jwrubel Puppeteer PDF functionality fully relies on Chromium's "Save as PDF" implementation. I'd recommend asking this question at [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev) or filing a bug to `https://crbug.com/new`. Chromium's PDF team might be able to help.

Closing this since it falls outside of the Puppeteer project. (but please feel free to post a link to the upstream discussion if you initiate one!)

**Comment by tbruckmaier** [comment]
Upstream discussion is here fyi: https://bugs.chromium.org/p/chromium/issues/detail?id=1024713 (does not seem to be implemented any time soon though)

**Comment by carden-jeremy** [comment]
Chromium changed that issue's status to "WontFix" on 11/16/2020, so if this feature is still wanted, it would be up to puppeteer to receive the PDF from Chrome and then edit it to convert the fields to AcroForms.

**Comment by Germs2004** [comment]
If you want a project that can convert HTML to PDF with AcroForms, this project works but is buggy: [wkhtmltopdf ](https://github.com/wkhtmltopdf/wkhtmltopdf)

The [documentation ](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt)says to add parameter "--enable-forms" and make sure every fillable field has a unique "name" attribute.
