### ISSUE TITLE
Custom HTML element PDF generation.

### ISSUE THREAD

**Issue by vladocar** [puppeteer/puppeteer#3680]
First, thanks for this great project!

I made CLI on top of puppeteer https://github.com/vladocar/screenshoteer

I have a problem PDF generation  with the custom select HTML elements.

Example:

const el = await page.$("#main");
el.screenshot(...) works without problem
el.pdf(..) doesn't work.

https://github.com/vladocar/screenshoteer/blob/cafa2455c10963bdc4ad90d828541b9f6e7c67fe/index.js#L76

Thanks!

**Comment by gidztech** [comment]
[`ElementHandle`](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#class-elementhandle) doesn't espose a `pdf` function, only [`Page`](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#pagepdfoptions) does. 

In order to create a PDF from a particular element, you will need to create a page with only the element(s) you want to have in the PDF. This can be automated with Puppeteer by [cloning the node](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) and setting the body content to that node, before creating a PDF of the entire page.

Check out [this example](https://github.com/GoogleChromeLabs/puppeteer-examples/blob/master/element-to-pdf.js) from the [puppeteer-examples](https://github.com/GoogleChromeLabs/puppeteer-examples) repository.

**Comment by vladocar** [comment]
Thanks!

**Comment by zhongnansu** [comment]
By using the approach of creating a screenshot and embeds into a template, I can generate the pdf of element, but the text in the pdf if not selectable, because it's a screenshot which is a png. Any idea how I can generate pdf of element with selectable text

**Comment by Yakov-Shechter** [comment]
> By using the approach of creating a screenshot and embeds into a template, I can generate the pdf of element, but the text in the pdf if not selectable, because it's a screenshot which is a png. Any idea how I can generate pdf of element with selectable text

@zhongnansu
Did you found a workaround for this problem?
I'm trying to use 'wkhtmltopdf' and other libraries w/o satisfying result.

Thank you
