### ISSUE TITLE
Bytes coverage vs puppeteer-to-istanbul

### ISSUE THREAD

**Issue by storenth** [puppeteer/puppeteer#3712]
For test coverage ability I used simple [code](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-class-coverage) to get percentage of initially executed code.
Bytes used by Puppeteer's class Coverage: **51.33689839572193%**
And after `nyc report --reporter=html` done, I try to look at the ./coverage/index.html and found a difference **_51.33689839572193%_** vs **_64.71%_**:
![coverage_issue](https://user-images.githubusercontent.com/18244131/50477230-ff882880-09fd-11e9-8abb-5e4c12084957.png)
Also I mention defect in Branch coverage number, it always 100%. To validate this issue I suggest clone this simple [repo](https://github.com/storenth/puppeteer-to-istanbul-example) for local reproduce.

**Comment by aslushnikov** [comment]
@storenth so what is the issue? The difference between coverage percentage might be due to different ways of computing coverage. 

Overall, looks like this will better suite the [puppeteer-to-istanbul](https://github.com/istanbuljs/puppeteer-to-istanbul) repository - they are experts with istanbul. Please, re-file this over to them.

**Comment by storenth** [comment]
https://github.com/istanbuljs/puppeteer-to-istanbul/issues/22
