### ISSUE TITLE
Some chrome flags not working in headless mode

### ISSUE THREAD

**Issue by dhijn** [puppeteer/puppeteer#3741]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Windows 7/10
* URLs (if applicable):
* Node.js version: 10.14.1

**What steps will reproduce the problem?**
```
'use strict';

const URL = 'https://www.allaboutwomen.in/sitemap.xml';

const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch({
		headless: true,
		ignoreHTTPSErrors: true,
		args: ['--disable-web-security', '--allow-running-insecure-content']
	});
const page = await browser.newPage();
await page.on('response', response => {
  const url = response.url();
  if (!url.startsWith('data:') && response.ok) {
    response.buffer().then(
        b => {
          console.log(`${response.status()} ${url} ${b.length} bytes`);
        },
        e => {
          console.error(`${response.status()} ${url} failed: ${e}`);
        }
    );
  }
});

await page.goto(URL);

})();
```

**What is the expected result?**

With `headless: false` the result is:
```
200 https://www.allaboutwomen.in/sitemap.xml 5398333 bytes
200 https://carzoom.in/wp-content/plugins/google-sitemap-generator/sitemap.xsl 6608 bytes
200 https://www.allaboutwomen.in/favicon.ico 0 bytes
```

**What happens instead?**

With `headless: true` the result is:
```
200 https://www.allaboutwomen.in/sitemap.xml 5398333 bytes
```
http://carzoom.in/wp-content/plugins/google-sitemap-generator/sitemap.xsl URL status is `blocked: origin` which is legit but `--disable-web-security` doesn't work. When `--disable-web-security` works (with `headless: false`) the same URL status is then `blocked: mixed-content` which is still legit but `--allow-running-insecure-content` flag doesn't work to disable it.

**Comment by aslushnikov** [comment]
@dhijn there are many flags that work in Chromium and don't work in Headless. This happens due to the architectural implications: both Headless and Chromium share the same layer called "content" that drives web rendering, but many flags are implemented in Chromium only.

Now, Chromium team is way bigger than Headless team, so we can't just implement every Chromium feature in Headless. But if there's a community demand (expressed as "likes" and comments here), we'll come back and do the engineering work to support the flags.

I'll close this for now, but this is subject to be reopened if needed.

**Comment by dhijn** [comment]
@aslushnikov thanks. Is there an official list of supported flags in Headless?

**Comment by aslushnikov** [comment]
@dhijn the best we have is the source code:
- the list of `//content` switches: [`//content/public/common/content_switches.h`](https://cs.chromium.org/chromium/src/content/public/common/content_switches.h?q=f:content+switches&sq=package:chromium&dr=CSs)
- the list of `//headless` switches: [`//headless/app/headless_shell_switches.h`](https://cs.chromium.org/chromium/src/headless/app/headless_shell_switches.h?q=f:headless+switches&sq=package:chromium&g=0&l=1)

If you're comfortable with https://cs.chromium.org, than you can search for the flag and see where it is used. If it lives somewhere under `//chrome`, than it's Chromium-only.

**Comment by junminstorage** [comment]
We have the similar issue, it blocks us to integrate PUPPETEER with CI pipeline. And we have to use Xvfb and launch chrome in regular mode.

**Comment by aslushnikov** [comment]
@junminstorage what flags do you lack?

**Comment by junminstorage** [comment]
this what we found: "--allow-running-insecure-content flag doesn't work to disable it."

**Comment by jainvijay** [comment]
Any other alternative to render http content under headless mode?

**Comment by hlr1983** [comment]
@aslushnikov, "--allow-running-insecure-content" in headless mode would be useful for me, since I'm scraping data from an old system that is not maintained anymore, and works well with this flag. It sometimes opens a print dialog window, which I think I can not handle running chrome regular mode on Xvfb (https://github.com/GoogleChrome/puppeteer/issues/3145).

Thanks.

**Comment by sohaib17** [comment]
crbug: https://crbug.com/1352473
