### ISSUE TITLE
Returning Date object from .evaluate

### ISSUE THREAD

**Issue by emilbayes** [puppeteer/puppeteer#376]
This is more of a question than an issue (but might escalate to the latter!).

Returning a `Date` from an `.evaluate` context:

```js
var puppeteer = require('puppeteer')

puppeteer.launch().then(async browser => {
  let page = await browser.newPage();
  const data = await page.evaluate(() => {
    return new Date(2017, 0, 1)
  })

  // data = {}

  browser.close();
});
```

I did not expect an "empty" object, but rather the `Date` object itself, milliseconds since epoch or the ISO8601 string.

**Comment by joelgriffith** [comment]
Unfortunately, as far as I'm aware, sending objects back and forth through Chrome requires a flag change here: https://github.com/GoogleChrome/puppeteer/blob/master/lib/FrameManager.js#L206, otherwise JSON objects don't get transported through the "bridge" properly.

You might call `.toString` or some other serialization method for the time being.

**Comment by aslushnikov** [comment]
@ak239 Alexey, looks like our serializer misbehaves here? The `JSON.stringify` works fine on date objects.

**Comment by ebidel** [comment]
We should also warn if the resolved object doesn't serialize properly: https://github.com/GoogleChrome/puppeteer/issues/310

**Comment by pavelfeldman** [comment]
This needs resolution, likely in a form of the object handles. M1 bug.

**Comment by pavelfeldman** [comment]
Closing in favor of #382.
