### ISSUE TITLE
document.querySelector return jquery

### ISSUE THREAD

**Issue by Trahtenberg** [puppeteer/puppeteer#3764]
Hello! I'm trying to get a page element, but I can't do it.

my code:
```
const result = await page.evaluate(()=>{
        const products = document.querySelector('div[class="products"]');

            return products;
    });
    console.log(result);
```

response:

`
{ jQuery224063212568064752822: { id: 406024, jsCardInit: true },
  jQuery224063212568064752821:
   { events: { click: [Array], deleteHeart: [Array] }, handle: {} } }
`

Help me, please

**Comment by vsemozhetbyt** [comment]
[`page.evaluate()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args) can only return serializable objects, and HTML elements are not usually serializable. Your result can be caused by some serialization method (`.toJSON()` etc) added to elements by a page code.

You can try to use [`page.evaluateHandle()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatehandlepagefunction-args) and to handle the result by APIs for `JSHandle`.

**Comment by Trahtenberg** [comment]
Thanks for your reply. I read the documentation. I can also get an element that I want to use with page.$('div[class="products"]'). But I did not understand, how can I get the attribute of the received element? (className or href or childs etc ). And is it possible to somehow turn it into a regular HTML element for convenient work?

**Comment by vsemozhetbyt** [comment]
you can use  `page.evaluate()` + `element.getAttribute()` or some more [complicated workarounds](https://github.com/GoogleChrome/puppeteer/issues/3786).

As for HTML elements manipulations, I can only think of two ways:
1. Use all needed DOM API in `page.evaluate()` function and transfer only the result you really need in Node.js context.
2. Use the rather complicated elementHandle/jsHandle puppeteer API.

**Comment by Trahtenberg** [comment]
vsemozhetbyt спасибо! Я уже допёр)))
