### ISSUE TITLE
I am trying to select a value from a async select mean that when i enter some value in select-input an api call go and fetch the options from the db!I want to wait until api call finished and then select a value from a drop down.Is There is any possible way to do this?

### ISSUE THREAD

**Issue by jamalabbasi** [puppeteer/puppeteer#3765]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by aslushnikov** [comment]
@jamalabbasi you can track API calls using Network events:
- [`request`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-event-request)
- [`response`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-event-response)
- [`requestfinished`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-event-requestfinished)
- [`requestfailed`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-event-requestfailed)

There's also a [`page.waitForRequest`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagewaitforrequesturlorpredicate-options) and [`page.waitForResponse`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagewaitforresponseurlorpredicate-options) helper methods.

Hope this helps.

P.S. Next time make sure to fill in the issue form rather than putting all description in issue title. This will greatly simplify our work.
