### ISSUE TITLE
--remote-debugging-port doesn't work

### ISSUE THREAD

**Issue by simov** [puppeteer/puppeteer#378]
:wave: 

### puppeteer.js

```js
var puppeteer = require('puppeteer')

puppeteer.launch({
  args: [
    '--remote-debugging-port=9222'
  ]
})
.then(async (browser) => {
  var page = await browser.newPage()
  await page.goto('https://github.com/GoogleChrome/puppeteer')
  debugger
})
```

```bash
node --inspect-brk puppeteer.js
```

```bash
Debugger listening on ws://127.0.0.1:9229/01cc097b-1fa0-497a-9e70-ee61e63b1d46
```

### Inspecting the Script that I'm running

![screenshot from 2017-08-18 19-02-57](https://user-images.githubusercontent.com/1694112/29467182-2e0f4d24-8448-11e7-952c-7c9c0cf856f5.png)

### Then I get this weird Target for the page that I'm loading through puppeteer

![screenshot from 2017-08-18 19-03-54](https://user-images.githubusercontent.com/1694112/29467295-9cc35eb8-8448-11e7-8771-80095a2ce422.png)

### I have these ports configured

![screenshot from 2017-08-18 19-04-18](https://user-images.githubusercontent.com/1694112/29467335-c1f3bd0e-8448-11e7-9417-2b12a23d579a.png)

The use case is as follows:

1. I run my tests through puppeteer
2. At some point I want to inspect the page that I'm testing
3. The **Target** links in `chrome://inspect` doesn't work

> Chrome 60
> Node 8.1.2

**Comment by simov** [comment]
I guess `{headless: false}` fixes the issue for me. I can use the inspector in that window. Initially I wanted to inspect the Application tab only, so that's why I wasn't thinking about the headless option.

**Comment by pavelfeldman** [comment]
I think what you are seeing is expected:
- you tell puppeteer to use `9222` as a remote debugging port
- you pause puppeteer and hence keep its headless browser opened
- you visit `chrome://inspect` and since `9222` is one of the ports that we inspect by default, you see what's inside.
- if you wait or refresh the page, it'll get the `GitHub - GoogleChrome/puppeteer: ` title
- you won't be able to inspect it because puppeteer is already using the inspection channel for the automation.

That last bit is going to be fixed once Chrome supports multiple remote debugging connections. Which should happen very soon.
