### ISSUE TITLE
screenshot to jpg problem 

### ISSUE THREAD

**Issue by sourth-rain** [puppeteer/puppeteer#3794]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.11.0
* Platform / OS version:mac
* URLs (if applicable):https://luotuo.tmall.com/
* Node.js version: v10.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
simple code here:

```
let browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'] });
let page = await browser.newPage();
await page.setViewport({ width: width, height: height });
await page.goto(request_url, {
        'waitUntil': 'domcontentloaded',
        'timeout': 120000
    });
 await page.waitFor(5000);
 await page.evaluate((distance, MAX_HEIGHT_PX) => {
        return new Promise((resolve, reject) => {
            let totalHeight = 0;
            let timer = setInterval(() => {
                window.scrollBy(0, distance);
                totalHeight += distance;
                if (totalHeight >= document.body.clientHeight || totalHeight >= MAX_HEIGHT_PX) {
                    clearInterval(timer);
                    resolve({
                        width: document.documentElement.clientWidth,
                        height: document.body.clientHeight,
                        totalHeight: totalHeight,
                        scrollTop: document.scrollingElement.scrollTop
                    });
                }
            }, 800,12000);
        })
    }, 500, MAX_HEIGHT_PX);
 await page.waitFor(5000);
 try {
          await page.screenshot({path: 'test.jpg',quality:60,fullPage: true}).catch((err)=>{
                   console.log(err);
          })
           } catch (error) {
                   console.log(error);
          }


```

**What is the expected result?**
i want to sceenshot and then save to jpg,but fail and not throw ang errors.then save png works,although incomplete pic;

**What happens instead?**
finally,i get a empty pic.can not open and size is 0 kb;
i have try to fix this problem two days,but i fail ,can anybody help.thanks

**Comment by sourth-rain** [comment]
this url ,its document.body.clientHeight is 70024px,if small pic.it works

**Comment by soulchild** [comment]
I just ran into a similar (same?) problem: Whenever I try to capture very long pages the resulting screenshot Buffer is empty. This problem is especially apparent when capturing pages with the `emulate()` function set to a mobile device (e.g. "iPhone X") because it severely increases the height due to the narrow width of mobile devices. This also only happens when the output format is set to `jpeg`. `png` seems to work fine. This got me thinking and I may have found the answer. According to [Wikipedia](https://en.wikipedia.org/wiki/JPEG):

> JPEG/JFIF supports a maximum image size of 65,535×65,535 pixels.

In my case, the resulting (jpg) screenshot would have been ca. 72,000 pixels tall (tested with the format set to `png`).

I think the only thing the Puppeteer/Chrome devs could do better is throwing some kind of error in case the resulting screenshot is apparently empty or could not be converted into the target format.

Hope this helps…
