### ISSUE TITLE
Puppeteer not loading websites with bot detection waiting page

### ISSUE THREAD

**Issue by RebliNk17** [puppeteer/puppeteer#3797]
### Steps to reproduce
Try to surf this site for example: https://kissanime.ac/
When loading, it first display a screen that says "We're just verifying you are a real human and not a bot."
puppeteer thinks that the website is fully loaded and returning that data...

* Puppeteer version:
1.8.0

* Platform / OS version:

* URLs (if applicable):
https://kissanime.ac/

**What is the expected result?**
Puppeteer should wait for the real site to load.

**What happens instead?**
Puppeteer return with the "We're just verifying you are a real human and not a bot." page.

Any way to pass it?

Thanks.

**Comment by aslushnikov** [comment]
@RebliNk17 instead of relying on Puppeteer's notion of navigation, you should wait for a website reaching a certain state. For this, use [`page.waitFor`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagewaitforselectororfunctionortimeout-options-args) function and wait for some selector.

Hope this helps.
