### ISSUE TITLE
(node:2323) UnhandledPromiseRejectionWarning: Error: Request Interception is not enabled!

### ISSUE THREAD

**Issue by hongdaliu** [puppeteer/puppeteer#3811]
await page.setRequestInterception(true)

**Comment by huan** [comment]
This issue is definitely a time saver!

**Comment by ptrkkim** [comment]
thanks guys this was great

**Comment by DevYuns** [comment]
I also have trouble with page.setRequestInterception(true). any other progress?

**Comment by christian-bromann** [comment]
@DevYuns can you provide a reproducible example?

**Comment by john-doherty** [comment]
@christian-bromann here's a reproducible example:

```js
// launch the browser
var browser = await puppeteer.launch({ headless: false });

// get existing tab/page (first item in the array)
var [page] = await browser.pages();

// inspect each request and blocking external resources
page.on('request', function(req) {

    var resourceUrl = url.parse(req.url());
    var resourceHost = resourceUrl.host;
    var blockedResources = ['google-analytics.com'];

    if (blockedResources.indexOf(resourceHost) > -1) {
        req.abort();
    } else {
        req.continue();
    }
});

// load barcode tracking website
await page.goto('https://orcascan.com');
```

Result = **Error: Request Interception is not enabled!**

If you add `await page.setRequestInterception(true);` it works, but it's not obvious - especially to new users.

Ideally, it should activate itself whenever the `request` event is subscribed to.

**Comment by albanx** [comment]
For some reason this is breaking in my code as well. What is strange is that in some macchine it fails in some other it passes. I have enabled the `setRequestInterception`. Must be failing in some specific versions of pupuppeteer

**Comment by TryingToImprove** [comment]
I had this issue with v10. Just upgraded to v13 of the node library and it seems to be working now..

**Comment by ForbiddenEra** [comment]
I've been seeing this a lot lately; was on v18.0.3 now on v18.2.1

was wondering if I could wrap .continue() in a catch but thinking that won't work since  continue() doesn't return the promise that's rejected etc

otherwise, I was hoping that checking `isInterceptResolutionHandled()` might help, but if it's not enabled then ...

my last thought was to try checking `if (request.interceptResolutionState() == 'none')` or something..

my guess is either I'm enabling/disabling intercepting somewhere I shouldn't be otherwise a page is redirecting while I'm handling the request..?

quite possibly a PEBKAC on my end though
