### ISSUE TITLE
Inconsistent SVG rendering. Screenshot randomly returns one of two a bit different versions

### ISSUE THREAD

**Issue by AndreyKozlov1984** [puppeteer/puppeteer#3850]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
1.11.0
* Platform / OS version:
Linux or Mac
* URLs (if applicable):
An example repo is created at https://github.com/ZeusTheTrueGod/puppeteer-svg-bug
* Node.js version:
11.8
**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
just run the index.js from the repo
https://github.com/ZeusTheTrueGod/puppeteer-svg-bug/index.js
Basically, I try to make a screenshot of a `min.svg` file 30 times and then look how many different png images I have. 

**What is the expected result?**
Ideally, there should be just one png image, and that happens to most of the files

**What happens instead?**
 but this `min.svg` file returns 2 different images.

I also want to add that while this could be a chromium bug, the `index.html` file from the repo returns a consistent result every time when attempts to render the same `min.svg` file via a canvas element.

**Comment by fleck** [comment]
I'm also having this issue with our screenshot CI builds

**Comment by bondom** [comment]
@AndreyKozlov1984 @fleck  2 different images are returned, because default deviceScaleFactor is 1 - it is a low value, therefore quality of svg on screenshot is worse. It seems that this 'worsening' process may give several little bit different results. To overcome this issue, you need to set deviceScaleFactor to bigger value.

@AndreyKozlov1984 I tried your example with deviceScaleFactor = 2, It returns a single png image
