### ISSUE TITLE
Feature request: possibility to handle `page.on('request',...)` in several places

### ISSUE THREAD

**Issue by yanivefraim** [puppeteer/puppeteer#3853]
Use case:

I am developing a testkit which does `page.on('request', ...)` in order to intercept specific requests. 
The problem: A user can write another interceptor which handles specific requests and calls `request.continue()` for all the rest (as this is mandatory for requests that we do not handle).

As a result, only the first request handler "wins" (the second handler will receive "request is already handled!" error.)

A possible solution: 
Today we must have `request.continue()` for every request that we do not want to handle. What if puppeteer will do it by default, for requests that it finds as "unhandled". In this case, each handler will only take care of its own interceptors, and will do nothing about the rest of requests.

**Comment by aslushnikov** [comment]
> What if puppeteer will do it by default, for requests that it finds as "unhandled".

@yanivefraim With the currently-exposed API, it's unclear when the request is "unhandled". Consider an artificial example of "network throttling" using request interception:

```js
page.on('request', request => {
  setTimeout(request.continue.bind(request), 1000);
});
```

Since Puppeteer gives away control over the request to the client, client might continue them anytime in future as they require. They might even drop the request on the floor without continuing to simulate server stalling. So from Puppeteer's stand point, we can't auto-continue requests since it will break many valid usecases.

However, it looks like your testkit introduces certain conventions over request interception, e.g. "request should be either synchronously aborted, or it will be auto-continued" (i might got it wrong). In this case, you can auto-continue all requests in a subsequent microtask:

```js
page.on('request', request => Promise.resolve().then(() => request.continue()).catch(e => {}));
```

Let me know if I understand you correctly and if it helps.

**Comment by yanivefraim** [comment]
@aslushnikov Thanks for the fast response. We will take it further from here.

**Comment by b5l** [comment]
Puppeteer could implement a public API to check whether a request is already handled or not. There is already the `_interceptionHandled` property on the `Request` class, we would essentially just need a getter for that. Any thoughts? @aslushnikov

**Comment by NinoSkopac** [comment]
Aslushnikov's "workaround" (i don't know what it is) works.

```js
page.on('request', request => {
  console.log(request.method(), request.url()); // Basically, do your work here
  
  return Promise.resolve().then(() => request.continue()).catch(e => {});
})
```

@aslushnikov Could you please explain why this works?

**Comment by whalderman** [comment]
> Aslushnikov's "workaround" (i don't know what it is) works.
> 
> ```js
> page.on('request', request => {
>   console.log(request.method(), request.url()); // Basically, do your work here
>   
>   return Promise.resolve().then(() => request.continue()).catch(e => {});
> })
> ```
> 
> @aslushnikov Could you please explain why this works?

Somebody correct me if I'm wrong, but I believe it's due to how all event handlers are fired synchronously. Returning a Promise forces the subsequent `request.continue()` to be fired after all event handlers have completed any synchronous work. Of course, you can't guarantee the other handlers aren't continuing/aborting the request, so you need to catch the possible "request is already handled!" error.

**Comment by ajs139** [comment]
It's unlikely the return has any part to play. According to the docs, the event emitter is based on [mitt](https://github.com/developit/mitt/), which [doesn't do anything](https://github.com/developit/mitt/blob/master/src/index.ts#L81) with the result of the handler. What's more likely is that `request.continue` throws an exception, so doing it in a different message in the [event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop) prevents the current "thread" from breaking.
