### ISSUE TITLE
HAR file's Initiator line is not helpful because some source files have everything in one line

### ISSUE THREAD

**Issue by gogo9th** [puppeteer/puppeteer#3883]
Hi,

I'm trying to analyze HAR files to figure out which Javascript statement triggered which HTTP request. However, many Javascript source files have all their contents in one or two lines. So even if HAR files point these lines as initiator lines, the information is not really helpful, because I cannot figure out exactly which Javascript statement triggered the resource download... For example, this is the information I have in the HAR file:
...
                "_initiator": "https://imgur.com/",
                "_initiator_detail": "{\"type\":\"parser\",\"url\":\"https://imgur.com/\",\"lineNumber\":0}",
                "_initiator_line": 1,
                "_initiator_type": "parser",
...
Is there any way I could get HAR reports based on pretty-printed version of source file? If this is not possible, is there any way I could still achieve the same goal from Developer Tools menu in Chrome?

**Comment by aslushnikov** [comment]
> Is there any way I could get HAR reports based on pretty-printed version of source file? If this is not possible, is there any way I could still achieve the same goal from Developer Tools menu in Chrome?

@gogo9th This looks more like a DevTools protocol question rather than a puppeteer one. You can get initiator from network requests if you enable [`Debugger domain`](https://vanilla.aslushnikov.com/#Debugger.enable) and then listen to [`Network.requestWillBeSent`](https://vanilla.aslushnikov.com/#Network.requestWillBeSent) events. [`initiator`](https://vanilla.aslushnikov.com/#Network.Initiator) has  stack trace that has a column number.

Hope this helps.
