### ISSUE TITLE
Huge performance degrade in headless (40x slower)

### ISSUE THREAD

**Issue by aalteirac** [puppeteer/puppeteer#3938]
Hi, 
OS:OSX 10.14.3
Puppeteer: 1.12.2
Node: 10.14.2

I'm facing major performance degrade from headless false to true.
My site is simple video tag pointing to webm stream. I have a deaplearn.js script working on the canvas (webgl).
With headless false I run the site perfectly, being able to grab a text every second without any problem.
When switching to headless, text grab takes 36 seconds.. so at least 36 times slower. I tried a lot of different args to be sure gpu was enable, proxy deactivated, next version etc... but no progress so far. 
My goal is to run on raspian but currently running osX, should I expect better perf on linux ?
Any ideas ?
Tx !

**Comment by JulianAnthes** [comment]
@aalteirac Have you tried https://github.com/GoogleChrome/puppeteer/issues/1260#issuecomment-348878456? 

Pasted here for reference:
```javascript
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      '--headless',
      '--hide-scrollbars',
      '--mute-audio'
    ]
  });
```

I'm pretty sure it's slowing down because of the disabled GPU rendering.

**Comment by aalteirac** [comment]
Hey @dschu-lab, yes tested with exactly the same results :-(

**Comment by aslushnikov** [comment]
@aalteirac internally, Chrome Headless on mac is a fake headless: it just hides window. Chrome Headless on Linux is a real thing, so yes, your milage might vary on different OS.

Would you mind sharing your demo so that we can investigate the perf slowdown locally?

**Comment by xse** [comment]
Hey, i'd recommand trying a bunch of args until you get better results, especially if you want to run it on raspbian.
Excuse my english it's fairly bad.
I'm using puppeteer since a few months, trying different things on an heavy webgl game. At first performances were terrible and i was loading that page in more than a minute, i'm now doing it way faster.

Since your goal seems to be using it on raspbian, here are some random stuff i learned using it on linux:
- just don't use it headless, on webgl pages i nearly always got worse results that way, you can always start a random X server and use that. (don't use xvfb!) It "needs" to use your gpu/igpu. Use "chrome://gpu" to check stuff, i get a lot of disabled or cpu only features when using it headless even tho i launch it with the same options. I've never managed to make it use the igpu on my server when running headless or with xvfb.

If you really want to use it headless:
- disable as much features as you can, try even those you don't understand. [This website is awesome for that.](https://peter.sh/experiments/chromium-command-line-switches/)
- Use **`'--disable-gl-drawing-for-tests'`**, i don't really understand what it does but as long as you don't need to take screenshots that's just the best option you can use. Everything will work as usual, "webgl stuff exists" on the page, you can interract/click on it and so on but it's not displayed, that way you'll save a lot of resources.

To give you an idea, on my Intel  i5-2300 server without graphic card here is my cpu without that option :
![without](https://i.imgur.com/ytpuY4a.png)

And here it is with  **`'--disable-gl-drawing-for-tests'`**:
![with](https://i.imgur.com/vHS71Kb.png)

- here are a few options i use/used successfully:

```javascript
      headless: false, // process.env['DISPLAY'] = ':0'; in index.js, xorg running.
      ignoreDefaultArgs: true, // needed ?
      devtools: false, // not needed so far, we can see websocket frames and xhr responses without that.
      //dumpio: true,
      defaultViewport: { //--window-size in args
        width: 1280,
        height: 882
      },
      args: [
      /* TODO : https://peter.sh/experiments/chromium-command-line-switches/
        there is still a whole bunch of stuff to disable
      */
        //'--crash-test', // Causes the browser process to crash on startup, useful to see if we catch that correctly
        // not idea if those 2 aa options are usefull with disable gl thingy
        '--disable-canvas-aa', // Disable antialiasing on 2d canvas
        '--disable-2d-canvas-clip-aa', // Disable antialiasing on 2d canvas clips
        '--disable-gl-drawing-for-tests', // BEST OPTION EVER! Disables GL drawing operations which produce pixel output. With this the GL output will not be correct but tests will run faster.
        '--disable-dev-shm-usage', // ???
        '--no-zygote', // wtf does that mean ?
        '--use-gl=swiftshader', // better cpu usage with --use-gl=desktop rather than --use-gl=swiftshader, still needs more testing.
        '--enable-webgl',
        '--hide-scrollbars',
        '--mute-audio',
        '--no-first-run',
        '--disable-infobars',
        '--disable-breakpad',
        //'--ignore-gpu-blacklist',
        '--window-size=1280,1024', // see defaultViewport
        '--user-data-dir=./chromeData', // created in index.js, guess cache folder ends up inside too.
        '--no-sandbox', // meh but better resource comsuption
        '--disable-setuid-sandbox'] // same
        // '--proxy-server=socks5://127.0.0.1:9050'] // tor if needed
    });
```

As you can see even without understanding what the options do you can get better results.
Anyway, if your goal is to grab a text every second i'd strongly recommand using **`'--disable-gl-drawing-for-tests'`**.
Otherwise, as @aslushnikov said, having a sample would help.
Have a good day!

**Comment by vigyanhoon** [comment]
'--no-zygote', // wtf does that mean ?
haha

**Comment by dimarqe** [comment]
Tried setting the options and it made my code perform worse. What helped me was using request interceptor to block certain resources from loading. Sites below have some really useful information on how to do it:
https://dev.to/waqasabbasi/optimizing-and-deploying-puppeteer-web-scraper-1nll
https://www.scrapehero.com/how-to-increase-web-scraping-speed-using-puppeteer/

**Comment by gumuruhsspj** [comment]
> Tried setting the options and it made my code perform worse. What helped me was using request interceptor to block certain resources from loading. Sites below have some really useful information on how to do it:
> https://dev.to/waqasabbasi/optimizing-and-deploying-puppeteer-web-scraper-1nll
> https://www.scrapehero.com/how-to-increase-web-scraping-speed-using-puppeteer/

sure this was good. But sometimes the elements need the css as well... so stylesheet blocking is optional. 
and not mandatory.

**Comment by Write** [comment]
I tried everything here but what solved my issue was this post : https://github.com/puppeteer/puppeteer/issues/5923
The problem was indeed userDataDir (or --user-data-dir= in args) being set with a relative path
Thanks @suchcodemuchwow for the solution https://github.com/puppeteer/puppeteer/issues/5923#issuecomment-657285335_
Using an absolute path instead of a relative one fixed the huge cpu/ram usage when headless was set to **true**

**Comment by NCLnclNCL** [comment]
> Hey, i'd recommand trying a bunch of args until you get better results, especially if you want to run it on raspbian. Excuse my english it's fairly bad. I'm using puppeteer since a few months, trying different things on an heavy webgl game. At first performances were terrible and i was loading that page in more than a minute, i'm now doing it way faster.
> 
> Since your goal seems to be using it on raspbian, here are some random stuff i learned using it on linux:
> 
> * just don't use it headless, on webgl pages i nearly always got worse results that way, you can always start a random X server and use that. (don't use xvfb!) It "needs" to use your gpu/igpu. Use "chrome://gpu" to check stuff, i get a lot of disabled or cpu only features when using it headless even tho i launch it with the same options. I've never managed to make it use the igpu on my server when running headless or with xvfb.
> 
> If you really want to use it headless:
> 
> * disable as much features as you can, try even those you don't understand. [This website is awesome for that.](https://peter.sh/experiments/chromium-command-line-switches/)
> * Use **`'--disable-gl-drawing-for-tests'`**, i don't really understand what it does but as long as you don't need to take screenshots that's just the best option you can use. Everything will work as usual, "webgl stuff exists" on the page, you can interract/click on it and so on but it's not displayed, that way you'll save a lot of resources.
> 
> To give you an idea, on my Intel i5-2300 server without graphic card here is my cpu without that option : ![without](https://camo.githubusercontent.com/96ecb5549bad6167e9e34b5212f4075cb7d2e63075a0a99635abb44ffc08771a/68747470733a2f2f692e696d6775722e636f6d2f797470755934612e706e67)
> 
> And here it is with **`'--disable-gl-drawing-for-tests'`**: ![with](https://camo.githubusercontent.com/01062339a3822dd82bd19bcf367ae1922fb04155d29f9022df6603ac53c8d673/68747470733a2f2f692e696d6775722e636f6d2f76485337314b622e706e67)
> 
> * here are a few options i use/used successfully:
> 
> ```js
>       headless: false, // process.env['DISPLAY'] = ':0'; in index.js, xorg running.
>       ignoreDefaultArgs: true, // needed ?
>       devtools: false, // not needed so far, we can see websocket frames and xhr responses without that.
>       //dumpio: true,
>       defaultViewport: { //--window-size in args
>         width: 1280,
>         height: 882
>       },
>       args: [
>       /* TODO : https://peter.sh/experiments/chromium-command-line-switches/
>         there is still a whole bunch of stuff to disable
>       */
>         //'--crash-test', // Causes the browser process to crash on startup, useful to see if we catch that correctly
>         // not idea if those 2 aa options are usefull with disable gl thingy
>         '--disable-canvas-aa', // Disable antialiasing on 2d canvas
>         '--disable-2d-canvas-clip-aa', // Disable antialiasing on 2d canvas clips
>         '--disable-gl-drawing-for-tests', // BEST OPTION EVER! Disables GL drawing operations which produce pixel output. With this the GL output will not be correct but tests will run faster.
>         '--disable-dev-shm-usage', // ???
>         '--no-zygote', // wtf does that mean ?
>         '--use-gl=swiftshader', // better cpu usage with --use-gl=desktop rather than --use-gl=swiftshader, still needs more testing.
>         '--enable-webgl',
>         '--hide-scrollbars',
>         '--mute-audio',
>         '--no-first-run',
>         '--disable-infobars',
>         '--disable-breakpad',
>         //'--ignore-gpu-blacklist',
>         '--window-size=1280,1024', // see defaultViewport
>         '--user-data-dir=./chromeData', // created in index.js, guess cache folder ends up inside too.
>         '--no-sandbox', // meh but better resource comsuption
>         '--disable-setuid-sandbox'] // same
>         // '--proxy-server=socks5://127.0.0.1:9050'] // tor if needed
>     });
> ```
> 
> As you can see even without understanding what the options do you can get better results. Anyway, if your goal is to grab a text every second i'd strongly recommand using **`'--disable-gl-drawing-for-tests'`**. Otherwise, as @aslushnikov said, having a sample would help. Have a good day!

--disable-gl-drawing-for-tests dont working if render it with software as flags --disable-gpu/--use-gl=swiftshader/--use-gl=desktop
