### ISSUE TITLE
PDF size is really high if imported fonts are used

### ISSUE THREAD

**Issue by gabimoncha** [puppeteer/puppeteer#3939]
### Steps to reproduce

Create an html template with normal font style (e.g. Arial). Generate PDF.
Import google font Lato, replace the previous font and then generate the PDF.

Using the normal font the pdf is almost 100 times smaller then using an imported google font.

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: macOS Mojave 10.14.3
* Node.js version: 10.15.0

I used this tutorial to setup `puppeteer` and `handlebars`:
https://futurestud.io/tutorials/node-js-create-a-pdf-from-html-with-puppeteer-and-handlebars

**Code to import google font**
```
<head>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Lato');
  </style>
</head>
```

**Comment by aslushnikov** [comment]
@gabrielmoncea PDF generation is powered by Chromium's "Save as PDF" functionality - Puppeteer is just a thin proxy. Please, re-file this issue to https://crbug.com/new - Chromium's PDF team might be able to help.

(if you end up submitting bug upstream to chromium - please post a link to the bug here for the future reference. Thanks!)

**Comment by PROxZIMA** [comment]
@gabimoncha, I'm generating a PDF with base64 embedded font. Adding `@font-face` doesn't affect much but the moment I add `body { font-family: opensans }`, the PDF size increases 25 folds.

Other than embedding base64 font, nothing works for me. Did you find any workaround for this?
