### ISSUE TITLE
HIgh IO / disk usage on linux  vs low IO usage on windows

### ISSUE THREAD

**Issue by r1si** [puppeteer/puppeteer#3952]
Hi, I have two puppeteer instance run on my windows 7 laptop and same two instance run on my debian server.

Only one difference is that linux one is run with "--no-sandbox" and "--proxy-server='x.x.x.x:yyyy'" args

In windows have a normal CPU usage and a low disk usage (avg 10 KB/s)
In linux have a little high CPU use due a high IO / disk usage (avg 1.5 MB/s)

any advice?

**Comment by matheuschimelli** [comment]
Hi. As you, i'm new here too. However, for first, i'm sugest to you to use the bug template to describe your issue.
Second, i'm having the same problem when i use linux. On windows, opening multiple pages at same time, i have no io problem. But when i use linux, the cpu usages goes up to more than 250%, and for more than one time, my script stopped without error, just stopped.

**Comment by aslushnikov** [comment]
@r1si @matheuschimelli I'd recommend asking this on [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev) google group since this doesn't seem to be related to Puppeteer itself. 

When reaching out to the google group, please make sure to provide excessive details to help folks reproduce this behavior.
