### ISSUE TITLE
PDF page size is slightly different from given params

### ISSUE THREAD

**Issue by rvalery** [puppeteer/puppeteer#4015]
Hello,

I have a problem when I try to export a page in PDF with puppeteer at a fixed size. For example, if I try to export a PDF with size 154mm x 214mm, the file ends with a slightly smaller size of 153.8mm x 213.8mm. I have tried to pass the page size in millimeters, in inches and in pixels, but nothing works.

I have also tried to increase the page size by a small amount (for example 154.1mm x 214.1mm), but it does not fix the problem (the size of the PDF is still 153.8mm x 213.8mm). If I increase the size a little more, for example if I pass a size of 154.2mm x 214.2, then the PDF ends with a slightly bigger size of 154.2mm x 214.1mm.

No matter the values I pass for width and height in page.pdf(), the PDF page size will "jump" from 153.8mm to 154.2mm, I can never obtain a value in between.

### Steps to reproduce

* Puppeteer version: 1.12.2
* Platform / OS version: MacOS Sierra 10.12.6
* URLs (if applicable):
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

Use the below script to reproduce the problem :

```
const puppeteer = require('puppeteer');
var address;

if (process.argv.length < 3) {
	console.log('Usage: node test_puppeteer.js URL');
} else {
	address = process.argv[2];
}

(async () => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await page.setViewport({width:1819, height:2528});
	await page.goto(address, {waitUntil: 'networkidle0'});
	await page.emulateMedia('screen');
	await page.waitFor(5000);
	const ratio = 96 / 300;

	await page.pdf({path:"test_puppeteer_153.9mm_213.9mm.pdf", width:"153.9mm", height:"213.9mm", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_154.0mm_214.0mm.pdf", width:"154mm", height:"214mm", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_154.1mm_214.1mm.pdf", width:"154.1mm", height:"214.1mm", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_154.2mm_214.2mm.pdf", width:"154.2mm", height:"214.2mm", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_6.062in_8.424in.pdf", width:"6.062in", height:"8.424in", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_6.063in_8.425in.pdf", width:"6.063in", height:"8.425in", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_6.064in_8.426in.pdf", width:"6.064in", height:"8.426in", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_6.065in_8.427in.pdf", width:"6.065in", height:"8.427in", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_581px_808px.pdf", width:"581px", height:"808px", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_582px_809px.pdf", width:"582px", height:"809px", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_583px_810px.pdf", width:"583px", height:"810px", scale:ratio, printBackground:true});
	await page.pdf({path:"test_puppeteer_584px_811px.pdf", width:"584px", height:"811px", scale:ratio, printBackground:true});

	await browser.close();
})();
```

**What is the expected result?**
The resulting PDF should have the page size specified by width and height params (in my case 154mm x 214mm)

**What happens instead?**
The resulting PDF has a different page size (in my case 153.8mm x 213.8mm)

![capture d ecran 2019-02-14 a 19 54 15](https://user-images.githubusercontent.com/222965/52810202-54592e80-3092-11e9-88fa-18f061969242.png)

**Comment by Nik-Voelker** [comment]
Hello Raphaël,

The observed behaviour is caused by the unit conversion within the PDF format and viewer and thus not related to Puppeteer. The PDF base system and its user space of boxes works on whole points internally. Points are then recalculated to inch or metric cm/mm, depending on the viewer system. Deviations of mm fractions are thus an error by design, unfortunately. They are around for quite some time. Common implementations work with a factor of 25.400 for inch to mm, and 1 pt considered to be 1/72 inch. Thus, via whole points: 1819 px / 300 dpi = 6.06333... inch = 436.55999... pt ≈ 436 pt / 72 * 25.400 = 153.81111 mm

Next available size would then be 437 pt -> 154,16388 mm. 

Hope it helps.

**Comment by rvalery** [comment]
Hello @Nik-Voelker,

Thank you for your answer, I now understand why the size of pages is slightly off.

I use Acrobat Pro to check exported PDF. It is an old version (10.1.16), but it has a menu to create a PDF from an URL. So I have made a simple test, described below :

1) Go to Menu File > Create > PDF File from a web page (naming might be a little different as I have translated menu labels from French)
<img width="1083" alt="capture d ecran 2019-03-07 a 16 32 55" src="https://user-images.githubusercontent.com/222965/53969881-e1bff980-40f9-11e9-94ea-da8ebad10516.png">

2) Enter the url : https://google.fr, then click on button "parameters..."
![capture d ecran 2019-03-07 a 16 59 05](https://user-images.githubusercontent.com/222965/53970166-6579e600-40fa-11e9-8cd7-63abb69859cf.png)

3) Set the page size to a custom format (154mm x 214mm), all margins to 0, and portrait orientation. Validate the parameters.
![capture d ecran 2019-03-07 a 16 59 18](https://user-images.githubusercontent.com/222965/53970183-6dd22100-40fa-11e9-8ab1-8929e1215196.png)

4) Create the PDF.  After creation, you can see that page size is 154mm x 214mm, without any rounding errors (ie. not 153.8mm x 213.8mm).
![capture d ecran 2019-03-07 a 16 33 03](https://user-images.githubusercontent.com/222965/53969958-05833f80-40fa-11e9-90a7-a0983bca1fa3.png)

This means creating a PDF with the right size is possible. Based on this test, and if the "rounding to point" problem is not cause by Pupeeter, I think it might be something in the way Chrome is creating the PDF, or maybe directly in Skia PDF. Unfortunately at the moment I don't know a simple way to test this...

**Comment by Nik-Voelker** [comment]
Hi Raphaël,

The "error" is PDF format inherent, as its internal unit is DTP point (same occurs with PostScript). Not only Skia but also libRSV/Cairo show the same behaviour. And also Adobe products:

Acrobat, InDesign, or Illustrator display the correct size, just rounding to the whole mm which eases the deviation. Even the (impossible) case of 1 pt (1/72″) error equals only to .35 mm which would be consumed by rounding to the whole mm. See attached sizes for your PDF calculated by macOS Preview, Adobe Acrobat, and the same document opened in Photoshop for rendering. When the unit of the latter is set to mm, the 154.16 x 214.14 (or 437 x 607 pt) resurface. 

Only that Cairo or Skia seem to calculate 436 x 606 pt for the same input size (off by .2 instead of the .16 mm by Adobe).

Not sure about your use case, but so far I have not encountered any drawbacks for (print) production. Technical error margins, e.g. in offset printing, are usually far beyond these values. It seems thus a mere question of UI aesthetics.

Cheers!

![google fr](https://user-images.githubusercontent.com/36933048/53976814-aa544b80-40ff-11e9-9c5c-8694ce66c429.jpg)

**Comment by rvalery** [comment]
Thank you for this complete explanation. Acrobat was indeed rounding the values, but I can see non-rounded values when opening the PDF with Photoshop as you suggest.

The use case was submitted by a client, that claims that these 0.2mm can mess with his margins. It's because he uses very small size for margins apparently. I was really doubting that this small size difference could have an impact, but I told him I would look into the problem. Thanks to you, I can now explain him that this is a PDF limitation, and it can't be changed.

Cheers!
