### ISSUE TITLE
Chrome process always exits on process.exit()

### ISSUE THREAD

**Issue by hlr1983** [puppeteer/puppeteer#4061]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: 
    uname -a
    Linux henrique-Latitude-5480 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
    lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04.2 LTS
    Release:	18.04
    Codename:	bionic
* URLs (if applicable):
* Node.js version: v10.15.1

**What steps will reproduce the problem?**

This isn't a problem, but I think it might be useful under some circunstances. If I run the following code, and it launches the chrome instance, chrome exits when nodejs exits.

```
"use strict";

(async () => {
    try {
        console.log('aaa');
        async function connectOrLaunch () {
            const puppeteer = await require('puppeteer');
            try {
                const connectChrome = await puppeteer.connect( { browserURL: 'http://localhost:35000' });
                return await connectChrome;
            } catch (e) {
                return await puppeteer.launch({
                    headless:false, 
                    timeout: 60000,
                    args: ['--remote-debugging-port=35000'],
                    handleSIGINT: false,
                    handleSIGTERM: false,
                    handleSIGHUP: false,
                });
            };
        }
        
        const browser = await connectOrLaunch();

        const incognito = await browser.createIncognitoBrowserContext();
        const page = await browser.newPage();
        await page.setCacheEnabled(false);
        //await page.goto('http://www.google.com');
        throw new Error('BLAH');
        
        // DO SOME STUFF
       
        await process.exit(0);
        
    } catch (e) {
        await console.log(e.stack);
        await process.exit(1);
        
    };
    
})();
```

What I want to do is to keep the chrome process running (for example, allowing others puppeteers to connect to the same chrome instance, or keep the window in headless=false), so I did small changes in the puppeteer code: [https://github.com/hlr1983/puppeteer/pull/1](https://github.com/hlr1983/puppeteer/pull/1)

Now I have the option handleNodeExit and can keep chrome instance running, so I do something like

```
return await puppeteer.launch({
                    headless:false, 
                    timeout: 60000,
                    args: ['--remote-debugging-port=35000'],
                    handleNodeExit: [0,2], // chrome exits when process.exit(0) or process.exit(2)
                    handleSIGINT: false,
                    handleSIGTERM: false,
                    handleSIGHUP: false,
                });
```

It's useful for me, as now I can call my js file many times, and don't mind about chrome is running or not. 
Maybe someone wants its to keep running depending on the code of the process.exit(code).

Of course, I could do the same with someting like `process.removeListener('exit',process.rawListeners('exit')[process.rawListeners('exit').length-1]);` just after the puppeteer.launch()

What do you think about it? Does anybody find it useful?

Thanks.

**Comment by aslushnikov** [comment]
@hlr1983 cool, thanks for sharing. In most cases, having the parent node.js process running is not a big deal for our clients.

Alternative solution to what you did is combing 
[`puppeteer.executablePath()`](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-puppeteerexecutablepath) and [`puppeteer.defaultArgs()`](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-puppeteerdefaultargsoptions) methods with node's native [`spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) to launch Chromium in any way you like. Since this doesn't seem to be widely demanded, I'd rather stick with user-land solutions here.

**Comment by bdiouih** [comment]
@hlr1983 thank you very much.

The following code still work very well, and with this, we are sure to be up to date with last puppeteer versions:
`process.removeListener('exit',process.rawListeners('exit')[process.rawListeners('exit').length-1]); `

Also don't forget to call the following, before process exit:

```
await page.close();
await browser.disconnect();
```

in order to terminate the current "tab" process.

**Comment by HaotianLyuForUsAll** [comment]
@hlr1983 I wonder how did you modify the code to support the chromium instance running in the background? Looks like your PR is closed, and I could not see it.

**Comment by dougpagani** [comment]
Since this PR wasn't merged, I implemented a workflow that leverages the bits that @aslushnikov suggested.

I got it to work without having to require any manual steps. It would be easy to put this into some kind of pre-script instrumentation (especially for tests). This script should be runnable so long as you have an npm project w/ puppeteer (+chromium) installed into node_modules. I only tested this on macos so disparities in process-signalling behavior might break it across OS's, but it's worth a shot even if you're on linux. I wanted to be able to ^C out of the initializing node process and leave a headful browser running, and that's what this gist does.

https://gist.github.com/dougpagani/4681838a12a7821c096640d491649a43
