### ISSUE TITLE
http://peter.sh is down

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#409]
[puppeteer.launch() description](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) states:

> List of Chromium flags can be found here.

and gives the link to http://peter.sh/experiments/chromium-command-line-switches/

However, this site is down (`ERR_CONNECTION_REFUSED`). Sorry if this is a known/temporary issue.

**Comment by kensoh** [comment]
Try this web archive for now (updated 17th Aug) - 
http://web.archive.org/web/20170817214451/https://peter.sh/experiments/chromium-command-line-switches/

I've been using Peter's website on and off the last few months and ok. Not sure if it's due to sudden traffic spike from Puppeteer launch, down for me too. I've just tweeted Peter to see if anything.

**Comment by benjamingr** [comment]
Can't we just keep a mirror here?

**Comment by ebidel** [comment]
I've pinged Peter. He says the site is coming back online shortly. Since this page is a long-time resource for the web, we wouldn't want to replicate it here.
