### ISSUE TITLE
Which is the best practice using puppeteer to create pdf?

### ISSUE THREAD

**Issue by chuongtrh** [puppeteer/puppeteer#4103]
I am using puppeteer to create pdf from HTML template. Which approach is best practice in two solutions below?

1. Always launch puppeteer and create a new **browser** to create pdf. The **browser** will be **closed** when created pdf is done.

```
(async () => {
  const finalHtml = 'html content...';
  const browser = await puppeteer.launch();
  const page = await browser.pages()[0];
  await page.setContent(finalHtml);
  await page.pdf({path: 'hn.pdf', format: 'A4'});

  await browser.close();
})();
```
2. Keep 1 instance browser. Always create a new **page** to create pdf. The **page** will be **closed** when created pdf is done

```
const browser = await puppeteer.launch();

(async () => {
  const finalHtml = 'html content...';
  const page = await browser.newPage();
  await page.setContent(finalHtml);
  await page.pdf({path: 'hn.pdf', format: 'A4'});
  await page.close();
})();
```

Thank advance.

**Comment by aslushnikov** [comment]
> Which approach is best practice in two solutions below?

@chuongtrh well, ideally I'd do the following:
- keep the browser instance opened
- alway create a new [`browser context`](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-class-browsercontext) and a page to create a pdf. The browser context is **closed** when created PDF is done.

This approach is nice since it yields very predictable results: pages will always open in pristine browsing context, meaning that there'll be no cookies or local storage. It's also quite efficient since creating browser contexts is very efficient.

The downside is that Chromium is a complicated application and might accumulate error over time; as a result, it might crash or misbehave, so a proper implementation would restart browser every once in a while or have some other error-handling.

So depending on your requirements, I'd either go with re-launching browser for every render (simple to implement) or re-using browser instance and re-creating just browser contexts (more involved but efficient).

Hope this helps.

**Comment by luckydrq** [comment]
>as a result, it might crash or misbehave, so a proper implementation would restart browser every once in a while or have some other error-handling.

@aslushnikov If we can "listen" to browser crash and re-launching a new one, that would be perfect! So is there a way?

**Comment by aslushnikov** [comment]
@luckydrq yes, you can listen to the [`browser.on('disconnected')`](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-event-disconnected) event.
