### ISSUE TITLE
Weird Lines in Screenshot in Headless

### ISSUE THREAD

**Issue by j** [puppeteer/puppeteer#4137]
In PNG/JPEG, my images are getting lines at higher resolutions.

![image](https://user-images.githubusercontent.com/589410/53993901-7ec46780-40e5-11e9-9f7d-ab421eef5e45.png)

In some cases, the lines are bigger and thicker.  If I turn headless mode off, or lower the image size, the lines go away.

How can I take clean images of larger viewports without the lines being there?  In the browser, the lines are not there.

**Comment by aslushnikov** [comment]
@j: I'm not sure what are the lines and why they appear. Usually it means that website is doing something finicky - and that's outside Puppeteer's control.

We can't help much here since we can't repro. Closing this, but feel free to re-file with a good script that we can run locally to debug your issues.
