### ISSUE TITLE
Puppeteer JavaScript margin and HTML CSS margin inconsistency

### ISSUE THREAD

**Issue by mortenmoulder** [puppeteer/puppeteer#4191]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: `^1.13`
* Platform / OS version: Debian (deployed via Docker `FROM node:8.15.1`)
* Node.js version: 8.15.1

**What steps will reproduce the problem?**
![image](https://user-images.githubusercontent.com/1304665/54751834-66237980-4bdc-11e9-9af4-c452dc57913e.png)

To produce the above image, print a PDF with the following code:

```
await page.pdf({
    format: "A4",
    displayHeaderFooter: true,
    headerTemplate: "<div style=\"margin-left:1.5cm; margin-right:1.5cm; margin-top: 0.5cm; font-size:12px; display:flex; flex-direction:row; justify-content:space-between; width:100%;\"><div>Version 1.2</div><div>Test</div></div>",
    footerTemplate: "N/A",
    printBackground: true,
    margin: {
        top: "1.5cm",
        right: "1.5cm",
        bottom: "1.5cm",
        left: "1.5cm"
    }
});
```

The `page.setContent()` can be set to anything.

**What is the expected result?**
Expected result is that the `margin-left: 1.5cm` should match the `margin` from the `page.pdf()` object. Clearly it does not in this case. I need to change the `margin-left` property to about `1.25cm` to get the same margin.

**Comment by SoerenWeber** [comment]
Were you able to find out what's causing this behavior, @mortenmoulder ? It seems like this inconsistency not only applies to margins but other size values as well; `font-size` and `padding` seem to be about 1.25x as large as in the body.

I hoped to find a css declaration in the [header/footer template](https://cs.chromium.org/chromium/src/components/printing/resources/print_header_footer_template_page.html) that's the culprit here but no luck.

**Comment by SoerenWeber** [comment]
This seems to be caused by inconsistent resizing between body and header/footer in Chromium. It's probably related to a scaling factor, [currently 1.33](https://github.com/chromium/chromium/blob/bd1d1ccda3817b04095109b33a354ffe85d3c3d7/components/printing/renderer/print_render_frame_helper.cc#L99), that's used in Chromium's print view. I guess the inconsistency stems from [this line](https://github.com/chromium/chromium/blob/bd1d1ccda3817b04095109b33a354ffe85d3c3d7/components/printing/renderer/print_render_frame_helper.cc#L2107) but I'm not sure why it is used that way.

As a work-around I used a CSS `scale()` transform function or set a `zoom` declaration to resize my elements to 75%. This isn't a pixel-perfect solution, at least in my case though.

I was able to find two related issues on Chromium's issue tracker [1][2]. For more background information on the scaling factor, another issue might be helpful [3].

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=833058
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=818496
[3] https://bugs.chromium.org/p/chromium/issues/detail?id=273306

**Comment by mortenmoulder** [comment]
@SoerenWeber Nice investigation! Nope, I never got around to doing anything like this myself. I just sticked with a virtual ruler (in the form of a regular window in Windows) to adjust my margins. As you said:

>This isn't a pixel-perfect solution

And I agree, but it works well enough to accept it. Thanks, though.

**Comment by adrianlocurcio** [comment]
Did someone find any solution for this ? I am trying to print something that needs very much precision at pixel level and i am not being able to get that. I need to match 1 exact pixel to get those lines joined: https://prnt.sc/u0pns7

**Comment by Xentox-Phil** [comment]
wow this persists still in 2025! THAT IS ACTUALLY INSANE

did anybody solve it completely without a hack?
