### ISSUE TITLE
Puppeteer Doesn't Render Javascript Pages From External Resources (Works only for localhost URLs)

### ISSUE THREAD

**Issue by PHPBeginnerStudent** [puppeteer/puppeteer#4210]
Hi Team!

I am trying to configure puppeteer to render Javascript Pages. 
I am using Puppeteer for this purpose and when I provide any external URL (not localhost pages), Puppeteer fetches only the source code of the URL (what you may see in view-source mode of the requested page), without rendering the entire DOM.
When I try to SSR any localhost Javascript page URL (a page generated by the same node js server on my local host) - all works fine. 

Please advise whether I am missing something or I need to try another approach.

**Comment by vsemozhetbyt** [comment]
[This answer](https://stackoverflow.com/a/55362495/2625560) seems to mention most usual suspects of the issue.

**Comment by PHPBeginnerStudent** [comment]
Hi! thanks for looking into my question! actually it is my post ads well, I asked the question in different places to get more ideas)

**Comment by RebliNk17** [comment]
@PHPBeginnerStudent have you find a solution?

Stuck on the same issue.... I tried everything i think...

Chromium\Firefox just not running the JavaScript code after the page finished loading...

**Comment by PHPBeginnerStudent** [comment]
Hello Reb!
Thank you very much for your feedback)
I am still looking for the solution but have no idea what it can be. I am
not that professional in node.js unfortunately, so need help of an expert.
I am wondering how Prerender is working, their free library is a bit
complicated for me...

**Comment by aslushnikov** [comment]
> Puppeteer fetches only the source code of the URL (what you may see in view-source mode of the requested page), without rendering the entire DOM.

@PHPBeginnerStudent this is not very much actionable; we'd need a good repro. Puppeteer just drives Chromium to navigate to a page; if Chromium doesn't run scripts on the page, it means something's wrong with it.

> Chromium\Firefox just not running the JavaScript code after the page finished loading...

@RebliNk17 This looks like the server responds with `text/plain` or something else instead of `text/html`.

To sum up: please re-file with a reproduction script and a URL that doesn't work for you. Otherwise we can only speculate and can't suggest anything actionable.
