### ISSUE TITLE
OpenBSD Support

### ISSUE THREAD

**Issue by jviotti** [puppeteer/puppeteer#4250]
Hey there! I'm wondering what would it take for Puppeteer to support OpenBSD and potentially other BSDs. I get an "Unsupported platform" error, but it this because Puppeteer does;t have active support for other operating systems, or because there are technical limitations in doing so? 

If so, can you provide a quick description of the technical challenges on porting Puppeteer to *BSD as some guidance for potential contributors?

**Comment by aslushnikov** [comment]
@jviotti the "unsupported platform" error comes because we don't have Chromium builds for OpenBSD. You can still use `puppeteer-core` to run with a pre-installed chromium binary. 

> If so, can you provide a quick description of the technical challenges on porting Puppeteer to *BSD as some guidance for potential contributors?

In order to have it in Puppeteer, we'd need to update our infra to produce OpenBSD builds. I don't see this happenning any time soon since it doesn't look like there's a lot of demand.

However, you're free to follow the route of https://github.com/alixaxel/chrome-aws-lambda package - they compile their own version of Chromium and ship it with puppeteer library. 

Hope I answered the question.
