### ISSUE TITLE
Can't cancel page request before navigation

### ISSUE THREAD

**Issue by vbisbest** [puppeteer/puppeteer#4255]
Using latest Puppeteer.

I am trying to write a utility to simply scrape hyper links from web pages.  I am including all javascript links as well as anchors.  I am clicking on <div> takes with puppet an intercepting the requestcreated event.  So when I click the first div tag, I get request created and I "abort" the request.  However now, I can not click the rest of the div tags because the page has now left and shows an "error navigating".   How can you capture a request before the navigation actually occurs and prevent it.  Thanks!

**Comment by xse** [comment]
Hey,

I'm pretty sure this isn't what your looking for, but as a workaround you should be able to get similar results.
- Create a js file that will be loaded by your node program and executed on the page using [page.evaluateOnNewDocument](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluateonnewdocumentpagefunction-args)

- That script "overrides" the way any page is sending those requests.

- That script can "communicate" with your puppeteer program using page.evaluate or just outputing objects to the page's console, you can then block/continue requests, send those requests parameters from the program to the script or the other way around.

I'm currently using something similar for intercepting websocket since puppeteer only allows me to see the frames but doesn't allow me to block/continue them. Doing so for XMLHttpRequest is doable.
Excuse my english, have a good day!

**Comment by aslushnikov** [comment]
> However now, I can not click the rest of the div tags because the page has now left and shows an "error navigating".

@vbisbest You should abort navigation request with "aborted" code - this is similar to a user hitting "stop" button. 

Hope this helps.

**Comment by aledalgrande** [comment]
I read various issues about stopping navigation and it didn't work for me with the suggested code until I added the optional `'aborted'` code to `abort`. Now it works perfectly! I think this should be emphasized.
