### ISSUE TITLE
some youtube page can not display well

### ISSUE THREAD

**Issue by wisenight** [puppeteer/puppeteer#4272]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: ubuntu 18.04
* URLs (if applicable): https://www.youtube.com/watch?v=JBXhHt5HAVw
* Node.js version: v11.13.0

**What steps will reproduce the problem?**

**What is the expected result?**
Can display video well.

**What happens instead?**
Can not display video.

**Comment by aslushnikov** [comment]
The following works for me:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://www.youtube.com/watch?v=JBXhHt5HAVw');
})();
```

**Comment by wisenight** [comment]
sorry, my mistake, the url should be https://www.youtube.com/watch?v=BoCt6yLTHy8

it will say yt can not support this kind of. video

**Comment by aslushnikov** [comment]
@wisenight ah, that's because Chromium doesn't support all video formats; see [FAQ:What features does Puppeteer not support?](https://github.com/GoogleChrome/puppeteer/#q-what-features-does-puppeteer-not-support) for details.

You'd need to connect to Chrome instead. Check out [here](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy) on how to pick correct Puppeteer version for your Chrome version.

Hope this helps.
