### ISSUE TITLE
Screenshot never finishes

### ISSUE THREAD

**Issue by dotjpg3141** [puppeteer/puppeteer#4273]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Windows Server 2016 Standard
* URLs (if applicable): https://www.google.com/
* Node.js version: v11.10.0

**What steps will reproduce the problem?**

Run puppeteer without active user interface.
I'm running it in teamsystem in a build step.

``` javascript
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.setViewport({ width: 1280, height: 800 })
await page.goto('https://www.google.com/')
console.log("Before screenshot");
await page.screenshot({ path: 'google.png', fullPage: true })
console.log("After screenshot");
await browser.close()
```

**What is the expected result?**

Takes screenshot.

**What happens instead?**

No screenshot is taken. The process gets stuck.

Note: If I connect to the build server via remote connection and start the script manually it works.

Maybe related to #3792, #3377

**Comment by grancalavera** [comment]
We the same issue, and we have added a repro case here: 

https://github.com/grancalavera/puppeteer-teamcity-screenshot-bug

- TeamCity Enterprise 2018.2.1 (build 61078)
- Agent running Windows Server 2012 R2 Standard 

As well, RDPing into the agent and running the test case works.

Changing the code to use thenables instead of `async` `await` fixes the issue:

```javascript
async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(filePath, {
    waitUntil: ["networkidle2"]
  });

  const timeoutId = setTimeout(() => {
    throw new Error(`screenshot "${screenshotPath}" timed out!`);
  }, TIMEOUT);

  page
    .screenshot({ path: screenshotPath })
    .then(() => {
      clearTimeout(timeoutId);
      assert.doesNotThrow(
        () => fs.statSync(screenshotPath),
        `screenshot "${screenshotPath}" not found!`
      );
    })
    .catch(e => {
      console.error(e.message || e);
      process.exit(1);
    });
}
```

Finally, we can't reproduce the issue when running the build on a Linux agent.

**Comment by dotjpg3141** [comment]
Running the build agent in interactive mode solved the issue for me:
http://donovanbrown.com/post/auto-start-build-agent-in-interactive-mode

**Comment by githubbr** [comment]
I am experiencing the same issues. I am developing on Mac using Visual Studio 2019 and working on a web api in dotnet core 2.2 which invokes node module which grabbing screenshot of web pages using Puppeteer. No issues at all during the development but issues occurs once I deployed my application to a Windows Server 2012. Other functions like `page.pdf()` and `page.content()` work fine, except `page.screenshot()`. Out of curiosity, I load up my project on a Windows 10 machine and all works fine in there (using Kestrel). It seems that the issue is specifically with either IIS or Windows Server 2012.

I have tried @grancalavera workaround but it still doesn't work for me.

My script works fine if I RDP to the machine and run it using command line.

**Comment by dotjpg3141** [comment]
Automatically signing in with the user executing puppeteer solved this issue for me (see link above).

Should I reopen this issue?

**Comment by grancalavera** [comment]
@githubbr did you add the `then` and `catch` directly to the `page.screenshot()` call? That seems to be the only way it works for me.

**Comment by githubbr** [comment]
> @githubbr did you add the `then` and `catch` directly to the `page.screenshot()` call? That seems to be the only way it works for me.

I did and that still doesn't work.

**Comment by githubbr** [comment]
> Automatically signing in with the user executing puppeteer solved this issue for me (see link above).
> 
> Should I reopen this issue?

I am not sure what you meant with automatically signing in ... I suppose the user executing puppeteer is `IISUSR`. 

I think this issue needs to be re-opened because both suggestions are workarounds.

**Comment by githubbr** [comment]
Further look at it, it seems that it is still timing out and execute `throw new Error(`screenshot "${screenshotPath}" timed out!`);`

**Comment by githubbr** [comment]
Can we or how do we turn on debug on nodejs and/or puppeteer module so that we know exactly where it is failing in `lib/Page.js`?

**Comment by githubbr** [comment]
For now, this is my workaround. Not ideal but I got the same thing:

```
await page.emulateMedia('screen');
await page.pdf({path: 'page.pdf'});
```

It gives me the screenshot in PDF format.

**Comment by aslushnikov** [comment]
>  am experiencing the same issues. I am developing on Mac using Visual Studio 2019 and working on a web api in dotnet core 2.2 which invokes node module which grabbing screenshot of web pages using Puppeteer

@githubbr this seems to be a dupe of https://github.com/GoogleChrome/puppeteer/issues/4290
