### ISSUE TITLE
Puppeteer firefox promise sometimes returns array, sometimes object

### ISSUE THREAD

**Issue by jan0991** [puppeteer/puppeteer#4295]
My code that I execute inside browser:
```
const getArticles = async (page) => {
    return await page.evaluate(() => {
        ...
        return Promise.resolve(formated.filter(x => x)) // formated is a normal array
    });
}
```

I have to call it like this:

```
        let newArticles = await getArticles(page)
         if(!Array.isArray(newArticles)) {
            newArticles = newArticles._v
        }
```
It seems very random. Sometimes it returns an array, sometimes object. With chrome, it was array every single time. Any ideas?

**Comment by aslushnikov** [comment]
@jan0991 did it resolve itself?

**Comment by jan0991** [comment]
I thought so, but nope. Still does this randomly.

**Comment by aslushnikov** [comment]
@jan0991 so can you please share a small script that will reproduce this?

**Comment by mjzffr** [comment]
Thanks for the report. I'm closing this issue since the experimental `puppeteer-firefox` package is no longer maintained. A replacement will be available
later this year. You can learn more about Mozilla's work on this at https://wiki.mozilla.org/Remote

See also https://github.com/puppeteer/puppeteer/pull/5137
