### ISSUE TITLE
Can't overwrite dialog handler to customize behavior in differents escenarios without destroy the page instance

### ISSUE THREAD

**Issue by devjoca** [puppeteer/puppeteer#4420]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14
* Platform / OS version: MacOs Mojave
* Node.js version: 12.10

**What steps will reproduce the problem?**
I'm working with puppeteer and I need to handle dialog without destroying the page instance
so is there a way to overwrite that handled, I'm getting  `Cannot dismiss dialog which is already handled!` when I try to overwrite.

```js
page.removeListener('dialog', () => { });
page.on('dialog', async dialog => {
    await dialog.dismiss();
});    
```

**What is the expected result?**
Should overwrite the behavior of the handler of the dialog event, so I don't need to create another page instance.

**What happens instead?**
Can't perform that action

**Comment by connectwithub** [comment]
I was also facing the similar error. 

In my case, It was happening because once before I had added the above function to handle another popup, and that function was still listening, as I had failed to remove its listener, and hence the error "_Cannot dismiss dialog which is already handled!_". What you can do in your case I belive is instead of using **on** if want to handle a dialog once use **once**. That way once a dialog is handled you can call the above function again to handle another dialog in another way.

Hope It helps.

**Comment by devjoca** [comment]
Thanks, `once` works perfectly
