### ISSUE TITLE
Some pages not fully loading when setRequestInterception set to true

### ISSUE THREAD

**Issue by vincenthawke** [puppeteer/puppeteer#4442]
* Puppeteer version: 1.14.0
* Platform / OS version: Windows 10
* Node.js version: 10.15.3

Complete code to reproduce the problem:
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ 
        headless: false, 
        devtools: false
    });
    const page = await browser.newPage();
    await page.setViewport({ width: 1920, height: 1080 });
    await page.setRequestInterception(true);
    page.on('request', request => {
        request.continue();
    });

    await page.goto('http://123tvnow.com/watch/cbs/',)
    .catch((e) => {console.log(e)})
    // await browser.close();
})();
```

If `setRequestInterception` is set to `true`, the page never fully loads event thou all requests seem to be handled. Some sub-pages of the included example website do load, like: `http://123tvnow.com/watch/espn`
If you enable dev tools you'll need to deactivate breakpoints and resume. It's just the way site owner coded it. 

After 30 seconds a `TimeoutError` error will be caught. I would like to understand why this is happening? It is especially confusing because some sub-pages load without a problem so I didn't expect the `xhr` streaming files be an issue or .ttf or something similar.

**Comment by snyamathi** [comment]
I've noticed this issue as well - removing the request interception allows test to proceed which would otherwise timeout.  In my case, I have the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` flag set and am using Chrome on my machine ( v74 ) but noticed that with Canary ( v76 ) the issue is no longer present and the requests go through as usual.

**Comment by jazoom** [comment]
I saw this with 1.15.0 and am now seeing it with 1.16.0.

**Comment by Yokutto** [comment]
Hello everyone,
I faced this issue updating puppeteer 1.12 to 1.15 without update Chrome version (**NOT CHROMIUM**) and in my case the page never loads and always show a blank page without any error.

To fix this, go to [release notes](https://github.com/GoogleChrome/puppeteer/releases), here you can see the **required** Chromium version in order to use puppeteer correctly, in this case, you need to update to: Chromium 75.0.3765.0. (puppeteer 1.15)

If you use Google Chrome (not chromium), you will need to wait until Jun 4 for official stable release (v75), or install the [version in beta](https://www.google.com/intl/pt-BR/chrome/beta/) (unstable)

**Comment by dvil88** [comment]
Version 1.14 is last one that this is working. According to issue #3118 `args: ['--enable-features=NetworkService'],` has to be added, well... no,  it's still not working.
Tried in puppeteer v1.8-v1.17 with chromium version 73.0.3683.86 (i'm using my own chromium instead of using the one downloaded by puppeteer) and it only works in versions <1.15

**Comment by Yokutto** [comment]
It's because puppeteer 1.15 **requires** chrome v75+

@dvil88, please read my comment and you will understand

**Comment by dvil88** [comment]
@Yokutto yup, I read it after writing my comment lol. I was using my own chrome because of the policy settings but now I've managed to add the settings to the chrome opened by puppeteer so I can work with that version.

**Comment by jazoom** [comment]
Doesn't work for me in the stated versions and I let Puppeteer download the version of Chromium automatically.

**Comment by terrywh** [comment]
puppeteer-core 1.17 with chrome v76 also stuck when using setRequestInterception

**Comment by aslushnikov** [comment]
@vincenthawke Thank you for filing this! ❤️
 
Fix has landed upstream with https://chromium-review.googlesource.com/c/chromium/src/+/1636684
Fix will be rolled in with the [upcoming Chromium roll](https://github.com/aslushnikov/puppeteer/tree/roll-r665405).

**Comment by el0911** [comment]
> I've noticed this issue as well - removing the request interception allows test to proceed which would otherwise timeout. In my case, I have the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` flag set and am using Chrome on my machine ( v74 ) but noticed that with Canary ( v76 ) the issue is no longer present and the requests go through as usual.

can u explain this?

**Comment by snyamathi** [comment]
It's been a while, so I don't remember exactly - but I believe there was some sort of issue with chrome 74 that was fixed with chrome 76 which prevented request interception from working properly.  Since then, I haven't seen issues and am using request interception without issue - though we've long since passed those two chrome versions!
