### ISSUE TITLE
Large html strings (over 1 million) do not return on 1.1.0 and crash anything newer with page crashed!

### ISSUE THREAD

**Issue by scottwein** [puppeteer/puppeteer#4460]
* Puppeteer version: 1.1.0
* Platform / OS version: docker on node
* Node.js version: 10.15.1

**What steps will reproduce the problem?**
Have a html string over 1.8 million chars long and it will never return set content
_Please include code that reproduces the issue._

let page = await browser.newPage();
    console.time("set content 1")
    await setPageHtml(page, asHtml(report));//this does not return
    console.timeEnd("set content 1")

**What is the expected result?**
To return a page buffer. 

**What happens instead?**
It does not throw any errors in 1.1.0 it just never returns. In any newer version even 1.16 anything over 1 million chars seems to crash it with a page crashed! error. I have tried every args listed to try to help this issue, but it does not help. 1.1.0 seems ok until about 1.6 million. I checked the utf-8 it is all valid.

**Comment by mnmkng** [comment]
I can confirm similar behavior at least on 1.14 and 1.15. When returning a large object (140MB stringified) from `page.evaluate()`, the page crashes.

It also happens when trying to upload such a large object to an API directly from browser using `fetch()`, without ever returning it back to Node.js. This probably happens due to all requests from browser being tracked.

Splitting the data structure into c.a. 24 parts of 6MB worked for us.

We were using websocket connection, so using `pipe` might help, but we haven't tried, since it breaks other parts of our software.

**Comment by scottwein** [comment]
I think page.evaluate crashing is documented. I can get it to work withg 1.8 million on 1.1.0 using the setContent function, but that functions does weird things to table headers like repeat them in the middle of the table for no reason. I tried with a pipe same result wont return.
