### ISSUE TITLE
Evaluate chrome extension background script

### ISSUE THREAD

**Issue by KBoiarchuk** [puppeteer/puppeteer#4521]
I have a chrome extension that executes code in background script. Using puppeteer with [jest](https://github.com/smooth-code/jest-puppeteer) and mocks some chrome api, I try to check, that background script calling chrome.runtime.id method

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: MacOS 10.14.5
* URLs (if applicable):
* Node.js version: 10.15.0

_Please include code that reproduces the issue._

[Code](https://gist.github.com/KBoyarchuk/6e8520949753e66c8cdcd8de6c06fb0d)

**What happens instead?**
No console.log output in background page console in puppeteer devtool mode. Error message **ReferenceError: chrome is not defined**

**Comment by aslushnikov** [comment]
@KBoyarchuk I don't understand [some parts of your code](https://gist.github.com/KBoyarchuk/6e8520949753e66c8cdcd8de6c06fb0d#file-background-tests-js-L36-L39) - let me extract them here:

```js
    const backgroundPageCode = await readFile(path.resolve('example/dist/background.js')); // line 36
    await backgroundPage.evaluate(backgroundPageCode);  // line 37
    expect(chrome.runtime.id).toHaveBeenCalled();  // line 38
    expect(chrome.runtime.id).toBe(id);  // line 39
```

On line 37, you evaluate some code in the context of your *background page*.
On line 38 though, you expect something to change in the *node.js context*. These are different contexts - so the `toHaveBeenCalled` hook will never yield true, since the call actually happens on the browser side.

Instead, you can use Puppeteer to subscribe to the `'console'` event:

```js
    const backgroundPageCode = await readFile(path.resolve('example/dist/background.js')); // line 36
    const [message] = await Promise.all([
      // Create a promise that will resolve when console message is delivered.
      new Promise(x => page.once('console', x)), 
      backgroundPage.evaluate(backgroundPageCode),
    ]);
    expect(message).toBeTruthy();
```

Hope this helps!

P.S. I recently gave a talk and hopefully explained it better - please take a look at [this video](https://youtu.be/r-2a8G0hXKc?t=1395) (the link points to the right time in presentation).
