### ISSUE TITLE
Page.select throwing error when select change page

### ISSUE THREAD

**Issue by gilles-yvetot** [puppeteer/puppeteer#4537]
### Steps to reproduce

* Puppeteer version: ^1.16.0
* Platform / OS version: macOs Mojave 10.14.5 
* URLs (if applicable): https://developer.mozilla.org/en-US/
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

```javascript
page.select('#language','fr')
```

**What is the expected result?**

1. Go to the MDN url indicated
2. scroll to the bottom of the page
3. change the language in the dropdown
4. it will redirect you to the MDN homepage of the chosen language

**What happens instead?**

It does this but throw an error at the same time. The issue seems to be that the select is triggering a page load and we are loosing the reference to the specified DOM element.

**Comment by NikolaiMaksimenkoPreply** [comment]
Should I update my version of puppeteer to fix this issue (seems like not, because I catch the same error with version 1.20) ? I still catching  en errors   :   `Protocol error (Runtime.callFunctionOn): Cannot find context with specified id` with `select` . Example : 
` await page.select('[currency]', 'USD');`
