### ISSUE TITLE
Is it always a good idea to `waitFor*`

### ISSUE THREAD

**Issue by rodoabad** [puppeteer/puppeteer#4546]
Is it always a good idea to always `waitFor*` elements to be visible before you do anything to them?

```
    await page.waitFor('.agree-btn');
    await page.click('.agree-btn');
    await page.waitForNavigation({
        waitUntil: 'networkidle0'
    });
```

The only way for `.agree-btn` to not be visible is if the page did not load.

I find myself always waiting for all the elements I'm about to interact with.

**Comment by aslushnikov** [comment]
> I find myself always waiting for all the elements I'm about to interact with.

@rodoabad it depends on how good do you know and control the website you automate. In many cases, waiting for load is just enough - if you know that this is something that website developers assume. If you don't have any idea, than the more you await preconditions - the more reliable your script is.

Btw you can de-dupe a little your code. Instead of typing the same selector twice, you can re-use the element handle that is returned from `page.waitFor`:

```js
const buttonHandle = await page.waitFor('.agree-btn');
await Promise.all([
  buttonHandle.click(),
  page.waitForNavigation({ waitUntil: 'networkidle0' }),
]);
```

Hope this helps.

**Comment by rodoabad** [comment]
Thanks, @aslushnikov. is the `Promise.all` necessary? In some examples, they are awaiting for navigation first before the click and vice versa. Why do you need to wait for all of them though?

I wanted to await for a click, then await for navigation to happen.

Is the workflow I'm thinking a bad pattern?

In some cases like the one I showed you, it wouldn't click the element even though it's visible and in the DOM if I wait for navigation...and click on the element would actually be a navigation (SPA).

**Comment by rodoabad** [comment]
Thanks for the shorthand too. Puppeteer can be pretty verbose.

Is there any shorthand for this?

```js
    const oktaSignInUsernameInput = '#okta-signin-username';

    await page.waitForSelector(oktaSignInUsernameInput);
    await page.type(oktaSignInUsernameInput, process.env.TEST_USERNAME);
```

This is the pattern we're using as opposed to the one you showed (which is also good).

**Comment by aslushnikov** [comment]
>  is the Promise.all necessary?

@rodoabad the good rule of a thumb is to combine a *watchdog* (`page.waitForNavigation`) and an *action* (`page.click`) with the `Promise.all`. Other patterns might work as well, but this one is bullet-proof and we recommend using it (we explain it in the [`page.click`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-pageclickselector-options) documentation).

> I wanted to await for a click, then await for navigation to happen.

This is racy, because the navigation might be very fast and you'll miss it while awaiting the `page.click`.

> In some cases like the one I showed you, it wouldn't click the element even though it's visible and in the DOM if I wait for navigation

If this happens for you - this is a bug! I'd look into it separately if you have a good repro that I can play with locally. In this case, please file another bug!

> Is there any shorthand for this?

Yeah, [`ElementHandle`]() has typing as well, so you can rewrite this as the following:

```js
const input = await page.waitFor('#okta-signin-username');
await input.type(process.env.TEST_USERNAME);
```

**Comment by rodoabad** [comment]
Thanks, @aslushnikov you've been very helpful. I will try and recreate the problem in a smaller repo since ours is not public.

But to give you some context, it's clicking a search result.

Given a user is searching for another person...
User should be able to click the result and go that person's area.

```js
const userToSearch = 'user';

const searchInput = await page.waitFor('[data-testid="search-input"]');
await searchInput .type(userToSearch);

/*
We wait for the element because the search results section
is not rendered until a search result is found.
*/
const searchResult = await page.waitFor('[data-testid="search-result"]');

await Promise.all([
  page.waitForNavigation({waitUntil: 'networkidle0'}),
  page.click(searchResult)
]);
```

Additional questions here trying to understand. How about the pattern below where the `waitFor` are also included in `Promise.all`. `type` and `click` might resolve first then `waitFor`.

> If you don't have any idea, than the more you await preconditions - the more reliable your script is.

**I guess the actual question is why *waiting for* isn't part of the default behaviour i.e. when I want to type, I'd like to wait for the element if it's available. The same thing goes for when clicking an element.**

```js
const userToSearch = 'user';

const searchInput = '[data-testid="search-input"]';

await Promise.all([
  page.waitFor(searchInput);
  page.type(searchInput , userToSearch);
]);

const searchResult = '[data-testid="search-result"]';

// wait for the element, navigation event, and click event to all finish
await Promise.all([
  page.waitFor(searchResult);
  page.waitForNavigation({waitUntil: 'networkidle0'}),
  page.click(searchResult)
]);
```

> @rodoabad the good rule of a thumb is to combine a watchdog (page.waitForNavigation) and an action (page.click) with the Promise.all. Other patterns might work as well, but this one is bullet-proof and we recommend using it (we explain it in the page.click documentation).

Since we're using `Promise.all`, is there a difference between.

The promise will only resolve if both of them resolves.

> The Promise.all() method returns a single Promise that resolves when all of the promises passed as an iterable have resolved or when the iterable contains no promises. It rejects with the reason of the first promise that rejects.

```js
Promise.all([
  page.waitForNavigation(),
  page.click(element)
]);
```

versus

```js
Promise.all([
  page.click(element),
  page.waitForNavigation()
]);
```
