### ISSUE TITLE
PDF file too large

### ISSUE THREAD

**Issue by tanweia** [puppeteer/puppeteer#458]
The PDF file obtained by HTML conversion is too large. Is there any way to compress it?

**Comment by jsnanigans** [comment]
Hi, if you are using the `page.pdf()` function, you could play with the settings a bit, maybe set the width, scale.
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions

if you just want to compress the pdf I would recomend this:
http://www.alfredklomp.com/programming/shrinkpdf/

**Comment by CaelanStewart** [comment]
@jsnanigans 

I've implemented PDF generation in a web app I'm building, and I'm having the same issue.

There are 28 pages in my case. The images used in the PDF do not repeat, and there are a total of 26 images. The combined filesize of those 26 images is ~12MB.

However, the output PDF from Chrome, at about 28 pages totals ~60MB. That's almost six times the size of the input images!

I gave the solution you suggested a try, however, this actually converted any text or vector graphic that sits atop an image, into an image - a very low resolution one at that, appearing very pixelated when viewed at 100% scale at the same DPI was specified in the command line arguments to the bash script. 

In some places, it actually rasterised text in places located above or below an image. However, there are many pages where text was not rasterised, and remains standard text - even pages that are almost identical to other pages where the text was rasterised.

Do you know why that might be?

**Comment by jsnanigans** [comment]
I'm really not an expert, but I can try to help.
I tried to recreate this, and made a simple html page with only a tiny bit of css and 15 images that were a combined 9.9 MB.
When I generate the pdf with puppeteer its 11MB, which I think is quite acceptable.

Here are a few things I would check:
1. Try to remove the CSS and see if the size changes
2. If you have any JS then disable that and check the size
3. Do the same with custom fonts
4. You could try to render the overlaying [dom text in a canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas), maybe that will help if nothing else does

Let me know how it goes

**Comment by CaelanStewart** [comment]
@jsnanigans 

Thank you for your response!

I cannot remove the JavaScript, because the system uses Vue to define templates in a document.

I have however removed all styles, with the exception of those that define the width/height of pages etc. such that the page count is the same. Also, as this project is time sensitive, I've not had the opportunity to work on a proper solution to isolate the document in the editor screen from the entire application's CSS. So when passed to Puppeteer for rendering, the applications' CSS (inc. Bootstrap, and a global custom font for the application itself) still applied to the document. Now, although the images are not showing at the correct size, some are smaller than they were before (namely any background-images), and some are not visible anymore, there are still a decent number of images, and the filesize came down to just **9.4MB**! So it definitely seems like this is something to do with styles being applied.

On the note of custom fonts, there are two in use for the document, and one custom font for the entire application. In the above test, there was still a custom font applied from the applications stylesheet. So to rule out an issue with the specific custom fonts used in the document, I removed those, and the output filesize remained almost identical, at ~60MB.

So it's definitely being caused by the stylesheets being applied to the document.

Bit unsure as to what could be causing this, could it be a bug with the Chrome render? It just doesn't make sense that it'd be that big because some CSS has been applied.

**Comment by jsnanigans** [comment]
Maybe it has something to do with the way that it translates the css styles into pdf-styling-code.. but I don't know enough about pdfs to even guess what exactly could cause the file-size to go up.

You could try to uncomment styles to find what the cause is and then remove that if you can, or you could use something like [purgecss](https://github.com/FullHuman/purgecss) to remove all the unused css and maybe you'll get lucky and whatever caused the filesize to skyrocket is removed

**Comment by CaelanStewart** [comment]
That's the intention. I'm going to start with the more exotic properties.

And on the point of purgecss, all of the styles specific to the document
have been written specifically for each page. All styles specific to the
document are used.

However, upon removing the document specific styles, and leaving only the
styles used for the application (inc. Bootstrap, and other libraries)  the
file size did go down to a sane level.

So That rules out any unused styles causing it.

And plus I'd expect that the renderer would cycle through each element in
the tree and retrieve some kind of computed style, therefore subsequently
ignore irrelevant styles. So based on that speculation it doesn't make
sense that unused styles would cause this.

Anyway, it's a Friday and I'm tired. I'll give it a go next week.

Thanks very much for the help, it's hugely appreciated.

**Comment by CaelanStewart** [comment]
@jsnanigans 

Hi, I've found the culprit! Sorry I took a while, we decided to neglect the size issue in favour of more pressing concerns.

It was the fact that we used background-images. To allow images of arbitrary aspect ratio in a container of fixed ratio, we used background-size: cover; rather than using object-fit: cover; such that the editor screen would function in IE and earlier versions of Edge without faffing with polyfills.

For whatever reason, Chromium's PDF renderer converts background-images into PNG files and embeds them as such. However, when using the good ol' 'img' tag, images are embedded as JPGs.

After making this change I observed an ~80% reduction in file size (now ~15MB rather than ~70MB). And the rendering process is also considerably faster.

You can see the report I came found here: https://bugs.chromium.org/p/chromium/issues/detail?id=801430

Hope that helps anybody who comes across this thread.

**Comment by jsnanigans** [comment]
@CaelanStewart thats awesome, thanks for letting us know about this strange behavior

**Comment by gabimoncha** [comment]
@jsnanigans @tanweia - I've also seen this problem, but I found a workaround by changing the font-family from an imported one to Arial. I'm not sure if this is the case here also. I've opened an issue #3939 explaining in more detail

**Comment by gavin310** [comment]
Just wanted to add some details on @CaelanStewart 's awesome observation. In his post it kinda sounds like using `object-fit` is a solution, but it's not. Any image that is cropped via CSS will be converted to a PNG as far as I can tell. Since my JPG was coming from a CMS, but needed to be cropped to a certain bounding box in the PDF, here's what I needed to do:

HTML:
`<div class="photo"><img src="myphoto.jpg"></div>`

CSS:
```
.photo { position: relative; overflow: hidden; width: 300px; height: 200px; }
.photo img { position: absolute; width: auto; height: 100%; left: 50%; top: 50%; transform: translate(-50%, -50%); }
```
This uses the parent element to mask the photo and doesn't actually crop the JPG, so it doesn't get converted to a PDF. If your image is a portrait layout you will probably need to change `width: auto; height: 100%;` to `width: 100%; height: auto;`. You could also make a function that determines if it's landscape or portrait and modify the CSS accordingly.

**Comment by CaelanStewart** [comment]
@gavin310 - Great observation. I think we short circuited this unknowingly by adding some custom code that handles `object-fit: cover|contain` by positioning the `<img />` within a container with `overflow: hidden;`. We needed that functionality to work in IE11 so that was the immediate solution.

I think the whole image is kept (and remains JPG) but then in the PDF it is cropped again at render-time, at least that's what I guess since the size issue didn't crop back up. 

Luckily unless you've got really whacky aspect-ratios then there's going to be minimal overhead at most sane counts. (I guess if the PDFs are huge and the overhead is a problem then you could always implement an API that generates hard-crops or use a canvas to generate in-browser).

**Comment by vadimbepro** [comment]
I resolved the issue in my program by removing Google Fonts  from page (fonts.googleapis.com)

**Comment by maxence33** [comment]
I experienced the same in rendering a page where CSS filters brightness, contrast and saturate were applied to an image. I have not properly studied the PDF to know if it was because images were rendered as PNG. But the solution I have found was to recreate my image back end with VIPS using similar modifications as those done with the CSS filters. 
I have made a small repos with those modificators for Ruby Vips : https://github.com/maxence33/ruby-vips-basic-alterations

**Comment by acxvgalanov** [comment]
After some investigation, I think I found the cause of the issue and a workaround:
Chromium engine converts JPEGs to PNGs if the JPEG has EXIF metadata field orientation != 1 (which is the default picture orientation). The resulting PNGs being times larger than the initial JPEGs is what causes the issue.

Here's the workaround I've used for puppeteer:

1. intercept puppeteer request for any image;
2. send our own fetch instead;
3. convert the image to JPEG (I used [sharp](https://www.npmjs.com/package/sharp) lib but I think any would help);
4. rotate the image (rotate w/o params means it uses existing metadata);
5. respond with the rotated image w/o metadata.

```
await page.setRequestInterception(true);
page.on('request', async (req) => {
  if (req.resourceType() !== 'image') {
    req.continue();
    return;
  }
  try {
    const response = await fetch(req.url(), {
      method: req.method(),
      headers: req.headers(),
    });
    const buffer = await response.arrayBuffer();
    const jpeg = await sharp(buffer)
      .jpeg({ mozjpeg: true })
      .rotate()
      .toBuffer();
    req.respond({ body: jpeg });
  } catch {
    req.continue();
  }
});
```

The resulting PDF came down to ~4 MB from being over 25 MB before the fix.
Hope that can be of help.

**Comment by BrancuAlexandru** [comment]
The following is how I fixed a 10x file size increase for a PDF being created out of rendered JSX:

To populate the PDF I was setting some text using dangerouslySetInnerHTML. That's not the issue, the issue is using the html string directly from the parent component. You have to do this:

```
const content = {
  __html: description
}
dangerouslySetInnerHTML={{ ...content }}
```

**Comment by isokosan** [comment]
For anyone coming to this later, I fixed this in not the best way perhaps, but I use graphicmagic to resample the PDF at 300 DPI, and achieved 10x size reduction:
```

function executeCommand (cmd, parameters) {
  const spawnSync = require('child_process').spawnSync
  const result = spawnSync(cmd, parameters, {
    cwd: process.cwd(),
    env: process.env,
    stdio: 'pipe',
    encoding: 'utf-8'
  })
  return !result.stdout && !result.stderr && !result.error
}

const resamplePDF = (source_pdf, output_file, res) => executeCommand('gs', [
  '-sDEVICE=pdfwrite',
  '-dNOPAUSE',
  '-dQUIET',
  '-dBATCH',
  '-dDetectDuplicateImages=true',
  '-dDownsampleColorImages=true',
  '-dDownsampleGrayImages=true',
  '-dDownsampleMonoImages=true',
  `-dColorImageResolution=${res}`,
  `-dGrayImageResolution=${res}`,
  `-dMonoImageResolution=${res}`,
  `-sOutputFile=${output_file}`,
  source_pdf
])
```

Save the pdf in a temp file, resample it then you can do what you like with it and clear the temporary files afterwards.

```
const pdf = await page.pdf(options)
const defaultPdfPath = 'temporary.pdf'
const resampledPdfPath = 'temporary-resampled.pdf'
await fs.writeFile(defaultPdfPath, pdf)
const resampleSuccess = resamplePDF(defaultPdfPath, resampledPdfPath, resample)
const resampledPdf = await fs.readFile(resampledPdfPath)
```

**Comment by ettore-syt** [comment]
@isokosan hey, thank you for posting your solution. 
We are using PDFShift for our conversions. We basically send an html string or point it to a url for large pdfs. 
The size of the received pdf is huge. Sometimes 20 pages can be over 200mb probably due to images and some other stuff mentioned above in this same thread. 

With your solution, we would just have to pass the built pdf through ghostscript?

**Comment by isokosan** [comment]
Yes exactly. I'm not familiar with pdfshift but you would have to download the large file first in a server environment with ghostscript and then do the resampling.

I instead use a puppeteer container myself with ghostscript installed, and made a custom pdf conversion service so the puppeteer generated large pdf does not have to be transferred anywhere.

I will make it publicly available once I get some concurrency issues solved. I'll post here again in a few days.

**Comment by michele-vinciguerra** [comment]
❤️ Thank to all. Saving me week.

**Comment by tkdchamp** [comment]
> @isokosan hey, thank you for posting your solution. We are using PDFShift for our conversions. We basically send an html string or point it to a url for large pdfs. The size of the received pdf is huge. Sometimes 20 pages can be over 200mb probably due to images and some other stuff mentioned above in this same thread.
> 
> With your solution, we would just have to pass the built pdf through ghostscript?

pdfshift probably also takes a lot longer to run due to not handling the images properly as explained in this thread - i recommend switching to pdfmyurl instead to avoid this

**Comment by rockingrohit9639** [comment]
Hi @isokosan  I saw your comment about using Ghostscript to resample the PDF at 300 DPI for a ~10× size reduction.

I’m dealing with a related challenge and wanted to ask for your insight. When I run Ghostscript inside a Docker container, the compression step takes 45–60 seconds, which is too slow for a production workflow.

Have you seen this kind of performance issue when running Ghostscript in containers?
If so, do you have any suggestions, optimizations, or alternatives that could help speed up the process?

Thanks in advance if you have any thoughts

**Comment by isokosan** [comment]
> Hi @isokosan  I saw your comment about using Ghostscript to resample the PDF at 300 DPI for a ~10× size reduction.
> 
> I’m dealing with a related challenge and wanted to ask for your insight. When I run Ghostscript inside a Docker container, the compression step takes 45–60 seconds, which is too slow for a production workflow.
> 
> Have you seen this kind of performance issue when running Ghostscript in containers?
> If so, do you have any suggestions, optimizations, or alternatives that could help speed up the process?
> 
> Thanks in advance if you have any thoughts

Yes, I had to queue these with separate workers, with many page PDFs I could not get around the performance issue.

Another issue I'm facing now is that some printers just won't print the PDF after compression, if you need printable PDFs make sure to test thoroughly.

If you find a solution let me know please!
