### ISSUE TITLE
Cannot change slowMo once puppeteer is launched 

### ISSUE THREAD

**Issue by alessbelli** [puppeteer/puppeteer#4584]
slowMo is very useful as a tool, but some pages have weird race conditions that make it very hard to work _without_ slowMo enabled. That makes it rather brittle for general testing, but still very useful to be able to toggle on a -per-page level or browser-level instead of on Connection.

Is there a good workaround for this, or would you consider this a feature to add to the puppeteer API?

**Comment by aslushnikov** [comment]
> Is there a good workaround for this, or would you consider this a feature to add to the puppeteer API?

@alessbelli I don't think this is a very common usecase, but let me suggest you a workaround.

```js
function enableSlowMo(page, delay) {
  const origin = page._client._onMessage;
  page._client._onMessage = async (...args) => {
    await new Promise(x => setTimeout(x, 250));
    return origin.call(page._client, ...args);
  }
);
```

Hope this helps!

**Comment by alessbelli** [comment]
Thank you, I ended up doing something similar!

**Comment by TomasHubelbauer** [comment]
I'd like to chime in with a suggestion for why this might be useful as a general API: I am using Puppeteer to record an automated testing session and in my use case there is no need for the session to run as fast as possible so I am using a value of `slowMo` which gives the resulting video a comfortable pace.

However, I am also removing ad banners from the page during the session because they cause jumps in the content which makes the video jarring to watch if they are left in (everyone who has browser web on mobile without an ad blocker before can probably relate). I'd like to remove these elements as fast as possible once `waitForSelector` matches them, but leave the rest artificially slowed down to preserve the pace of the video.

For now I'm probably going to explore network-based blocking or something.

**Comment by 17gstyron** [comment]
Here is an updated version of @aslushnikov `s function so solve this.
```javascript
const enableSlowMo = (page, delay) => {
  const origin = page._client()._onMessage
  page._client()._onMessage = async (...args) => {
    await new Promise((x) => setTimeout(x, delay))
    return origin.call(page._client(), ...args)
  }
}
```
