### ISSUE TITLE
keep page open after xhr response error

### ISSUE THREAD

**Issue by hamid07ss** [puppeteer/puppeteer#4602]
* Puppeteer version: 1.17.0
* Platform / OS version: Windows 10
* Node.js version: 10.15.3

I want to check the message on adding a duplicate user. on adding duplicate user, server return http status code 409 and then puppeteer close the page.
**I want to keep the page open, even server returned an http error like 409 (CONFILICT)**

for example after clicking the submit button and on getting screen shot, I got this error:
`protocol error: session closed`
and test failed.

```javascript
await page.click('button[type="submit"]')
await page.screenshot({
  path: "/user/duplicate.png",
  type: "png",
  fullPage: true
});
```

**Comment by aslushnikov** [comment]
> and then puppeteer close the page.

@hamid07ss This might happen because the page crashes. A common reason for page crash is out-of-memory, which might indeed happen given that you take a full page screenshot.

So the recommendations would be:
- either make sure host system has enough RAM to drive Chromium and produce full-page screenshots
- avoid taking screenshots that take too much memory

Hope this helps.

**Comment by hamid07ss** [comment]
puppeteer closes the page and failed the test on any server error.

that's mean on first step page sending an xhr request
now if the http response of this xhr is more than 400 => puppeteer closes the page
