### ISSUE TITLE
puppeteer-firefox is still headless when devtools is true

### ISSUE THREAD

**Issue by StephanBijzitter** [puppeteer/puppeteer#4611]
Not a big bug, just a small inconsistency.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0 (chrome) and 0.5.0 (firefox)
* Platform / OS version: Mac
* URLs (if applicable): N/a
* Node.js version: 8.10.0

**What steps will reproduce the problem?**
```js
const browser = await puppeteer.launch({
    devtools: true
});
```

**What is the expected result?**
The browser opens non-headless, with developer tools available.

**What happens instead?**
While chrome gives the expected result, firefox remains headless.

**Workaround!**
This very small and easy workaround will make the behaviour for firefox and chrome the same:

```js
const browser = await puppeteer.launch({
    devtools: true,
    headless: false
});
```

Granted, firefox's developer tools will not be open, but I assume that's a work in progress anyway (or is simply not possible right now).

**Comment by mjzffr** [comment]
Thanks for the report. I'm closing this issue since the experimental `puppeteer-firefox` package is no longer maintained. A replacement will be available
later this year. You can learn more about Mozilla's work on this at https://wiki.mozilla.org/Remote

See also https://github.com/puppeteer/puppeteer/pull/5137
