### ISSUE TITLE
CSS Coverage doesn't maintain @media queries

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [puppeteer/puppeteer#4633]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.0
* Platform / OS version: macOS 10.14.5
* Node.js version: 11.2.0

**What steps will reproduce the problem?**

If you have a simple html page like:

```
<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <title>Puppeteer Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
        h1 {
            font-size: 10px;
        }
        @media (min-width: 700px) {
            h1 {
                font-size: 22px;
            }
        }
    </style>
</head>
<body>
<h1>Hello</h1>
</body>
</html>
```

Then you use a the following node app to check for CSS coverage:

```
const puppeteer = require('puppeteer');
const util = require('util');
const fs = require("fs");

(async () => {
 const page = await browser.newPage();
 await page.coverage.startCSSCoverage(); 
 await page.goto('http://localhost/puppeteer.php');
  await page.setViewport({
     width  : 320,
     height : 640
 }); // SET MOBILE VIEWPORT
 const css_coverage = await page.coverage.stopCSSCoverage();
 await browser.close();

let final_css_bytes = '';
let total_bytes = 0;
let used_bytes = 0;

for (const entry of css_coverage) {
  final_css_bytes = "";

  total_bytes += entry.text.length;
  for (const range of entry.ranges) {
    used_bytes += range.end - range.start - 1;
    final_css_bytes += entry.text.slice(range.start, range.end) + '\n';
  }

  let url = entry.url.split('?')[0]; // Remove parameters

  filename = url.split('/').pop();

  if(filename === "")
    filename = "root.css";

  fs.writeFile('./'+filename, final_css_bytes, error => {
    if (error) {
      console.log('Error creating file:', error);
    } else {
      console.log('File saved');
    }
  });
}
})();
```

**What is the result?**

The output from your ranges will be:

```
h1 {
    font-size: 10px;
}
h1 {
        font-size: 22px;
    }
```

And not a useable result like:

```
h1 {
    font-size: 10px;
}
@media (min-width: 700px) {
    h1 {
        font-size: 22px;
    }
}
```

**Comment by dariygray** [comment]
The same thing happens in Chrome DevTools

![Image 1](https://user-images.githubusercontent.com/9871980/61162025-4efff300-a50f-11e9-8578-c0ba85f5e652.jpg)

**Comment by aslushnikov** [comment]
This is an upstream bug - re-filed to Chromium repository: https://crbug.com/983887

**Comment by NoteToSelfFindGoodNickname** [comment]
Still not fixed in Canary.

One can work around the problem the following way if you use the json export:

Let's assume the coverage tool exports the following json file:

      {
        "start": 1055,
        "end": 1086
      },

Make sure your CSS is nicely formatted. To do that use CSS beautifier: https://www.freeformatter.com/css-beautifier.html

This tool makes sure that the indents are perfectly right.

Starting from the "start" position 1055 in your CSS file, search backwards for the following string:

ChrW(13) & ChrW(10) & " " & ChrW(13) & ChrW(10)

This is the definite start of the element. 

Do the same from the "end" position: 
Search for ChrW(13) & ChrW(10) & " " & ChrW(13) & ChrW(10), starting from the end position.

This will make sure you will get the code until the very end and not cut off:

![good1](https://user-images.githubusercontent.com/29504639/110173750-5fa95f00-7dff-11eb-9a41-39d70471c8b6.png)

**Comment by noum** [comment]
@NoteToSelfFindGoodNickname Assuming both first and last rule in the @media are marked as used then I can see this work

**Comment by vanushwashere** [comment]
Now I've got the issue when `@media()` string is marked as used but its closing bracket is marked as unused and it breaks the whole generated Critical CSS.
Here is a couple of examples:

![Screenshot_20240614_165719](https://github.com/puppeteer/puppeteer/assets/24995381/842ae41e-0f41-4bd0-baaf-afe635650690)


![Screenshot_20240614_165853](https://github.com/puppeteer/puppeteer/assets/24995381/92ead727-5674-49c8-8b1d-6343789850e0)

I filled a bug in the Chromium: https://issues.chromium.org/issues/347047858
