### ISSUE TITLE
Synchronous versions of page.$ and page.$eval

### ISSUE THREAD

**Issue by akashdsouza** [puppeteer/puppeteer#4640]
**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: macOS High Sierra
* Node.js version: 10.16

**What steps will reproduce the problem?**
This is a feature request

I'm not sure if I should request this somewhere upstream. But, it would be useful to have synchronous versions for page.$, especially, when working with ast tools such as css-tree. There are cases where I would like to check if a css selector is used in the page.

**Comment by aslushnikov** [comment]
For synchronous DOM access, I'd recommend run your code inside web page. You can also hack node.js execution model with native extension like [deasync](https://github.com/abbr/deasync), but I wouldn't recommend doing this.

**Comment by dandv** [comment]
I'm just starting with puppeteer, and also ran into the problem that the vast majority of calls are async. This makes debugging very annoying and time-consuming, because my IDE (WebStorm) can't evaluate `await` expressions.

I'd like to understand, why does `getProperty()` need to be async? Aren't all properties of the node already available? Can it be made synchronous, so mapping links to their hrefs becomes much simpler, i.e. `links.map(l => l.getProperty('href')` ?

The current approach is convoluted enough that someone raised an issue about figuring it out - #4116.
