### ISSUE TITLE
When generating a PDF, intradocument links don't work

### ISSUE THREAD

**Issue by jason-medeiros** [puppeteer/puppeteer#4687]
I'm generating PDF reports using puppeteer, and noticed that intrapage links don't work.

I include a top anchor here:
`<a name="report_top">Top</a>`

then I include a reference link as such:
`<a href="#report_top">Go To Top</a>`

Clicking on the go-to link does nothing.

Is there anything in puppeteer that allows intradocument links?  I need them for report navigation.

**Comment by aslushnikov** [comment]
@jason-medeiros PDF's are generated by Chromium. Chromium PDF team will be happy to help - can you please submit this bug to https://crbug.com/new and file a link here for back-referencing?

**Comment by BrianSHenderson** [comment]
Did you have any success in getting it to work?  I have the same issue here.

**Comment by trondulseth** [comment]
@jason-medeiros did you ever get this to work?

**Comment by johansenja** [comment]
If anyone else is coming to this, it works for me if you turn the relative link into an absolute link ie. instead of `href="#section"` have `href="https://mysite.com/#section"` - your browser will still recognise that it is on the same page, and it will also work in the generated PDF.
Obviously only possible if you own the site! And could be a bit of a hassle to do for every single link, but it's a solution at least
