### ISSUE TITLE
How to solve a CAPTCHA Challenge

### ISSUE THREAD

**Issue by bhavyaagg** [puppeteer/puppeteer#473]
In case of CAPTHA Challenge, i am getting "Please upgrade to a supported browser to get a reCAPTCHA challenge."

![example](https://user-images.githubusercontent.com/20207154/29577170-264e4872-8788-11e7-8b77-5d272b0c2f80.png)

How should we solve the CAPTCHA Challenge?

**Comment by icarusmiles** [comment]
Well you can set a different userAgent, however you may still get prompted to do an actual CAPTCHA, which I have no clue how to automate. The whole purpose of them is to obviously avoid bot access.

**Comment by Garbee** [comment]
As @miles-collier pointed out, you don't automate captcha's. They are put into place specifically to prevent automated access to various resources. If that's a problem for you, you need to disable the captcha in a test environment. If you aren't in control of the site in question, then you're out of luck for automating around them. If captcha's could be automatically bypassed, they wouldn't be effective in doing their task.

**Comment by sandysandeepkumar** [comment]
`<input` aria-invalid="false" class="jss153 jss138" id="lCaptcha" name="captcha" placeholder="49 + 24 =" type="text" value=""> ``

how to handle with puppetter headless chrome

**Comment by Garbee** [comment]
@sandysandeepkumar Please read the previous comments in this thread. They detail why Puppeteer can't help with captchas and how you need to handle them if applicable. If you aren't in control of the site, then there is nothing that can be done. It's up to you to figure out on your own.

**Comment by nicoandmee** [comment]
> @sandysandeepkumar Please read the previous comments in this thread. They detail why Puppeteer can't help with captchas and how you need to handle them if applicable. If you aren't in control of the site, then there is nothing that can be done. It's up to you to figure out on your own.

are you sure? because i can solve all amazon captcha using tesseract/ocr with some degree of error. puppeteer provides all the resources you need to automate captcha solving, both using something like tesseract, and a 3rd party provider like an anticaptcha. i dont think captchas are very effective at stopping bots haha. to the person who posted this, feel free to reach out to me outside of puppeteer repository if you need help!

**Comment by Garbee** [comment]
> because i can solve all amazon captcha using tesseract/ocr with some degree of error. 

Which seems to fall specifically in...

> It's up to you to figure out on your own.

That isn't something puppeteer can or will provide to do for people.

I'm not saying automatically solving them is impossible. I'm simply saying helping bypass them isn't something in the scope of this project.

**Comment by berstend** [comment]
Purely from a technical standpoint I might add that the recaptcha error originally reported here is due to to the lack of out-of-process iframes support (https://github.com/GoogleChrome/puppeteer/issues/2548). 

Puppeteer should definitely not try to aid in captcha solving but thrive to support all kinds of web content on par with regular Chrome. 😄
