### ISSUE TITLE
browser.on('targetcreated') and  browser.on('targetdestroyed') are executed repeatedly

### ISSUE THREAD

**Issue by prprprus** [puppeteer/puppeteer#4757]
#### Environment Information

- Puppeteer version: v1.18.1
- Platform / OS version: macOS 10.14.5
- Node.js version: v11.14.0

#### Reproduce The Problem

1. Run the following code.
```node
const pptr = require('puppeteer');

(async () => {
  // 1. Launch
  const browser = await pptr.launch({
    headless: false,
    devtools: true,
  });
  let page = await browser.newPage();

  // 2. Register browser events
  browser.on('targetcreated', function () {
    console.log('New Tab Created');
  });
  browser.on('targetdestroyed', function () {
    console.log('Tab Close');
  });

  // 3. Goto website
  await page.goto('https://example.com');
})();
```
2. Open a new tab manually, `console.log('New Tab Created');` will be executed twice. Close tab, `console.log('Tab Close');` will also be executed twice.

#### Expected Result

`console.log('New Tab Created');` and `console.log('Tab Close');` are both executed once.

#### What happens instead

`console.log('New Tab Created');` and `console.log('Tab Close');`  are both executed twice.

**Comment by npetzall** [comment]
You should check the target.type before calling it a page.

**Comment by adminbestbet** [comment]
`
await page.evaluateOnNewDocument(() => {
    console.log(123);
})
`

Browser Console printed 3 times 123.


My problem is that the start page loads 3 iframes.

**Comment by npetzall** [comment]
@adminbestbet I guessed that the original issue is related to:
targetcreate, targetdestroyed the function can actually take a target as an argument.
and that a target can have multiple types, it's not always a tab/page -> 
 https://github.com/puppeteer/puppeteer/blob/v1.18.1/docs/api.md#targettype

So actually doing 
```
browser.on('targetcreated', function (target) {
    console.log(target.type + ' was created');
});
browser.on('targetdestroyed', function (target) {
   console.log(target.type + ' was destroyed');
});
```
But it's a while since it had the same issue. So I might be remembering it wrong.

For the evaluteOnNewDocument 
>  whenever the page is navigated
    whenever the child frame is attached or navigated. In this case, the function is invoked in the context of the newly attached frame

So you could check https://github.com/puppeteer/puppeteer/blob/v1.18.1/docs/api.md#pageframes to see how many frames the page has. Since I interpret it as when page is navigated and when frame is attached or navigated. So there might be multiple calls, but with different contexts.

**Comment by prprprus** [comment]
Thank you all for your help, this query is rather old, closed.
