### ISSUE TITLE
Reusing Browser And Page

### ISSUE THREAD

**Issue by SkyHacks** [puppeteer/puppeteer#486]
Is there anything wrong with launching a browser, connecting a new page, and then reusing that page to generate several PDFs over the lifetime of my server process?

I've created a PDF generator module on my server and I would like to just keep puppeteer running all the time instead of constantly tearing down the browser/page.

I'm assuming that if several requests for PDFs come in at once they will just queue up? What about memory usage? 

I've looked for anything I can find about this but haven't found much so far. Any tips are much appreciated!!

**Comment by historylife** [comment]
i think your question is related to myine :)

https://github.com/GoogleChrome/puppeteer/issues/485

**Comment by aslushnikov** [comment]
> Is there anything wrong with launching a browser, connecting a new page, and then reusing that page to generate several PDFs over the lifetime of my server process?

This seems totally legit. 

> I'm assuming that if several requests for PDFs come in at once they will just queue up?

Since you're reusing the page, you'd like every request to navigate page first and generate a pdf next. In case of two concurrent requests, it would be up to your server logic to make sure request handlers don't race with each other.

One common approach would be to use a `chain` promise. E.g. consider the following pseudo-code:

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
let chain = Promise.resolve();
// Request handler 
app.get('/pdf', (req, res) => {
  // Handle request generation in the end of the chain
  chain = chain.then(async () => { 
    await page.goto(req.query.url);
    const pdf = await page.pdf();
    res.send(pdf);
  });
});
```

>  What about memory usage?

I'm unaware of any memory leaks.

**Comment by rohmanhm** [comment]
I more interested in `connect()` method.
But I can't find any related examples.

**Comment by seangwright** [comment]
When I start my express app, the first pdf that gets saved to the file system is always blank. The second pdf is sometimes rendered but without any text content in the dom (just elements and styles). It seems like something isn't ready when the api receives the first few requests, but after those everything is fine.

```
(async function() {
  const express = require("express");
  const puppeteer = require("puppeteer");
  const bodyParser = require("body-parser");
  const cors = require("cors");
  const app = express();

  app.use(cors());
  app.use(bodyParser.json());

  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  let chain = Promise.resolve();
  let counter = 0;

  app.post("/api/send", (req, res, next) => {
    chain = chain.then(async () => {
      await page.setContent(req.body.root);

      const buffer = await page.pdf({
        path: `test-${counter}.pdf`,
        height: "1400px"
      });
      counter++;
      res.send({ success: buffer });
      console.log("sent");
    });
  });

  app.listen(7071);
})();
```

I have a feeling I'm doing something wrong combining async and promises. I'm running node `8.3.0`.

**Comment by jasondonnette** [comment]
@sgwatgit I found that if `setContent` has any images (or anything that requires a network request for whatever reason), I need to run:

```
await page.waitForNavigation({
  waitUntil: 'load',
});
```

after I run `setContent`.

However if there aren't any network requests in `setContent`, the `waitForNavigation ` call hangs indefinitely, so in my case I check to see if there are any images first. I couldn't find anything in the API to handle this, but it seems to work.

Edit: I found that if the page has the image in cache it also hangs (since it loads before it has anything to wait for). It would be great if there was an official api for this, @aslushnikov do you know of a better way to handle waiting for requests from `setContent`?

**Comment by aslushnikov** [comment]
Filed #728 to track the `page.setContent` usecase.

**Comment by BkSouX** [comment]
Thanks @jasondonnette 
It fixed my issue #768 !

**Comment by YAmikep** [comment]
I have a question related to this.
How to reset event listeners on a page?
I tried the following `page.removeAllListeners(['request', 'response']);` but it does not work.

For example:

```
for(...) {
  // Reset event listeners on page
  // ?

  // Add new listeners
  page.on('request', onRequestX);
  page.on('response', onResponseX);

  // Go to url
  await page.goto(urlX);
}
```

Thanks

**Comment by xctest** [comment]
@YAmikep try this: page.removeAllListeners('response'); this works for me
