### ISSUE TITLE
Failed to lauch firefox

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#4874]
On Ubuntu 16

- pupeteer with chrome is fine
- puppeteer with firefox gives me: 

```
const pptrFirefox = require('puppeteer-firefox');
(async () => {
  const browser = await pptrFirefox.launch();
})();

```
Failed to lauch firefox

I tried headless and no headless.
Any idea ?

**Comment by josephsurin** [comment]
Having the same issue on Ubuntu 18.04, even with the `--no-sandbox` argument.

**Comment by mjzffr** [comment]
Thanks for the report. I'm closing this issue since the experimental `puppeteer-firefox` package is no longer maintained. A replacement will be available
later this year. You can learn more about Mozilla's work on this at https://wiki.mozilla.org/Remote

See also https://github.com/puppeteer/puppeteer/pull/5137
