### ISSUE TITLE
await page.$() hangs forever on puppeteer-firefox

### ISSUE THREAD

**Issue by GuillaumeGomez** [puppeteer/puppeteer#4881]
The following code never returns (the element exists):

```js
const x = await page.$("#elem");
```

However, it works perfectly fine on the chrome version of puppeteer.

OS: linux (ubuntu 19.4)
node: v10.15.2
npm: 6.11.2
puppeteer-firefox: cba0f98a2ac7edd3c2bffd0ac53185877403da6b (last commit at the time)

**Comment by GuillaumeGomez** [comment]
Arf sorry, I thought I was on the puppeteer-firefox repository... Reopening the issue there.

**Comment by GuillaumeGomez** [comment]
I am on the good repository actually. Sorry for the noise...

**Comment by mjzffr** [comment]
Thanks for the report. I'm closing this issue since the experimental `puppeteer-firefox` package is no longer maintained. A replacement will be available
later this year. You can learn more about Mozilla's work on this at https://wiki.mozilla.org/Remote

See also https://github.com/puppeteer/puppeteer/pull/5137
