### ISSUE TITLE
Error: Node is either not visible or not an HTMLElement When Element is clearly awaited for and visible 

### ISSUE THREAD

**Issue by switch201** [puppeteer/puppeteer#5022]
I am trying to click a drop down option in the app I am testing but when I attempt to click I get this error message: `Error: Node is either not visible or not an HTMLElement`

I was able to get the text of the element in question by calling
`myElementHandleInstance.getProperty('innerText')`
but for some reason I am unable to click the element. I have waited for the element to become visible on the screen. I even added in a 300 second sleep to make absolutely sure the element was appearing.

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: MAC OS
* URLs (if applicable): N/A
* Node.js version: 9.5.0

**What steps will reproduce the problem?**
I'm not sure as I can't give you access to the site I am testing. But I will try to answer any questions that come up.

_Please include code that reproduces the issue._
Here is a sample of the HTML I am interacting with

```
<select class="jss2373 jss2385" name="state[0] aria-invalid="false">
  <option value="please-choose" selected="">Select a state</option>
  <option value="AL">Alabama</option><option value="AK">Alaska</option>
  <option value="AZ">Arizona</option><option value="AR">Arkansas</option>
  <option value="CA">California</option><option value="CO">Colorado</option>
  <option value="CT">Connecticut</option><option value="DE">Delaware</option>
  <option value="DC">District Of Columbia</option><option value="FL">Florida</option>
  ...
```

This is what my code is doing with this, the frame work this is set up in is a little to complex to get into here, so this is somewhat sudo code:
```
this.browser.click('select[name="state[0]"]') //this clicks the drop down
await this.sleep(300) //long sleep to make absolutely sure the element is on the page
selectionList = this.browser.$('select[name="state[0]"]').$$('option') //this returns an Array of ElementHandles (returns all the option elements)
await selectionList[0].getProperty('innerText') //prints Alabama when console.loged
await selectionList[0].click()  //throws error mentioned in title
```

**What is the expected result?**
The element should be clicked. if I can get text from the element I should be able to click as well

**What happens instead?**
this error gets thrown Error: Node is either not visible or not an HTMLElement

**Comment by ghost** [comment]
We have very similar issue. 
In our case, if dropdown options are rendered offscreen (i may be wrong with terminology here, sorry), you will get this error. Imagine (sorry, i cant post screenshots) you have a long dropdown at the bottom of the page (there's a lot of content and you should scroll to see target dropdown). You click on dropdown, and it have 100 options. Some of them will not be on screen. If you try to `click` for options that are "not visilbe" (they just dont fit) you will get the exception. 
We also have similar cases where we read a placeholder of text input, but visible input width is almost zero (you cant see placeholder, it's truncated, just input element border), due to window size (think like, 100px X 300px with paddings, margins etc. :smile:). You can query it through dev console for example, and you get your value. But puppeteer cant find this node and you get this error. Same thing applies to `puppeteer-core` + custom chromium builds.
We catched that error while we was workin "headfull" and we just randomly tossed window size while puppeteer did his job.

**Comment by Rendez** [comment]
As I posted in S.O. yesterday, I was having a similar issue: https://stackoverflow.com/questions/47014724/click-visible-elements-using-puppeteer/58325214#comment-103008647

In my case, the container div had a `display: none`, and it was 'shown' so `page.waitForSelector('div', { visible: true })` effectively returned true when toggled BUT, it also had some transition cycle so waiting for it to be "displayed" is what worked. I figured a more idiomatic way of checking if an element is displayed and ready to be clicked: waiting for element.hover() to be successful, retrying every second until it is, otherwise throwing.

**Comment by switch201** [comment]
I don't think my case applies to either of the above. in my case the full list is shown on screen and I am waiting long enough to ensure the elements are rendered. I think it has to do with the way Chromium renders certain drop down lists. the way the list looks is different than when I run the test using another framework in straight chrome. I think its an issue specific to chromium.

**Comment by Rendez** [comment]
Curious, have you tried with `puppeteer-firefox` then?

**Comment by switch201** [comment]
@Rendez I have not. isn't that a relatively new feature? I can look into it and try and test using that just to see if there is a difference in behavior. I use TestCafe as well as puppeteer, so when i said I ran the test in another framework thats what I meant. The code used to the execute the tests are the same in either case. the only thing that changes is the underlying engine.

**Comment by ecolss** [comment]
Same issue here.
Any working solutions?

**Comment by amustafa15** [comment]
also having this issue. any updates?

**Comment by t1a2l** [comment]
Any updates?

**Comment by TheWuster935** [comment]
@t1a2l I have this same issue but I found that if I take a screenshot right before I click the element it happens to work. Not sure why since waitForSelector with visible set to true runs without a problem... The issue also disappears if I turn off headless mode with Puppeteer.

**Comment by liweiting** [comment]
also having this issue. any updates?

**Comment by niveinii** [comment]
> @t1a2l I have this same issue but I found that if I take a screenshot right before I click the element it happens to work. Not sure why since waitForSelector with visible set to true runs without a problem... The issue also disappears if I turn off headless mode with Puppeteer.

It can be due to the fact that screenshot takes 1/6 and it is enough time to make your screen fully render:
https://pptr.dev/#?product=Puppeteer&version=v5.3.1&show=api-pagescreenshotoptions
