### ISSUE TITLE
How can I automate the training of pupeteer?

### ISSUE THREAD

**Issue by vyomsrivastava** [puppeteer/puppeteer#5049]
So I want to create a chrome plugin that will capture the user's activity like clicks, keystrokes and that element's XPath on which the click/keystrokes are being recorded.  So it there any Open Source JS library available that can capture all these details?

P.S. Do not suggest [clickly](https://github.com/checkly/puppeteer-recorder) which acts as a puppeteer recorder

**Comment by mathiasbynens** [comment]
cc @benjamingr

**Comment by benjamingr** [comment]
Hey, this is actually really complicated because there are a few fundamental problems in selecting an element well. I am also not sure why puppeteer recorder doesn't work for you for your case.

There are alternatives like Selenium IDE you can consider but they are not really puppeteer or built on the devtools API. 

--- 

If you just need to generate a selector you can use the devtools code for generating a selector (we needed to do this at one point - so we extracted it to a library which you are welcome to use [here](https://github.com/testimio/DOMPath)).

Note that we have quite a lot of code around selecting elements in Testim and then we build locators (matrices of hundreds of selectors) and use machine learning to iterate on those to get good scores between test runs. I can't open source the locator code because it's very related to what Testim does (sadly) :]  

I am going to present generating accessibility annotations automatically using a similar technique at a conference in a few months which you are welcome to use for inspiration.

---

As for actually recording actions - things like drag and drop are actually pretty hard (but there are harder things), you are welcome to check the chromium source for cases where it's documented the debugger doesn't work (the Input namespace goes to `input_injector_PLATFORM` in the source - for example on [mac](https://cs.chromium.org/chromium/src/remoting/host/input_injector_mac.cc?q=input_injector_mac&sq=package:chromium&dr) puppeteer's click does an `CGPostMouseEvent` which doesn't work for a lot of cases.

We literally have tens of thousands of lines of code to record things like "Drag and Drop" correctly and even that isn't perfect. I talk a bit about why automation is hard [here](https://www.youtube.com/watch?v=pGSYpKPjD6I).
