### ISSUE TITLE
How to Turn Off the 'Hold Command-Q to Quit' Warning in Chromium?

### ISSUE THREAD

**Issue by avalanche1** [puppeteer/puppeteer#5088]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20
* Platform / OS version: macos 10.14

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Start puppeteer in `headless: false` mode
2. Press cmd+q

**What is the expected result?**
Chromium exits

**What happens instead?**
Chromium displays  'Hold Command-Q to Quit' Warning

**Comment by benjamingr** [comment]
This isn't actually related to Puppeteer. You would have run into this with ChromeDriver or anything else that does automation and even without any automation:

Here is a hint for a solution, basically:

 - Navigate to a page you control.
 - Open an HTTP server (or other communication channel) on the Node side that you control (so not the CDP)
 - Intercept the command Q in JavaScript (using a keydown handler)
 - Send a request to your node server
 - Kill the browser from puppeteer (using browser.close)

**Comment by avalanche1** [comment]
hmm... sounds very complicated.
don't you know a chromium start arg for that per chance? smth like `--load-extension`

**Comment by benjamingr** [comment]
I would still go with the server as none of this is a public of guaranteed API and as I said this issue is not actually related to puppeteer.

One of the cool things about chromium is the amazing code search and the fact it's open source.

 1. If you go to `cs.chromium.org` you can pretty easily find `confirm_quit_panel_controller` (which contains the Cmd+Q toQuit" window.
 1. You can see there is a [shortcut](https://cs.chromium.org/chromium/src/chrome/browser/ui/cocoa/confirm_quit_panel_controller.mm?type=cs&q=ConfirmQuitPanelController&g=0&l=212-219) usability wise here (double tap) which is fast.
 1. You can see a ComfirmQuitPanelController is obtained by calling `[[ConfirmQuitPanelController sharedController]`) which you can search for.
 1. Doing so gets you [here](https://cs.chromium.org/chromium/src/chrome/browser/app_controller_mac.mm?q=ConfirmQuitPanelController+sharedController&dr=C&l=500-520) where you can find a check at `prefs::kConfirmToQuitEnabled`.
 1. That gets you [the flag name](https://cs.chromium.org/chromium/src/chrome/common/pref_names.cc?q=kConfirmToQuitEnabled&dr=CSs&l=424) which is `"browser.confirm_to_quit"`
 1. You can see in the appearance page (another code search) that this is how chrome itself controls that setting inside [the settings page](chrome://settings/?search=Show+warning+before+quitting+with+%E2%8C%98Q). 

So this depends on what chrome/chromium you're using to run puppeteer but given that you can just edit it by opening the JSON file of the preferences. There is an example (in Ruby but JS should be easy) here: https://github.com/benbalter/dotfiles/blob/master/script/setup/chrome#L26
Note that none of this is actually related to puppeteer and is likely off-topic for this repo :]

**Comment by avalanche1** [comment]
You're awesome!
