### ISSUE TITLE
PDF Prints Blank Pages

### ISSUE THREAD

**Issue by PaulGLujan** [puppeteer/puppeteer#5170]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20
* Platform / OS version: macOS Mojave, Version 10.14.4
* URLs (if applicable):
* Node.js version: v10.15.0

**What steps will reproduce the problem?**
1) Print a multipage HTML file as a multipage PDF.

**What is the expected result?**
1) Print the PDF without additional white pages.

**What happens instead?**
1) For different margin widths, blank pages get added between pages. For example, when the page margins are 7mm a blank sheet is inserted after page 2. When page margins are 7mm, a blank page is inserted after page 5. With no margins, a blank page is added after page 2.

**Comment by kblok** [comment]
Do you have a piece of code to test?

**Comment by deepaktatineni** [comment]
Either use Margins from PDFOptions or set them in custom CSS. Mixing both will lead to unexpected results. 

Try setting `page:break: always` explicitly where you need to break pages. 

`page.$$('selector', page => page.style.pageBreakBefore = 'always')`

**Comment by SharanHundekar** [comment]
any update on this, even i m facing the same problem.

**Comment by akash18m** [comment]
Hello, I am also facing the similar issue. Still not able to find any solution 😢. But, I have been doing research and find out that this issue can be because of [Issue 2278](https://github.com/puppeteer/puppeteer/issues/2278)
<img width="901" alt="Screenshot 2020-04-25 at 2 43 14 AM" src="https://user-images.githubusercontent.com/28988972/80257478-a33f2280-869e-11ea-8098-794a15a756b6.png">
Also as seen in the image, I have created the pdf with `printBackground: true`. There is white-space at bottom and right side of every page. Which is causing very few mm content to render on next page, hence adding a new page for this. If anyone can relate this 2 problems and provide a solution or workaround, it will be very helpful.

**Comment by MatthiasKunnen** [comment]
I have this issue while printing an empty page in A4 format with the following CSS:
```css
body {
    min-height: 29.7cm;
}
```

I fixed it by moving the min-height to `screen` as such:
```css
@media screen {
    body {
        min-height: 29.7cm;
    }
}
```
