### ISSUE TITLE
Feature request: Connect to remote running Pupeteer via local browser

### ISSUE THREAD

**Issue by thernstig** [puppeteer/puppeteer#5227]
As an example, TestCafe has this implementation: https://devexpress.github.io/testcafe/documentation/recipes/test-on-remote-computers-and-mobile-devices.html

Imagine you are developing on a remote VM via ssh. VS Code Remote supports such a case. Now imagine you start Pupeteer on the remote VM, but you want to view the test in a headfull (i.e. non headless) browser. This is exactly what TestCafe support, and it would be cool if there was a way to do this with Pupeteer as well.

**Comment by jsbarrett** [comment]
I was also wanting this kind of functionality ... though I don't know if it's in the scope of the puppeteer project or not.
But I found something that kind of works.

If you have X11 forwarding enabled in your ssh connection, you can actually get a peak as to what the browser is doing on the remote machine.
It's laggy and not a perfect solution. But I have found it to be better than nothing when I really need to see what's happening.

I actually did it by accident in another project and realized I could apply it to my puppeteer needs.

**Comment by stangerjm** [comment]
I would like this too. My use-case is that I have a project setup on a remote workspace and I would like to be able to attach to my local browser.

Currently I do something similar to what @jsbarrett does where I have X11 forwarding enabled so that I can see what is going on, but it is quite laggy and not an ideal solution. 

It would be awesome if there was some way to be able to run tests on a remote workspace and attach to a local browser.

**Comment by acosonic** [comment]
This would actually be a very good feature. 

Use-case scenario that I needed was to connect to instance on server, without having to install GUI on server.

I had to run in headless false mode, in order to visually inspect why is there something wrong while running same code on server and dev machine.

(Tunrs out it was just server's IP being blocked for some reason, and thus waitForFunction didn't yield result)...

But to findout that I had to install a lot of software on server in order to run GUI on it...
