### ISSUE TITLE
Page loading issue when setRequestInterception set to true

### ISSUE THREAD

**Issue by abdulbasitjs** [puppeteer/puppeteer#5292]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: macOS Mojave 10.14.6
* URLs (if applicable):  http://remote.hrhcare.org/
* Node.js version: 10.16.0

**What steps will reproduce the problem?**
Run the following code:

```
const puppeteer = require('puppeteer');
async function doScreenCapture(url, site_name) {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();
   
    await page.setRequestInterception(true);
    page.on('request', interceptedRequest => {
        interceptedRequest.continue();
    });

    await page.goto(url, { waitUntil: 'networkidle2', timeout: 30000 });
    await page.screenshot({
        fullPage: true,
        path: `${site_name}.png`
    });
    await browser.close();
}

doScreenCapture('http://remote.hrhcare.org/', 'test1');
```

**What is the expected result?**

It should load the page. Further, I have added the following argument  **'--enable-features=NetworkService'** but unfortunately no luck. 

**What happens instead?**
Page doesn't load. Page hangs due to the setRequestInterception method. Any suggestion?

**Comment by kblok** [comment]
The problem is with the `RDWAStrings.xml` inside the `Site.xsl` file 
![image](https://user-images.githubusercontent.com/2198466/72188744-d3a5ce00-33d9-11ea-900c-917b228198e9.png)

puppeteer is not receiving the `Network.requestWillBeSent` event for that file and that's why it's getting stuck.

I'm getting a mime warning on that file, but I don't know if that causing the issue.

![image](https://user-images.githubusercontent.com/2198466/72188831-0a7be400-33da-11ea-82da-7b8e62f5dfe1.png)

Knowing that, I know this is **SUPER** hacky, but a workaround would be listening to the `Fetch.requestPaused` event, as puppeteer does, and unlocking that request manually.

```js
page._client.on('Fetch.requestPaused', e => {
    if(e.request.url.includes("RDWAStrings.xml")) {
      page._client.send('Fetch.continueRequest', {
        requestId: e.requestId
      });
    }
  });
```

I know... I know... but this works...

**Comment by abdulbasitjs** [comment]
Thank you @kblok for the detailed answer. it is really helpful. 
**Appreciated**
