### ISSUE TITLE
Screenshot with fullPage option is not working correctly for this site

### ISSUE THREAD

**Issue by Rana-xD** [puppeteer/puppeteer#5318]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: Mac
* URLs (if applicable): https://recruit.jackall.co.jp/
* Node.js version: 10.15.0

**What steps will reproduce the problem?**

I try to screenshot that site with fullPage option. But, It only capture the top part. Beside that, it only contain white area or blank area. Below is my code

 `let browser = await puppeteer.launch({`
       ` defaultViewport: {`
            `width:1900,`
            `height:1080`
         ` }`
   ` });`
    `let page = await browser.newPage();`
    `await page.goto('https://recruit.jackall.co.jp/',{ waitUntil: "networkidle0" });`
    `await page.screenshot({ path: 'issue-4212.png', fullPage: true});`
    `await browser.close();`

 May I know what is the correct way to screenshot that type of website? I'm really appreciate your help.

**What is the expected result?**
https://pu-ai-bc.s3-ap-southeast-1.amazonaws.com/uploads/screenshot-recruit.jackall.co.jp-2020.01.17-17_13_17.png

**What happens instead?**
https://pu-ai-bc.s3-ap-southeast-1.amazonaws.com/uploads/issue-4212.png

**Comment by kblok** [comment]
Shouldn't you wait a little bit more? or wait for some selector to know that the page is ready?

**Comment by timparker183** [comment]
waiting isn't the issue... I'm up against the same thing with 2.0.0 - I wrote up a novel here:
https://github.com/puppeteer/puppeteer/issues/5300

a recent change has the resulting image clipped to the viewport.  If the target page doesn't have any handlers on the 'resize' event, you can get the actual rendered size (after the page settles) and reset the viewport to the actual size - you're still hosed if the page is really long (i.e. the resulting image is greater than about 11 megapixels), but if it's not too huge... that should do the trick..   check the code fragments in #5300 for more details

**Comment by Rana-xD** [comment]
@timparker183 
What is the alternative solution? Should I downgrade puppeteer version or should I try to find the optimal code to handle that kind of site?

**Comment by timparker183** [comment]
That's a difficult decision with many factors to consider.  In general, I don't like going backward, but sometimes we don't have a choice.  I don't know what other constraints you have, so I can't say what your best option is.  I have explored moving to earlier Puppeteer releases, but I quickly get into trouble because most earlier Chromium builds don't run on the current AWS Lambda platforms (Node 10 or Node 12).  If your environment allows use of earlier versions, it's probably worth a try - if for no other reason than to clearly identify where the breaking changes occurred.
