### ISSUE TITLE
page.screenshot clip not working correctly, fullPage is ok

### ISSUE THREAD

**Issue by minzojian** [puppeteer/puppeteer#5410]
i have 2 pages content, and try to capture into 2 PNGs
![image](https://user-images.githubusercontent.com/361781/74232326-87fd8180-4d03-11ea-9aa3-ec722893739c.png)  
when i set fullPage,it works fine  
however, when i try to set clip:{x:0,y:1000,width:1000,height:1000} and going to capture the second page, i got a empty content. that's wired. even i try to set clip clip:{x:0,y:0,width:2000,height:2000}  and going to capture a whole content area, i still got only the first page content, what happen?
![image](https://user-images.githubusercontent.com/361781/74233460-aa909a00-4d05-11ea-9372-1afdf8d570b9.png)

**Comment by minzojian** [comment]
same problem like this post https://github.com/puppeteer/puppeteer/issues/5300

**Comment by ibrahimalthomali** [comment]
I wounder if clipping is based on available image after screenshot is taken. So it may be the image is lets say 100x100 and you try to clip a region outside this region at X and Y > 100. While fullPage image is larger??? Not sure but i am guessing here. 

I have an issue with fullPage changing the actual viewport size and therefore elements are not where expected. See my issue [#5411](https://github.com/puppeteer/puppeteer/issues/5411). I wounder if you or anyone else found the same?

**Comment by caramdache** [comment]
I have the same issue, `clip` is not working. Unless I'm mistaken, the `clip` parameter is ignored by the `screenshotCapture` function:

```
clip = {x: 0, y: 0, width: deviceMetrics.width, height: deviceMetrics.height, scale: 1};
```

https://github.com/ChromeDevTools/devtools-frontend/blob/f5d825ac1bb6eca13782947e30e5c5c78b9de1f0/front_end/emulation/DeviceModeModel.js#L736

**Comment by luminous8** [comment]
I just updated from puppeteer 1.XX to puppeteer 5.00 and realised that the clip function doesn't work as before. It'll always take the viewport height unless we set the viewport height to the content height. But this doesn't work in some cases.

I've been using the clip function for at least 2 years and never got any issue. Now I can't update to the latests releases because of this.

Does someone found and alternative solution to take fullsize screenshot with the clip function?

**Comment by lpolito** [comment]
> I just updated from puppeteer 1.XX to puppeteer 5.00 and realised that the clip function doesn't work as before.

Literally just made the same jump and having the same problem.

All of our automated screenshot tests took screenshots bound by a clip selector. Previously setting `clip` would allow screenshot to take an image of whatever was inside the bounds of clip, regardless of what the viewport was set to. If a portion of the clip was outside of the viewport, the screenshot was still complete.

Now it looks like the viewport size is limiting what the screenshot can take, even if a clip is specified.

To get around this, we set an arbitrarily high `defaultViewport` `height` (in my case 10000px just to be safe) so that any screenshot we take aren't affected by the viewport size. I hope this helps anyone else having the same issue.

edit: And realizing now this doesn't fix all cases, of course, but it's workable.
