### ISSUE TITLE
Headless chromium hogs too much (over 10GB) memory when exporting huge tabular reports to PDF

### ISSUE THREAD

**Issue by charIeszhao** [puppeteer/puppeteer#5416]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: RHEL 7.x
* URLs (if applicable):
* Node.js version: 10.16.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Prepare a huge tabular report data that consists of more than 50000 rows and 12 columns, in json format.
2. Dynamically generate the table in html template with the data above, within a single browser tab
3. Export tabular report page to PDF

**What is the expected result?**
PDF should be exported successfully, with affordable CPU and memory resources.

**What happens instead?**
I have a server with more than 10GB free memory and 4GB swap space, and when rendering a tabular report as big as 50000+ rows and 12 cols, the CPU usage is 100% and also chromium takes all the available memory & swap space, then crashed because of insufficient resource.

I understand the data size is too big and this might even be a chromium issue instead of puppeteer, but I would like to know if there is any way to mitigate the problem.

Thanks!

**Comment by koolkishan** [comment]
Were you able to fix that issue ? If yes please share the solution.

**Comment by wdelmas** [comment]
The root cause is Chromium's rendering pipeline. When you generate PDFs with 15k+ rows, Chrome builds the entire DOM, layouts everything, then rasterizes to PDF. Each step holds memory that can't be garbage collected until completion.

**What worked for me:**

1. **Pagination server-side** — Split into 1k-row chunks, generate multiple PDFs, merge with `pdf-lib`
2. **Streaming approach** — For tables, render page-by-page using `page.pdf()` with specific page ranges
3. **Memory flags** — Add `--single-process` and limit `--js-flags="--max-old-space-size=4096"`

If you're hitting this in production at scale, I eventually moved to a dedicated PDF API service. The infrastructure overhead of keeping Puppeteer stable (memory, Chrome updates breaking things, cold starts) wasn't worth it for my use case.
