### ISSUE TITLE
Puppeteer take blank screen shot after 4 to 5 elements

### ISSUE THREAD

**Issue by rashidaurangzeb** [puppeteer/puppeteer#5427]
When I run puppeteer on elements it will take blank screen shot after 4 to 5 elements. Example code is 

await page
        .goto('xyz.com', {
            waitUntil: 'load',
})
const __hrefs = await page.$x("//a[contains(@href,'http')]");
let a=0;
for (const i of __hrefs) {
await i.screenshot({
path: a+'.jpg'
})
} 

I am using node version 13.

**Comment by klendathu667** [comment]
I am having the same issue with puppeteer taking blank white screenshots.    

Setup: 
Puppeteer : 13.5.1 
Jest: 25.1.0 
Environment (local, Windows 10, Node 6.0)  
(Gitlab, same versions puppeteer 13.5.1, jest 25.1.0, node 6.0) 


I have Puppeteer tests that run against a web service. I have it setup so that if a test fails, it takes a screenshot.  Those screenshots are always turning up as blank white screens.  I have tried using both png and jpeg options, fullpage false or true, doesn't make any difference.     It successfully takes the screenshot , it's just they are all blank. 

Example code: 
if (currentTest.failedExpectations.length != 0) {
    try {
      // console.log(this.currentTest);
      console.log(currentTest);
      console.log(currentTest.failedExpectations);
      let pagesLoc = await global.driver.pages();

      for (let pageForScreenshot of pagesLoc) {
        let pageTitle = await pageForScreenshot.title();
        let now = new moment();
        let time = now.format("MM_Do_YY_h_mm_ss_a");
        let screenshotPath = `${process.cwd() +
          path.sep}${currentTest.fullName + pageTitle + time}.png`;
        console.log(screenshotPath);
        await pageForScreenshot.screenshot({
          path: screenshotPath,
          type: 'png',
          fullPage: true,
        });
