### ISSUE TITLE
Please add section in troubleshooting for "Running Puppeteer on Google Cloud Build"

### ISSUE THREAD

**Issue by scifihotchoc** [puppeteer/puppeteer#5469]
I am struggling to get puppeteer installed and working on Google Cloud Build.  I get the following error after installing puppeteer using 'npm i puppeteer' and try to use it:

[ ERROR ]  Failed to launch chrome!
Step #2:            /workspace/mysrc/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome:
Step #2:            error while loading shared libraries: libX11-xcb.so.1: cannot open
Step #2:            shared object file: No such file or directory

Having read [this post](https://github.com/puppeteer/puppeteer/issues/3443), I try to install dependencies with an Ubuntu step and get errors with every single package with errors such as " Unable to locate package ..." or "Couldn't find any package by regex ..."

It would really help if there was a comprehensive guide on how to get puppeteer working on Google Cloud Build since this seems to be extremely hard.

**Comment by stefl** [comment]
I've also struggled with this, so sharing some of what I've found following these instructions to set up a Docker image using this repo: https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/yarn-puppeteer

This resolves the issue you have posted above @scifihotchoc.

However, it then introduces a further problem about not being able to connect to the Websocket to communicate with the Puppeteer instance.

The Docker image seems to give you a Puppeteer@2.0.0 instance, which appears to then spawn a bundled Chromium.

My use case is to generate Critical CSS for my website build pipeline, so I'm using the "Critical" NPM package, which in turn depends on Penthouse, with Puppeteer pinned to @1.15.0

The Docker image installs on Google Cloud Build, but when I attempt to generate Critical CSS (which works on my local machine), I must specify the path to the binary that the Docker image includes. 

```
browser = await puppeteer.launch({
  executablePath: "/usr/bin/chromium-browser",
    args: ['--disable-gpu', '--no-sandbox', '--disable-dev-shm-usage'],
    headless: true
});
```

You can then pass the Puppeteer instance to Critical:

```
if(browser) {
  criticalConfig['penthouse'] = {
    puppeteer: {
      getBrowser: () => browser,
    },
    keepLargerMediaQueries: true
  }
```

When Critical runs, it fails with "Error: WebSocket is not open: readyState 3 (CLOSED)". Debugging, I can see that a process is created because I get it's PID, but I'm unable to connect to it.

I suspect the problem here is the version mismatch between the dependencies and the version of Chromium that is bundled with the Docker container.

Some information on handling these kinds of problems when deploying Puppeteer under Google Cloud Build would be extremely helpful! I can imagine that once we know how to get this running, CI processes using Puppet on Cloud Build would be very helpful indeed.
