### ISSUE TITLE
Chrome crashes without any error reporting when run on windows 10 shared drives

### ISSUE THREAD

**Issue by valyrie97** [puppeteer/puppeteer#5483]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: Windows 10
* URLs (if applicable): N/A
* Node.js version: 12.13.0

**What steps will reproduce the problem?**

This requires 2 windows 10 computer (server/client)

- Have a windows 10 local network shared drive (Server)
- from another computer (Client), map the location to a drive letter
- still on the client, install puppeteer to the shared drive; then run:
```
require('puppeteer').launch({headless: false})
```

**What is the expected result?**

Puppeteer to work as it normally would, launch a blank page headed

**What happens instead?**

Each page crashes instantly, and appears to only generate a timeout error eventually (I might be missing an event, I'm unsure!) 

Here is a screenshot of what it looks like in action

![image](https://user-images.githubusercontent.com/6365746/76143080-01a63800-6042-11ea-8f14-a26669e90380.png)

Edit: more clear phrasing

**Comment by 0length** [comment]
I have the same problem.. My puppetter application is installed on mount point dir to another drive..

**Comment by alex-drocks** [comment]
Same problem here. On a private office local network, it opens the browser real quick and immediately shuts down without error messages. After 30seconds the timeout is exceeded and the process it terminated. This only happens when executing from within a local network disk. If I copy paste the same project on a drive that is not in the network, it works instantly.
