### ISSUE TITLE
LocalStorage is missing in userdataDir when using headless mode

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#5612]
* Puppeteer version: 2.1.1
* Platform / OS version: Ubuntu

When Chromium will be launched in headless mode `Local Storage` will be missing in profile folder.
When Chromium will be launched in headfull mode `Local Storage` presents and contain data.

What am I doing wrong?

**Comment by schelkun** [comment]
So headless profile includes:
`blob_storage  Cache  Code Cache  Cookies  Cookies-journal  File System  QuotaManager  QuotaManager-journal  Session Storage`

But where is `Local Storage`?

**Comment by schelkun** [comment]
Please note, this is **not** https://github.com/puppeteer/puppeteer/issues/1268 related!
My profile dir is empty before headless launch.

**Comment by Manc** [comment]
I've just started playing with Puppeteer 8.0.0 on macOS and also find that localStorage is not being restored, neither in headless nor headful.

```js
const browser = await puppeteer.launch({
	headless: false,
	userDataDir: './user_data',
});
```

The web page I load stores Cookies, IndexedDB and Local Storage. Both Cookies and IndexedDB will be restored when I run my script again later, but `window.localStorage` will be empty.

**Comment by ihorml** [comment]
I have the same issue on fresh puppeteer: `puppeteer@^23.7.1:`  
headless:true/false doesn't matter 

I try just to launch some page in headless:false, set `localStorage.setItem` and set cookies using devtools. After that I interrupt the script and re-launch it again (holy shit, typing that I realized what the bug is!) 

## Solution
So, the issue is that puppeteer DOESN'T SAVE LocalStorage when you interrupt script (cmd/ctrl+C or close by your hands in headless=false). If to use "browser.close()" - the localStorage save/recovery feature works pretty good 

@Manc @schelkun 4 years late - the solution found :D
