### ISSUE TITLE
Manual browser revision not used, used package.json instead 

### ISSUE THREAD

**Issue by manuman94** [puppeteer/puppeteer#5617]
Currently my webdriver was updated and only supports Chrome 81 version. As I'm using the Puppeteer chromium binary, I checked that is still using Chrome v80, the revision comes from package.json.

I saw that I can change the binary download revision using environment variables or npm config, and it works perfectly. But the fact is that the launcher is always using the previous revision as it gets it through package.json, see this lines:

https://github.com/puppeteer/puppeteer/blob/7a2a41f2087b07e8ef1feaf3881bdcc3fd4922ca/src/Puppeteer.js#L63

It would be great if Puppeteer handle the revision in install.js storing it if it comes from environment variable or npm config to use it then in Puppeteer.js without changing package.json.

Greetings.

**Comment by mathiasbynens** [comment]
Pass the `executablePath` option to `puppeteer.launch`. See https://github.com/puppeteer/puppeteer/blob/v2.1.1/docs/api.md#puppeteerlaunchoptions.

**Comment by manuman94** [comment]
This does not solves the problem. 

The fact is that Puppeteer handles his own Chromium download on googleapis. As a developer I don't think I have the need to know in which route downloads it, I think this should be done automatically inside Puppeteer, as it knows the path in which will be stored.

The ideal behaviour should be: if developer specified a revision, Puppeteer downloads that revision and stores its executable path to use it.

**Comment by mathiasbynens** [comment]
> The ideal behaviour should be: if developer specified a revision, Puppeteer downloads that revision and stores its executable path to use it.

Currently Puppeteer is tied to a given Chrome revision. It's possible to use it with other Chromium versions but we cannot offer any guarantees about support or stability in those cases, and so it doesn't make sense for Puppeteer to provide a first-class API for using arbitrary revisions as it can easily lead to breakage. 

Download the revision yourself, and then use `executablePath`.

**Comment by manuman94** [comment]
Currently Puppeteer allows specifying a custom revision and downloads it for you. I don't know why you don't want to end that process as it doesn't make sense by itself.

**Comment by rikkiprince** [comment]
I think there's some miscommunication going on here. This has also broken the build of some of our tests.

The question here, @mathiasbynens is, Why does Puppeteer not download the same version of Chromium that matches the version of chromedriver being used by Puppeteer?

If it is tied to a given Chrome revision as you say, why does it fail to run because the chromedriver is set wrong?

**Comment by rikkiprince** [comment]
Ok, it turns out our issue was because Protractor and its dependency `webdriver-manager` automatically updated to Chrome 81.

Are Puppeteer and Protractor used together a lot? If so, is there a best practice way of synchronising the version of chromium Puppeteer provides and the version of webdriver-manager Protractor uses?

**Comment by manuman94** [comment]
Hi! Sorry, I couldn't reply until today. Yes, I'm using Protractor and that was the issue.

It's a nice way to bring my e2e tests to my CI system since I don't have to manage the Chrome version in Gitlab, I can use Puppeteer version.

The only way I found to make the Chrome version match is forcing the revision in Puppeteer.

Thanks!

**Comment by ajspera** [comment]
We've also run into this problem a couple times. Just wanted to drop a note in response to @mathiasbynens that this issue is not an arbitrary revision, it is the latest version. As @rikkiprince mentioned protractor keeps it up to date while puppeteer does not do so at the same pace causing the mismatch. For the guys using this just in CI testing, our immediate solution was to go back to installing chrome through ci container scripts and removing puppeteer.
