### ISSUE TITLE
Puppeteer V3. Reference firefox executable in karma configuration

### ISSUE THREAD

**Issue by mpalourdio** [puppeteer/puppeteer#5679]
Hello,

As of puppeteer v3, the npm package `puppeteer-firefox` in not recommended anymore. I just cannot figure what is the upgrade path to replace a karma configuration like below without including `puppeteer-firefox` in my dependencies.

```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html
const process = require('process');
process.env.CHROMIUM_BIN = require('puppeteer').executablePath();
process.env.FIREFOX_BIN = require('puppeteer-firefox').executablePath();

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-firefox-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, './coverage/bjorkfr'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromiumHeadless', 'FirefoxHeadless'],
    customLaunchers: {
      FirefoxHeadless: {
        base: 'Firefox',
        flags: ['-headless'],
      },
    },
    singleRun: false,
    browserNoActivityTimeout: 100000
  });
};
```

Please note the  `FIREFOX_BIN` env var export. What is the recommended way with V3 ? Any upgrade path documented ?

Thanks by advance.

**Comment by mjzffr** [comment]
You may continue using puppeteer-firefox for now, despite the deprecation warning. Firefox support in puppeteer is still experimental so the way Firefox executable is managed by puppeteer may still change.

I'm not familiar with Karma but at a glance it seems like you can have have just one `BROWSER_BIN` set to `puppeteer.executablePath()`, and then when that config file is used in an environment where `PUPPETEER_PRODUCT=firefox` is set, Puppeteer will launch Firefox instead of Chrome. Just a guess...

**Comment by mpalourdio** [comment]
Karma can run tests in different browsers **in parallel**. That's why it's interesting to reference both executable paths in its configuration before the run. Setting the `PUPPETEER_PRODUCT` as env var does not solve the problem I think.

What I imagine, is having in pupetteer the possibility to reference both executable like this
```javascript
const chrome = require('puppeteer').chromeExecutable();
const firefox = require('puppeteer').firefoxExectuable();
```

**Comment by mjzffr** [comment]
You don't necessarily need `PUPPETEER_PRODUCT`.

Puppeteer has different Launcher classes for Firefox and Chrome, and an internal state for which launcher is being used. To use puppeteer v3 for both Firefox and Chrome, I think Karma should create two Puppeteer instances and call `launch` on each with the appropriate `product` option. How much control do you have over how Karma launches browsers? Perhaps you need to file an issue there.

Another thing to consider is how Karma installs Puppeteer as a dependency, since Firefox isn't fetched by Puppeteer by default. (Eventually I expect Puppeteer will download all browsers during its install step, but we're not there yet.)

For the executable path bit, either call `executablePath()` on the corresponding Puppeteer instance if you can, or you could also create a BrowserFetcher for each product and get path via `revisionInfo`. You can see an example of this in the Puppeteer install script: https://github.com/puppeteer/puppeteer/blob/master/install.js#L40

Let us know how that goes...

**Comment by mpalourdio** [comment]
Thanks for your valuable feedback. Just to be clear, karma does not install puppeteer as a dependency. Karma just runs tests with the browsers available on the host it runs, if it finds them in the system PATH, it will run tests on them. That's why using karma with puppeteer is very convenient when you run tests on an host where you're not root.

That's why overriding environment variables when running with pupetteer is mandatory in `karma.conf.js`, so it can override the browsers already installed (for example if they are outdated, or whatever reason)

**Comment by whimboo** [comment]
@mpalourdio can you please re-check with the most recent Puppeteer release? Does that work better?

**Comment by mpalourdio** [comment]
@whimboo I can give it a try. But regarding the changelog from v3.0.0, I can't figure if pupepeteer now downloads a full firefox executable that I can reference with something like 
```javascript
const firefox = require('puppeteer').firefoxExectuable();
```

Or does it ?

**Comment by jkroepke** [comment]
Yes, but the path is wrong. `require('puppeteer').executablePath()` give always `latest` back but on fs its `79.0a1`.

```
jkr@joe-nb Downloads % PUPPETEER_PRODUCT=firefox npm i puppeteer

> puppeteer@3.3.0 install /Users/jkr/Downloads/node_modules/puppeteer
> node install.js

Requesting latest Firefox Nightly version from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central
Downloading Firefox Nightly r79.0a1 - 78.2 Mb [====================] 100% 0.0s
Firefox Nightly (79.0a1) downloaded to /Users/jkr/Downloads/node_modules/puppeteer/.local-firefox/mac-79.0a1
npm WARN saveError ENOENT: no such file or directory, open '/Users/jkr/Downloads/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/jkr/Downloads/package.json'
npm WARN Downloads No description
npm WARN Downloads No repository field.
npm WARN Downloads No README data
npm WARN Downloads No license field.

+ puppeteer@3.3.0
updated 1 package and audited 71 packages in 24.51s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

jkr@joe-nb Downloads % PUPPETEER_PRODUCT=firefox node -e "console.log(require('puppeteer').executablePath());"
/Users/jkr/Downloads/node_modules/puppeteer/.local-firefox/mac-latest/Firefox Nightly.app/Contents/MacOS/firefox
jkr@joe-nb Downloads % ls -lah "/Users/jkr/Downloads/node_modules/puppeteer/.local-firefox/mac-latest/Firefox Nightly.app/Contents/MacOS/firefox"
ls: /Users/jkr/Downloads/node_modules/puppeteer/.local-firefox/mac-latest/Firefox Nightly.app/Contents/MacOS/firefox: No such file or directory
jkr@joe-nb Downloads % ls -lah "/Users/jkr/Downloads/node_modules/puppeteer/.local-firefox/"
total 0
drwxr-xr-x   3 jkr  staff    96B Jun  2 17:08 .
drwxr-xr-x  12 jkr  staff   384B Jun  2 17:08 ..
drwxr-xr-x   3 jkr  staff    96B Jun  2 17:08 mac-79.0a1
```

**Comment by mjzffr** [comment]
Yes, the path is wrong unless you call `Puppeteer.launch` first, because
that is what resets the launcher class to match the requested product. A
refactoring of the Puppeteer class, Puppeteer's install script and other
infra plumbing is needed to properly support multiple browsers.

**Comment by whimboo** [comment]
@mpalourdio is everything working for you meanwhile with a more recent release of Puppeteer?

**Comment by mpalourdio** [comment]
Yep thanks, closing now !
