### ISSUE TITLE
I want to be a contributors, what skills I have to learn?

### ISSUE THREAD

**Issue by micilini** [puppeteer/puppeteer#5848]
Hi everyone, i found the development of this project quite interesting, but I don't know which skills are important for me to become a contributor, I believe that many things can be improved.

Do I need to learn C ++? What languages?

**Comment by katlegoalpha** [comment]
kindly follow this link https://github.com/firstcontributions/first-contributions

**Comment by FalkF** [comment]
This project uses mainly JavaScript and Typescript. I guess it would be best to start learning a little JS right after you checked the link above. Basic knowledge about browsers (e.g. DOM or HTML) will help as well.
Also feel free to always post an issue for your idea so that you can discuss it with others and get help or ideas. If you mention that you want to work on it yourself usually nobody will steal the issue from you. But you can still ask more experienced devs where to start or what the rough steps are that you need to take.

**Comment by micilini** [comment]
I understand @FalkF ... I check the code and found many Javascript and Typescript files, I think that code works like an API that communicates with chrome headless. 

As a user of this library (puppetter) I could see that under the hood, Chorme is executed, and with that we use this API called puppeteer to communicate with it.

As a user, I noticed some memory problems that could be fixed, and from my analysis of this code, I may have to make modifications directly in chrome and not in the APIs.

In that case I will have to know C ++, right? since it looks like chrome headless was written on it, right?

And another, can anyone tell me if the chrome that is running together with this library (puppeteer) is open source (I can modify it, as well as I can do in this library)?

**Comment by munrocket** [comment]
Probably you should become a chromium contributor. It’s opensource project.

**Comment by jackfranklin** [comment]
Hi @micilini ,

As @FalkF mentioned, this project is largely TypeScript and JS now. Chromium is indeed open source and you can find out more about that here: https://www.chromium.org/Home.

If you do have any features you'd like to implement feel free to raise an issue so we can discuss them.
