### ISSUE TITLE
Gmail login issue - couldn't sign you in with automation browser

### ISSUE THREAD

**Issue by fahadshehzada** [puppeteer/puppeteer#5855]
Hi,
When I try to login from my gmail account and entering email address and click next, it says

![image](https://user-images.githubusercontent.com/61680750/81785836-3fc74880-9518-11ea-822a-b49c48bb24e5.png)

I also tried to ignore automation tag, also tried setting user-agent but no resolution and I got still here. I'm automating using puppeteer with chromium browser.

   const browser = await puppeteer.launch(
                {
                    headless: false,
                    ignoreDefaultArgs: ["--enable-automation"]
                }
            )

            const page = await browser.newPage()

**Comment by bozdoz** [comment]
I hit this before and needed to manually create a new page, and login.  Using a userDataDir, I was able to persist cookies so that next time I ran the script this error didn't occur.  Hope that helps.  Short answer on stackoverflow: https://stackoverflow.com/questions/59514049/unable-to-sign-into-google-with-selenium-automation-because-of-this-browser-or/61545042#61545042

**Comment by sghofrany** [comment]
@bozdoz I tried manually creating a new page and logging in but I still get the same error. And the link you provided is for selenium.

**Comment by bozdoz** [comment]
Yeah I responded to a Selenium post, but the solution for me was the same.  Curious how you got the same error.  I think I tried this solution a few times and it worked every time.

**Comment by sghofrany** [comment]
I think I figured out the issue. I believe Google flags certain accounts if there are too many login attempts.

**Comment by Siva-RK-L** [comment]
I am also facing the same issue, I tried even re-installing browser and even used new mail id. No luck
