### ISSUE TITLE
The documentation does not explain what a 'Target' is

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#5880]
The Puppeteer API documentation lists a type called a 'Target', but does not explain what it is and how it relates to BrowserContexts/Pages/Frames/etc. In particular it is missing from the diagram in the Overview, and there is no explanation of its lifecycle - e.g. you can use `page.target()` to get a target related to a page, but how long does it live for? If you `page.goto()` another URL, do you need to fetch a new Target? etc

**Comment by jribbens** [comment]
Not stale

**Comment by jribbens** [comment]
Not stale

**Comment by OrKoN** [comment]
Target is a CDP-specific concept that I think should not be directly exposed to the end-users but it unfortunately was. There is some documentation here https://github.com/aslushnikov/getting-started-with-cdp/blob/master/README.md#targets--sessions but, generally, I think we should try to deprecate the target API instead of documenting it better.

**Comment by jribbens** [comment]
Presumably there would still be some way of getting a CDP connection?
