### ISSUE TITLE
Page not shown when starting with puppeteer

### ISSUE THREAD

**Issue by T0BiD** [puppeteer/puppeteer#5913]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.1.0
* Platform / OS version: Win 10
* URLs (if applicable): https://www.ebay-kleinanzeigen.de/m-einloggen.html
* Node.js version: 13.9

**What steps will reproduce the problem?**

~~~~
(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();

    page.goto('https://www.ebay-kleinanzeigen.de/m-einloggen.html');
})();
~~~~

**What is the expected result?**
The expected result is that the website is shown. It works in Chrome, Firefox and everywhere else. It even works when I'm using chromium.

**What happens instead?**
Blank page. I checked the headers, but nothing really stood out.

When I start chromium with puppeteer and navigate to the site by myself, it still doesn't work. 

Edit: It seems to be a chromium thing.. I started chromium normally and it worked, but when I started chromium with the flag remote-debugging-port=21222 it didnt.

Is there a way for a webpage to actually see if the browser is openend that way?

**Comment by yss14** [comment]
@T0BiD I'm stuck with the same problem. Did you solve it?

**Comment by ghost** [comment]
@T0BiD @yss14 Seems like something is preventing the website to be shown. I tried it in Chrome with the same results as you guys got. The Webpage was blank and I could't interact with the Elements. For my Project it wasn't necessary to see the Webpage at all but would have been good for debugging. So then I tried puppeteer-firefox, although it is deprecated because I got the strange feeling it had something to do with Chrome. With Firefox it got it working. Page didn't load for some reason but I was able to interact with the Elements. Basically I was able to login.
