### ISSUE TITLE
Failed to install puppeteer

### ISSUE THREAD

**Issue by giovcastillo** [puppeteer/puppeteer#5949]
https://github.com/puppeteer/puppeteer/blob/b874cacaef22fed40efb140741942555a8de55f4/install.js#L175

Well, this is my first GitHub account but I really wanted to report this error,
```js
} catch(error) { // it should be like this, otherwise it throws exception
```

**Comment by vsemozhetbyt** [comment]
This is optional catch binding, see: https://2ality.com/2017/08/optional-catch-binding.html
It is supported [since Node.js 10](https://node.green/#ES2019-misc-optional-catch-binding), and current puppeteer versions [require Node.js 10 or more](https://github.com/puppeteer/puppeteer#usage). So you need to upgrade the Node.js so that the issue can be fixed.
