### ISSUE TITLE
Cannot install the dependencies on Cloud9

### ISSUE THREAD

**Issue by IonicaBizau** [puppeteer/puppeteer#5978]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: Latest
* Platform / OS version: Probably CentOS, on Cloud9

**What steps will reproduce the problem?**

```sh
ec2-user:~/environment (master) $ sh sudo yum install alsa-lib.x86_64 atk.x86_64 cups-libs.x86_64 GConf2.x86_64 gtk3.x86_64 ipa-gothic-fonts libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXrandr.x86_64 libXScrnSaver.x86_64 libXtst.x86_64 pango.x86_64 xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-fonts-cyrillic xorg-x11-fonts-misc xorg-x11-fonts-Type1 xorg-x11-utils -y 
Loaded plugins: priorities, update-motd, upgrade-helper
1073 packages excluded due to repository priority protections
Package alsa-lib-1.0.22-3.9.amzn1.x86_64 already installed and latest version
No package atk.x86_64 available.
Package 1:cups-libs-1.4.2-67.21.amzn1.x86_64 already installed and latest version
No package GConf2.x86_64 available.
No package gtk3.x86_64 available.
Package ipa-gothic-fonts-003.02-4.2.2.amzn1.noarch already installed and latest version
Package libXcomposite-0.4.3-4.6.amzn1.x86_64 already installed and latest version
Package libXcursor-1.1.14-2.1.10.amzn1.x86_64 already installed and latest version
Package libXdamage-1.1.3-4.7.amzn1.x86_64 already installed and latest version
Package libXext-1.3.2-2.1.10.amzn1.x86_64 already installed and latest version
Package libXi-1.7.2-2.2.9.amzn1.x86_64 already installed and latest version
Package libXrandr-1.4.1-2.1.8.amzn1.x86_64 already installed and latest version
No package libXScrnSaver.x86_64 available.
Package libXtst-1.2.2-2.1.9.amzn1.x86_64 already installed and latest version
Package pango-1.28.1-10.11.amzn1.x86_64 already installed and latest version
Package xorg-x11-fonts-100dpi-7.2-9.1.5.amzn1.noarch already installed and latest version
Package xorg-x11-fonts-75dpi-7.2-9.1.5.amzn1.noarch already installed and latest version
Package xorg-x11-fonts-cyrillic-7.2-9.1.5.amzn1.noarch already installed and latest version
Package xorg-x11-fonts-misc-7.2-9.1.5.amzn1.noarch already installed and latest version
Package xorg-x11-fonts-Type1-7.2-9.1.5.amzn1.noarch already installed and latest version
Package xorg-x11-utils-7.5-6.7.amzn1.x86_64 already installed and latest version
Nothing to do
```

Some of the packages that are required, are simply not found in the environment.

**What happens instead?**
Puppeteer does not load on Cloud9 due to missing dependencies.

**Comment by pala-sh** [comment]
Installing puppeteer to an EC2 can be a little different. There is another problem which hasn't been addressed.

To answer your question you don't have to worry about downloading Chromium separately as `npm i puppeteer` would take care of downloading the Chromium that's compatible with puppeteer and take care of the rest.

However, the more troublesome issue that you will run into is to make sure that the required dependencies are installed on the EC2 in order to run Puppeteer. These dependencies differ between distributions(CentOS, Ubuntu/Debian etc...).

Follow these steps,

Install all the dependencies required. You can refer this link for the list, https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
After all the dependencies are installed, install npm and configure proxy in .npmrc if you are behind a VPC/proxy.
Then as usual go ahead with npm i puppeteer and proceed as always
Let me know if this works and reach out to me if you have any doubts.

**Comment by IonicaBizau** [comment]
Some of the dependencies are not found, as I already mentioned. It simply says that “Package x was not found.”
