### ISSUE TITLE
Error: Protocol error (Page.navigate): Cannot navigate to invalid URL

### ISSUE THREAD

**Issue by xiaoqiao112** [puppeteer/puppeteer#6002]
Jump to local template page for screenshot error reporting，Do you know how to deal with it？

**Comment by mgifford** [comment]
Mostly linking together issues here:
https://github.com/puppeteer/puppeteer/issues/594#issuecomment-325935296
https://github.com/puppeteer/puppeteer/issues/5475
https://github.com/puppeteer/puppeteer/issues/4780

For me though the problem was actually that I'd been blocked by their network.  Apparently even though i was crawling a client's site, my IP got identified and 

```
Access Denied
You don't have permission to access "http://www.example.com/" on this server.
Reference #18.ca2b11fve648.1623430415.53485fb
```

Nothing a VPN can't solve though.

**Comment by tquangvinh** [comment]
I have the same problem and no solution yet
