### ISSUE TITLE
Issue with event handlers test in FF

### ISSUE THREAD

**Issue by jackfranklin** [puppeteer/puppeteer#6020]
In the PR that landed Mitt I added a spec to ensure that event handlers get cleaned up and re-added correctly. This passes locally for me in Chromium and FF, but on CI it always fails on FF. I have skipped the test which you can find here: https://github.com/puppeteer/puppeteer/blob/master/test/page.spec.js#L134

I'm not sure why it fails or what the root cause is unfortunately, but @whimboo or @mjzffr would you mind taking a look when you get a chance? Happy to try to help out if I can.

Thanks!

**Comment by whimboo** [comment]
@jackfranklin can you please give a link to such a job in CI? I would like to see the  exact failure and maybe stack.

**Comment by jackfranklin** [comment]
@whimboo sure, here's an example: https://travis-ci.com/github/puppeteer/puppeteer/jobs/349067290

**Comment by whimboo** [comment]
@jackfranklin would you mind running the tests in CI with the Firefox preference `remote.log.level=trace` set?

**Comment by whimboo** [comment]
The tests in question are [`removing and adding event handlers`](https://github.com/puppeteer/puppeteer/blob/9f9b4ed72ab0bb43d002a0024122d6f5eab231aa/test/page.spec.ts#L125-L159).

There is https://bugzilla.mozilla.org/show_bug.cgi?id=1673104 which covers this specific problem.

**Comment by juliandescottes** [comment]
As discussed on #8204 this issue affects both Firefox and Chrome headful, and comes from a request to favicon.ico.
This request seems skipped entirely with Chrome headless, which is why it didn't show up on CI so far.

We want to fix this by either avoiding the requests to favicon for those tests, or ignoring the favicon.ico responses in the assertions.
