### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by glutamate** [puppeteer/puppeteer#6048]
### Steps to reproduce

click a link anywhere on the Internet to puppeteer documentation. e.g. in forums, puppeteers own docs, readmes. For instance, just a small example, any of the links to docs in https://www.npmjs.com/package/puppeteer-core e.g. https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core

**Tell us about your environment:**

Not relevant

**What steps will reproduce the problem?**

1. visit https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core

**What is the expected result?**

I should see the documentation linked

**What happens instead?**

I see the github 404 page

**Comment by GalileoCap** [comment]
The url is wrong, it should say "main" instead of "master". Here's a working url:
https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteer-vs-puppeteer-core

**Comment by avighub** [comment]
> The url is wrong, it should say "main" instead of "master". Here's a working url:
> https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteer-vs-puppeteer-core

It worked for me too...
I was trying below URL which was not working
https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions

It worked when I replaced with **main**

Thank you.

**Comment by ghost** [comment]
Everyone - this is just one of thousands of projects to have hundreds of thousands of broken links because of Github's ill-thought, illogical reactionary nonsense to rename "master" to "main". Yes, really: https://news.ycombinator.com/item?id=23500093
PLEASE keep the pressure on Github to re-think this.
Email, annoy, tweet every day until they revoke, or at least alias the branches, because stuff like this is causing thousands of wasted hours each day.

**Comment by glutamate** [comment]
this is now fixed
