### ISSUE TITLE
Could I help you guys to translate the API`s doc into chinese?

### ISSUE THREAD

**Issue by Aaronphy** [puppeteer/puppeteer#608]
I`d love to do these .  And I used to use 'webdriver.io'

**Comment by ebidel** [comment]
Nice, we'd love help with that! But since the API and docs are still in a state of flux, I'm wondering if we should wait a bit? Eventually we plan to have a proper documentation page/site for 1.0.

**Comment by aslushnikov** [comment]
@Aaronphy We discussed this with @pavelfeldman and @paulirish. We won't be able to maintain chinese translation as a part of this repository because english docs change rapidly and translation would be constantly outdated.

However, if you host the translation on your own website and will take care of it, we'll be happy to refer to it from our docs!

**Comment by Aaronphy** [comment]
@ebidel @aslushnikov  I will have a try to take care of it .

**Comment by aslushnikov** [comment]
Thanks @Aaronphy. Reach back to us when you're ready so that we can refer to your translation.
