### ISSUE TITLE
Link to troubleshooting broken since `main` branch change

### ISSUE THREAD

**Issue by Georgegriff** [puppeteer/puppeteer#6082]
![image](https://user-images.githubusercontent.com/9056958/85394666-c96e2b00-b546-11ea-99fe-4c85bd09e59e.png)

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by mathiasbynens** [comment]
Since this is already fixed in the source (https://github.com/puppeteer/puppeteer/blob/fdc6fda46eca945f837d70f2457378c3b1a045ea/src/node/BrowserRunner.ts#L227), this will be fixed with the next release. We _could_ set up a `master` branch as a mirror of `main` until then, but I'd rather not, since it'd complicate PRs (people might still have an old checkout that sends PRs to master). Instead, let's just publish a patch release asap. @jackfranklin @hanselfmu @OrKoN WDYT?

**Comment by jackfranklin** [comment]
We need to be careful here not to publish `main` as is as there's breaking changes due to go out as `v5`. There's no reason not to publish v5 this week (the breaking changes are very minor).

Or we could branch from the `v4` tag and ship `4.0.1` that just fixes this link. What do you prefer?

**Comment by mathiasbynens** [comment]
I was thinking of branching from v4 and shipping v4.0.1, but if we can commit to publishing v5 this week let's do that instead.

**Comment by jackfranklin** [comment]
Thinking about it, if we want v5 to include our own type defs, we might be pushing it to rush that out this week with other things going on, so v4.0.1 is probably the safest option. No real need to rush a major release out.

**Comment by jackfranklin** [comment]
This is now fixed in v4.0.1.
