### ISSUE TITLE
Response is Null when Navigating to a PDF

### ISSUE THREAD

**Issue by floydtagle** [puppeteer/puppeteer#610]
When navigating to a PDF in headless mode the Response is Null. What Im trying to do is download the loaded pdf page and save it locally. Bellow is my code.. Thanks.

```js
const puppeteer = require('puppeteer');

(async () => {
const browser = await puppeteer.launch({headless:true});
const page = await browser.newPage();
const response = await page.goto('http://www.africau.edu/images/default/sample.pdf', {waitUntil: 'networkidle'});
console.log(response);
browser.close();
})();
```

**Comment by floydtagle** [comment]
hi, is there any solution to achieve this using puppeteer? The pdf Im trying to download is build on the fly, so its quite difficult to use Http Request and pass all the needed cookies or parameter to download the pdf. I try to catch it using the page request and response but still no luck on it. please I really need help on this. Thanks a lot!

**Comment by aslushnikov** [comment]
@floydtagle this works fine in non-headless mode, so looks like a bug in headless. I filed upstream bug: [crbug.com/761295](https://bugs.chromium.org/p/chromium/issues/detail?id=761295)

**Comment by floydtagle** [comment]
@aslushnikov Thank you so much, but my deployment is on linux server so I really need this functionality.. no choice I need to wait until this bug is fix.. Thank you so much again..

**Comment by floydtagle** [comment]
Hi @aslushnikov  using non-headless do you have any suggestion or idea on how to save locally the pdf? Thanks a lot.

**Comment by aslushnikov** [comment]
@floydtagle that's under development; see #299

**Comment by floydtagle** [comment]
@aslushnikov Thanks! 
 about [this..](https://bugs.chromium.org/p/chromium/issues/detail?id=761295), does it mean, that you cannot navigate to pdf in headless chrome? or what? Thanks!

**Comment by aslushnikov** [comment]
@floydtagle yes, chrome headless doesn't know how to navigate to PDFs. You can use [pdf.js](https://mozilla.github.io/pdf.js/) to render PDF if there's a need to.

**Comment by xprudhomme** [comment]
I have a working solution..(spent half a day understanding what was going on).

My idea was to use the Fetch API, then use the arrayBuffer or blob response type in order to send the result back to an exposed function, which in turn would write the data to a file.

But obviously, the page.exposeFunction() method serializes the exposed function parameters using JSON.stringify, meaning we cannot pass data such as ArrayBuffers or Blobs (these type would be destroyed). 

Using the Fetch API DOMString response type (string) did not work either, for some reason the string was somehow altered (its encoding I think) when passed into the exposed function.

Eventually, I decided to fetch the PDF data as an ArrayBuffer, convert the ArrayBuffer to a string in UTF-8 encoding, pass that UTF-8 string into the exposed function, and then compute the reverse method on the other side: the exposed function convert the UTF-8 string back to an ArrayBuffer, which can be used to write the data in a file on the user file system.

Some bits of my code here:

```javascript
page.exposeFunction("writeABString", async (strbuf, targetFile) => {

        const str2ab = function _str2ab(str) { // Convert a UTF-8 String to an ArrayBuffer

            let buf = new ArrayBuffer(str.length); // 1 byte for each char
            let bufView = new Uint8Array(buf);

            for (let i=0, strLen=str.length; i < strLen; i++) {
              bufView[i] = str.charCodeAt(i);
            }
            return buf;
        }

        return new Promise((resolve, reject) => {
        
            // Convert the ArrayBuffer string back to an ArrayBufffer, which in turn is converted to a Buffer
            let buf = Buffer.from(str2ab(strbuf));
            
            // Try saving the file.        
            fs.writeFile(targetFile, buf, (err, text) => {
                if(err) reject(err);
                else resolve(targetFile);
            });
        });
    });
```

And then, from within an evaluate call, you would have the following :

```javascript
page.evaluate( async () => { 

    function arrayBufferToString(buffer){ // Convert an ArrayBuffer to an UTF-8 String

        let bufView = new Uint8Array(buffer);
        let length = bufView.length;
        let result = '';
        let addition = Math.pow(2,8)-1;

        for(let i = 0;i<length;i+=addition){
            if(i + addition > length){
                addition = length - i;
            }
            result += String.fromCharCode.apply(null, bufView.subarray(i,i+addition));
        }
        return result;
    }

   let geturl = "https://whateverurl.example.com";
    
   return fetch(geturl, {
       credentials: 'same-origin', // usefull when we are logged into a website and want to send cookies
       responseType: 'arraybuffer', // get response as an ArrayBuffer
   })
   .then(response => response.arrayBuffer())
   .then( (arrayBuffer) => {
       let bufstring = arrayBufferToString(arrayBuffer);
       return window.writeABString(bufstring, '/tmp/downloadtest.pdf');
   })
   .catch( (error) => {
       console.log('Request failed: ', error);
   }); 
 });
```



The PDF file is eventually well downloaded and saved at the /tmp/downloadtest.pdf location :)

**Comment by gombosg** [comment]
@Xavatar this worked nicely, thanks! Please edit your comment above because the `page.evaluate()` line is missing. (see your comment in [this thread](https://github.com/GoogleChrome/puppeteer/issues/299#issuecomment-340199753))

Also, I had to start Chrome with `--disable-web-security` to disable CORS and be able to fetch from other domains (sometimes necessary).

**Comment by xprudhomme** [comment]
@gombosg : Thanks for pointing this out, I've fixed it, and also added JS highlighting!
