### ISSUE TITLE
Clicking on an element in an iframe fails

### ISSUE THREAD

**Issue by krlwlfrt** [puppeteer/puppeteer#618]
`page.click(selector)` does not click an element in a frame of the page.

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError [ERR_ASSERTION]: No node found for selector: SELECTOR
```

How is it possible to click the element? Getting the frame that contains the element and doing `frame.click(selector)` does not work.

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: frame.click is not a function
```

**Comment by paulirish** [comment]
I looked into this and it turns out there's a bug you didn't yet run into that would have stopped you dead in your tracks. :) I'll add the details to this ticket since it basically breaks clicking correctly inside a frame.

repro script:

```js
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({headless: false, slowMo: 250});
const page = await browser.newPage();
await page.goto('https://www.w3schools.com/TAgs/tryit.asp?filename=tryhtml_button_test');

const frames = await page.frames();
const tryItFrame = frames.find(f => f.name() === 'iframeResult');
const framedButton = await tryItFrame.$('button');

const outerHTML = await framedButton.evaluate(e => e.parentNode.outerHTML);
console.log('the outerhtml: ', outerHTML); // to verify we're talking about the right element.. (we are.)

framedButton.click();
})();
```

Basically on this page we want to click the "Click me!" button. However a click is dispatched on top of the banner ad at the top of the page causing a new tab to open.

![image](https://user-images.githubusercontent.com/39191/29886462-00bf1108-8d6f-11e7-9a00-6afc2147ce1f.png)


It appears that when `elhandle.click()` is called, pptr gets the boundingclientrect and then dispatches an input event to the coordinates.

**However this doesnt account for an iframe that's not at 0,0 of the page's viewport.** Puppeteer needs to handle the viewport position of the iframe.

Here's the debug log showing this back and forth:

![image](https://user-images.githubusercontent.com/39191/29886418-d566d540-8d6e-11e7-9cb3-dec39265c85c.png)

(FWIW i gathered this log with `env DEBUG="*" env DEBUG_COLORS=true node examples/click-button-in-frame.js 2>&1 | grep -v Network`)

**Comment by aslushnikov** [comment]
Ah, indeed! #445 will solve this

**Comment by SMJ93** [comment]
@aslushnikov any update on this? We are still not able to interact with elements inside an iframe.

**Comment by Lumersgo** [comment]
any update ?  I also met this problem , because My app needs to use third party login script which includes a frame . Sadless.

**Comment by aslushnikov** [comment]
Fixed with https://github.com/GoogleChrome/puppeteer/pull/971

**Comment by krlwlfrt** [comment]
Thank you very much! Which release will contain this fix?

**Comment by albertkim** [comment]
Eagerly awaiting this as well, our application needs to interact with a couple iframes, so this is the only issue preventing us from being able to do full end-to-end testing.

**Comment by fran0254** [comment]
Have you solved the problems of frames? I need help, we have all the projects stopped

**Comment by aslushnikov** [comment]
This should be working fine in version [0.12.0](https://github.com/GoogleChrome/puppeteer/releases/tag/v0.12.0)

This is actually a dupe of #684

**Comment by entrptaher** [comment]
This clicks the element properly,

```js
const puppeteer = require('puppeteer');
(async() => {
    const browser = await puppeteer.launch({
        headless: false,
        slowMo: 250
    });
    const page = await browser.newPage();
    await page.goto('https://www.w3schools.com/TAgs/tryit.asp?filename=tryhtml_button_test', {
        waituntil: "networkidle0"
    });
    const frame = await page.frames().find(f => f.name() === 'iframeResult');
    const button = await frame.$('button');
    button.click();
})();
```
