### ISSUE TITLE
Question: Manipulate PDF document properties at generation time

### ISSUE THREAD

**Issue by maxgram** [puppeteer/puppeteer#6284]
Hello, maybe someone knows if it is possible to manipulate PDF properties at generation time? For example, each PDF file has Security tab (cmd+d in Adobe Reader) in properties that allow to enable/disable Printing, Content copying, etc (please refer to screenshot below). In addition, it would be great to be able to set "Two page view" programatically so whenever user opens generated PDF it already has preselected view for them. I might be missing something, but could not find how to provide those settings to Puppeteer and would be very thankful if someone could help to figure this out. If it is not possible at the moment, advice on where is the best place to start adding this functionality would be also highly appreciated
![image](https://user-images.githubusercontent.com/10034857/88611546-3d748500-d057-11ea-8195-d387ba838c0b.png)

**Comment by mathiasbynens** [comment]
This is not currently possible with Puppeteer. If you want to go and implement this, you could propose a patch adding options corresponding to these settings to [the CDP `Page.printToPDF` command](https://source.chromium.org/chromium/chromium/src/+/master:headless/lib/browser/protocol/page_handler.cc;l=43-144;drc=d5fead7f7f100aa003eca1b7908cd3a31171c792).

Closing this issue for now since we don't have plans to work on this.
