### ISSUE TITLE
Getting freform text from a div

### ISSUE THREAD

**Issue by ballfam** [puppeteer/puppeteer#6300]
I'm trying to extract the text from a site that looks like this:

       <div class="u-vr4x">

       "
      <br>
     The U pups came to us full of fleas and ticks. These guys were a mess. They are so sweet now and so soft mouthed. I'm calling 
      them retriever mixes because of their soft mouth. They are very sweet and get along very well with each other. I'm sure that 
      they will make any family a great pet. Going to be about 70 to 75 lbs.<br>
      <br>
      <br>
       "
          </div>

But for the life of me, I can't get querySelector to grab anything. I tried something like this:

`
const result = await page.evaluate(
      () => Array.from(
        document.querySelectorAll('.u-vr4x'))
     console.log(result);
`

And it gives me this:

`[
  {}, {}, {}, {}, {}, {}, {}, {},
  {}, {}, {}, {}, {}, {}, {}, {},
  {}, {}, {}, {}, {}, {}, {}, {}
]`

There are 24 occurrences of that class, so they were all found, but it looks like they are empty (which they are not). Anyone know if it is possible to extract the contents of the text inside them?

**Comment by vsemozhetbyt** [comment]
puppeteer can transfer two types of data between Node.js and browser context: serializable data (i.e. data that is supported by `JSON.stringify()`/`JSON.parse()`) and JavaScript object ids (including DOM elements) — `JSHandle` and `ElementHandle`. Later ones have a bit more complicated API (see `JSHandle` and `ElementHandle` methods or methods that mention them).

`page.evaluate()` can only transfer serializable data, and instead of un-serializable data, it returns undefined or empty objects. DOM elements are non-serializable as they contain circular references and methods.

So if you just need some text or element attributes, try to do most of the processing in the browser context and return just serializable data.

```js
const result = await page.evaluate(() => Array.from(
  document.querySelectorAll('.u-vr4x'),
  element => element.innerText
);
console.log(result);
```

**Comment by ballfam** [comment]
Yup, innterText did the trick, Thanks.

Sorry, I'm new to Java Script; after decades or writing C, this is a totally different universe.
