### ISSUE TITLE
emulateMediaFeatures does not work on firefox

### ISSUE THREAD

**Issue by LarsDenBakker** [puppeteer/puppeteer#6323]
`emulateMediaFeatures` does not work on Firefox, it throws an error:

```
Error: Protocol error (Emulation.setEmulatedMedia): Emulation.setEmulatedMedia RemoteAgentError@chrome://remote/content/Error.jsm:25:5
UnknownMethodError@chrome://remote/content/Error.jsm:108:7
execute@chrome://remote/content/domains/DomainCache.jsm:96:13
receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:86:45
```

In playwright it is possible to set the color scheme media query. Look at their code, they set `colorScheme` as a property: https://github.com/microsoft/playwright/blob/master/src/firefox/ffPage.ts#L298 instead of an array of features in puppeteer: https://github.com/puppeteer/puppeteer/blob/main/src/common/Page.ts#L1429

I looked into making a PR for this, but in the code I don't see any branching between browser types. Is there a policy on how differences between chromium and firefox should be handled?

**Comment by mjzffr** [comment]
Thanks for looking into making a PR. The Playwright approach doesn't apply here, since the Playwright team maintain a _fork_ of Firefox with their own custom protocol: https://github.com/microsoft/playwright/blob/master/browser_patches/firefox/juggler/protocol/PageHandler.js#L178

The protocol implementation in actual Firefox doesn't include `Emulation.setEmulatedMedia` yet. The tracking bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1549434 Please feel free to [get in touch](https://wiki.mozilla.org/Remote) about your use case; it can help us prioritize. Or you can submit a patch to Firefox, of course. :)

**Comment by LarsDenBakker** [comment]
@mjzffr thanks for the clarification! I'll close this issue then since it's already tracked elsewhere.
