### ISSUE TITLE
puppeteer-firefox Not Loading Extensions

### ISSUE THREAD

**Issue by ProfessorManhattan** [puppeteer/puppeteer#6355]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: Ubuntu 20.04
* Node.js version:12.18.3

**What steps will reproduce the problem?**

Install puppeteer-firefox and open Firefox with browser.open({headless: false})

**What is the expected result?**

Extensions installed on Firefox should load

**What happens instead?**

When I open Firefox with firefox-puppeteer, the extensions I installed are missing. I realize Firefox is bundled with puppeteer-firefox but I need to access the locally installed Firefox with the extensions loaded. Is there a way to use the locally installed Firefox instead of the bundled version?

**Comment by mjzffr** [comment]
`puppeteer-firefox` has to talk to its own (very old) bundled Firefox because it uses a custom protocol that official Firefox binaries don't support. I suggest you try using `puppeteer` rather than `puppeteer-firefox`, and then you can automate official Firefox binaries. See [PUPPETEER_PRODUCT](https://pptr.dev/#?product=Puppeteer&version=v5.2.1&show=api-environment-variables) for more info.

As for extensions, I think you can get your extensions by providing a specific Firefox profile ("user data dir" in Chrome parlance). What I would do is create a fresh profile (go to about:profiles in Firefox), install the extensions you want and then provide the profile directory in your Puppeteer options.

**Comment by ProfessorManhattan** [comment]
For anyone trying to accomplish this, I ended up using https://github.com/cyfrost/install-gnome-extensions
