### ISSUE TITLE
Empty document object

### ISSUE THREAD

**Issue by anuragphadke** [puppeteer/puppeteer#6370]
**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: Mac
* URLs (if applicable): https://news.ycombinator.com
* Node.js version: 14.xx

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
const iPhone = puppeteer.devices['Pixel 2 XL'];

async function start(canonical_url) {
  const browserURL = 'http://127.0.0.1:9222';
  const browser = await puppeteer.connect({browserURL});

  const page = await browser.newPage();
  await page.emulate(iPhone);
  await page.goto(canonical_url, {
    waitUntil: 'networkidle2',
  });

  const data = await page.evaluate(() => document.documentElement);
  console.log(data);
}

```
**What is the expected result?**
entire document object

**What happens instead?**
{}

Wondering why I am not able to get access to the entire document object and why it returns {}

**Comment by vsemozhetbyt** [comment]
puppeteer can transfer two types of data between Node.js and browser context: serializable data (i.e. data that is supported by `JSON.stringify()`/`JSON.parse()`) and JavaScript object ids (including DOM elements) — JSHandle and ElementHandle. Later ones have a bit more complicated API (see JSHandle and ElementHandle methods or methods that mention them).

`page.evaluate()` can only transfer serializable data, and instead of un-serializable data, it returns `undefined` or empty objects. DOM elements are non-serializable as they contain circular references and methods.

So if you just need some text or element attributes, try to do most of the processing in the browser context and return just serializable data.

**Comment by anuragphadke** [comment]
@vsemozhetbyt : thx for the pointers. Would it be possible to use chrome devtools protocol to get this data? 
I can access `document.documentElement` via Chrome Extension, just wondering if its possible to get the object via puppeteer.

**Comment by vsemozhetbyt** [comment]
Not directly. You can manage elements and extract data via `page.evaluate()` or do this via JSHandle/ElementHandle API:

```js
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    // Way 1.
    const data1 = await page.evaluate(() => {
      const element = document.body;
      return element.outerHTML;
    });
    console.log(data1);

    // Way 2.
    const element = await page.evaluateHandle(() => document.body);
    const elementProperty = await element.getProperty('outerHTML');
    const data2 = await elementProperty.jsonValue();
    console.log(data2);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by anuragphadke** [comment]
@vsemozhetbyt : thank you so much for all your help and helping me understand the intricacies of JSHandle. Closing this ticket.
