### ISSUE TITLE
Page.click() does not work with an input selector

### ISSUE THREAD

**Issue by pauloacosta** [puppeteer/puppeteer#6462]
Ps.: View the issue #3347 - The problem continues.

Steps to reproduce
Tell us about your environment:

Puppeteer version: 5.3.0
Platform / OS version: Windows 10
URLs (if applicable):
Node.js version: v12.18.3
What steps will reproduce the problem?

I am trying to use page.click() to click at a Button . If I use the selector button[type='button'] in developer console it works. However, puppeteer keeps throwing an error that no node was found.

This issue is the same problem related at: https://github.com/puppeteer/puppeteer/issues/3347

I am using a workaround:

        selector = 'button[type="button"]';
        await youtube.page.waitForSelector (selector);
        await youtube.page.evaluate((selector) => document.querySelector(selector).click(), selector);

**Comment by gidztech** [comment]
I just ran into this and for me it was because the element wasn't in view. According to https://github.com/puppeteer/puppeteer/issues/2190#issuecomment-380254352, Puppeteer will attempt to scroll the element into view before clicking, but it can fail sometimes, like if you have custom scrolling behavior.

I was able to get it working for me with:

```
await page.evaluate(selector => document.querySelector(selector).scrollIntoView(), [mySelector]);
await page.click(mySelector);
```

I think Puppeteer should be throwing an error if it fails to get the element in view itself, as part of the `click` function, because right now it thinks it's successfully clicked the element but it didn't. This is misleading. 

I know it errors if you click an element that has no height.
