### ISSUE TITLE
Socket hang up error when connecting to Firefox run by web-ext

### ISSUE THREAD

**Issue by alexanderby** [puppeteer/puppeteer#6498]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: macOS 10.15.6
* Node.js version: 12.18.3
* Browser version: Firefox Nightly 83.0a1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```javascript
// @ts-check
const path = require('path');
const puppeteer = require('puppeteer-core');
const webExt = require('web-ext');

async function openFirefox() {
    const runner = await webExt.cmd.run({
        sourceDir: path.join(__dirname, 'extension'),
        firefox: {
            'darwin': '/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin',
            'win32': `${process.env.PROGRAMFILES}\\Firefox Nightly\\firefox.exe`,
        }[process.platform],
    }, {
        shouldExitProgram: false,
    });
    const {debuggerPort} = runner.extensionRunners[0].runningInfo;
    return await puppeteer.connect({
        browserWSEndpoint: `ws://localhost:${debuggerPort}`,
    });
}

async function test() {
    try {
        await openFirefox();
        console.log('WORKS');
    } catch (err) {
        console.error(err);
        process.exit(13);
    }
}

test();
```

**What is the expected result?**
Runs without errors.

**What happens instead?**
Throws a `socket hang up` error.

**Comment by mjzffr** [comment]
I ran Firefox Nightly with `-start-debugger-server 64496 -foreground -no-remote --remote-debugging-port=1234`, which are the args you mention in https://github.com/puppeteer/puppeteer/issues/5532#issuecomment-706219796 and I can confirm that the correct protocol server is active.

You need to pass `--remote-debugging-port=1234` to Firefox, and then `browserWSEndpoint` in your script should be something like this: `ws://localhost:1234/devtools/browser/456fa4d1-3783-4c91-8044-96bc710a5290`

To get the correct URL, you could read the browser process output. That's what Puppeteer's launcher does under the hood: https://github.com/puppeteer/puppeteer/blob/e94a1e87dc65fcb83e9e2bb49ebaeec2f04fb399/src/node/BrowserRunner.ts#L244-L250

Closing this, since it's not an issue with Puppeteer or Firefox. Feel free to reopen if you learn anything new about the root cause. Thanks :)
