### ISSUE TITLE
lint jsdoc types

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#65]
We should lint jsdoc types.

I spent some time trying to make closure compiler work with node.js, but it didn't work due to issues with node module requires.

**Comment by JoelEinbinder** [comment]
I tried using typescript to do type checking. I had some success after removing all of our requires and module exports, and concatenating everything into one big file. There were a lot of errors because our `WebSocket` is different from browser's `WebSocket`, and typescript gets confused by `frame.evaluate` because of the context switch and the way arguments are passed in.

**Comment by sukrosono** [comment]
Did the code base will use typescript after pull number 219 finished ? :fearful:

**Comment by aslushnikov** [comment]
> Did the code base will use typescript after pull number 219 finished ? 😨

@brutalcrozt no, we'll continue using JS with jsdoc annotations.
