### ISSUE TITLE
Close browser after function bound with page.exposeFunction() call ?

### ISSUE THREAD

**Issue by eltomjan** [puppeteer/puppeteer#6594]
Is there some standard way to get (async) page result ?
- Node.js starts page in puppeteer
- there is some self-initiated processing in page
- after processed page calls exposeFunction
And how to close (chromium) properly now ?
Inside browser window.close does not work (but reused 1st tab).
Browser cannot be closed after exposeFunction nor from its invocation in Node.js (exception).

```
const browser = await puppeteer.launch({});
const page = await browser.pages();
await page[0].goto('file:///...');
page[0].exposeFunction('reader', (html) => {
    fs.writeFileSync(path.join(__dirname, pdf.replace('.pdf', '.htm')), html);
    session.on('Page.lifecycleEvent', event => {
        console.log(JSON.stringify(event));
        if (event.name === 'firstMeaningfulPaint') browser.close();
    });
});
```
Error reported sometimes or if closed without some ansync hook
```
Error: Protocol error (Runtime.evaluate): Target closed.
    at puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (puppeteer\lib\Connection.js:182:12)
    at Page._onBindingCalled (puppeteer\lib\Page.js:568:18)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {message: 'Protocol error (Runtime.evaluate): Target closed.', stack: 'Error: Protocol error (Runtime.evaluate): Tar…ctions (internal/process/task_queues.js:94:5)'}
```

**Comment by yyvess** [comment]
Thanks for you response, I suspect that my issue is caused by my Chromium version that is 84.

**Comment by dpmott** [comment]
You probably cannot safely synchronously close the browser from within the exposed function.

You could try to wrap the call to `browser.close()` as `setTimeout(() => { browser.close(); }, 0)`, so that the function can return before the browser is closed.

However, I'd recommend trying to find a way to return a boolean from the function, and then to use that to close the browser from code that is not in the exposed function.
