### ISSUE TITLE
TypeError : The “original” argument must be of type function

### ISSUE THREAD

**Issue by fx1357** [puppeteer/puppeteer#6699]
* Puppeteer version: 5.5
* Platform / OS version: window10 64x
* Node.js version: 14.15.3

_Please include code that reproduces the issue._

1. import  puppeteer  from 'puppeteer'

**What is the expected result?**
working well

**What happens instead?**
error occurred
TypeError : The "original" argument must be of type function

please read this (Same error as me)

https://stackoverflow.com/questions/61770784/typeerror-err-invalid-arg-type-the-original-argument-must-be-of-type-functi

answers included here don't work or cause other errors

Please solve this problem

**Comment by niklasdahlheimer** [comment]
Just wanted to add some "investigation-results":
It turns out that Puppeteer [3.0.2](https://github.com/puppeteer/puppeteer/releases/tag/v3.0.2) is the first version which fails with the mentioned error.
I use puppeteer with Meteor 2.1 which bundles Node 12.21.0. It's crashing on my host (Win10 x64) and also in a Docker container (Alpine).

**Comment by ryan11223344** [comment]
I have the same issues now @niklasdahlheimer did you ever get an answer to this?

**Comment by chrislink14** [comment]
I had this same error when working with puppeteer. The fix for my that I found was to ensure I was only running puppeteer on the server side of the code. Not sure if this will fix it for everyone. I was also working with MeteorJS so just moving the puppeteer functionality to a Meteor.call to call puppeteer from the client.

**Comment by kirstenhh** [comment]
I'm currently getting this issue running bpmn-to-image, which incorporates puppeteer. I've also tested the example given in the above bug report and it is still throwing the error.

**Comment by OrKoN** [comment]
@kirstenhh which version of Puppeteer does that package use? does it still reproduce with the latest version of Puppeteer?  I am not able to reproduce it with the latest version and the original code from the StackOverflow issue.

**Comment by OrKoN** [comment]
Okay, thanks for the info. Please re-open if it's still an issue with the latest version.

**Comment by saeedhemmati** [comment]
@OrKoN 
I facing this issue with puppeteer v19.8.5. I want use of puppeteer in nextjs and also in client side with the following code:

```javascript
try {
        const browser = await puppeteer.connect({
          browserWSEndpoint:
            'ws://127.0.0.1:50197/devtools/browser/0f8f46d5-6369-4ed1-9b33-328c0459b927',
        });
      } catch (e) {
        console.log({ e });
      }
```

I create puppeteer instance in `nextjs.config.js` file and get the `ws` url address to use in clientside puppeteer.
Finally get this error:

```
Unhandled Runtime Error
TypeError: The "original" argument must be of type Function
```

**Comment by OrKoN** [comment]
@saeedhemmati I am not able to reproduce. Please try with the latest version and provide an example repository demonstrating the issue (best to file a new issue).
