### ISSUE TITLE
pdf always print an extra page. last page always blank. Unexpected white footer in last 2nd page.

### ISSUE THREAD

**Issue by hi-hai** [puppeteer/puppeteer#6704]
* Puppeteer version: v5.5.0
* Platform / OS version: Ubuntu 20
* Node.js version: v10.19.0

**What steps will reproduce the problem?**

1. Run below codes (https://try-puppeteer.appspot.com/), will get the pdf of two pages. 2nd page is black and a gray header.
```
const browser = await puppeteer.launch();
const page = await browser.newPage();

const html = `<html>
<head>
	<meta charset="utf-8" />
	<style>
		html {
			-webkit-print-color-adjust: exact;
		}
		body {
			margin: 0;
			padding: 0;
			background-color: orange;
		}
		.page {
			width: 110px;
			height: 50px;
			background-color: #ccc;
			margin: 0;
padding:0;
;
		}
	</style>
</head>
<body>
<div class="page">AAA</div>
</body>
</html>`;

await page.setContent( html, { waitUntil: 'networkidle2' } );
await page.emulateMedia('screen');
await page.pdf( {
		width: '110px',
		height: '50px',
		path: `test.pdf`
} );	

await page.close();
await browser.close();
```

**What is the expected result?**
One page in pdf only

**What happens instead?**
Two pages. 1st page has a white footer. 2nd page has a gray header and blank body.

This issue is also mentioned in https://github.com/puppeteer/puppeteer/issues/589 
https://stackoverflow.com/questions/59887883/puppeteer-js-printing-empty-page-at-the-end
https://stackoverflow.com/questions/50237402/puppeteer-full-page-screenshot-getting-extra-white-space-rendered-at-bottom-of
https://stackoverflow.com/questions/63374307/puppeteer-avoid-margin-on-last-page-while-printing

**Comment by QAnders** [comment]
This is not any "official" answer, just trying to help out... :)

This most often has to do with some object is "spilling over" to the second page due to margins and/or padding which can't be seen. I often alter my css and draw borders around the objects (`style="border: 1px solid red;"`) so you can see where the objects ends and what is spilling over.

Most often your local browser (Chrome is of course best to use) agrees with Puppeteer so load your HTML in the browser an select to "Print..." (set printer to "Save as PDF" or similar) and you'll see in the preview how many pages it's going to print. 
The alter your css to lessen the height/width of your objects to make sure only one page is printed.

If you are using a header/footer in Puppeteer then you need to make room for those as well so you'd have to lessen your height of the "page". There also it helps to add a border around the header and footer to make it visible. **NB!** somethins the footer is added as a tiny small box so make sure you add some "font-size" to the header/footer objects.

Sometimes it helps adding this if no obvious object is spilling over:
```
        @media print {
            /* prevent blank page at end */
            table:last-of-type { page-break-after: auto; }
            html, body {
                height: 100%;
            }
        }
```

**Comment by pushmiq** [comment]
still happens

**Comment by Lionberg** [comment]
And still happening...

**Comment by heytulsiprasad** [comment]
No idea if it's my code or puppeteer, but it does happen for me. 
Tried above fix by adding in css, no result.

**Comment by againer** [comment]
I was able to fix the extra blank page with `pageRanges` and a little bit of jank. The css solutions I found all over the inet didn't do anything for me.
```javascript

// metadata.height for us is a mapping between format and pixels based on 96 DPI
// https://pptr.dev/api/puppeteer.pdfoptions
const totalPages = await page.evaluate(
    (height) => Math.ceil(document.body.scrollHeight / (height || 1056)), metadata.height);

await page.pdf({...params, pageRanges: `1-${totalPages}`});
```

We support dynamic paper `format` in our system. If you are just supporting only `Letter`, then you can probably get away with using:
```javascript
const totalPages = await page.evaluate(() => Math.ceil(document.body.scrollHeight / (1056)));
await page.pdf({...params, pageRanges: `1-${totalPages}`});
```
