### ISSUE TITLE
Attempt file downloading via direct navigation triggers error in Puppeteer

### ISSUE THREAD

**Issue by starrify** [puppeteer/puppeteer#6728]
### 1. Environment

* Puppeteer version: puppeteer@5.5.0
* Platform / OS version: Arch Linux at kernel version 5.10.3-arch1-1, x86_64
* URLs (if applicable): See example below
* Node.js version: v15.5.0

### 2. Quick Description

It's known that Chromium in its headful mode is capable of downloading files by using [the `Browser.setDownloadBehavior` CDP method](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior).

It is observed that (see examples below) the current version of Puppeteer (5.5.0) fails in downloading the files:
- When the file-downloading URL is provided directly for navigation

while succeeds:
- When the same file-downloading URL is visited via an in-page action of clicking on the link
- Or when sending [the `Page.navigate` CDP method](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate) directly than using [Puppeteer's `page.goto`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagegotourl-options)

(in all three cases it is the same URL that is being downloaded)

### 3. A sample script for illustration

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    userDataDir: '/tmp/tmp_chrome_profile',
  });
  const page = await browser.newPage();
  await page._client.send('Browser.setDownloadBehavior', {
    behavior: 'allow',
    downloadPath: '/tmp/tmpdown/',
  });
  let downloadState = null;
  await page._client.on('Page.downloadProgress', ({guid, totalBytes, receivedBytes, state}) => {
    downloadState = state;
  });
  const testType = process.env.TEST_TYPE || '1';
  if (testType == '1') {
    // direct download
    await page.goto('https://coronavirus.data.gov.uk/downloads/easy_read/overview/United%20Kingdom.docx');
  } else if (testType == '2') {
    // indirect download -- navigate to the index page then download via a click
    await page.goto('https://coronavirus.data.gov.uk/');
    await page.waitForSelector('div.govuk-grid-row a[href="/downloads/easy_read/overview/United Kingdom.docx"]');
    await page.click('div.govuk-grid-row a[href="/downloads/easy_read/overview/United Kingdom.docx"]');
  } else if (testType == '3') {
    // no Puppeteer navigation -- use CDP directly instead
    await page._client.send('Page.navigate', {
      url: 'https://coronavirus.data.gov.uk/downloads/easy_read/overview/United%20Kingdom.docx',
    })
  }
  async function checkResult() {
    if (downloadState == 'completed') {
      console.log('download completed');
      await browser.close();
    } else {
      setTimeout(checkResult, 100);
    }
  }
  checkResult();
})();
```

### 4. Sample results from the above script

Case 1: When the file-downloading URL is provided directly for navigation -- fails within Puppeteer
```
$ rm -rf /tmp/tmpdown/ && TEST_TYPE=1 node test.js && ls /tmp/tmpdown/
/tmp/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_ABORTED at https://coronavirus.data.gov.uk/downloads/easy_read/overview/United%20Kingdom.docx
    at navigate (/tmp/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async FrameManager.navigateFrame (/tmp/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/tmp/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/tmp/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at async /tmp/test.js:21:5
```

Case 2: When the same file-downloading URL is visited via an in-page action of clicking on the link -- succeeds
```
$ rm -rf /tmp/tmpdown/ && TEST_TYPE=2 node test.js && ls /tmp/tmpdown/
download completed
'United Kingdom.docx'
```

Case 3: When sending [the `Page.navigate` CDP method](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate) directly than using [Puppeteer's `page.goto`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagegotourl-options) -- succeeds
```
$ rm -rf /tmp/tmpdown/ && TEST_TYPE=3 node test.js && ls /tmp/tmpdown/
download completed
'United Kingdom.docx'
```

**Edited:** It seems that in this case 3 example, the navigation request from the CDP method also gives an error. It is just that such error won't affect the actual file downloading task. Given below is a sample response from the `Page.nagivate` CDP method:

```
{"frameId":"8F5624D4BE6BE24F40AB845DD85F616E","loaderId":"312751DE4B880C95ED2A7CFDED219238","errorText":"net::ERR_ABORTED"}
```

### 5. Misc

The above sample script picks a random URL for illustration purposes. Assumption is that it is not the hard-coded URL that causes the observed issue, since the same issue can be observed as well in many other URLs.

I understand that such feature (file downloading) might be yet recognized as unsupported in Puppeteer. However it would really be nice if we could somehow get rid of the error.

**Comment by leoriviera** [comment]
I've been facing this very same issue, so any headway would be good to know about. :)

**Comment by andorthehood** [comment]
To anyone who found this issue, this is the workaround that I'm using:

    async function goto(page, link) {
        return page.evaluate((link) => {
            location.href = link;
        }, link);
    }

    goto(page, link);

**Comment by austospumanto** [comment]
@andormade That solved it for me (was using `page.waitForNavigation(link)` before). Thanks!

**Comment by josephmturner** [comment]
I was able to use @starrify's Case 3 example to achieve the download I needed.

**Comment by BitComputer64** [comment]
A little late to the party, but I'm facing a similar issue right now (a niche use-case, but just bear with me).
Copying the original issue's format:

### 1. Environment
* Puppeteer version: puppeteer@19.7.2
* Platform / OS version: Debian GNU/Linux 11 at kernel version 5.10.16.3-microsoft-standard-WSL2, x86_64 (running in docker container)
* URLs (if applicable): See below for example
* NodeJS version: v18.15.0

### 2. Quick Description
In a similar vein to the original problem, I'm trying to use puppeteer's `page.goto()` method with limited success.
Rather than navigating to a download URL, I'm trying to go to a `javascript:` url, which results in ERR_ABORTED. For instance, `javascript:document.body.innerHTML="<h1>hi!</h1>"`.
Through using Chrome's devtools protocol, [Page.navigate](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate) successfully navigates to such a URL, executing the javascript as expected. Using `page.goto()` fails. Below is the described behavior in action.

### 3. Sample Code
The code below is a heavily simplified version of the workflow I'm using:
```js
import puppeteer from 'puppeteer'
const browser = await puppeteer.launch({
    headless: false,
    args: [
        '--incognito',
        '--js-flags=--jitless',
        '--no-sandbox',
        '--disable-gpu'
    ]
});
const page = await browser.newPage();
await page.goto("https://www.example.com");
const url = 'javascript:console.log("this is a test.");';
await page.goto(url);
```

### 4. Sample Results
When executed, an error similar to the following is generated:
```
$ node app.js
...
Error: net::ERR_ABORTED at javascript:console.log("this is a test.");
    at navigate (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:214:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Frame.goto (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:180:21)
    at async CDPPage.goto (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:436:16)
    at async file:///app/app.js:14:1
```

### 5. Miscellaneous Comments
What's interesting is that outside of Docker, this script *seems to* still execute the JS. Sure, it errors out, but the javascript *still ends up executing*.
However, when I tried the same code out inside a different (but very very similar project) it both errored out and didn't execute the code. The only perceptible difference between the two projects (to me) was that the code ran inside a docker container.
And of course, using the CDP works fine, albeit still with the ERR_ABORTED generated (but the javascript still runs!).
P.S. I am aware that I can use `page.evaluate()` in order to execute JS, like detailed above for solving the download issue. However, my use case specifically demands that `page.goto()` is called, so I need some way to get it to work.

**Comment by jboolean** [comment]
Thank you https://github.com/puppeteer/puppeteer/issues/6728#issuecomment-986082241 !!! This took me so long to figure out. Seems like this should be reopened?

**Comment by alangunning** [comment]
> To anyone who found this issue, this is the workaround that I'm using:
> 
> ```
> async function goto(page, link) {
>     return page.evaluate((link) => {
>         location.href = link;
>     }, link);
> }
> 
> goto(page, link);
> ```

Thank you 🥇 , still the only working workaround I found in 2024
