### ISSUE TITLE
Cache downloaded Chromium

### ISSUE THREAD

**Issue by marc-mabe** [puppeteer/puppeteer#6833]
We are using `npm ci` on our CI platform to make sure we are working on a clean install. The tests running there are executed multiple times per day for multiple projects all using puppeteer.

> npm ci
> 
> Description
> 
> This command is similar to npm install, except it's meant to be used in automated environments such as test platforms, continuous integration, and deployment -- or any situation where you want to make sure you're doing a clean install of your dependencies.

The problem is that each run downloads Chromium again even if it was downloaded before already. Which will be multiple GB per day in traffic we have to pay for :(

It would be really helpful if you could cache Chromium in NPM cache to be used for later downloads of the same file the same way as the packages itself are cached in NPM.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.1
* Platform / OS version: Mac & Linux
* URLs (if applicable): -
* Node.js version: 10.23.2

**What steps will reproduce the problem?**

1. Add puppeteer as (dev) dependency in package.json
1. npm ci

**What is the expected result?**

Chromium should be installed from NPM cache if already downloaded before

**What happens instead?**

Chromium gets downloaded each time

**Comment by meeq** [comment]
See prior discussion on this issue in https://github.com/puppeteer/puppeteer/issues/2759

**Comment by dfernandez79** [comment]
Hi, since this discussion appears multiple times and it's a common issue. I wanted to share a workaround that I use in my dev machine:

* By default `npm` stores its cache in `$HOME/.npm`, so you can use that directory to store the downloaded Chromium instead of `node_modules/puppeteer`
* The install script doesn't try to download Chromium again if you have it in the download location
* You can specify the Chrome executable location when running your tests.

The commands to implement these steps:

```sh
# this downloads chromium in ~/.npm/chromium (it only downloads it the first time)
PUPPETEER_DOWNLOAD_PATH=~/.npm/chromium npm ci

# when running your tests, if you use macOS (check the contents of ~/.npm/chromium if you use Linux):
PUPPETEER_EXECUTABLE_PATH=~/.npm/chromium/mac-869685/chrome-mac/Chromium.app/Contents/MacOS/Chromium npm test
```

You can put these env variables in your shell profile (eg. `.zshrc`), and you only need to update them if you change the puppeteer version.

Hope it helps!

**Comment by dfernandez79** [comment]
An update to my last comment, if you set `PUPPETEER_DOWNLOAD_PATH` you don't need to also set `PUPPETEER_EXECUTABLE_PATH`. By default the code here: https://github.com/puppeteer/puppeteer/blob/bba3f41286908ced8f03faf98242d4c3359a5efc/src/node/Launcher.ts#L596
means that Puppeteer will try to find the executable in the download path.

It means that solving this issue is extremely easy:

```sh
export PUPPETEER_DOWNLOAD_PATH=~/.npm/chromium
```
In you shell config... and that's all 😄 

Probably this should be documented in the README.

**Comment by mathiasbynens** [comment]
@dfernandez79 Nice! Would you like to submit a patch documenting this in the README?

**Comment by dfernandez79** [comment]
Yes, I'll do it 👍
