### ISSUE TITLE
Request Interception Cannot Override All Headers

### ISSUE THREAD

**Issue by ks07** [puppeteer/puppeteer#686]
Using Puppeteer 0.10.2

The request interception API doesn't allow me to override (or indeed view) all the HTTP headers sent with a request. It does not appear to be possible to set the `Referer` header at all, and it is only possible to set the `Cookie` header if the browser is not already sending an actual value.

See this example script:
```javascript
const puppeteer = require('puppeteer');

async function main() {
    const browser = await puppeteer.launch({args: ['--no-sandbox']});

    let page = await browser.newPage();

    await page.setRequestInterceptionEnabled(true);
    page.on('request', req => {
        let headers = req.headers;
        headers['referer'] = 'http://www.example.com/';
        headers['cookie'] = 'somekey=somevalue';
        req.continue({
            headers: headers
        });
    });

    await page.goto('http://localhost/checkheaders');
    browser.close();
}

main();
```

The `Referer` header is not sent by the browser. The `Cookie` header is correctly sent only if there is not already a cookie being sent normally by the browser (i.e. navigating to another page on the same domain which sets a cookie will cause that cookie to take precedence over any cookie header set in the request interception). This bug also seems to have the same affect when trying to use page.setExtraHTTPHeaders(), although the name suggests this is intentional.

This is unfortunately a step-back from PhantomJS, where `page.customHeaders` could be used to override headers at will.

**Comment by aslushnikov** [comment]
@ks07 Thanks for filing this. There's a [`page.setExtraHTTPHeaders`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetextrahttpheadersheaders) method which should be roughly equivalent to the `page.customHeaders`.

**Comment by katp4** [comment]
@aslushnikov coming from a phantomjs background, is there currently any way to set custom headers only for the initial page open as opposed to every single request?

See phantomjs page.onInitialised event
http://phantomjs.org/api/webpage/property/custom-headers.html

**Comment by aslushnikov** [comment]
@katp4 you should be able to do this with request interception API (see `setRequestInterceptionEnabled` method).

**Comment by GuilloOme** [comment]
any update on this one?

**Comment by Aitchy13** [comment]
I could only seem to add to existing request headers by **removing**:
```
await page.setRequestInterceptionEnabled(true);
```
Although an AssertionError is thrown, it appears to work.

**Comment by amit-traiana** [comment]
Is there any news on that?

There's authentication proxy before our nodejs server - one which we prefer no to test in that specific environment due to complexity. What this proxy do is to add a specific `cookie` header with the session.

I'm able to add this cookie header with `page.setExtraHTTPHeaders` for the first request in line, but it's being over-written by the response cookie. I want to simulate the proxy be adding the session to every request (which is exactly what the proxy do), but I'm un-able to over-write the cookie header once it's being set with neither `page.setExtraHTTPHeaders ` or by intercepting the request and trying to over-write it manually.

**Comment by amit-traiana** [comment]
Is there any news on that?

There's authentication proxy before our nodejs server - one which we prefer no to test in that specific environment due to complexity. What this proxy do is to add a specific cookie header with the session.

I'm able to add this cookie header with `page.setExtraHTTPHeaders` for the first request in line, but it's being over-written by the response cookie. I want to simulate the proxy be adding the session to every request (which is exactly what the proxy do), but I'm un-able to over-write the cookie header once it's being set with neither `page.setExtraHTTPHeaders` or by intercepting the request and trying to over-write it manually.

**Comment by emiliavanderwerf** [comment]
Puppeteer version 6.0.0 seems to override Referer and Cookie headers correctly - see the screenshot. The code is very similar from the original, just updated with small changes:

```
const puppeteer = require('puppeteer');

async function main() {
    const browser: Browser = await puppeteer.launch({
        args: ['--no-sandbox'],
        headless: false
    });

    let page: Page = await browser.newPage();

    await page.setRequestInterception(true);
    page.on('request', req => {
        let headerOverride: Record<string, string> = req.headers();
        headerOverride['referer'] = 'http://www.example.com/';
        headerOverride['cookie'] = 'somekey=somevalue';
        req.continue({
            headers: headerOverride
        });
    });

    await page.goto('http://localhost/checkheaders');
    browser.close();
}

main();
```

![image](https://user-images.githubusercontent.com/28126679/106616935-17ff9100-653c-11eb-9974-735f1d8630db.png)

**Comment by hkalex** [comment]
I am trying to overwrite "sec-" headers, but also not working :(
