### ISSUE TITLE
page.screentshot will scroll the page to top

### ISSUE THREAD

**Issue by VetchM** [puppeteer/puppeteer#6921]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@7.1.0
* Platform / OS version: windows
* URLs (if applicable): https://image.baidu.com/
* Node.js version: Node v14.15.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

await page.evaluate(scrollToBottom)       //scroll to bottom of the page
await page.screenshot({ path: path.resolve(String(Date.now()) + '.png') });

**What is the expected result?**
scrennshot justs take a picture of current screen 

**What happens instead?**
it automatically scrolls back to top of the page then take a picture
same code works fines on puppeteer@5.5.0

I checked on non headless mode and sure it's page.screenshot() scrolled my page,
this behavior doesn't happen on other search engine such as google and sougou.

**Comment by lehni** [comment]
I am seeing similar issues with `v8.0.0`  in our e2e tests that work fine on `v5.5.0`:

- nested iframes that were scrolled to their bottom before the screenshot appear as scrolled to the top in the screenshot. I verified with non-headless and they are indeed scrolled down, yet the screenshot shows them at their top.

- a screenshot of a page scrolled to a given element mid-ways also is taken in the wrong place, but not at the top, somewhere wrongly in between, and again not where the browser actually is.

It looks like scrolling and screenshots have been broken somewhere in `v7` and the problem is still present in `v8`.

I am seeing this issue both on macOS and Linux.

**Comment by pringelmann** [comment]
+1 I am experiencing the same issue. Only solution is to roll back to v5

**Comment by lehni** [comment]
I guess we should work on a simple reproducible test case… Ours is unfortunately quite hard to isolate. @Pringels perhaps you have something you could provide?

**Comment by lehni** [comment]
This bug is still present in `v9`

**Comment by pringelmann** [comment]
> I guess we should work on a simple reproducible test case… Ours is unfortunately quite hard to isolate. @Pringels perhaps you have something you could provide?

Ours is also non-trivial to isolate. I can try set up a codesandbox or something and replicate it there.

**Comment by lehni** [comment]
It turns out v6 also still works. I'm fairly certain now that this bug was introduced in 401d84e4a3508f9ca5c24dbfcad2a71571b1b8eb

@sadym-chromium could you perhaps take a look at this issue?

**Comment by lehni** [comment]
It looks like the `captureBeyondViewport: false` introduced in #7063 may help fix this issue. 401d84e4a3508f9ca5c24dbfcad2a71571b1b8eb has set this to true…  

See: https://github.com/puppeteer/puppeteer/commit/401d84e4a3508f9ca5c24dbfcad2a71571b1b8eb#diff-7b571f1b17991b899111f41e9844844f2fd527b4c1a775aaeb713ceb8b17959aR1696

**Comment by lehni** [comment]
I can confirm: Passing `{ captureBeyondViewport: false }` to `page.screenshot()` solves this problem for us indeed. 🎉

**Comment by lehni** [comment]
After reading through #6805 I think this behavior will not change and the fix is simply to include the above option. I think this issue can be closed. Related: #7043
