### ISSUE TITLE
Node is detached from document error

### ISSUE THREAD

**Issue by t1a2l** [puppeteer/puppeteer#6955]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 19.4.1
* Platform / OS version: windows 10
* URLs (if applicable): 
* Node.js version: 18.12.1

**What steps will reproduce the problem?**

datepickers inputs must be selected by id a.k.a await page.$("#current_date");
if selected by name - await page.$("input[name=current_date]");
i cant change its value.

_Please include code that reproduces the issue._

const expected_date = await page.$("input[name=current_date]");

await expected_date.focus();
await expected_date.click({clickCount: 3});
await expected_date.press('Backspace');
await expected_date.type("2021-03-02"); 
await page.waitForTimeout(1000);
await page.keyboard.press('Enter');

**What is the expected result?**
the date input to change text to "2021-03-02".

**What happens instead?**
 Error: Node is detached from document
      at ElementHandle._scrollIntoViewIfNeeded (node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:317:19)

**Comment by t1a2l** [comment]
Please open the issue i still have it with the latest version

**Comment by t1a2l** [comment]
@Lightning00Blade Hey can you reopen this? it is a bug.

**Comment by Lightning00Blade** [comment]
Hello, I took a look at it having this HTML
```
  <div>
    <label for="current_date">Date:</label>
    <input type="date" id="current_date" name="current_date">
  </div>
```
and using this Puppeteer snippet worked for me (both for name and id):
```
  await date.focus();
  // You can do this
  await date.type("4302022");
  // Or this
  await date.type("4"); // Month
  await date.type("30"); // Date
  await date.type("2022"); // Year
  // Or this
  await date.evaluate((element) => element.value = "2022-04-30");
```
Mind you that the order when typing may differ as browser may try respect the local date format for typing. 
Because of that I would recommend using the evaluate way. 
Not sure why you need to the `click` and `Backspace`, but the `clicks` brake them while the `Backspace` does nothing.

Also running you original code with the `name` or `id` yields the same result of empty value.
