### ISSUE TITLE
Best way to wait for request to finish in e2e-test

### ISSUE THREAD

**Issue by ManuSevenval** [puppeteer/puppeteer#704]
I want to use puppeteer with jest for running e2e-tests.
therefore i wrote the following test:

```
const puppeteer = require('puppeteer');

describe('Login', () => {
	const appUrlBase = 'https://localhost:3000/';

	let browser;
	let page;

	beforeAll(async () => {
		browser = await puppeteer.launch({ignoreHTTPSErrors: true});
		page = await browser.newPage()
	});

	test('user can login', async () => {
		page.on('response', response => {
			if (/login$/i.test(response.url)) {
				expect(response.status).toBe(201);
			}
		});

		await page.goto('https://localhost:3000/');

		await page.click('input[name="username"]');
		await page.type('*****');

		await page.click('input[name="password"]');
		await page.type('*****');

		await page.click('button[type="submit"]', {waitUntil: 'networkidle'});
	});

	afterAll(async () => {
		browser.close()
	})
});)
```

Now I am wondering:

1. What would be the best way to watch one specific request? (instead of my regex in the response event handler)
2. Whats the best way to wait for this specific request?

Because depending on the response times of my server the test suceeds, or fails with the message:
`Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

**Comment by ebidel** [comment]
This is a good question for StackOverflow :) 

> What would be the best way to watch one specific request?

What you have works, but you could also try the waitFor* methods. In particular,
 [`page.waitForNavigation`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions) or `page.waitForFunction` might be useful.

I see a couple of options for fixing the timeout issue:
- mock the API response instead of making a live request
- increase jasmine's timeout
- use something like `Promise.race([page.waitForNavigation(...), new Promise(r => setTimeout(r, 3000))])` to set a hard limit (3s) on how long the request should take. Fail the test if the timeout is reached.

Closing since this is not specific to Puppeteer.
