### ISSUE TITLE
CSP bypassing in Firefox not working

### ISSUE THREAD

**Issue by unstablegeedan** [puppeteer/puppeteer#7209]
I am trying to use Firefox Nightly browser instead of using chromium in puppeteer. but when I shifted to Firefox Nightly i started to encounter below error

Error: Protocol error (Page.setBypassCSP) 
![CSP_ERROR](https://user-images.githubusercontent.com/42197018/117155189-2fb81100-adda-11eb-98c1-c3eaab6f1580.png)

I would like to know is there any workaround to bypass CSP in Firefox puppeteer or will this get resolved in future !!!

**Comment by WallisonLima** [comment]
try deleting the puppeteer file from the node_modules folder and install, after that insert it into the instance that starts your puppeteer `{product: "firefox"}`  ... it should look like this `const browser = await puppeteer.launch ({headless: false, product: "firefox"})`

**Comment by xNS5** [comment]
~~I'm also experiencing this issue. I deleted + installed puppeteer, no dice.~~

~~It seems that any call to `.setBypassCSP()` whether passing `true` or `false` results in this error, so I just commented out the line calling that function and I was able to run my project again.~~

~~OS: MacOS 10.15.7~~
~~Node Version: 16.0.0~~
~~Puppeteer Version: 7.12.1~~

~~The library I need to use (@axe-core/puppet) requires <9, and installing puppeteer@8.0.0 also has this issue. Testing with 9.0.0 also yields this error.~~

~~Edit: According to [this thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1649375), it seems like Firefox doesn't support disabling CSP for now. The ticket got moved to 'doing' only recently.~~

I misread the documentation. Turns out my issue stemmed from me putting `pate.SetBypassCSP()` before navigating to pages. Please disregard what I said!
