### ISSUE TITLE
Headful runs fail for latest version of chrome with Protocol error (Page.navigate)

### ISSUE THREAD

**Issue by joecanuelspotify** [puppeteer/puppeteer#7318]
### Context

We use puppeteer on Chrome to run some tests. These tests work fine when being run headless, but we noticed they started failing in headful mode starting with Chrome 90 and are still broken in Chrome 91. It seems like the page isn't useable after a while.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 9.1.1 (and have tried 10.0.0)
* Platform / OS version: Chrome 91.0.4472.77
* URLs (if applicable):
* Node.js version: Node v14.15.4

**What steps will reproduce the problem?**

1. Run the following typescript script
```
import puppeteer from 'puppeteer';

async function delay(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: false,
      // Chrome 91.0.4472.77 for me, but edit this to point to your path
      executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
    });

    const puppeteerPage = await browser.newPage();
    await puppeteerPage.goto("https://www.google.com");
    await delay(20000);

    // Crashes here
    await puppeteerPage.goto("https://www.google.com");
  } catch (e) {
    console.error(e);
  }
}

main();
```

2. Observe a similar error to this
```
Error: Protocol error (Page.navigate): Session closed. Most likely the page has been closed.
    at CDPSession.send (***/node_modules/puppeteer/src/common/Connection.ts:262:9)
    at navigate (***/node_modules/puppeteer/src/common/FrameManager.ts:183:39)
    at FrameManager.navigateFrame (***/node_modules/puppeteer/src/common/FrameManager.ts:161:7)
    at Frame.goto (***/node_modules/puppeteer/src/common/FrameManager.ts:642:37)
    at Page.goto (***/node_modules/puppeteer/src/common/Page.ts:1385:49)
    at main (***/chrome-headful-example.ts:19:25)
```

**What is the expected result?**
The page stays available.

**What happens instead?**
The code crashes with the above error after waiting for a bit.

### Note
* I've tried args: `args: ['--disable-dev-shm-usage']` and it still fails with that.

**Comment by SpamapS** [comment]
I am pretty sure that I've located the root cause of this problem. What I observe is that if I drop the delay in the script above to 1000ms, the script passes. Anything above finds the CDPSession in varying stages of having been torn down by the browser. I believe this is happening because, upon startup, Chrome phones home, as we have a managed Google domain. When enterprise configs are asserted, it shuts down any dev tools (CDP) connections.

I believe Puppeteer likely needs to try and reconnect if the CDPSession has closed. That would probably solve this. Another thing to attempt would be to see if the browser perhaps can offer some kind of flag to check whether it is actually initialized, delay the connection setup until that flag has been set.

**Comment by ayapi** [comment]
Maybe similar problem,

```js
const client = await page.target().createCDPSession()
client.send('Network.clearBrowserCache')
```

```
ProtocolError: Protocol error (Network.clearBrowserCache): Target closed.
```

> What I observe is that if I drop the delay in the script above to 1000ms, the script passes.

Me too.
