### ISSUE TITLE
Request.resourceType doesnt match DevTools

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#734]
`request.resourceType` doesn't always match the resourceType shown in devtools:

<img width="1029" alt="screen shot 2017-09-09 at 11 12 41 am" src="https://user-images.githubusercontent.com/238208/30242685-d8a7df18-954f-11e7-919f-48e023b4bfd0.png">

<img width="525" alt="screen shot 2017-09-09 at 11 12 44 am" src="https://user-images.githubusercontent.com/238208/30242684-d8a790f8-954f-11e7-8075-201aef30c131.png">

```js
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch();
const page = await browser.newPage();

const responses = [];
page.on('response', resp => {
  responses.push(resp);
});

page.on('load', resp => {
  responses.map(async (r, i) => {
    const request = await r.request();
    console.log(request.url, request.resourceType);
  });
});

await page.goto('https://news.ycombinator.com/', {waitUntil: 'networkidle'});
browser.close();
})();
```

**Comment by aslushnikov** [comment]
@ebidel interesting! Almost everything is reported as "Other".

DevTools workaround this by falling back to mimeType: [DevTools code](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/network/NetworkDataGridNode.js?type=cs&q=displayType+f:front_end&sq=package:chromium&l=652). This approach wouldn't work for us since we need `resourceType` to process interception, and the mimeType is only available in the response.

**Comment by ebidel** [comment]
Could we provide something (`request.mimeType` property) that uses the `mime` module to figure out the type? Even if we can't fix this bug, that info would be useful by itself to write files with the proper extension, use `new Blob()`, etc.

**Comment by zicai** [comment]
+1

**Comment by aslushnikov** [comment]
@ebidel that's a protocol bug; I'll fix it upstream.

**Comment by aslushnikov** [comment]
Upstream bug: [crbug.com/765501](https://bugs.chromium.org/p/chromium/issues/detail?id=765501)
