### ISSUE TITLE
PDF rendering - OpenType font names were not embedded

### ISSUE THREAD

**Issue by borriglione** [puppeteer/puppeteer#7401]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.1.0
* Platform / OS version: Ubuntu 18
* URLs HTML: https://www.tutory.de/entdecken/dokument/schriftarten-test.html
* URL PDF: https://www.tutory.de/entdecken/dokument/schriftarten-test.pdf
* Node.js version: 14.14

**What steps will reproduce the problem?**

1. Create a PDF by:

```
    const browser = await puppeteer.launch({
      args: ['--font-render-hinting=none', '--disable-gpu'],
      headless: true,
    })
    const page = await browser.newPage()
    await page.goto('https://www.tutory.de/entdecken/dokument/schriftarten-test.html', { waitUntil: 'networkidle0' })
    await page.evaluateHandle('document.fonts.ready')
    await page.focus('body')
    ctx.body = await page.pdf({
      printBackground: true,
      scale: 1,
      landscape: false,
      width: 800,
      height: 600,
    })
    page.close().then(() => browser.close())
```
2. Parse pdf by: `pdffonts Schriftarten\ Test.pdf`

**What is the expected result?**

We would expect that TrueType- and OpenType-Fonts were embedded with the correct name in PDF.

**What happens instead?**

The OpenType-fonts "OpenDyslexic" (OpenDyslexic-Regular.otf) and "ComicNeue" (ComicNeue-Regular.otf) were rendered correctly in HTML and PDF but their font name and type is not correctly shown in PDF font meta informations. Instead they were shown as `[none] Type 3 Custom `.  Only the TrueType-Fonts have the correct name.

```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
OpenSans-Regular                     CID TrueType      Identity-H       yes no  yes      4  0
OpenSans-SemiBold                    CID TrueType      Identity-H       yes no  yes      6  0
[none]                               Type 3            Custom           yes no  yes      7  0
Roboto-Regular                       CID TrueType      Identity-H       yes no  yes      8  0
[none]                               Type 3            Custom           yes no  yes      9  0
Lora-Regular                         CID TrueType      Identity-H       yes no  yes     10  0
```

**Comment by tkrah** [comment]
@borriglione Did you ever find a solution to this? I've affected by this too since a few days where I get this:

```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes      4  0
BAAAAA+CourierNewPSMT                CID TrueType      Identity-H       yes yes yes      5  0
CAAAAA+ArialMT                       CID TrueType      Identity-H       yes yes yes      6  0
CAAAAA+ArialMT                       CID TrueType      Identity-H       yes yes yes      7  0
[none]                               Type 3            Custom           yes no  yes      8  0
CAAAAA+ArialMT                       CID TrueType      Identity-H       yes yes yes      9  0
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes     10  0
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes     13  0
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes     14  0
EAAAAA+Arial-BoldItalicMT            CID TrueType      Identity-H       yes yes yes     15  0
```
And this is going to be a problem for post processing the result as the font information is important there. Did you find a cause or workaround?

**Comment by borriglione** [comment]
@tkrah unfortunately not. We switched to TrueType-fonts wherever possible.

**Comment by tkrah** [comment]
@borriglione Bummer, but thanks for the feedback. The font which fails there is already a TrueType font, but for a reason unknown yet, it fails to be embedded correctly. Unfortunately that topic has not too  much traction - seems I am going to use one of the system fonts instead of a custom TrueType one.

**Comment by borriglione** [comment]
@tkrah Alternatively you can edit the font file itself and try to add missing meta informations. It's a bit of work but can be an option

**Comment by tkrah** [comment]
@borriglione After digging around, at least for me it seems to be a new chrome issue.
Using  Chrome for Testing version 129.0.6668.100 I get this:

```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes      4  0
BAAAAA+CourierNewPSMT                CID TrueType      Identity-H       yes yes yes      5  0
CAAAAA+ArialMT                       CID TrueType      Identity-H       yes yes yes      6  0
DAAAAA+JustAnotherHand-Regular       CID TrueType      Identity-H       yes yes yes      8  0
EAAAAA+Arial-BoldItalicMT            CID TrueType      Identity-H       yes yes yes     11  0
```

While version 130.0.6723.58 does result in:

```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes      4  0
BAAAAA+CourierNewPSMT                CID TrueType      Identity-H       yes yes yes      5  0
CAAAAA+ArialMT                       CID TrueType      Identity-H       yes yes yes      6  0
CAAAAA+ArialMT                       CID TrueType      Identity-H       yes yes yes      7  0
[none]                               Type 3            Custom           yes no  yes      8  0
CAAAAA+ArialMT                       CID TrueType      Identity-H       yes yes yes      9  0
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes     10  0
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes     13  0
AAAAAA+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes     14  0
EAAAAA+Arial-BoldItalicMT            CID TrueType      Identity-H       yes yes yes     15  0
```

Nothing else changed, some font files etc., just a version switch and it is broken. I can't pin down *what* in 130.x does cause this and if it is a known bug / regression / feature but at least I can downgrade to the old one as a workaround for the moment and try to address this issue upstream.

**Comment by AnshDubey1999** [comment]
I am running into this at the moment. @tkrah did you end up finding a fix? 

For me, all of the fonts seem like 
[none]                               Type 3            Custom           yes no  yes      8  0.

**Comment by tkrah** [comment]
> I am running into this at the moment. [@tkrah](https://github.com/tkrah) did you end up finding a fix?
> 
> For me, all of the fonts seem like [none] Type 3 Custom yes no yes 8 0.

Actually yes. It is just a bug in pdffonts of poppler, you need a patch to display the font name instead of none, but it is embedded correctly. E.g. Ubuntu 22.04 does miss that pstch, 24.04 works and does show the font name correctly.

For the change from TrueType to Type3, that is a change in the skia pdf engine of chrome itself how to embed the font, which is not a bug, discussed that upstream in a bug ticket with the developers.

So nothing wrong here at all ;-).

**Comment by ufresh2013** [comment]
I try to embed the **Noto Sans** font in PDF generation with Puppeteer because it is open source.

I have figured out how to properly embed fonts in PDF, and it works for me.

Here’s what needs to be done:

1. Install the Noto Sans font on your Windows computer. Use **static .ttf** font files, not **variable** font files. Variable fonts cannot be embedded into PDF correctly; they will be converted to **Type 3 fonts** instead.
If you download Noto Sans from Google Fonts, use the font files located in the `/static` folder instead of the variable font files.

2. Install the font as a Windows system font for **all users**.
Do **not** copy and paste the font files into the `C:\Windows\Fonts` folder directly, and do **not** install them without proper permissions.
Grant **full permissions** to the font files; otherwise, Puppeteer will not have access to read them.

3. If you want to use variable fonts, inject the font files directly using CSS `@font-face`. ex: "Noto Color Emoji", it's a variable font.

After install font correctly, here is my css code:
```css
.some-div {
    font-family: 'Noto Sans', 'Noto Sans Thin', 'Noto Sans Thai', 'Noto Sans SC',
    'Noto Sans TC', 'Noto Sans KR', 'Noto Sans Arabic', 'Noto Sans Devanagari',
    'Noto Sans Hebrew', 'Noto Color Emoji';
}

@font-face {
  font-family: 'Noto Color Emoji';
  src: url('./NotoColorEmoji-Regular.ttf') format('truetype');
}
```
