### ISSUE TITLE
recapcha click

### ISSUE THREAD

**Issue by chosserlonger1** [puppeteer/puppeteer#7439]
Hello! Please help me. How can I click on this square to go to the solution of the captcha? I've already tried everything!
![image](https://user-images.githubusercontent.com/87817223/126650973-c72835ce-d030-43e9-9971-71943e329656.png)
![image](https://user-images.githubusercontent.com/87817223/126651050-6cb57ce3-467c-438a-8091-75916c291a53.png)

**Comment by Vordlex** [comment]
You have 2 ways to do that
1. Create an extension that detects this iframe by url (window.location.url) and if it is recaptcha, you click and do whatever you want. This is the bad way because you can't run extensions with headless.

2. In puppeteer, you can wait for iframe selector and when it exists, you pass it to an variable like that:

```
    await page.waitForSelector("iframe")
    const elementHandle = await page.$("#free_play_recaptcha > form > div > iframe")
    const iframe = await elementHandle.contentFrame()
    
    //now iframe is like "page", and to click in the button you can do this
    await iframe.click("#recaptcha-anchor > div.recaptcha-checkbox-border")
    //or
    await iframe.evaluate(() => {
        document.querySelector("#recaptcha-anchor > div.recaptcha-checkbox-border").click()
    })
```
