### ISSUE TITLE
`element.screenshot()` captures wrong area in non-headless mode

### ISSUE THREAD

**Issue by stracker-phil** [puppeteer/puppeteer#7514]
### Steps to reproduce

When using `element.screenshot()` Puppeteer produces different results in headless/non-headless mode. The headless screenshot is correct, the non-headless image captures the wrong screen region.

* Puppeteer version: 10.2.0
* Platform / OS version: MacOS BigSur (11.5.2)
* URLs (if applicable): -
* Node.js version: v14.15.4

#### What steps will reproduce the problem?

Use the following test script to generate two screenshots:

```js
const puppeteer = require('puppeteer');

async function test_screenshot(browser, name) {
  const page = await browser.newPage();
  await page.goto('https://google.com');

  await page.waitForSelector('.W2aPtb');
  const logo = await page.$('.W2aPtb');
  await logo.screenshot({path: name});
  await browser.close();
}

// Testcase 1: Screenshot in headless mode.
(async () => {
  const browser = await puppeteer.launch({ headless: true });
  await test_screenshot(browser, 'image-headless.png');
})();

// Testcase 2: Screenshot in non-headless mode.
(async () => {
  const browser = await puppeteer.launch({ headless: false });
  await test_screenshot(browser, 'image-not-headless.png');
})();
```

#### Result 

The above snippet **should** result in identical two images, but the result is the following:

* image-headless.png (correct)  
    ![](https://content.screencast.com/users/Philipp-Stracker/folders/Snagit/media/49051feb-91c5-442c-a002-56603630e107/image-headless.png)

* image-non-headless.png (wrong)  
    ![](https://content.screencast.com/users/Philipp-Stracker/folders/Snagit/media/e4a7d3ef-0eb0-40b7-be64-3106b5ace279/image-not-headless.png)  
    Image dimensions are correct, but the snap-region is too far down/right

Comparison:

![](https://camo.githubusercontent.com/fa4b83a3d252d83da71f3927462b11fe43243636b20f3589b79f6606fe0294eb/68747470733a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f5068696c6970702d53747261636b65722f666f6c646572732f536e616769742f6d656469612f39373531393564612d383865622d346264362d393662632d3330366166323735333666362f676574456c656d656e7453637265656e73686f742532306275672e6a7067)

**Comment by ashleynewson** [comment]
I also encountered this issue. The offset appears to be equal to the displacement of the viewport from the top-left corner of the physical display. (Or, at least that's how it appears when using a single-monitor X11 setup). If I move the window to align the viewport with the screen's corner, the screenshot captures the correct region.

I believe it has been broken since puppeteer v10.2.0, due to the following change:

https://github.com/puppeteer/puppeteer/pull/7390/files#diff-3c9735f4a6d946de9c02aef89aa2feb6d3dfd8c7f524aeaffed3967e52a85560L426

Prior to this, puppeteer used the similar `layoutViewport` property, which (as far as I've tested) produced `pageX` and `pageY` values of `0` (in the absence of scrolling). This change switched to using `cssLayoutViewport`, which (as far as I've tested) sets `pageX` and `pageY` to the displacement of the viewport from the corner of the screen (in the absence of scrolling). When scrolling is involved, these values both seem to increase by the scrolled amount (though, the intended and actual metric is unclear to me).

These `pageX` and `pageY` values are subsequently added to the clipping position (`clip.x`, `clip.y`), hence why the screenshot region is misaligned.

When running in a headless environment, this displacement from the corner of the screen appears irrelevant, with `pageX` and `pageY` equal to 0 (in the absence of scrolling), hence why it works fine in a headless setup.

I'm not familiar with the intended semantics of `layoutViewport` and `cssLayoutViewport`. Their documentation is slightly confusing:

https://chromedevtools.github.io/devtools-protocol/1-3/Page/#method-getLayoutMetrics
https://chromedevtools.github.io/devtools-protocol/1-3/Page/#type-LayoutViewport

> offset relative to the document (CSS pixels)

I would have assumed that should mean zero when there is no scrolling involved, as the document would be placed exactly where the physical viewport is. It's very unclear to me how scrolling when zoomed _should_ affect this value.

I'm not certain as to whether this is a bug originating from puppeteer, the dev tools protocol, or chromium.

**Comment by BeleganStartup** [comment]
I'm using version 19.1.1

only when headless is false, I get the correct screenshot.

(Wrong [headles => true] : What I get)
![headless:true](https://i.ibb.co/LRypmYm/m2c.png)

(Correct [headles => false] : What I want )
![headless:true](https://i.ibb.co/h82rH3t/m2.png)

**Comment by juliansyahrifqi** [comment]
I'm using v22.2.0 and solve by using ``boundingBox`` function. See [https://pptr.dev/api/puppeteer.elementhandle.boundingbox](https://pptr.dev/api/puppeteer.elementhandle.boundingbox)

The ``boundingBox`` is return ``{ x: positionX, y: positionY, width: widthOfElement, height: heightOfElement }``. It can use for the ``clip`` option for the ``screenshot`` function

```javascript
const element = await mainFrame.$("element-selector");
const boundingBox = await element.boundingBox();

if (boundingBox) {
  const clip = {
    x: boundingBox.x,
    y: boundingBox.y,
    width: boundingBox.width,
    height: boundingBox.height,
  };
  await page.screenshot({ path: "image.png", clip: clip });
}

```
