### ISSUE TITLE
TypeError: Cannot read property '_launcher' of undefined

### ISSUE THREAD

**Issue by akornatskyy** [puppeteer/puppeteer#7529]
puppeteer-core: 10.2.0
nodejs: v16.8.0
typescript: 4.4.2

```
TypeError: Cannot read property '_launcher' of undefined
    at null.launch (.../node_modules/puppeteer-core/src/node/Puppeteer.ts:155:17)
```

it works as expected with typescript 4.3.5.

**Comment by akornatskyy** [comment]
This bug can be reproduced when you import `launch` from `puppeteer-core`, e.g.

```typescript
import {launch} from 'puppeteer-core';

// somewhere later in your code
async f() {
  await launch(options);
}
```
More details are in Typescript 4.4 Announcement, [More-Compliant Indirect Calls for Imported Functions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#more-compliant-indirect-calls-for-imported-functions).

Workaround:

```typescript
import puppeteer from 'puppeteer-core';

// somewhere later in your code
async f() {
  await puppeteer.launch(options);
}
```

**Comment by timocov** [comment]
It seems that puppeteer exports a class instance as a default export, but in the types all functions of the class are just simple functions (they don't require to provide a context). I'd say that the bug is in puppeteer package which accidentality does wrong type of export (at least in types). So probably types should be different (instead of set of function it should be a class, which you obviously cannot import with `import {} from` statement)?

**Comment by timocov** [comment]
So basically [this line](https://github.com/puppeteer/puppeteer/blob/78941e562c28c8b54626a3c9dc4cd2e7a92a7074/src/api-docs-entry.ts#L99) is wrong, since [the entry point exports](https://github.com/puppeteer/puppeteer/blob/78941e562c28c8b54626a3c9dc4cd2e7a92a7074/src/node.ts#L23) a class instance, not separated functions.

**Comment by mcshaman** [comment]
This is making it rather difficult stub `launcher`, I can't pass it as a variable.

```javascript
// mocha.test.js
import puppeteer from 'puppeteer'

const { launch } = puppeteer

it('test', () => {
	launch()
})
```

```
$ npx mocha ./mocha.test.js
```

```
  1) test

  0 passing (4ms)
  1 failing

  1) test:
     TypeError: Cannot read property '_launcher' of undefined
      at launch (node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:125:21)
      at Context.<anonymous> (file:///Users/McShaman/demo/mocha.test.js:6:2)
      at processImmediate (node:internal/timers:463:21)
```

**Comment by Sjonnie2nd** [comment]
I was using:
import {Browser, launch, Page, PDFOptions, PDFMargin} from 'puppeteer'
and
launch()
gave the same "_launcher" error.

Trying to change it to:
import puppeteer from 'puppeteer'
gives a typescript errror: "..has no default export"

Simply changing it to
import * as puppeteer from 'puppeteer'
worked for me.
(by fe. calling puppeteer.launch())

**Comment by Whobeu** [comment]
I just rebuilt a project under 4.4.4 that I last touched in August. When I ran the resultant JavaScript, I got this error as well. Applied @Sjonnie2nd change above to "import * as puppeteer from 'puppeteer'" and it works fine. I kept my separate imports of LaunchOptions and SetCookie (import { LaunchOptions, SetCookie } from 'puppeteer'). Only "launch" requires the "puppeteer" prefix.

Side note: looking at the generated code by pre-4.4, the output is:

`const browser = await puppeteer_1.launch(browserOptions);`

With 4.4+, the output is:

`const browser = await (0, puppeteer_1.launch)(browserOptions);`

It looks like Typescript has decided to change it's output.
