### ISSUE TITLE
Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by zhanto97** [puppeteer/puppeteer#7562]
https://github.com/puppeteer/puppeteer/blob/491614c7f8cfa50b902d0275064e611c2a48c3b2/src/common/HTTPResponse.ts#L154

I am getting "Cannot read property 'body' of undefined". In which scenarios can 
`await this._client.send('Network.getResponseBody', {
    requestId: this._request._requestId,
}); ` 
return undefined?

**Comment by tuckerconnelly** [comment]
This happened for me when the page redirected and there technically was no response. Chrome gets rid of response data when the page redirects (you can confirm this in the Network tab in devtools). Solution would be to prevent the redirect if possible, or try to just use fields that are still available like `response.statusCode()`.

**Comment by jschfflr** [comment]
@zhanto97 Thanks for taking the time to report this issue!
It sounds like we could be more helpful in this case and throw a more actionable exception. Happy to look into this!

**Comment by jschfflr** [comment]
@tuckerconnelly or @zhanto97 Could you find a minimal reproduction for this error?

**Comment by jschfflr** [comment]
I'm closing this for now as it's currently not actionable. For redirects you should get an `Response body is unavailable for redirect responses` error. Feel free to reopen when new insights emerge :)

**Comment by cam-duncan** [comment]
@jschfflr I think what @tuckerconnelly was referring to was not that the response you're _listening_ to is a redirect, but that the page redirects as a side effect to what you're looking for.

For example:

Take a typical login page. You may want to listen for the response body of the login page if the status is always returned as a 200. In this case, you'd likely listen for the auth call and then try to parse the data. However, since login was successful, the browser redirected you to the homepage of the application as a _side effect_ of a successful login. Thus, when you try to parse the response to the auth request you receive a "Cannot read properties of undefined (reading 'body')" type error (Node).

**Comment by vahidd** [comment]
for me, this happened because I was trying to get the body of the preflight (OPTION) request. fix:
```javascript
page.on('response', res => {
    if (res.url().includes('PATH') &&
      res.headers()['content-length']) {
      res.json().then(result => {
        console.log(result);
      });
    }
  });
```
