### ISSUE TITLE
[Bug]: Page breaks causing content being hidden and overflowed

### ISSUE THREAD

**Issue by Richacinas** [puppeteer/puppeteer#7593]
### Bug description

Steps to reproduce the problem:

1. Rendering a `table` with rows and cells inside and some text content.
2. Make it so a page break is in the middle of this table.
3. See how it gets cut and overflowed (after the page break)

![Captura de pantalla de 2021-09-23 13-03-47](https://user-images.githubusercontent.com/7046504/134496436-f7ff1a2a-bdac-4d5f-9625-c5989cf08db7.png)

### Puppeteer version

5.5.0

### Node.js version

14.15.0

### npm version

6.14.8

### What operating system are you seeing the problem on?

Linux

**Comment by Richacinas** [comment]
I have tried giving `display:block` to every `td` and `tr` inside the `table` element, without success. It doesn't matter what combination of CSS I try. The problem keeps happening.

**Comment by jschfflr** [comment]
@Richacinas Thanks for your report! 
As Puppeteer is not directly responsible for generating the PDFs but only fetches them from Chromium - could you file a bug report there and reference this issue? You can find the Chromium bug tracker at https://crbug.com.
I'll close the issue here as it's not actionable from the Puppeteer side.

**Comment by sayo96** [comment]
I'm running into the same problem. Is there a fix for this
