### ISSUE TITLE
Evaluation failed ( when inside child process)

### ISSUE THREAD

**Issue by thetutlage** [puppeteer/puppeteer#763]
So I have trying to use puppeteer for writing tests. Everything worked great, until I started using `nyc` for coverage reports.

Everytime I run puppeteer as child process of `nyc`, it throws an exception shared below.

```js
  Error: Evaluation failed: ReferenceError: cov_1oomibe77f is not defined
    at e (<anonymous>:1:27)
    at HTMLFormElement.<anonymous> (<anonymous>:1:93)
    at ElementHandle.evaluate (/Users/myapp/node_modules/puppeteer/lib/ElementHandle.js:56:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

To isolate the issue, I created this repo https://github.com/thetutlage/puppeteer-tests. Which has an `index.js` file to start the browser and submit a form.

1. Now if run the file as `node index.js` it works great. 
2. But if I run it as `./node_modules/.bin/nyc node index.js` the same exception is thrown. 100% of times reproducible. 

I am trying to run my node process as a child process but not under `nyc` to see if the problem persist, but still want to create an issue to have some feedback from you guys too.

Thanks

**Comment by JoelEinbinder** [comment]
This looks like it is because `nyc` messes with the JavaScript in order to provide coverage data, but we run `.toString()` on some of functions and send the strings into the page.

**Comment by thetutlage** [comment]
Yes, I tried running the main node process inside a child process and everything works great. For sure it has something to do with `nyc` or any other instrumentation tools. 

Would you mind keeping this issue open, meanwhile I dig into `nyc` codebase to understand which part causes this issue?

**Comment by aslushnikov** [comment]
@thetutlage from a brief analysis, that's what I see.
NYC/istanbul does the following:
- sets up a global `cov_XXX` variable in the node.js context
- transforms the code so that every line writes to the `cov_XXX` variable, reporting coverage

Puppeteer is a node.js library, but it runs certain parts of the code in a browser context (for example, the [`page.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args) method does just this).
- NYC knows nothing about browser, thus it doesn't setup the `cov_XXX` variable there.
- NYC also doesn't know which code Puppeteer will execute in browser context and which will be run in node.js, so it just transforms everything

As a result, it tries to refer to the `cov_XXX` variable from-inside the browser, and this naturally yields an exception during code evaluation:
```js
  Error: Evaluation failed: ReferenceError: cov_1oomibe77f is not defined
    at e (<anonymous>:1:27)
    at HTMLFormElement.<anonymous> (<anonymous>:1:93)
    at ElementHandle.evaluate (/Users/myapp/node_modules/puppeteer/lib/ElementHandle.js:56:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

> Would you mind keeping this issue open, meanwhile I dig into nyc codebase to understand which part causes this issue?

I don't think there's anything we can do in puppeteer to fix this issue. Do you still want this issue to be open?

**Comment by thetutlage** [comment]
Nope, it's fine to close the issue. Thanks for sharing insights 👍

**Comment by felixfbecker** [comment]
@thetutlage Did you find any workaround? E.g. maybe use `// istanbul:ignore` comments around `evaluate()`, or exclude the test files from instrumentation completely?

**Comment by felixfbecker** [comment]
It seems that ignoring doesn't work because of https://github.com/istanbuljs/nyc/issues/890

**Comment by 3p3r** [comment]
I just wanted to report that ignoring does work. I am able to work around this issue by putting `/* istanbul ignore next */` at the beginning of every `page.evaluate` call:

```
/* istanbul ignore next */
await page.evaluate(data => { return data*2; }, 2);
```

**Comment by frantallukas10** [comment]
Hi, I have same problem, here is my project https://github.com/frantallukas10/youtu-get
I try to create test for my function where I use puppeteer for get every title and id from youtube playlist
here is my test: https://github.com/frantallukas10/youtu-get/blob/master/tests/test.js
and here is my function: https://github.com/frantallukas10/youtu-get/blob/master/src/main.js

thank you for your help or information... =)

**Comment by frantallukas10** [comment]
maybe I have same problem https://github.com/GoogleChrome/puppeteer/issues/5175#issue-523897962

anybody can help me please?
