### ISSUE TITLE
Clinking Link opens pdf in browser, how to save as file instead?

### ISSUE THREAD

**Issue by sfelice777** [puppeteer/puppeteer#7768]
I am using Puppeteer v11.0.0 with Chromium
I want this to work headed and headless.

I click a button that opens a PDF file in the browser.
After the PDF opens, in the DOM I see a tag like this <embed>

I'd like to intercept the request and just have the PDF save to my local disk without even opening in the browser if possible?
Thanks

**Comment by prmichaelsen** [comment]
I'm not sure this is a bug. The issue is puppeteer `page.pdf` generates links that assume puppeteer is running. I'd like to generate pdfs from html that use relative links that open new pdf files stored on local file system. This is something pdf supports. See https://stackoverflow.com/questions/17800596/relative-file-links-in-pdf-files

Is puppeteer source public? I'd like to modify the code myself just for my local env.

**Comment by OrKoN** [comment]
I aggree with @prmichaelsen it does not look as a bug to me because it's what the browser renders.
