### ISSUE TITLE
[Bug]: Firefox response buffers not working

### ISSUE THREAD

**Issue by lambdaupb** [puppeteer/puppeteer#7772]
### Bug description

Steps to reproduce the problem:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  try {
  const page = await browser.newPage();
  const cdp = await page.target().createCDPSession();
  cdp.on('Network.loadingFinished', async req => {
    const rr = await cdp.send('Network.getResponseBody', {'requestId': req.requestId});
    console.log("cdp response "+rr.body.substring(0, 10));
  });
  cdp.send('Network.enable', {'maxTotalBufferSize':1024*1024*10, 'maxResourceBufferSize':1024*1024*10});
  page.on('response', async resp => {
    try {
      console.log("intercept url: "+resp.url());
      const buf = await resp.buffer();
      console.log(resp.url()+": -> "+buf.toString('base64').substring(0, 30)+"...");
    } catch (e) {
      console.log(e);
    }
  });
  const response = await page.goto('http://danluu.com/', {waitUntil:"domcontentloaded"});
  const cont = await page.content();
  console.log("nav content: "+cont.toString().substring(0,10))
  await new Promise(r => setTimeout(r, 2000));
  } finally {
    await browser.close();
  }
})();
```

## Firefox 95

```
% PUPPETEER_PRODUCT=firefox PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true PUPPETEER_EXECUTABLE_PATH=/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox-bin node test.js
intercept url: http://danluu.com/
nav content: <html><hea
intercept url: http://danluu.com/favicon.ico
```

## Chromium 

```
% PUPPETEER_PRODUCT=chrome PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true PUPPETEER_EXECUTABLE_PATH=/Users/xxx/Downloads/chrome-mac/Chromium.app/Contents/MacOS/Chromium  node test.js
intercept url: http://danluu.com/
cdp response <style>.pd
http://danluu.com/: -> PHN0eWxlPi5wZHt3aWR0aDo0ZW07Zm...
nav content: <html><hea
```

Probably related: #7344

### Puppeteer version

11.0.0

### Node.js version

v16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by lambdaupb** [comment]
The following works in playwright.

```js
const {firefox} = require('playwright');

(async () => {
  const browser = await firefox.launch();
  try {
  const page = await browser.newPage();
  const response = await page.goto('http://danluu.com/', {waitUntil:"domcontentloaded"});
  const buf = await response.body();
  console.log("buffer -> "+buf.toString('base64'));
  const cont = await page.content();
  console.log("nav content: "+cont.toString().substring(0,10))
  await new Promise(r => setTimeout(r, 2000));
  } finally {
    await browser.close();
  }
})();
```

## output
```
 % node testpw.js 
buffer -> PHN0eWxlPi5wZHt3aWR0aDo0ZW07ZmxleC1zaHJpbms6MDtwYWRkaW...
nav content: <html><hea
```

**Comment by lambdaupb** [comment]
Seems to be due to https://bugzilla.mozilla.org/show_bug.cgi?id=1549459

**Comment by whimboo** [comment]
It's also `Network.loadingFinished` which is not implemented yet. See https://bugzilla.mozilla.org/show_bug.cgi?id=1549506 for details.

Note that it will be less likely that these APIs will get implemented at all for CDP.

**Comment by ciekawy** [comment]
any chance to access the response body somehow on firefox? 

as I see on some other firefox patch https://phabricator.services.mozilla.com/D74579, there is a method which should make the body updated 
```
_onResponseFinished(browser, httpChannel, body) {
    const responseStorage = this._browserResponseStorages.get(browser);
    if (!responseStorage) {
      return;
    }
    responseStorage.addResponseBody(httpChannel, body);
    this.emit("requestfinished", httpChannel, {
      requestId: requestId(httpChannel),
      errorCode: getNetworkErrorStatusText(httpChannel.status),
    });
  }
```

**Comment by brandonros** [comment]
I kind of "went deep" on this one

The bug is in these files (I think):

https://github.com/mozilla/gecko-dev/blob/091b275909bfa1c65bc6650b5af7ce1bc0f277fa/remote/cdp/observers/NetworkObserver.sys.mjs#L298

https://github.com/mozilla/gecko-dev/blob/091b275909bfa1c65bc6650b5af7ce1bc0f277fa/remote/cdp/domains/parent/Network.sys.mjs#L430

HTTPResponse.buffer() waits on this.#bodyLoadedPromise: https://github.com/puppeteer/puppeteer/blob/931d4fced52aefbefdc8b21edfe3d1528e4e448b/packages/puppeteer-core/src/common/HTTPResponse.ts#L198
  this.#bodyLoadedPromise is provided by this.#bodyLoadedPromiseFulfill: https://github.com/puppeteer/puppeteer/blob/931d4fced52aefbefdc8b21edfe3d1528e4e448b/packages/puppeteer-core/src/common/HTTPResponse.ts#L75
    this.#bodyLoadedPromiseFulfill is provided by _resolveBody(): https://github.com/puppeteer/puppeteer/blob/931d4fced52aefbefdc8b21edfe3d1528e4e448b/packages/puppeteer-core/src/common/HTTPResponse.ts#L129
      _resolveBody() is only ever called by NetworkManager:
        sad path (handleRequestRedirect): https://github.com/puppeteer/puppeteer/blob/931d4fced52aefbefdc8b21edfe3d1528e4e448b/packages/puppeteer-core/src/common/NetworkManager.ts#L462
        sad path (emitLoadingFailed): https://github.com/puppeteer/puppeteer/blob/931d4fced52aefbefdc8b21edfe3d1528e4e448b/packages/puppeteer-core/src/common/NetworkManager.ts#L624
        happy path (emitLoadingFinished): https://github.com/puppeteer/puppeteer/blob/931d4fced52aefbefdc8b21edfe3d1528e4e448b/packages/puppeteer-core/src/common/NetworkManager.ts#L595

NetworkManager.emitLoadingFinished is not being called (I verified this by adding a bunch of logs), aka Firefox "CDP" client is not sending it:
  https://github.com/mozilla/gecko-dev/blob/091b275909bfa1c65bc6650b5af7ce1bc0f277fa/remote/cdp/domains/parent/Network.sys.mjs#L430 it sends Network.responseReceived here but never calls `Network.loadingFinished`

I see it sending `requestfinished` here https://github.com/mozilla/gecko-dev/blob/091b275909bfa1c65bc6650b5af7ce1bc0f277fa/remote/cdp/observers/NetworkObserver.sys.mjs#L298 but that code is 4 years old. I do

I think the fix here would be somebody on the Mozilla/gecko-dev/Firefox team expanding `gecko-dev/remote/cdp/observers/NetworkObserver.sys.mjs` + `gecko-dev/remote/cdp/domains/parent/Network.sys.mjs` to emit the missing CDP `Network.loadingFinished` event.

**Comment by whimboo** [comment]
Thanks for tracking all this down @brandonros! But sadly this protocol is only in maintenance mode right now, which means we won't add new features like that one.

Instead we are focusing on the implementation of WebDriver BiDi which soon will get network events as well. And at some point Puppeteer will fully switch to that protocol as well.

@OrKoN I would suggest that we close this issue. Do you agree?

**Comment by OrKoN** [comment]
Yes, fine by me.
