### ISSUE TITLE
[Bug]: current version of node-fetch has high severity vulnerability CVE-2022-0235

### ISSUE THREAD

**Issue by humble-barnacle001** [puppeteer/puppeteer#7921]
### Bug description

Steps to reproduce the problem:

1. npm audit

See CVE-2022-0235

### Puppeteer version

13.1.1

### Node.js version

16

### npm version

8.1

### What operating system are you seeing the problem on?

Linux, Windows

**Edit:** patch released https://github.com/puppeteer/puppeteer/releases/tag/v13.1.2

**Comment by lgarron** [comment]
In particular, since Puppeteer pins exact dependency versions, GitHub and various tools will assume that any other version of a transitive dependency is incompatible:

<img width="948" alt="Screen Shot 2022-01-22 at 14 41 05" src="https://user-images.githubusercontent.com/248078/150657690-03e59782-5cb6-4547-9bc2-93d86a4b328c.png">

Also note that:
- `npm install node-fetch@3.1.1` will not address the security alert from `npm audit`.
- `npm audit fix --force` will *downgrade* Puppeteer to `v5.3.1` to avoid the vuln.

So this isn't exactly easy to address in downstream codebases without a new Puppeteer version that avoids the vulnerable dependency versions.

A comment by @jschfflr https://github.com/puppeteer/puppeteer/pull/7717#issuecomment-951988594 suggests that a simple upgrade might have compatibility issues:

> @jackfranklin It looks like node-fetch only supports esm starting with v 3.0.

**Comment by humble-barnacle001** [comment]
Updating to v2.6.7 fixes the issue

**Comment by Trott** [comment]
For several hours, the GitHub CVE/tooling reported that this was only fixed in node-fetch@3.1.1. It is also fixed in node-fetch@2.6.7 and GitHub/npm tooling and materials have been updated to show that, so this should be a pretty straightforward/easy fix at this point.

**Comment by humble-barnacle001** [comment]
Should be fixed by #7924

**Comment by PythonCoderAS** [comment]
#7924 has fixed it but it won't be patchable by dependabot without a new patch release.

**Comment by drealecs** [comment]
Can we also patch the other major versions? I mean, cherry-pick https://github.com/puppeteer/puppeteer/pull/7924/commits/2a8d94cd65c4e2275c3a3ea392652ccd98446bcc
As per https://github.com/puppeteer/puppeteer/blob/main/docs/api.md that means:
- 11.0.0 to 11.0.1 as the last one supporting v93 chromium.
- 12.0.1 to 12.0.2 as the last one supporting v97 chromium.

In my use case, we are running the v93 version of chromium as it is available on latest alpine.

**Comment by drealecs** [comment]
Following the PR discussion(https://github.com/puppeteer/puppeteer/pull/7924), I end up using the overrides feature from npm 8.3+ and added to `package.json`:
```
  "overrides": {
    "puppeteer": {
      "node-fetch@2.6.5": "2.6.7"
    }
  },
```

**Comment by humble-barnacle001** [comment]
Patch released in https://github.com/puppeteer/puppeteer/releases/tag/v13.1.2

**Comment by lgarron** [comment]
I don't think it's been mentioned here yet, but `v13.1.2` is out with the dependency update:

https://github.com/puppeteer/puppeteer/releases/tag/v13.1.2

Thanks, @OrKoN! ❤️
