### ISSUE TITLE
Data in Response.buffer() is broken when charset in Content-Type not set correctly

### ISSUE THREAD

**Issue by Kxrr** [puppeteer/puppeteer#795]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Mac OS 10.11.3
* URLs (if applicable): 

**What steps will reproduce the problem?**

1. Make a web server response the JSON data contains some unicode string
2. The Server will send the JSON data to client with wrong Content-Type which is ``text/plain`` in the example
3. The  ``puppeteer`` request the server and received the data, but the data in  puppeteer's Response.buffer() is broken(not equal to the original data)

Here's the example scrpit to reproduce the issue:

```javascript
const http = require('http');
const puppeteer = require('puppeteer');

const ORIGINAL_DATA = Buffer.from(JSON.stringify({'msg': '测试'}));


function serve() {
    http.createServer(function (req, res) {
        // The correct header should be 'application/json; charset=utf-8'
        // but I change it to 'text/plain' to  REPRODUCE THE BUG
        res.setHeader('Content-Type', 'text/plain');
        res.writeHead(200);
        res.end(ORIGINAL_DATA);
    }).listen(8001);

}

async function responseSuccess(res) {
    let dataReceived = await res.buffer();
    console.log('Received:\n', dataReceived);
    console.log('Original:\n', ORIGINAL_DATA);
    console.log('\n')
}

async function doRequest() {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    page.on('response', responseSuccess);
    let res = await page.goto('http://localhost:8001');
}


serve();
doRequest();
```

**What is the expected result?**

Here's the output from console.log in the example script 

```
Received:
 <Buffer 7b 22 6d 73 67 22 3a 22 e6 b5 8b e8 af 95 22 7d>
Original:
 <Buffer 7b 22 6d 73 67 22 3a 22 e6 b5 8b e8 af 95 22 7d>
```

**What happens instead?**

```
Received:
 <Buffer 7b 22 6d 73 67 22 3a 22 c3 a6 c2 b5 e2 80 b9 c3 a8 c2 af e2 80 a2 22 7d>
Original:
 <Buffer 7b 22 6d 73 67 22 3a 22 e6 b5 8b e8 af 95 22 7d>
```

**Comment by Kxrr** [comment]
Hey guys, will anyone take a little time to look into this issue?

**Comment by aslushnikov** [comment]
@Kxrr filed upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=771825

**Comment by JohnBruce** [comment]
not sure if this is related, or separate, or new, but on sites where an explicit encoding is set, IE.  utf8, and there happen to be characters from some other encoding set in the pages content, when I use page.content() to get the page contents, I get a truncated version of the page contents.  Whats interesting, is that if I take a look at response buffer, the full html content is there.  Unfortunately, the response buffer is pretty useless on a site where you're trying to look at the page after some javascript has executed.  Some example sites where this is happening:

//this guy is doing some pretty intense stuff to stop crawlers, so i'm listing 2
https://www.supply.com/  

//might need to set a non headless chrome useragent and / or wait a few seconds because of redirects
http://www.mysupermarket.co.uk/grocery-categories/Adhesives_in_ASDA.html

**Comment by ggicci** [comment]
Why would this happen? 😕 In some cases, this bug makes puppeteer useless if the user can't change the server's wrong behavior for some reason. Looking forward a fix :D

**Comment by heroboy** [comment]
upup.
The upstream issue was closed. They suggest use `Fetch.getResponseBody`.

**Comment by rekatrina** [comment]
I have encountered this problem, too.  Any solution?

**Comment by heroboy** [comment]
@aslushnikov as the upsteam issue marked wontfix. What will do at the puppeteer side?
