### ISSUE TITLE
[Bug]: page.type is very slow when the text is too long

### ISSUE THREAD

**Issue by clyan** [puppeteer/puppeteer#8051]
### Bug description

1. await page.type(`span[lang=${from}] textarea`, text);
The text is very long， He typed one by one like a typewriter, take a long time

### Puppeteer version

11.0.0

### Node.js version

v14.18.0

### npm version

6.14.15

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
I think this is intended for this command: it types characters one by one as fast as it can. E.g., this command tries to emulate a real user behaviour. It is also possible that there will be a slow down caused by the target page if the element does some keydown/keyup handling.

If you want to instantly enter a text, it's better to use `element.evaluate((el, text) => el.value = text, text)` if the input allows that.
