### ISSUE TITLE
SVG computed width incorrect

### ISSUE THREAD

**Issue by staab** [puppeteer/puppeteer#814]
This is probably more a problem with headless Chrome, but I'm a bit out of my depth, and since I'm using the custom buildpack referenced in https://github.com/GoogleChrome/puppeteer/issues/290#issuecomment-323254964 I figured I'd start here.

The problem is that headless chrome reports both `getComputedTextWidth` and `getBBox().width` differently from macOS chrome (and incorrectly). This could certainly be user error, so let me know if there are troubleshooting steps I should take.

### Steps to reproduce

* Puppeteer version: 0.10.2
* Platform / OS version: heroku-16 (Ubuntu 16.04.3 LTS)

You'll need nodejs, yarn, npm, and heroku-cli installed to run the repro steps.

1. git clone git@github.com:staab/puppeteer-getComputedTextLength.git
2. cd puppeteer-getComputedTextLength
3. yarn
4. yarn start - this will give you the computed width on your local machine - on OSX Sierra it gives me:

```
tspan.getComputedTextLength 74.8671875
tspan.getBBox().width 74.890625
```

5. bash deploy-to-heroku.sh
6. heroku logs | grep tspan | awk '{print $3" "$4}' - this gives you the computed width on heroku - I get

```
tspan.getComputedTextLength 92.9140625
tspan.getBBox().width 93.90625
```

**What is the expected result?**

For getComputedTextLength and getBBox to return the same values across platforms.

**What happens instead?**

In different contexts I've seen anywhere from 12% (21px) to 24% (12px) difference.

**Comment by ebidel** [comment]
Thanks for the repro. Anything related to rendering differences between mac and linux would indeed be a headless chrome bug. Mind filing at https://bugs.chromium.org/p/chromium/issues/list and linking to that from here?

**Comment by tjunnone** [comment]
@staab Your example does not specify a font, so the default text size will differ on macOS and Ubuntu, leading to different bounding boxes. The system fonts available are also different on the systems, unless you use a webfont.

You can verify if this is the issue by using the page.screenshot Puppeteer API to screenshot the page on both systems, and verify the difference visually.

**Comment by aslushnikov** [comment]
@tjunnone this indeed looks like fonts issue. Font rendering depends heavily on the OS, so I wouldn't expect bounding boxes of text nodes to be the same.

**Comment by darkraincloud** [comment]
I'm having this problem with Puppeteer running with Jest in Windows. In my case, what I see is that code that works in the browser doesn't work in the tests. I'm trying to find line lengths of SVG text objects. I have tried three methods: getComputedTextLength(), getBBox(), and getBoundingClientRect(). 

For example, something that does NOT work is:
   var node = document.createTextNode("some text"),
         span = document.createElement('span'),
         width = 0;
 
   span.style.fontSize = size;
   span.style.fontFamily = fontFamily;
   span.style.fontWeight = weight;
   span.appendChild(node);
   
   width = span.getBBox().width;

The error that I get from Jest/Puppeteer with both getComputedTextLength() and getBBox() is "getBBox is not a function." It turns out that getBoundingClientRect is a function, but it returns a rectangle whose x, y, width, and height are all zero.

This all sort of makes sense, because I figure Puppeteer is running in headless mode, so there is no actual node that it can get the length of. In my code, I put in if-statement to route around the problem when getComputedTextLength does not exist. But it's annoying.

**Comment by aslushnikov** [comment]
> This all sort of makes sense, because I figure Puppeteer is running in headless mode, so there is no actual node that it can get the length of. 

@darkraincloud this doesn't sound right to me. Headless mode has nothing to do with the actual nodes and their existence.

From the code that you posted: you should create elements with SVG namespace using [`document.createElementNS`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS). Otherwise the getBBox won't be defined.

Hope this helps.

**Comment by fabswt** [comment]
`getBBox` and `getBoundingClientRect` are broken in Chrome, see https://bugs.chromium.org/p/chromium/issues/detail?id=349835
