### ISSUE TITLE
No page navigation lock ?

### ISSUE THREAD

**Issue by caddave** [puppeteer/puppeteer#823]
I'm looking for a page navigation lock feature or alternative like phantomjs has http://phantomjs.org/api/webpage/property/navigation-locked.html

**Comment by aslushnikov** [comment]
@davedmarketing no, there's no navigation lock for now. Could you please share your usage scenarios - why would you need one?

**Comment by caddave** [comment]
@aslushnikov For me I was looking into it for a site that had unpredictable behavior and was getting redirected randomly or elements with links popping up randomly and my script was clicking on them accidentally.

**Comment by GuilloOme** [comment]
here is my use case (close to @davedmarketing  one):

**Context**: Using puppeteer to inject a probe in a page and retrieving urls related to the given page.
**Requirements**: Staying on a the page as long as we do not have all the urls.
**Behavior**: The probe "click/hover/keystroke" every part of the page and it's commun to hit a "navigation away" action (through a `window.location='url'` or `window.location.href='url'`call)

**Comment by GuilloOme** [comment]
I finally found a workaround to this (ie. blocking navigation while retrieving the destination url)… with a [custom chrome extension](https://gist.github.com/GuilloOme/2bd651e5154407d2d2165278d5cd7cdb).

**But, because of #659, it CAN'T be used with `headless: false`.** Hopefully, this should be resolved with #872 .

**Why a chrome extension?**
*Short version*: because of DOM insolation
*Long version*: 
At the page level, we can block navigation away by hijacking the `window.onbeforeunload` event but we will not be able to know what is the destination. 
The only way (I found) to prevent navigation is to use the `chrome.webRequest.onBeforeRequest` event available at extension level because it provide a way to manipulate the request before it is issue to the network level (so before the navigation start).

**How it works?**
1. On a request related to "frame type" navigation, the extension block it.
1. the extension notify the content-script that a url have been blocked.
1. the content-script notify the page of the blocked url.
1. puppeteer can then retrieve the url from the page.

We need here a content-script to pass message between the extension and puppeteer (through the page)

here the snippet of the blocking logic in the [extension](https://gist.github.com/GuilloOme/2bd651e5154407d2d2165278d5cd7cdb): 
```javascript
function onBeforeRequestListener(details) {
    let currentTab = tabs[details.tabId]; // retrieving the current tab
     
    // blocking only when the request is for http and with different url
    if (currentTab.url.startsWith('http') && _compareUrls(details.url, currentTab.url)) { 
        console.warn(`Navigation to ${details.url} blocked.`); 

        // message the page about this blocked url
        chrome.tabs.executeScript(details.tabId, {file: 'content.js'}, function() {
            chrome.tabs.sendMessage(details.tabId, {url: details.url});
        });
        
        // redirect to nowhere
        return {redirectUrl: 'javascript:void(0)'};
    }
}
```
Full code available: https://gist.github.com/GuilloOme/2bd651e5154407d2d2165278d5cd7cdb

**Comment by aslushnikov** [comment]
@GuilloOme interesting approach! You can also implement this idea using request interception. This way you won't need to run extension.

**Comment by GuilloOme** [comment]
@aslushnikov, correct me if I'm mistaken:
I did check it but I couldn't find a way to differentiate a "navigation" request type from a "document" request type. The chrome API give me `main_frame` and `sub_frame` as a request type which is more precise than `document` provided by the DevTools Protocol. As I found out, the DevTools protocol identify the resource type`document` only based on the `mimeType` (see [my answer on stackoverflow](https://stackoverflow.com/questions/43405952/is-there-any-way-to-get-all-mime-type-by-the-resourcetype-of-chrome/47166602#47166602))

**Comment by sukhjitsingh-impactradius** [comment]
@aslushnikov rather than a navigation lock I wanted to click and open a new tab for each element on the page and setrequestinterception for each new page, but the request interception is not added in time to catch the initial redirect. I've attemped @GuilloOme's solution like above using chrome.webRequest but like he says above it lacks a way to connect the extension to the puppeteer code (or I'm not using it correctly). I've scoured the issues and stackoverflow, is there a way to set requestinterception at the browser level? If not, do you have any suggestions?
```
const page = await browser.newPage();
await page.goto("someurl");
let elements = page.$$('button'); // anchors, buttons, and any other elements to click
// targetcreated event fires once new page is opened
const newPagePromise = new Promise(fulfill => browser.once('targetcreated', target => fulfill(target.page())));
// click using middle button to open page in new tab
elements[0].click({button:'middle'});
// wait for newPage to be created from above promise
const newPage = await newPagePromise;

// gather requests from newly opened tab/page
if(newPage != null){
    newPage.setRequestInterception(true);
    newPage.on('request', interceptedRequest => {
        console.log(`-------InterceptedRequest.url: ${interceptedRequest.url}`);
        interceptedRequest.continue();
    });
}
```
^This is where I'm at right now, but again, hitting that newPage.on() too late.

**Comment by GuilloOme** [comment]
@sukhjitsingh-impactradius, communication between the extension and the node process is not straightforward  but possible, I did that [here](https://github.com/delvelabs/htcap/tree/migrate_from_PhantomJS_to_Chromium_headless/core/crawl/probe). 
To achieve that, you have to use messaging between the extension and the page (through the `content.js`, see: [l.22 of my gist](https://gist.github.com/GuilloOme/2bd651e5154407d2d2165278d5cd7cdb#file-example_navigation_away_test_case-html-L22)). Then, you have to inject some code in the page DOM to handle the message in the page using `page.evaluate()` and use `page.exposeFunction()`to return the result to puppeteer.
As I said, not straightforward but possible :wink:

**Comment by aslushnikov** [comment]
> I did check it but I couldn't find a way to differentiate a "navigation" request type from a "document" request type.

@GuilloOme ah indeed, you're right. My suggestion wouldn't work for you then.

> @aslushnikov rather than a navigation lock I wanted to click and open a new tab for each element on the page and setrequestinterception for each new page, but the request interception is not added in time to catch the initial redirect.

@sukhjitsingh-impactradius that's a good usecase, thank you. @caseq: this might be another point towards browser-wide request interception

**Comment by sukhjitsingh-impactradius** [comment]
@aslushnikov is there work being done for this request or is there possibly somewhere you think upstream where I can log a ticket for this, if it hasn't already?

**Comment by aslushnikov** [comment]
>  is there work being done for this request

@sukhjitsingh-impactradius not yet.

> is there possibly somewhere you think upstream where I can log a ticket for this, if it hasn't already?

You can file a ticket on `crbug.com` against devtools protocol, it will help us with bookkeeping.

**Comment by IvanTrendafilov** [comment]
+1, navigation lock would be super useful when dealing with unstable / buggy pages

**Comment by Vandivier** [comment]
Thumbs up. Here's my use case: Scrape a website with pages conforming to a regex like
/resource/1
/resource/2
...
eventually /resource/n doesn't exist and gets a redirect to a 404 page

I want to detect that to end a recursive chain of puppeteer requests.

**Comment by sukhjitsingh-impactradius** [comment]
@Vandivier you can do that by checking the response.status like so: 
`page.on('response', (response) => {
        result.httpStatusCode = response.status();
	});`

**Comment by matrey** [comment]
+1

My use case is for testing an ecommerce website, validating each link in the menu. Most of these links just open another level of submenu (they do have a href set, but some javascript on the page intercepts the event before). But some links, not always at the "leaf" level, directly send you to other pages.

I tried using puppeteer's request interception but it's too late, we already navigated away. It just saves a bit of time by not loading the new page.
If a navigation lock was available in puppeteer, it would save me the effort of having to rebuild all the context (menu opened, sub menu opened, etc.) when hitting an outgoing link.

FYI I was previously using Nightmare (based on Electron) and was able to achieve my objective with the help of this module: https://github.com/rosshinkley/nightmare-navigation-lock/blob/master/nightmare-navigation-lock.js

**Edit**
A potential way to cover my use case with minimal intrusion into the tested website: define window.onbeforeunload so that it shows a dialog when we try to navigate away. Then dismiss the dialog.
That prevents leaving the page ; however it doesn't let you know what the target page URL would have been. So it's still not as good for my use case as the navigation lock in Nightmare was.

```
await page.evaluate(() => {
  window.onbeforeunload = function() { return "Are you sure you want to leave this page?"; };
});
page.on('dialog', async dialog => {
  await dialog.dismiss();
});
```

**Comment by sukhjitsingh-impactradius** [comment]
I wanted to share my workaround for this issue. Instead of using the setRequestInterception or using a chrome extension like @GuilloOme is using (which I believe still does not work with headless mode). I start a proxy server before starting my browser that catches all requests and blocks any that I don't want to see. I am using the [Proxy-Chain](https://github.com/apifytech/proxy-chain) library like so: 
```
const puppeteer = require('puppeteer');
const ProxyChain = require('proxy-chain');
const proxy = new ProxyChain.Server({ 
        port: 5050,
        
        verbose: false,
        
        prepareRequestFunction: ({ request, username, password, hostname, port, isHttp }) => {
            if(request.url === 'urlThatIWantToBlock'){
                console.log("Found url: " + request.url + ": blocking");
                return;
            }else{
                return {
                    // Do not require authentication...more info on usage for this can be found on the github link above
                    requestAuthentication: false,

                    // Sets up an upstream HTTP proxy to which all the requests are forwarded.
                    // If null, the proxy works in direct mode.
                    upstreamProxyUrl: null,
                };
            }
        },
    });

    proxy.listen(() => {
        console.log(`Proxy server is listening on port ${5050}`);
    });

    let browserArgs = [
        '--no-sandbox', 
        '--disable-setuid-sandbox',
        `--proxy-server=http://127.0.0.1:5050`,
    ];
    // Launch headless chromium browser
    // Run with headless: false for debugging with the browser visible
    // Run with slowMo: numberOfMilliSecondsToSlowDownEachEvent to debug slowly
    const browser = await puppeteer.launch(
        {
            dumpio: true,
            headless: true,
            args: browserArgs
            // ,slowMo: 2000
        }
    );
```
This works for both http and https. Also, this is a very rudimentary solution for my use case, there are probably better ways to do this; though, I like my solution because it is done within node.js.

**Comment by Qianlitp** [comment]
+1,  I have been waiting for this new feature for a long time. Navigation lock is a nice feature when i write a crawler. The remaining links on this page will be lost when the crawler trigger a navigation event. I can use this `beforeunload` method to cancel navigation, the URL that will be navigated cannot be obtained.

**Comment by nguyen190887** [comment]
+1
We faced the same problem. Our use case is opening a web page, then click on links and buttons on the page to fire Analytics tagging. Finally, we validate the correction of tagging fired. This was used to be very straightforward when we used PhantomJS, but thing changed after we switched to Chrome Headless.

We now workaround by using "beforeunload" approach suggested above. However, the tests are sometime not stable. It would be great if we can support this feature. Thanks.

**Comment by ghost** [comment]
One of the thing I've resolved to doing is searching for all hrefs and removing them before every action so they don't get clicked accidentally. Not great.

**Comment by Wildhoney** [comment]
@Qianlitp good thinking! Something like the following seems to work just fine:

```javascript
page.on('dialog', dialog => dialog.dismiss());
page.evaluate(() => {
    window.onbeforeunload = function() {
        return 'You have unsaved changes!';
    }
});
```

@dave-dm although a good answer too, you can't prevent page navigation from `onClick` events, etc...

**Comment by jiangfengming** [comment]
`req.respond({ status: 204 })` can prevent the navigation by js.

```js
const url = 'https://www.example.com/'

page.on('request', req => {
  if (req.isNavigationRequest() && req.frame() === page.mainFrame() && req.url() !== url) {
    // no redirect chain means the navigation is caused by setting `location.href`
    req.respond(req.redirectChain().length
      ? { body: '' } // prevent 301/302 redirect
      : { status: 204 } // prevent navigation by js
    )
  } else {
    req.continue()
  }
})

page.goto(url)
```

**Comment by panthony** [comment]
The solution suggested by by @jiangfengming was working well until the new `1.13.0` release where `page.goto` hangs until it timeout, unfortunately.

**Comment by aslushnikov** [comment]
@panthony works just fine for me with 1.13.0. One correction however is to use `request.abort` instead of `request.respond` - this way we can properly abort navigation.

Try running the following script and than manually navigating from "example.com" to any other website:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();

  const URL = 'https://example.com';

  page.on('request', req => {
    if (req.isNavigationRequest() && req.frame() === page.mainFrame() && req.url() !== url) {
      req.abort('aborted');
    } else {
      req.continue();
    }
  });
  await page.setRequestInterception(true);
  await page.goto(url)
})();
```

This is the recommended way to implement navigation locks.

**Comment by panthony** [comment]
@aslushnikov Ok, I started to return 204 when aborting the navigation request made goto failed:

https://github.com/GoogleChrome/puppeteer/issues/3421#issuecomment-434959968

Guess I'll give abort a try again :)

**Comment by aslushnikov** [comment]
@panthony let me know how it goes!

**Comment by rymdhund** [comment]
@aslushnikov The code you linked timeouts for me every time when I change example.com to a page that does `window.location = 'http://google.com'`. Both on 1.13.0 and 1.14.0. Maybe it's the interception that is causing trouble again?

```
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const url = 'http://example.com';

  page.on('request', req => {
    console.log(`request: ${req.url()}`);
    if (req.isNavigationRequest() && req.frame() === page.mainFrame() && req.url() !== url) {
      console.log('abort');
      req.abort('aborted');
    } else {
      req.continue();
    }
  });
  await page.setRequestInterception(true);
  await page.goto(url)
})();
```

**Comment by aslushnikov** [comment]
@rymdhund not sure, the following works just fine for me.

Note: the `page.goto` will throw the `ERR:ABORTED` since you abort the navigation, so you should handle the exception.

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const url = 'http://example.com';

  page.on('request', req => {
    console.log(`request: ${req.url()}`);
    if (req.isNavigationRequest() && req.frame() === page.mainFrame() && req.url() !== url) {
      console.log('abort');
      req.abort('aborted');
    } else {
      req.continue();
    }
  });
  await page.setRequestInterception(true);
  await page.goto(url)
})();
```

**Comment by panthony** [comment]
@aslushnikov Aborting the navigation request like suggested above will make the `goto` hang if you happen to use `waitUntil: [ 'networkidle2' ]`.

**Comment by DCtheTall** [comment]
Hey all, now that Chrome is planning on deprecating the Network.* Devtools Protocol API, has anyone found a way to do this using the new Fetch Devtools API?
