### ISSUE TITLE
[Bug]: No way to tell what triggers a net::ERR_ABORTED response

### ISSUE THREAD

**Issue by rmzg** [puppeteer/puppeteer#8246]
### Bug description

Under a number of different circumstances, such as calling `page.goto`, puppeteer will throw `Error: net::ERR_ABORTED`, as far as I can tell, this is an internally generated error message not based on the server response and as such there is no way to determine *why* chrome has decided to throw this error.

Is there *any* kind of tracing/logging/debugging that can determine why chrome/puppeteer has decided to generate this error?

### Puppeteer version

13.5.2

### Node.js version

17.8.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: net::ERR_ABORTED at https://www.totaljobs.com/job/net-software-developer-programmer/reflex-computer-recruitment-job97238730
```

**Comment by fdciabdul** [comment]
you are blocked by server , however puppeteer itself is easy to be detected , so you have to configure the puppeteer to undetected 

also you can use some plugin called `puppeteer-extra` and `puppeteer-extra-plugin-stealth`

**Comment by SolomonM-dev** [comment]
I am having the same problem, has there been any solution for that ?

**Comment by smashah** [comment]
I was experiencing this issue and it was actually due to an error thrown by chrome.

Immediately before experiencing this issue I migrated my Ubuntu system to use jemalloc system-wide instead of glib malloc.

This change caused puppeteer to start throwing these `net::ERR_ABORTED` errors. I thought it was because the site was blocking my requests - that was not the case.

Using some diagnostic CLI command as shown below:

```
admin@m18574:~/orch$ google-chrome-stable --headless --dump-dom https://www.how2shout.com --no-sandbox
[1218/022947.825929:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1218/022947.843086:WARNING:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
[1218/022947.846753:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[1218/022947.871366:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1218/022947.871403:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
[1218/022947.877119:ERROR:network_service_instance_impl.cc(513)] Network service crashed, restarting service.
```

This command is actually supposed to spit out the html of the page `https://www.how2shout.com`.

There are a few errors here. Only one is the cause of `net::ERR_ABORTED`:

```
[1218/022947.877119:ERROR:network_service_instance_impl.cc(513)] Network service crashed, restarting service.
```

I was able to see that the internal chrome network service was crashing. This crash caused the chrome process to throw `net::ERR_ABORTED` which makes sense as the connection was literally aborted due to the network service crashing. This is in contrast to the assumption that the website was aborting the request.

If you are experiencing this issue please ensure that you have disabled `jemalloc` for the chrome process.

Note: You can use `jemalloc` for specific process by setting the environment variable specifically for that process. For example:

```bash
> LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so node index.js
```

**Comment by smashah** [comment]
@FabianoFMSilva Run this and check/share the output:

```
google-chrome-stable --headless --dump-dom https://www.how2shout.com --no-sandbox
```

**Comment by ptk-dev** [comment]
****Just one solution.****
handle your promises mindfully. when they collidle by parallel function on same page this occurs problem occurs by the side of puppeteer.

**Comment by MoizRed** [comment]
I am facing this problem right now when i deployed my puppeteer Bot to render.com to scrape some information from my government website.

 it could be due to geolocation censorship. which i confirmed later using https://www.experte.com/internet-censorship

the bot works fine when hosted locally . but when i deployed it and run it on render.com i get the the following CL output : 
```
PAGE LOADED
/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:218
                    ? new Error(`${response.errorText} at ${url}`)
                      ^
Error: net::ERR_ABORTED at [my gov website]
    at navigate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:218:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Frame.goto (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:184:21)
    at async CDPPage.goto (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:438:16)
    at async Timeout._onTimeout (file:///usr/src/app/script.js:65:1)
```
any other site works just fine.

**Comment by jonnyeom** [comment]
> **Just one solution.** handle your promises mindfully. when they collidle by parallel function on same page this occurs the problem. by the side of puppeteer. as one page can be handled by a single function at a time or may be. as It worked for me.

I had the same thing. I was trying to set an object onto the global instance in a foreach (Therefore running multiple puppeteer instances). Thank you!
