### ISSUE TITLE
browser.version() reports Chrome/xxx when Chromium/xxx is being used

### ISSUE THREAD

**Issue by karl-geoedge** [puppeteer/puppeteer#8309]
### Bug description

Steps to reproduce the problem:

1. call browser.version()

eg:
```
await browser.version().then(function(version) {
 console.log(version);
});

//returns Chrome/99.0.4844.0 when it should return Chromium/99.0.4844.0


### Puppeteer version

13.5.1

### Node.js version

16.14.2

### npm version

8.5.5

### What operating system are you seeing the problem on?

Windows

### Relevant log output

_No response_

**Comment by karl-geoedge** [comment]
NOTE: this is using the default version of chromium downloaded with puppeteer 13.5.1 
I believe it is happening with all version of puppeteer on all platforms

**Comment by OrKoN** [comment]
I don't think it's something that can be fixed in Puppeteer. Puppeteer gets the version from the binary using the CDP's `Browser.getVersion`. If you can elaborate on the use case for returning `Chromium` there, feel free to open a bug at crbug.com as it probably does not only affect the version Puppeteer gets but also the user agent string.
