### ISSUE TITLE
how to invoke printer using puppeteer

### ISSUE THREAD

**Issue by gavincilp** [puppeteer/puppeteer#841]
Hi, 
is there a way to print a page or an element using puppeteer?

**Comment by Garbee** [comment]
You can generate a PDF. Accessing printers to physically print however is, I'd believe, out of scope.

**Comment by ebidel** [comment]
Definitely out of scope. Once you have a PDF from Puppeteer, it's your call how you use it :)

**Comment by gavincilp** [comment]
thanks @Garbee  and @ebidel , but i think if you can print from chrome then you should be able to print using headless chrome.

**Comment by Garbee** [comment]
Headless is missing a lot of features like this. Because to effectively print, you need a ux layer for user interaction.

As said earlier, generate the PDF or image you want, then you can find other software to run in the same script chain to print it out without interaction. This isn't something Chrome Headless or Puppeteer should be taking on.

**Comment by gavincilp** [comment]
thanks @Garbee . understood. :-)
