### ISSUE TITLE
[Bug]: Puppeteer doesn't capture some OOPIF requests (Flaky)

### ISSUE THREAD

**Issue by adamraine** [puppeteer/puppeteer#8507]
### Bug description

The following script will exit 1 if there were some missing `Network.requestWillBeSent` events:
https://gist.github.com/adamraine/e9ae2e811bde239db24a47535008e228

On my computer the script exits 1 most of the time. Other machines have a hard time reproducing the described result. I have reproduced it on a Linux cloudtop as well.

The script needs `waitForDebuggerOnStart: true` so it has time to enable network instrumentation before the OOPIF starts loading. The problem is that setting `waitForDebuggerOnStart: true` in this script doesn't affect anything because puppeteer sets `waitForDebuggerOnStart: false` (See log)

@paulirish and I developed a "fix" that prevents this script from exiting 1, but unsure how it would affect the rest of puppeteer. It's also possible that this "fix" just makes the script fail less often:
https://github.com/puppeteer/puppeteer/compare/main...adamraine:wait-for-debugger-on-attach

### Puppeteer version

14.3.0

### Node.js version

14.18.2

### npm version

8.4.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
https://gist.github.com/adamraine/5b06ee25b09c815dee73962255c76dc1
```

**Comment by OrKoN** [comment]
I think this is essentially the same as https://github.com/puppeteer/puppeteer/issues/7990 Coincidentally I started working on refactoring Puppeteer yesterday. One problem is that Firefox does not seem to support waitForDebuggerOnStart so a backward compatible solution is needed. Also, it's a bigger refactoring since setting waitForDebuggerOnStart in existing places would not ensure that the target configuration is race-free as far as I can tell.
