### ISSUE TITLE
[Bug]: Asynchronous parallel page load works weird on different OS

### ISSUE THREAD

**Issue by sekaiamber** [puppeteer/puppeteer#8677]
### Bug description

I've build a simple system to get html by sending a URL.

I worked on my **MacBook Pro**(M1 Max, 64G memory, Monterey, node v14.17.4, npm 6.14.14, puppeteer 15.3.2). Everything goes fine.

In my case, when I request a example page, it ususally take 3s for loading and running rest of code. And when I send 5 requests at same time, after 3s, the 5 responses will return at same time, beause I built this system asynchronously.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/10176695/179974833-19a33500-2ec1-488d-b3eb-2edd67177e77.png">

But when I deploy this system on my **Linux** server(2 vCPU, 8G memory, Ubuntu 22.04, node v14.20.0, npm 6.14.17, puppeteer 15.3.2), I find that, the system seems like running synchronously: for a single request, it takes 3s; but when I send 5 requests at same time, it takes 3 * 5 ≈ 15s, and all responses returns at same time.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/10176695/179974091-5e290b70-11cf-412c-b7b3-cce2063fe49e.png">

Any ideas for my issue?

### Puppeteer version

15.3.2

### Node.js version

14

### npm version

6.14

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by OrKoN** [comment]
Hey, it looks like the reason for this is that the server has only two vCPUs. I assume you get HTML by navigation to a URL in a new tab. Since every tab is a new process in Chromium, you'd see some slowdown. Perhaps, try asking the question on StackOverflow providing your code https://stackoverflow.com/questions/tagged/puppeteer and someone might help to optimize it.
