### ISSUE TITLE
Debugging puppeteer

### ISSUE THREAD

**Issue by elenaoat** [puppeteer/puppeteer#868]
Is there a way to debug puppeteer? 
I am trying hopelessly to click a button/submit a form and it just won't do it :/
Here's an example:
```
    await page.focus('#outer-container > nav > span.right > span.search-notification-wrapper > span > form > input[type="text"]');
    await page.type("SSSSSS");
    await page.click('#outer-container > nav > span.right > span.search-notification-wrapper > span > form');
```

**Comment by aslushnikov** [comment]
@elenaoat I'd start with launching puppeteer in non-headless mode to see what's actually going on:
```js
const browser = await puppeteer.launch({
  headless: false, // launch headful mode
  slowMo: 250, // slow down puppeteer script so that it's easier to follow visually
});
```

**Comment by ebidel** [comment]
A bunch other debugging tips are in the readme: https://github.com/GoogleChrome/puppeteer#debugging-tips

**Comment by elenaoat** [comment]
Frankly, just setting it to a slow motion doesn't help at all. This was the very first thing I've done. I will read through the debugging tips, thanks @ebidel.

**Comment by tokland** [comment]
This is what I do to interactively develop or debug puppeteer scripts:

* Create a base script:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  Object.assign(global, {browser, page});
  
  await page.goto('https://reddit.com/r/programming');
  await page.waitForFunction('false', {timeout: 10000000});
  await browser.close();
})();
```
* In a normal Chrome, go to `chrome://inspect`. 
* Under _Devices_, click _Open dedicated DevTools for Node_. 
* Run the script like this in a shell: `$ node --inspect myscript.js`.
* Go to the _Console_ tab, you should have variables `browser` and `page` ready to use.

Note: You can also add breakpoints (`debugger`), but while it's stopped, promises won't resolve. Since pretty much all puppeteer functions return a promise, that's kind of annoying.  If anyone knows a workaround for this, it would be great to here. 

Update: I see that you @ebidel already proposed something similar, [link](https://github.com/GoogleChrome/puppeteer/issues/398#issuecomment-323551586), I think that should be also in the README.

**Comment by joelgriffith** [comment]
Would like to throw out there that https://chrome.browserless.io/ is also available for debugging purposes. It lets you inject `debugger;`'s and log's (in the pages context), as well as exposes devtools + an interactive view of the page. I'll see if I can't get it in the examples/docs since this tends to come up frequently

**Comment by benjamingr** [comment]
Hey, just to add to the party a few years later my team wrote an [open source tool to help with debugging puppeteer and playwright tests](https://github.com/testimio/root-cause/) - we are looking for feedback and would love people to check it out and tell us what they think. It's still early on and we can make changes.
