### ISSUE TITLE
[Bug]: User Pass Https Proxies Not Working

### ISSUE THREAD

**Issue by cyrusnaficy** [puppeteer/puppeteer#8705]
### Bug description

Steps to reproduce the problem:

1. Put your IP and port in args `--proxy-server=https=${splitproxy[0]}:${splitproxy[1]} `
2. Launch the page like usual
3. Authenticate User:Pass await page.authenticate({ username: splitproxy[2], password: splitproxy[3], })

The page will open and immediately close. I already tried to do `--proxy-server=https://${splitproxy[0]}:${splitproxy[1]}` instead of the `https=`, but upon doing that, the page opens and just endlessly loads, never rendering the actual page. 

I tried using other packages which support Puppeteer Proxies, but they do not support User Pass Https proxies. The only one which did, `puppeteer-page-proxy` had the same endless loading version.

When using proxies that are IP whitelisted, they work just fine. There seems to be a problem authenticating the proxies. Is there any way to use `https-proxy-client` via httpsAgent for puppeteer? I tried connecting via intercepting a request, but then the same endless loading occurs. The proxies I am using work fine with Axios, Got, and other request modules. I have yet to try it with Playwright. 

Please let me know if you can recomend any useful proxy packages or ways to authenticate user pass https proxies with puppeteer. Thanks

### Puppeteer version

15.5.0

### Node.js version

16.6.0

### npm version

8.11.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
err_http_response_code_failure & or err_tunnel_connection_failed
```

**Comment by OrKoN** [comment]
Unfortunately, I am not familiar with proxies :( would it be possible to for you to provide an isolated repro that includes a proxy server/puppeteer client implementation so that we could debug both at the same time?

**Comment by OrKoN** [comment]
also `page.authenticate` seems to be for the HTTP auth, does the proxy really use it? or is the page itself behind auth?

**Comment by TrustyJar** [comment]
Ok, for some reason on Windows only, when reading proxies from a file using fs, the last split (password) has `\r` included in the string, which throws off the auth. It isn't visible when logging the password or debugging. Very odd. Doing `splitproxy[3].replace('\r', '')` solved the issue. 

I believe the issue was with how I imported my files, so I am going to close. Still very odd that this is a Windows only error for me. I would assume that the same error would throw on Mac if I am importing the proxies file the same way.
