### ISSUE TITLE
Navigation Timeout during page.waitForNavigation

### ISSUE THREAD

**Issue by BkSouX** [puppeteer/puppeteer#871]
Hi

I would like to get more info when I have a timeout during
```javascript
await page.waitForNavigation();
```

Is it possible to know which requests are throwing a timeout ?

I just have that exception : 

```
Navigation Timeout Exceeded: 30000ms exceeded[0m
    at NavigatorWatcher.waitForNavigation (/opt/thumbnail-generator/node_modules/puppeteer/lib/NavigatorWatcher.js:73:20)
```

Thank you

**Comment by aslushnikov** [comment]
@BkSouX it means that navigation didn't complete in 30 seconds.
You can track all requests with the [`request`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-request) event, and you can keep track of finished requests using the [`requestfailed`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-requestfailed) and [`requestfinished`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-requestfinished) events.

**Comment by BkSouX** [comment]
Ok, is there a way to finish the loading of the page even if there is a timeout on some request inside the page ?

**Comment by aslushnikov** [comment]
@BkSouX I think there's some confusion about what page loading is.
1. There's no single correct definition of a loaded page out there.
2. Puppeteer provides some good estimations for page's loaded state:
    - `'load'`: page is considered loaded when it fires the "load" event.
    - `networkidle`: page is considered loaded when there's no network activity going on.

By default, the `page.waitForNavigation` will wait for the `load` event to be issues. Unless there's a timeout option, it will try to do so for 30 seconds, and then throw the "Timeout Exceeded" error.

```js
await page.waitForNavigation();
```

Since this throws for you the timeout exception, it means that page failed to fire the `load` event
is the 30 seconds timespan. It has nothing to do with timeouting requests.
