### ISSUE TITLE
[Bug]: screenshot clips element

### ISSUE THREAD

**Issue by klebs6** [puppeteer/puppeteer#8833]
### Bug description

Hi folks! 

To reproduce, attempt to screenshot the following element: 
`/html/body/div[1]/div[1]/article/div/section[7]/dl[3]/dd/span/img`

on the page: 
`https://www.wikiwand.com/en/random_forest`

The screenshot turns out like this:
<img width="897" alt="Screen Shot 2022-08-23 at 11 11 30 PM" src="https://user-images.githubusercontent.com/92199902/186312262-b48db232-3bc5-4993-9232-bb686845aa61.png">

Here is how I am configuring the page with puppeteer:

<img width="830" alt="Screen Shot 2022-08-23 at 11 08 25 PM" src="https://user-images.githubusercontent.com/92199902/186311861-1410d6d0-6557-458a-ac70-cbde6bb36fc9.png">

<img width="827" alt="Screen Shot 2022-08-23 at 11 12 16 PM" src="https://user-images.githubusercontent.com/92199902/186312340-0423e3cf-d0f7-49ad-ad0d-268eafba6bbf.png">

I notice I can fix the clipping if I expand the page viewport at the beginning of program execution.  However, this changes the way the rest of the screenshots I would like to capture will render. 

Is there a way I can avoid this clipping without changing the global viewport settings on the page?  When I try to change the viewport at the site of every screenshot, I get a wide variety of odd artifacts showing up in the end result screenshots.  This might be due to the fact that I have already gathered the elements I would like to screenshot with the previous viewport settings.

### Puppeteer version

zenika-alpinechrome-withpuppeteer@1.0.0 ,  @cliqz/adblocker-puppeteer@1.23.9,  puppeteer@6.0.0

### Node.js version

v18.7.0

### npm version

8.18.0

### What operating system are you seeing the problem on?

macOS

**Comment by jrandolf** [comment]
Could you provide a sample script?

**Comment by klebz** [comment]
I have been working on this since my original post -- it is not clear to me that the error is actually in puppeteer. 

While I was attempting to create for you an example script, I ended up getting frustrated with javascript debugging and rewrote the whole thing in Rust to A/B test.   

The trouble was that the trivial example scripts all seemed to work.  The errors only popped up in my more complex, production code.

So, I wanted to know whether the problem was in my code, in puppeteer, or in some layer underneath.

I was able to eliminate many bugs from my code by using Rust. 

Unfortunately, I am still seeing odd screenshotting behavior at the last stage of the pipeline.  

In Rust, I am using the (also wonderful) rust library `fantoccini`.  

The fantoccini library code seems sound. 

I am concerned that the problem might be with the webdriver layer underneath, or in my usage of it.  
This hunch comes from the fact that the screenshotting bugs I am encountering seem very similar between fantoccini and puppeteer.  

I am not sure whether the webdriver layer is shared or similar between fantoccini and puppeteer.  It looks like it is just a protocol to talk to chromedriver.

After rewriting in rust, I have verification that the divs I want to screenshot are totally correct in terms of their html content.

The issue seems to come up when I resize the viewport several times during screenshotting several elements in a row.

I am nearly ready to cut my losses and move on to a different strategy of achieving my end goal.  I may just want to save the divs directly as text and process them downstream instead of attempting to capture their content as PNG at this stage.

I have attempted a variety of tactics while screenshotting, in order to attempt to massage correct behavior into place.

Unfortunately, the basic idea of setting the window to the size of the bbox and screenshotting (with or without padding, with or without reinitialization to some large window frist) doesn't seem to work.
