### ISSUE TITLE
[Feature]: Expose Frame for JSHandle (and ElementHandle)

### ISSUE THREAD

**Issue by stevenwdv** [puppeteer/puppeteer#8882]
`JSHandle#executionContext()` was removed in v17, but with it also the ability to get the Frame or Page from a handle was removed. Previously one could use `handle.executionContext().frame()`, but now there is no way to get the Frame anymore. I would propose adding a `JSHandle#frame()` method to get the Frame from an element.

Note: `ElementHandle#contentFrame()` is for `<iframe>`s, this does not return the Frame that an element is on or a JSHandle is part of.

**Comment by OrKoN** [comment]
@stevenwdv do you mean this https://github.com/puppeteer/puppeteer/pull/8875? Note that the getter is on the ElementHandle at runtime but was not exported via types until that PR.

**Comment by stevenwdv** [comment]
@OrKoN Ah, hadn't seen that. Yes that would cover my current needs, although I wonder what the reason is for not exposing it for all `JSHandle`s?

**Comment by OrKoN** [comment]
@stevenwdv JSHandles could come from service workers or workers and, thus, might not have a frame associated with them. In general, if you have a JS handle you should be able to do :

```
  const handle = await page.evaluateHandle(() => 1 + 2);
  console.log((await handle.evaluateHandle(() => document.body)).frame);
```

to see if JSHandle's context has DOM and has a frame. I guess the issue is then resolved? Let me know if there are additional use cases we overlooked.
