### ISSUE TITLE
After adding the configuration file, you will need to remove and reinstall puppeteer for it to take effect.

### ISSUE THREAD

**Issue by wojtekxtx** [puppeteer/puppeteer#9403]
What the hell?

Guys, we are in XXI century. There is a thing called `lazy loading`. Its super useful thing and its a breeze to implement.

**Comment by OrKoN** [comment]
Could you clarify which parts of the config are not taken into effect? if you mean the installation location, the installation only happens on `npm i` in npm scripts. Otherwise, the installation location lookup or any other configuration does not require installation. Note that if Puppeteer is already installed, npm might choose not to re-run install scripts.

**Comment by OrKoN** [comment]
Well, thanks for the feedback. We don't plan on writing config files for the users as the config is completely optional for installing Puppeteer. We are working on a CLI for browser download which would decouple `npm i` from the browser download.
