### ISSUE TITLE
[Bug]: Code does not download pdf file from link

### ISSUE THREAD

**Issue by cleciobruno** [puppeteer/puppeteer#9557]
### Bug expectation

The code is supposed to download the pdf file from the link and save to my machine, but it doesn't.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
(async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const page = await browser.newPage();

  await page.goto(
    "https://www.thecampusqdl.com/uploads/files/pdf_sample_2.pdf"
  );
  const client = await page.target().createCDPSession();
  await client.send("Browser.setDownloadBehavior", {
    behavior: "allow",
    downloadPath: "C:/meu local/",
  });
})();
```

### Error string

no error

### Puppeteer version

19.5.2

### Node version

18.12.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by Kle0s** [comment]
A couple of things:
1. You need to configure the download behaviour before downloading. It was not allowed before the configuration, and when you got to the page it was prohibited, so it did not download.
2. You need to configure the download behaviour for the same CDP session so using `page.target().createCDPSession()`  is also problematic. Since, as far as I recall, puppeteer does not provide and interface to the used CDP session currently, you can use `page._client()` to access it. NOTE: Accessing the client via the internal-api is subject to changes and is subject to changes.

All in all, this is a fixed code that should work for you:
```js
const puppeteer = require("puppeteer");
(async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const page = await browser.newPage();
  const client = page._client();
  await client.send("Browser.setDownloadBehavior", {
    behavior: "allow",
    downloadPath: "C:/meu local/",
  });
  await page.goto(
    "https://www.thecampusqdl.com/uploads/files/pdf_sample_2.pdf"
  );

})();

```

**Comment by OrKoN** [comment]
I believe it's the same as https://github.com/puppeteer/puppeteer/issues/299 Try using the workarounds @Kle0s mentions or other in that issue thread.

**Comment by CloudItaly** [comment]
hello. i have a problem. 
I use this code https://github.com/puppeteer/puppeteer/issues/9557#issuecomment-1399441291 
into Visual Studio Code (MacOS). 

Once the script is started from Visual Studio, the browser opens with the PDF viewer but it is not saved in the folder. If you manually press the icon, it is saved in the chosen folder. How is it resolved?

**Comment by JanioSamuel** [comment]
@CloudItaly try using headless: true
