### ISSUE TITLE
[Bug]: can not get element in a iframe

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#9643]
### Bug expectation

 await page.goto('https://www.shejijia.com/');
  await sleep(5000);
   await page.waitForXPath("//*[text()='注册/登录']", { timeout: 5000 });
  const m_login_btn = await  page.$x("//*[text()='注册/登录']");
  await m_login_btn[0].click();
  await sleep(5000);
 
const iframe =await page.$$("#alibaba-login-box");
console.log('iframe..',iframe);
const tmpbtn =await  iframe[0].$("#login>div.corner-icon-view.view-type-password>i");
console.log("tmpbtn...",tmpbtn);  //tmpbtn is null,which should not be
![iframe](https://user-images.githubusercontent.com/19261291/217862291-b3c2deb7-2541-4e72-b217-7263889b7e30.png)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
await page.goto('https://www.shejijia.com/');
 await sleep(5000);
 await page.waitForXPath("//*[text()='注册/登录']", { timeout: 5000 });
 const m_login_btn = await  page.$x("//*[text()='注册/登录']");
 await m_login_btn[0].click();
 await sleep(5000);
 
const iframe =await page.$$("#alibaba-login-box");
console.log('iframe..',iframe);
const tmpbtn =await  iframe[0].$("#login>div.corner-icon-view.view-type-password>i");
console.log("tmpbtn...",tmpbtn);  //tmpbtn is null,which should not be
```

### Error string

no error reported

### Puppeteer version

18.1.0

### Node version

16.19.0

### Package manager

npm

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment]
Hey, there is not enough information to reproduce the bug: make sure you use waitForFrame (and not `const iframe =await page.$$("#alibaba-login-box");` as it is the iframe DOM element and it does not allow querying its children) and waitForSelector instead of querying for elements directly. Also, not that depending on whether it is a Puppeteer-driven browser, sites might implement protections and render different content.
