### ISSUE TITLE
Firefox tests on MacOS are much slower compared to Ubuntu tests

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#9648]
Examples:

firefox-headless tests on macos-latest
succeeded 2 hours ago in 27m 25s
https://github.com/puppeteer/puppeteer/actions/runs/4142214498/jobs/7165355344

firefox-headless tests on ubuntu-latest
succeeded 1 hour ago in 13m 7s
https://github.com/puppeteer/puppeteer/actions/runs/4142214498/jobs/7165354734

**Comment by OrKoN** [comment]
cc @whimboo

**Comment by OrKoN** [comment]
An example run with the trace info (only the launcher spec):

https://github.com/puppeteer/puppeteer/actions/runs/4145033164/jobs/7168864438
https://github.com/puppeteer/puppeteer/actions/runs/4145033164/jobs/7168864939

**Comment by OrKoN** [comment]
Thanks for the analysis. Still it seems Firefox on mac is about 3x slower than Chrome on Mac. Are there easy some optimisations possible (maybe via some command line flags)? If not, then let's close it.

**Comment by lutien** [comment]
Unfortunately, we don't have anything like this at the moment :(
I think the time should go down generally for Firefox, when more tests start passing.

**Comment by OrKoN** [comment]
@lutien are you going to spend some time on getting the tests to pass? I thought you would not spend much time on the CDP support now. So perhaps it makes sense to skip tests that won't get fixed? Also, in the launcher spec example most or all tests are passing but Firefox test time seems to 2.5m vs 30sec for Chrome.

**Comment by whimboo** [comment]
Please note that this is most likely related to slow startup times of Firefox and maybe some shutdown delays. As we talked on Matrix a while ago it would be great to see a CI job on MacOS (launcher spec tests should be enough) that have full trace logs ('remote.log.level=Trace`) enabled. This potentially could indicate what's slow - maybe it's related to the workers GitHub is using.

**Comment by OrKoN** [comment]
@whimboo there are two runs with the trace info linked above:

https://github.com/puppeteer/puppeteer/actions/runs/4145033164/jobs/7168864438
https://github.com/puppeteer/puppeteer/actions/runs/4145033164/jobs/7168864939

**Comment by whimboo** [comment]
So generally it takes ~3s for Firefox to startup on MacOS. Given the amount of tests this adds quite a good amount of extra time.

For `userDataDir option should restore state` it means that Firefox runs this test in 9985ms while Chrome only takes 1426ms. That alone makes a difference of ~8.5s because the browser starts twice (~6s extra time for Firefox).

We are aware of slowness during startup and there is a bug filed for that (which I actually cannot find), but there is nothing easy to do right now to get this solved.

One thing that we could try is to create a specific Firefox profiler export for a test that launched Firefox once. We would have to [measure startup and shutdown](https://profiler.firefox.com/docs/#/./guide-startup-shutdown). The exported JSON file would have to be marked as an artifact so that we can upload to our profiler for analysis. If you could run that I'm happy to have a look at the results.
