### ISSUE TITLE
[Bug]: package managers now give warning about unmet peer dependency `mitt`

### ISSUE THREAD

**Issue by jeremymeng** [puppeteer/puppeteer#9665]
### Bug expectation

**Expected**
No warnings when add puppeteer to my project

**Actual**
pnpm, yarn and npm give a warning about unmet peer dependency `mitt`

> ??? puppeteer
  ??? puppeteer-core
    ??? chromium-bidi
      ??? ? missing peer mitt@"*"
Peer dependencies that should be installed:
  mitt@"*"

Are we now supposed to include `mitt` every place where we use `puppeteer`?

### Bug behavior
had to check one to see if the bot is happy
- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```ts
import puppeteer from 'puppeteer'
```

### Error string

missing peer mitt@"*"

### Puppeteer version

19.7.0

### Node version

14.19.0

### Package manager

npm

### Package manager version

9.4.2

### Operating system

Linux

**Comment by jeremymeng** [comment]
adding some active maintainer @OrKoN 
it looks that in the github action, the installation step failed even before verifying issue, so the bot keeps adding `not-reproducible` label
https://github.com/puppeteer/puppeteer/actions/runs/4168905695/jobs/7216254640

**Comment by OrKoN** [comment]
@jeremymeng that is strange because mitt is prod dependency and we never declare it as a mitt dependency. I get no warning installing Puppeteer with npm.

**Comment by OrKoN** [comment]
@jeremymeng Do you get the warning if you uninstall and install puppeteer in an existing project?

**Comment by mikeharder** [comment]
> I am not sure why package managers don't resolve it given that the mitt is a prod dependency for puppeteer.

I do not see `mitt` as a prod dependency for either `puppeteer` or `puppeteer-core`.  The only match I found in this repo is a `devDependency` for `puppeteer-repo`:

https://github.com/puppeteer/puppeteer/blob/56f99f7b10e7f696b92287af3abdc0fca0d51ddb/package.json#L166

**Comment by OrKoN** [comment]
@mikeharder you are right. I forgot that it gets rolled up and shipped as part of Puppeteer https://github.com/puppeteer/puppeteer/tree/main/packages/puppeteer-core/third_party so that Puppeteer runs in the browser too. Therefore, it explains why package managers don't find it. So the warning is coming from chromium-bidi, but it does not affect Puppeteer in any way because it's not used unless you experiment with WebDriver BiDi. Sorry for the confusion.

**Comment by mikeharder** [comment]
@OrKoN: I agree that #9667 should fix this issue.  We will test it as soon as it is released.  I just wanted to clarify why `mitt` wasn't being installed.

**Comment by mojadev** [comment]
Just fyi: This was a breaking change for me in a webpack project that caused the build pipeline to fail due to a semver update
`
#16 70.42 ERROR in ./node_modules/puppeteer-core/lib/cjs/puppeteer/common/bidi/BidiOverCDP.js 40:32-89
#16 70.42 Module not found: Error: Can't resolve 'chromium-bidi/lib/cjs/bidiMapper/bidiMapper.js' in '/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/bidi'
#16 70.42 resolve 'chromium-bidi/lib/cjs/bidiMapper/bidiMapper.js' in '/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/bidi'
#16 70.42   Parsed request is a module
#16 70.42   using description file: /app/node_modules/puppeteer-core/package.json (relative path: ./lib/cjs/puppeteer/common/bidi)
#16 70.42     resolve as module
`

I just added the dependency now and it works fine (I guess I could also have added it as an external, but we needed a quick fix now)

**Comment by karlhorky** [comment]
@mojadev @movila this is resolved in [`puppeteer-core@v19.7.2`](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v19.7.2):

- https://github.com/puppeteer/puppeteer/pull/9667#issuecomment-1438380599
