### ISSUE TITLE
[Bug]: Key modifiers on subsequent down() calls not working

### ISSUE THREAD

**Issue by SEUH** [puppeteer/puppeteer#9770]
### Bug expectation

I expect subsequent calls to down() to not ignore key modifiers like docs say at https://pptr.dev/api/puppeteer.keyboard.down/#remarks.

The example worked in eralier puppeteer version, probably v5.x. Not sure about any version in between.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent('<input id="login">');
  
  await page.waitForSelector('#login');
  let input = await page.$('#login');
  
  await page.keyboard.down('Shift');
  await input.type('a');
  await page.keyboard.up('Shift');
  
  await page.keyboard.press('CapsLock');
  await input.type('a');
  
  await page.keyboard.down('Shift');
  await page.keyboard.down('a');
  await page.keyboard.up('a');
  await page.keyboard.up('Shift');
  
  let value = await input.getProperty('value').then(_ => _.jsonValue());
  
  if (!value.includes('A')) {
    throw new Error('no uppercase a found')
  }
  
  await browser.close();
})();
```

### Error string

no uppercase a found

### Puppeteer version

19.7.2

### Node version

v18.12.1

### Package manager

yarn

### Package manager version

3.4.1

### Operating system

Linux

**Comment by SEUH** [comment]
Also reproduces in official pptr docker image with 
```
docker run -it --rm -v $(pwd)/test.js:/home/pptruser/test.js --init --cap-add=SYS_ADMIN ghcr.io/puppeteer/puppeteer:latest node test.js
```

**Comment by OrKoN** [comment]
@jrandolf could you please take a look?

**Comment by jrandolf** [comment]
The comment applies only when you use the key code for the key down. For example,

```ts
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent('<input id="login">');
  
  await page.waitForSelector('#login');
  let input = await page.$('#login');
  
  await page.keyboard.down('Shift');
  await page.keyboard.down('KeyA');
  await page.keyboard.up('KeyA');
  await page.keyboard.up('Shift');
  
  let value = await input.getProperty('value').then(_ => _.jsonValue());
  
  if (!value.includes('A')) {
    throw new Error('no uppercase a found')
  }
  
  await browser.close();
})();
```

For historical reasons, we combine "key" and "code" values as acceptable inputs for key presses but only when given the latter do we actually apply modifiers because with the former (e.g. 'a'), you are specifying an explicit value.

It could be said however that we are already bias since shifting for "code" values follows the US layout, so it could "make sense" to reverse map the "key" to the "code" and then apply shift, but this would be breaking behavior.

May I ask what your use case is that requires you to do this explicit shifting?
