### ISSUE TITLE
[Bug]: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by georges-ph** [puppeteer/puppeteer#9814]
### Bug expectation

Expected to not get any errors cause the program is stopping. I don't know what is this error. I guess it depends on the website.
The pdf gets successfully saved but after that the error happens.

This link https://github.com/puppeteer/puppeteer/ doesn't throw anything.
https://whatsapp.com and https://web.whatsapp.com do throw it

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer")

async function getPdf() {
	const browser = await puppeteer.launch({
		headless: false,
	})
	const page = await browser.newPage()
	await page.setViewport({ width: 2560, height: 1440 })
	await page.goto("https://web.whatsapp.com", {
		waitUntil: "networkidle0",
	})

	const image = await page.screenshot({
		fullPage: true,
		type: "jpeg",
		encoding: "base64",
	})

	await page.goto("data:image/jpeg;base64," + image, {
		waitUntil: "networkidle0",
	})

	await page.pdf({
		format: "Tabloid",
		path: "file.pdf",
	})

	await browser.close()
}

getPdf()
```

### Error string

node:internal/process/promises:288             triggerUncaughtException(err, true /* fromPromise */);             ^  [Error: EBUSY: resource busy or locked, unlink 'C:\Users\Geo\AppData\Local\Temp\puppeteer_dev_chrome_profile-oh5r5G\Default\Session Storage\000003.log'] {   errno: -4082,   code: 'EBUSY',   syscall: 'unlink',   path: 'C:\\Users\\Geo\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-oh5r5G\\Default\\Session Storage\\000003.log' }  Node.js v18.15.0

### Puppeteer version

19.7.3

### Node version

18.15.0

### Package manager

npm

### Package manager version

9.6.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Actually, it looks like I found the culprit.

**Comment by bongleeEveri** [comment]
Hi @OrKoN, we are facing the same issue in our Prod environment. We saw that for this fix you used 'rmrf' to clean up user data but in the current version 'rm' is being used. We suspect that the issue is happening due to rm being used below.

Is there a reason why the new version is using rm instead of rmrf? If not could we re-introduce rmrf for user deletion in the new version similar to how it was done on this commit?

Please let us know if you need any more info and thanks in advance!

![image](https://github.com/user-attachments/assets/7e60de12-1954-41d2-b381-7c7255dba35c)

### Error string
Error: EBUSY: resource busy or locked, unlink 'C:\Windows\TEMP\puppeteer_dev_chrome_profile-900Abb\first_party_sets.db-journal'

### Puppeteer version
"puppeteer-core": "22.11.1"

### Node version
20.11.1

### Package manager
npm

### Package manager version
10.2.4

### Operating system
Windows

**Comment by OrKoN** [comment]
`rm` is a function provided by Node so we are not going to use a separate dependency for removing dirs anymore. Note that we run it with the following params:

```
const rmOptions = {
  force: true,
  recursive: true,
  maxRetries: 5,
};
```

and it generally works well on our CI. If you get this error it seems likely the directory is still in use by a running process (or some Windows processes). If you have a minimal reproducible example, please file a new issue.

**Comment by bongleeEveri** [comment]
Got it, thank you for your response. We will see if we can recreate the issue using the latest puppeteer package.

One more question did using the rimraf package for this PR resolve the issue? If so do you know why rimraf worked in this case?

**Comment by OrKoN** [comment]
> One more question did using the rimraf package for this PR resolve the issue? If so do you know why rimraf worked in this case?

IIRC we originally changed to rm without retries and rimraf I believe has retries baked-in. As per https://github.com/puppeteer/puppeteer/issues/9814#issuecomment-1461889568 we have been seeing the issue in our own CI but we do not see it anymore.
