### ISSUE TITLE
[Bug]: page.mouse.wheel(delta) not properly accounting for devicePixelRatio

### ISSUE THREAD

**Issue by tambien** [puppeteer/puppeteer#9903]
### Bug expectation

Depending on the external monitor that i run my mousewheel tests on, the scroll amount is different. Depending on the monitor i execute the code in, the browser might report this change as `deltaY: 200` or `deltaY: 100` (see example below). 

Since `devicePixelRatio` is overridden to always be `1`, I also can't find a simple way to counteract this behavior by doing something like: `await page.mouse.wheel({deltaY: (100 / window.devicePixelRatio)});`

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// Puppeteer: 
await page.mouse.wheel({deltaY: 100});

// Browser: 
document.body.addEventListener("wheel", (e) => {
  console.log("deltaY: " + e.deltaY)
});
```

### Error string

Incorrect scroll amount

### Puppeteer version

19.7.5

### Node version

16.16.0

### Package manager

npm

### Package manager version

8.11.0

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
This seems like a bug in chromium, that `delta` is reported differently compare to let's say `windows.scrollY` , since Puppeteer `19.8.0` (released last Friday) you can set the `viewport.deviceScaleFactor` to `0` get the system default, then you can use your workaround. This may affect other thing so be warned.

**Comment by tambien** [comment]
@Lightning00Blade thanks for the response! i'll look into it
